### PR TITLE
add mouse smoothing in uncapped rendering mode

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Thanks @mikeday0

### CODE REVIEW

**Review by rfomin — APPROVED** [review]
I don't have this issue, so I haven't tested it.

**Comment by fabiangreffrath** [comment]
Sigh, me neither, I just adapted the implementation from Crispy. This will be one of these PRs where I can't say anything about the improvements, because I don't even experience the original problem. 😁

**Comment by mikeday0** [comment]
FWIW, I have found on Crispy that this change is most beneficial when running: 1. uncapped 2. vsync and 3. 60 Hz monitor refresh rate. If you turn slowly using the mouse the improvement in smoothness is definitely apparent. (For me, at least.) I don't notice any difference with vsync off. I can test out the Woof implementation tonight. Seems only fair, as it was my silly idea after all. 😄

**Comment by fabiangreffrath** [comment]
Yes, that'd appreciated, thank you! I'll merge this if you say you can feel a difference. Also, the idea is absolutely not silly but excellent!

**Comment by mikeday0** [comment]
:+1: for the Woof implementation! Definitely smoother.

**Comment by fabiangreffrath** [comment]
Thank you! Would it make sense to restrict this to vsync enabled? Or will this clash with g-sync/freesync?

**Pull request merged**
