### PR TITLE
don't let failed loadgame attempts reset gameepisode/gamemap

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — APPROVED** [review]
LGTM

**Comment by fabiangreffrath** [comment]
Thanks! Actually, this bug was quite catastrophical: Load a PWAD, enter MAP01 and save a game. Load another PWAD, enter MAP02 and try to load the game from the first PWAD, decline the question and save the game instead. The savegame will be silently corrupted!

**Comment by rfomin** [comment]
Right, in Pr+ they moved the checksum/wads string before `gameskill = *save_p++; gameepisode = *save_p++;`, I didn't notice that.

**Comment by fabiangreffrath** [comment]
Yes, but they also build the checksum across all map lumps, whereas we only check for the current map's lumps. Needless to say I like our approach better. 😉

**Pull request merged**
