### PR TITLE
take the crosshair patch height and width into consideration

### LINKED ISSUE #1025: Crosshair leaves pixels behind if drawn over wide Status Bar
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/4836654377)._

See for yourself, towards the bottom right corner:
woof0001

Seems like fixing it is just a matter of redrawing those extra parts, whether they're rock background or a proper wide Status Bar graphic.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1025

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Does your approach wrap the crosshair around the view window boundaries?

I was thinking of something more simple like:
```patch
diff --git a/src/hu_stuff.c b/src/hu_stuff.c
index 7129915..e36f5bb 100644
--- a/src/hu_stuff.c
+++ b/src/hu_stuff.c
@@ -1306,8 +1306,14 @@ static void HU_UpdateCrosshair(void)

 void HU_UpdateCrosshairLock(int x, int y)
 {
-  crosshair.x = ((viewwindowx + x) >> hires) - WIDESCREENDELTA;
-  crosshair.y = ((viewwindowy + y) >> hires);
+  x >>= hires;
+  y >>= hires;
+
+  if (x > crosshair.w && x < scaledviewwidth - crosshair.w)
+    crosshair.x = x + (viewwindowx >> hires) - WIDESCREENDELTA;
+
+  if (y > crosshair.h && x < scaledviewheight - crosshair.h)
+    crosshair.y = y + (viewwindowy >> hires);
 }

 void HU_DrawCrosshair(void)
```

**Comment by rfomin** [comment]
> Does your approach wrap the crosshair around the view window boundaries?

Yes, although I've never used the lock on feature, I don't know how it's supposed to work. With your approach, it will be centered, right?

**Comment by rfomin** [comment]
The current version works like this::

https://user-images.githubusercontent.com/5077629/235610357-04dd60de-0de2-438c-b521-37a896d1f82e.mp4

Your patch didn't work, I don't know how to fix it.

**Comment by fabiangreffrath** [comment]
> The current version works like this:

That's how it's supposed to look, thank you!

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
