### PR TITLE
apply dpkg-buildflags during CI

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
Hmm, I don't understand what `eval "$(dpkg-buildflags --export=sh)"` does?

**Comment by fabiangreffrath** [comment]
It runs the code emitted by the command. Not sure if it actually works, I am experimenting with this...

**Comment by fabiangreffrath** [comment]
It seems to override compiler flags for clang but properly appends to them for gcc. 🤷

**Comment by rfomin** [comment]
don't know what's going on here 😄 We can enable LTO in cmake if you like.

**Comment by fabiangreffrath** [comment]
Doesn't work as I expected.

**Comment by fabiangreffrath** [comment]
> I don't know what's going on here 😄 We can enable LTO in cmake if you like.

I wanted to make sure we use at least Debian's default compiler flags, which contain some very reasonable defaults [1]. However, the set contains a flag affecting LTO that clang doesn't understand. Thus, by applying it from the environment, all the other compiler flag tests failed, because it complained about the LTO one.

See e.g. the "hardening" section of https://manpages.debian.org/testing/dpkg-dev/dpkg-buildflags.1.en.html

**Pull request closed without merging**
