### PR TITLE
use std memory functions in memio.c

### LINKED ISSUE #1820: Demo playback randomly crashes the port
When attempting to play various Doom 2 v1.9 compatible demos on woof (such as 22no0804, 30uvx942, 30no1552, 30uv2325) the game just closes itself for no reason. This is random, it might not happen at all during a full playback but when it does happen, it's usually a short while into the demo. I've tried setting the compatibility level for it but that didn't solve the issue.

All demos I've tested play back absolutely fine under PrBoom+ (UMAPINFO), dsda-doom 0.27.5 and doom2.exe

### PR DESCRIPTION
**Pull request by rfomin**
May fix #1820

@ceski-1 Could you please test this? I haven't been able to reproduce it yet.

### CODE REVIEW

**Comment by ceski-1** [comment]
Thanks, I will check it out when I'm back at my computer (it's late here).

**Comment by ceski-1** [comment]
I'm having trouble getting the game to crash again today _without_ the fix, so this may take a while to confirm.

**Comment by ceski-1** [comment]
Okay, I ran an hour of demo looping and there was no crashing with this PR. So what are the downsides of dropping the zone memory calls completely in these functions? No more contiguous memory? Performance impact on slower computers? Would it make more sense to have a separate `memio_std.c` just for special cases like midi, instead of affecting everything that currently uses `memio.c` functions?

**Comment by fabiangreffrath** [comment]
I don't think there are any downsides. Our `Z_Malloc()` is plain `malloc()` under the hood with some header information per allocated memory block to keep track of priority groups. As it is now, `Z_Malloc()` with `PU_STATIC` is more or less the same as `malloc()` already.

**Comment by rfomin** [comment]
I also agree that there is no downside.

I still cannot catch the crash with the master branch, maybe my CPU is not fast enough.

**Pull request merged**
