### PR TITLE
non power of two skies

### PR DESCRIPTION
**Pull request by rfomin**
Fixes sky in Sigil 2. Not sure about this.

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Looks plausible, sure. 

What happens at the max angle, when `0xffffffff` overflows to `0`?

Modulo is expensive. Should we add a power-of-2 check (e.g. `x & (x-1) == 0`) and call the regular function then, or should we leave this to the compiler and standard library?

**Comment by rfomin** [comment]
> What happens at the max angle, when `0xffffffff` overflows to `0`?

Nothing, it seems to be working fine.

> Modulo is expensive. Should we add a power-of-2 check (e.g. x & (x-1) == 0) and call the regular function then, or should we leave this to the compiler and standard library?

Almost everything in these functions is pre-calculated. You mean this line? `col %= texturewidth[tex];` I don't think it's worth it.

**Comment by fabiangreffrath** [comment]
> > What happens at the max angle, when `0xffffffff` overflows to `0`?
> Nothing, it seems to be working fine.

Hm, I think it's just unremarkable for this specific sky texture, but there is a gap: 

woof0000

**Comment by rfomin** [comment]
> Hm, I think it's just unremarkable for this specific sky texture, but there is a gap:

So this approach doesn't work? Does [#1323](https://github.com/fabiangreffrath/woof/pull/1323) fix it?

**Comment by fabiangreffrath** [comment]
> So this approach doesn't work? Does [#1323](https://github.com/fabiangreffrath/woof/pull/1323) fix it?

Nope. It just fixes the other cases reported after the original fix was applied.

**Comment by rfomin** [comment]
Does GZDoom have it as well?
Screenshot_Doom_20231212_185333
If so, then it's intended 😄

**Comment by fabiangreffrath** [comment]
Seems so. You have to look up to actually see it.

Screenshot_Doom_20231212_130525

**Comment by fabiangreffrath** [comment]
Erm, once more:

Screenshot_Doom_20231212_130826

**Comment by rfomin** [comment]
So everything is good? Should we do another bugfix release or wait a bit?

**Comment by fabiangreffrath** [comment]
Well, we are now on par with GZDoom. The rest is bad design decisions.

Not sure about the new release. I have nothing against it.

**Pull request merged**
