### PR TITLE
add half pixel correction to fix distortion

### PR DESCRIPTION
**Pull request by rfomin**
Before:
woof0004
After:
woof0003
Test WAD: [test_plane.zip](https://github.com/fabiangreffrath/woof/files/11549191/test_plane.zip)

The fix was taken from Eternity Engine: https://github.com/team-eternity/eternity/blob/4559505c1f0a08e27e03e226574e7a7c43865984/source/r_plane.cpp#L210-L218 (they use floats so they actually can calculate the exact center).

The same issue is present in Crispy Doom and PrBoom+/DSDA-Doom software render. Thanks to @JNechaevsky for bug report and testing.

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
LGTM, thanks!

**Comment by JNechaevsky** [comment]
Would you mind if I'll PR this code to Crispy * ? One question, though - should this code:
```
  if (centery == y)
    return;
  else if (y < centery)
    dy = (abs(centery - y) << FRACBITS) - FRACUNIT / 2;
  else
    dy = (abs(centery - y) << FRACBITS) + FRACUNIT / 2;
```
...be simplified to:
```
  if (centery == y)
    return;

    dy = (abs(centery - y) << FRACBITS) + (y < centery ? -FRACUNIT : FRACUNIT) / 2;
```

**Comment by fabiangreffrath** [comment]
Sure, it won't hurt. :wink:

**Comment by kraflab** [comment]
Is it weird that I prefer this kind of quirk to the fixed version? 😅

**Comment by JNechaevsky** [comment]
Wierd indeed! I have checked - real life engine is also using fixed version of planes drawing. :grinning: 

image

**Pull request merged**
