### PR TITLE
cross-fading screen wipe implementation

### LINKED ISSUE #1547: `wipe_ColorXForm` is broken in some resolutions
_Tested in the [latest master commit](https://github.com/fabiangreffrath/woof/commit/aa10fcc17d47099420e72fcab0004dc397b93178)._

Before anything, I'd like to say that **I consider this to be of very low priority**.

The unused "ColorXForm" wipe seems to have been broken with the recent addition of arbitrary-resolution support, in spite of the changes made to its code.

With 300% resolution at 16:9 widescreen, by the end of the wipe the screen looks like this (it returns to normal afterwards):
imagen

Knowing that it is unused, I believe it could very well just be removed altogether. However, if you insist on keeping it, I believe it should at least be working properly; I've fixed it for Nugget (https://github.com/MrAlaux/Nugget-Doom/commit/433b76e35fe937d3531ec8a30812aa02421e3e7a), so I could make a PR fixing it for Woof.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #1547

### CODE REVIEW

**Comment by rfomin** [comment]
While we here, I suggest adding this to not "trash the CPU":
```diff
diff --git a/src/d_main.c b/src/d_main.c
index 26e28f7..a7ec34a 100644
--- a/src/d_main.c
+++ b/src/d_main.c
@@ -448,6 +448,7 @@ void D_Display (void)
       int nowtime, tics;
       do
         {
+          I_Sleep(1);
           nowtime = I_GetTime();
           tics = nowtime - wipestart;
         }
```

**Review by rfomin — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
More fun with screen wipes. Today: ROTT style! :clown_face: 

```C
static int wipe_doColorXForm(int width, int height, int ticks)
{
  const float rot = fade_tick * 2 * M_PI / 32;
  const float cosrot = cos(rot), sinrot = sin(rot);
  float scale;
  byte *src;

  if (fade_tick <= 32)
  {
    scale = (32. - fade_tick) / 32;
    src = wipe_scr_start;
  }
  else
  {
    scale = (fade_tick - 32.) / 32;
    src = wipe_scr_end;
  }

  memset(wipe_scr, 0, height * video.pitch);

  for (int y = 0; y < height; y++)
  {
    for (int x = 0; x < width; x++)
    {
      int newx, newy;

      x -= width / 2;
      y -= height / 2;

      newx = (int)(scale * (cosrot * x - sinrot * y));
      newy = (int)(scale * (cosrot * y + sinrot * x));

      x += width / 2;
      y += height / 2;

      newx += width / 2;
      newy += height / 2;

      if (newx >=0 && newx < width && newy >= 0 && newy < height)
      {
        wipe_scr[newy * video.pitch + newx] = src[y * width + x];
      }
    }
  }

  fade_tick += ticks;

  return (fade_tick > 64);
}
```

**Comment by rfomin** [comment]
> More fun with screen wipes. Today: ROTT style!

It looks fun, but I think Doom is too "serious" for that 😄

**Comment by fabiangreffrath** [comment]
Sure, I was just experimenting with some other transitions.

**Pull request merged**
