### PR TITLE
avoid unnecessary bit-shifts in ds_xstep/ds_ystep calculation

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
@liPillON I don't expect miracles from this change, but nevertheless. 😉

**Comment by liPillON** [comment]
yeah I'm getting 113 fps at best, basically the same performance as with #1110

**Comment by rfomin** [comment]
Compilers are smart enough to optimize it. The generated code is the same: https://godbolt.org/z/6EMfn7hfY

**Comment by rfomin** [comment]
> What's more readable than a plain multiplikation and division?

But these are not plain operations, these are operations according to the rules of fixed-point arithmetic. Okay, but would it be nice to add a comment.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
