### PR TITLE
Refresh status bar background when cycling automap overlay in fullscreen

### PR DESCRIPTION
**Pull request by ceski-1**
Fixes https://github.com/fabiangreffrath/woof/issues/1762

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Although this looks correct to me, it's a bit sad that this is necessary. But I guess this is the price to pay for not strictly keeping drawer and ticker functions separate.

**Comment by fabiangreffrath** [comment]
Or let's rather say, for setting states in drawer functions that depend on other states set in thinker functions.

**Comment by ceski-1** [comment]
I agree that this isn't ideal. Maybe it's worth looking for a solution that doesn't need to run every frame.

**Review by rfomin — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
