### PR TITLE
scale ENDOOM with "nearest" quality, keep "linear" else

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by ceski-1** [comment]
Awful:
Untitled

**Comment by fabiangreffrath** [comment]
Apparently not that easy.

**Comment by fabiangreffrath** [comment]
> Awful: Untitled

Granted, this looks aweful. But this is the result of some non-integer scaling of the screen, right? I am asking because maybe this is a solution (https://github.com/fabiangreffrath/woof/issues/929#issuecomment-1460915399).

**Comment by ceski-1** [comment]
That's right. That's what it looks like at completely default settings except windowed. If you do integer multiples some people will wonder why the ENDOOM screen isn't aspect ratio corrected. If you do aspect ratio correction you'll have some people wonder why the text is uneven (nearest) or blurry (any kind of filtering). rfomin's suggestion of using .ttf is probably a better long term solution.

**Comment by ceski-1** [comment]
If you want a simple solution for now that is a compromise, why not render to a giant texture at nearest, then copy to a smaller target with linear? Like Chocolate.

**Comment by fabiangreffrath** [comment]
Yes, maybe we should go the 320x200 -> 1600x1200 (nearest) -> screen (linear) way for textscreen.

**Comment by ceski-1** [comment]
I would also suggest only using the "normal" font since that one is faithful to the way DOS looked. The large one is too rounded.

**Pull request closed without merging**
