### PR TITLE
Fix interpolation frac overflow

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
https://github.com/kraflab/dsda-doom/commit/1a9f1a6053ddfba4a102c93f5bc25cf9c375066e

**Comment by fabiangreffrath** [comment]
I don't get why this fails to build. `extern int gametic` is declared in `doomstat.h` which is included.

**Comment by rfomin** [comment]
> I don't get why this fails to build. `extern int gametic` is declared in `doomstat.h` which is included.

This is because the woof-setup target does not include doomstat.h/doomstat.c (and I don't think it should).

Have you been able to reproduce this issue? There is an original report: https://discord.com/channels/218106532406099969/776233266411339786/1230919513747357769

**Comment by fabiangreffrath** [comment]
> This is because the woof-setup target does not include doomstat.h/doomstat.c (and I don't think it should).

Ouch, I didn't realize this is a linking error.

> Have you been able to reproduce this issue? There is an original report: https://discord.com/channels/218106532406099969/776233266411339786/1230919513747357769

No, I have never encountered this issue myself. The youtube video doesn't appear to be available anymore.

**Comment by rfomin** [comment]
Perhaps we had a similar problem before: https://github.com/fabiangreffrath/woof/commit/28f0d25c3f3a5661841959e9f62a2df375f8b292

**Comment by ceski-1** [comment]
I guess I don't get it. How often is `GetTimeMS_Scaled() * TICRATE` overflowing? Was this happening in single player or multiplayer? Which version of Woof?

**Comment by rfomin** [comment]
> How often is `GetTimeMS_Scaled() * TICRATE` overflowing?

So far I haven't been able to get `GetTimeMS_Scaled() * TICRATE` to overflow. I suggest to wait with this fix, maybe we will get another bug report.

**Comment by fabiangreffrath** [comment]
Right, so far I haven't been able to identify the short hickup in this video either.

https://discord.com/channels/218106532406099969/1205400822687473705/1303037061103878194

**Pull request closed without merging**
