### PR TITLE
fix voxel rendering clipping flicker

### PR DESCRIPTION
**Pull request by rfomin**
Earlier fix was not enough.

Fix this issue: https://github.com/fabiangreffrath/woof/pull/1266#issuecomment-1817461243 Perhaps we should ask author about it.

### CODE REVIEW

**Comment by rfomin** [comment]
I tested the build of https://gitlab.com/andwj/voxel-rend and there are no issues. So the integer overflow still only happens in hires, my previous fix was just wrong.

**Comment by fabiangreffrath** [comment]
I wonder if we should rather declare some variables as `int64_t` instead of casting?

**Comment by rfomin** [comment]
> I wonder if we should rather declare some variables as `int64_t` instead of casting?

I don't know, from my testing it doesn't seem to be necessary. Admittedly, I don't really understand what's going on in that part of the code.

**Comment by fabiangreffrath** [comment]
Okay, let's fix it incrementally. I'm glad you found that overflow.

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
