### PR TITLE
implement multiplayer setup (based on Chocolate Doom)

### PR DESCRIPTION
**Pull request by rfomin**
It's not finished, needs some polishing. Not sure about colors, I like "Romero Blue". Also we don't have an icon.

I'm thinking about enabling scaling or alternative font from https://int10h.org/oldschool-pc-fonts/

### CODE REVIEW

**Comment by rfomin** [comment]
Also at the moment we have two versions of `doomkeys.c` - in the main game and in libtextscreen. I suggest syncing them to the version from Choco.

**Comment by fabiangreffrath** [comment]
> Also at the moment we have two versions of `doomkeys.h` - in the main game and in libtextscreen. I suggest syncing them to the version from Choco.

Yes, agreed.

**Comment by fabiangreffrath** [comment]
Sorry for the long break, family holidays in the Netherlands. Feel free to merge this if you feel like it @rfomin.

**Comment by fabiangreffrath** [comment]
Let's please squash-merge multi-commit PRs as long as they build a "logical unit".

**Comment by rfomin** [comment]
> Let's please squash-merge multi-commit PRs as long as they build a "logical unit".

Oh, this is what I wanted to do. I guess I messed up with github ui. Should we revert this?

**Pull request merged**
