### PR TITLE
FOV adjustments for skies

### PR DESCRIPTION
**Pull request by ceski-1**
Fixes https://github.com/fabiangreffrath/woof/issues/1471

### CODE REVIEW

**Comment by ceski-1** [comment]
https://github.com/fabiangreffrath/woof/assets/56656010/a8f134a4-dd14-4d93-b46a-bd56eabe49da

**Comment by MrAlaux** [comment]
I like it!

Though, I personally don't quite like that the stretched sky still has a "seam" at the top with a sufficiently-high FOV -- after all, I enable sky stretching to get rid of that seam.

Keeping the sky size constant regardless of FOV would be weird, but what about just stretching it vertically to fit the screen? That's what I do in Nugget, see:

<details>
<summary>
Spoiler
</summary>

FOV = 120:
imagen

FOV = 160:
imagen

Note that the sky is overly-stretched in both cases since I couldn't figure out the proper math. 120 looks good to me even with the over-stretch, and Woof doesn't go beyond that for now, so the distorted sky at 160 isn't much of an issue yet; do keep it in mind, though.

</details>

**Comment by ceski-1** [comment]
> I personally don't quite like that the stretched sky still has a "seam" at the top with a sufficiently-high FOV

Me neither, that's why I lingered on it in the video to see what others thought. I'll brainstorm some more, thanks for the suggestions.

**Comment by rfomin** [comment]
> > I personally don't quite like that the stretched sky still has a "seam" at the top with a sufficiently-high FOV
> 
> Me neither, that's why I lingered on it in the video to see what others thought. I'll brainstorm some more, thanks for the suggestions.

I like the way it works at the moment, not sure if we should make it more complicated.

**Comment by ceski-1** [comment]
I think we're kind of stuck with the `228` value for `SKYSTRETCH_HEIGHT` to comply with: https://zdoom.org/wiki/Sky_stretching while also trying to preserve a consistent look across all FOVs. So it's a trade-off. Maybe it's best to leave it simple for now?

**Comment by rfomin** [comment]
> Maybe it's best to leave it simple for now?

I vote yes.

**Comment by fabiangreffrath** [comment]
+1 for keeping it simple.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
