### PR TITLE
implement bilinear sharpening from Crispy Doom

### PR DESCRIPTION
**Pull request by rfomin**
Seems to be a popular feature request. I think the difference is worth it:
on
image
off
image

I wanted to do it with shaders, but it's tricky if we need direct3d and opengl support, maybe in the next release. To be honest, the difference with the SDL implementation is not that big, from my experiments. Also zero performance difference on my system.

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Well, okay. 😉

**Comment by ceski-1** [comment]
Woof seems blurrier than Crispy for some reason:

Crispy (smooth pixel scaling: on):
crispy

Woof (enable bilinear sharpening: yes):
woof

**Comment by rfomin** [comment]
> Woof seems blurrier than Crispy for some reason

Woof only scales by 2x, Crispy can choose a larger factor. Perhaps I should copy Crispy's logic.. @fabiangreffrath?

**Comment by fabiangreffrath** [comment]
> > Woof seems blurrier than Crispy for some reason
> 
> Woof only scales by 2x, Crispy can choose a larger factor. Perhaps I should copy Crispy's logic. @fabiangreffrath?

Yes, sure, whatever you prefer. 😁

**Pull request merged**
