### PR TITLE
Revert "don't use SDL_RenderSetLogicalSize (#1847)"

### PR DESCRIPTION
**Pull request by rfomin**
This reverts commit 8a8a47c29ef7d9a3c1f03fc8daaf0bbd7b05544a.

It was reported that this makes the image more blurred.

### CODE REVIEW

**Comment by gendlin** [comment]
Isn't this more a side effect of smooth pixel scaling being enabled?

**Comment by rfomin** [comment]
> Isn't this more a side effect of smooth pixel scaling being enabled?

Maybe, but I like this feature. I honestly don't see much of a problem, but I mostly use a small laptop, maybe on a larger monitor it's a different story.

**Comment by ceski-1** [comment]
@xemonix0 You mentioned blurriness with the recent logical size changes. Does this PR fix that issue for you?

**Comment by gendlin** [comment]
> Maybe, but I like this feature. I honestly don't see much of a problem, but I mostly use a small laptop, maybe on a larger monitor it's a different story.

I'm just saying this person could fix the blurriness issue by turning that option off, rather than by us removing this otherwise useful code. Or we could just force off smooth scaling at integer scales (where it previously did nothing but increase GPU overhead, except for a weird special case where scaled up buffer == output res)

**Comment by rfomin** [comment]
> Or we could just force off smooth scaling at integer scales (where it previously did nothing but increase GPU overhead, except for a weird special case where scaled up buffer == output res)

As we use aspect ratio correction we can't have perfect integer scale.  See "bilinear downsampling" is what "smoth scaling" really is.

On:
image
Off:
image

**Comment by gendlin** [comment]
> See "bilinear downsampling" is what "smoth scaling" really is

I know. It sucks. :)

> we can't have perfect integer scale.

Right, other than at 1600x1200. I was more thinking about the horizontal axis, but the whole point of smooth pixel scaling is to add blur - if you don't like blur it should be turned off (and it should be off by default IMO).

**Comment by rfomin** [comment]
> > See "bilinear downsampling" is what "smoth scaling" really is
> 
> I know. It sucks. :)

Perhaps we can improve it somehow. Maybe we will try some shaders with SDL3.

> (and it should be off by default IMO).

For me it's better than raw nearest neighbor.

**Comment by xemonix0** [comment]
> @xemonix0 You mentioned blurriness with the recent logical size changes. Does this PR fix that issue for you?

Yes, looks great, just like in 14.5.0

**Review by ceski-1 — APPROVED** [review]
Looks okay to me too. Maybe SDL3 will open up some shader opportunities. For now, the "use an upscaled nearest multiple, then bilinear filter the rest of the way" approach is the best compromise we have and it can always be disabled for a nice performance boost on older computers.

**Pull request merged**
