### PR TITLE
Add "FOV Affects Skies" toggle

### PR DESCRIPTION
**Pull request by ceski-1**
[Doomworld post](https://www.doomworld.com/forum/post/2801996) describing request.
[Previous discussion](https://github.com/fabiangreffrath/woof/pull/1474#issuecomment-1945319647) where we originally wanted this.

The menu item is a placeholder for quick testing only, unless we want to keep it.

There are pros and cons to various sky settings:

https://github.com/fabiangreffrath/woof/assets/56656010/78fe2a14-e200-4554-b36e-b61d7cb834ff

### CODE REVIEW

**Comment by MrAlaux** [comment]
> The menu item is a placeholder for quick testing only, unless we want to keep it.

I only remember a single request for this -- the one you linked, no less -- so I think it can be kept config-only until and unless more people ask for it.

By the way, thanks for this!

**Comment by rfomin** [comment]
I like this option, it looks more natural when the FOV doesn't affect the sky, it works the same way in most games doesn't it?
I suggest `fovsky == false` by default and make it config only option.

**Comment by ceski-1** [comment]
> I think it can be kept config-only until and unless more people ask for it.

> I suggest `fovsky == false` by default and make it config only option.

I agree.

**Comment by ceski-1** [comment]
I'd like to know what others think about `fovsky 0` with a high FOV. I think the sky looks a little odd when looking up and down.

**Comment by rfomin** [comment]
> I'd like to know what others think about `fovsky 0` with a high FOV. I think the sky looks a little odd when looking up and down.

I think high FOV looks odd in general, so it's okay.

**Comment by fabiangreffrath** [comment]
> I'd like to know what others think about `fovsky 0` with a high FOV. I think the sky looks a little odd when looking up and down.

I never play with `fov != 90`, but i think the scrolling feels completely unnatural when turning with `fovsky 0`.

**Comment by MrAlaux** [comment]
> I'd like to know what others think about `fovsky 0` with a high FOV. I think the sky looks a little odd when looking up and down.

I agree, the movement looks weird. I might be missing something, but what if the vertical displacement were affected by FOV? I.e. it moves less with a higher FOV, and vice versa. The user who made the request you linked implicitly doesn't use mouselook, so that's an aspect we can play with.

**Comment by fabiangreffrath** [comment]
I'm fine with adding this as a config-only feature. I don't care if enabled or disabled by default, I don't use FOV!=90 anyway. 😉

**Comment by ceski-1** [comment]
I'll come back to this once I finish up with input refactoring.

**Comment by ceski-1** [comment]
I'm going to abandon this since I can't figure out a good solution. Some aspects of the sky rendering code make absolutely no sense.

**Comment by rfomin** [comment]
> I'm going to abandon this since I can't figure out a good solution. Some aspects of the sky rendering code make absolutely no sense.

I like the solution in this PR already, what is so bad about it?

**Comment by ceski-1** [comment]
> I like the solution in this PR already, what is so bad about it?

It doesn't look right to me when turning or using free look. The list of criteria for a proper sky implementation is, in my opinion: correct top edge alignment, correct "baseline" alignment, must work with the 4 or 5 sky types, and must rotate consistently with the current FOV. These goals conflict with each other. I tried a few other approaches and they always fell short in one way or another.

**Comment by rfomin** [comment]
> The list of criteria for a proper sky implementation is, in my opinion: correct top edge alignment, correct "baseline" alignment, must work with the 4 or 5 sky types, and must rotate consistently with the current FOV.

It's a long list. Perhaps we shouldn't be so strict, I think many users would appreciate this feature even in the form of this PR.

**Comment by ceski-1** [comment]
> It's a long list. Perhaps we shouldn't be so strict, I think many users would appreciate this feature even in the form of this PR.

Maybe I'll come back to this later, but with a different approach.

**Pull request closed without merging**
