### PR TITLE
Prevent light scale overflow

### PR DESCRIPTION
**Pull request by ceski-1**
Fixes https://github.com/fabiangreffrath/woof/issues/1603

Can you try this @MrAlaux?

### CODE REVIEW

**Comment by rfomin** [comment]
It works for me, good find!

**Comment by MrAlaux** [comment]
Looks like this fixes it. As far as I tested, the strips don't manifest anymore, and using the saves that I shared, this PR's screenshots are identical to 12.0.2's... mostly.

It seems to be unrelated to this particular issue, but there's a tiny discrepancy between these two screenshots:

[screenshots.zip](https://github.com/fabiangreffrath/woof/files/14646938/screenshots.zip)

Look slightly to the left of the zombieman that's closer to the middle of the screen, on the gray/silver tech texture. The master artifact that I tested this issue on already had the discrepancy, though, so it wasn't these changes that introduced it.

**Comment by ceski-1** [comment]
> It seems to be unrelated to this particular issue, but there's a tiny discrepancy between these two screenshots:

Yes, I see it too. It's very subtle. It seems unrelated to this issue/PR, like you said, so something to look at later. I did a difference layer in Photoshop and bumped up the levels to make it obvious (ignore the status bar eyes):

<details><summary>Difference Layer</summary>

diff

</details>

**Comment by fabiangreffrath** [comment]
Very good catch, both of you!

**Pull request merged**
