### PR TITLE
use actual thing height in aiming code path

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by ceski-1** [comment]
Two suggestions:

<details>
<summary>1. Crosshair fix</summary>

https://github.com/fabiangreffrath/woof/assets/56656010/8ea682ff-5240-40bc-a4e8-503ed511db89

```diff
diff --git a/src/r_things.c b/src/r_things.c
index dd6644f..05026e4 100644
--- a/src/r_things.c
+++ b/src/r_things.c
@@ -645,10 +645,12 @@ void R_ProjectSprite (mobj_t* thing)
   // [Alaux] Lock crosshair on target
   if (STRICTMODE(hud_crosshair_lockon) && thing == crosshair_target)
   {
+    const fixed_t thingheight = direct_vertical_aiming ? thing->info->actualheight : thing->height;
+
     HU_UpdateCrosshairLock
     (
       BETWEEN(0, viewwidth  - 1, (centerxfrac + FixedMul(txc, xscale)) >> FRACBITS),
-      BETWEEN(0, viewheight - 1, (centeryfrac + FixedMul(viewz - interpz - crosshair_target->height/2, xscale)) >> FRACBITS)
+      BETWEEN(0, viewheight - 1, (centeryfrac + FixedMul(viewz - interpz - thingheight/2, xscale)) >> FRACBITS)
     );
 
     crosshair_target = NULL; // Don't update it again until next tic
```

</details>

<details>
<summary>2. Autoaim fix</summary>

https://github.com/fabiangreffrath/woof/assets/56656010/d322c6b6-0f8c-4044-bd6e-ec6f9ef33d73

```diff
diff --git a/src/p_mobj.c b/src/p_mobj.c
index ee57342..ee2f85d 100644
--- a/src/p_mobj.c
+++ b/src/p_mobj.c
@@ -1481,11 +1481,6 @@ mobj_t* P_SpawnPlayerMissile(mobj_t* source,mobjtype_t type)
     {
       // killough 8/2/98: prefer autoaiming at enemies
       int mask = demo_version < 203 ? 0 : MF_FRIEND;
-      if (direct_vertical_aiming)
-      {
-        slope = source->player->slope;
-      }
-      else
       do
 	{
 	  slope = P_AimLineAttack(source, an, 16*64*FRACUNIT, mask);
@@ -1494,7 +1489,10 @@ mobj_t* P_SpawnPlayerMissile(mobj_t* source,mobjtype_t type)
 	  if (!linetarget)
 	    slope = P_AimLineAttack(source, an -= 2<<26, 16*64*FRACUNIT, mask);
 	  if (!linetarget)
-	    an = source->angle, slope = 0;
+	  {
+	    an = source->angle;
+	    slope = direct_vertical_aiming ? source->player->slope : 0;
+	  }
 	}
       while (mask && (mask=0, !linetarget));  // killough 8/2/98
     }
```

```diff
diff --git a/src/p_pspr.c b/src/p_pspr.c
index f64e069..3ae5530 100644
--- a/src/p_pspr.c
+++ b/src/p_pspr.c
@@ -793,11 +793,6 @@ void A_FireOldBFG(player_t *player, pspdef_t *psp)
 	  // killough 8/2/98: make autoaiming prefer enemies
 	  int mask = MF_FRIEND;
 	  fixed_t slope;
-	  if (direct_vertical_aiming)
-	  {
-	    slope = mo->player->slope;
-	  }
-	  else
 	  do
 	    {
 	      slope = P_AimLineAttack(mo, an, 16*64*FRACUNIT, mask);
@@ -806,7 +801,10 @@ void A_FireOldBFG(player_t *player, pspdef_t *psp)
 	      if (!linetarget)
 		slope = P_AimLineAttack(mo, an -= 2<<26, 16*64*FRACUNIT, mask);
 	      if (!linetarget)
-		slope = 0, an = mo->angle;
+	      {
+	        an = mo->angle;
+	        slope = direct_vertical_aiming ? mo->player->slope : 0;
+	      }
 	    }
 	  while (mask && (mask=0, !linetarget));     // killough 8/2/98
 	  an1 += an - mo->angle;
```

</details>

**Comment by ceski-1** [comment]
Test map: [spawntest.zip](https://github.com/fabiangreffrath/woof/files/12696714/spawntest.zip)
```
woof -file DOTB_RC3.wad spawntest.wad -warp 1
```

**Comment by fabiangreffrath** [comment]
Thank you!

> 1. Crosshair fix

Wouldn't this change also make sense in the non-direct aiming case?

**Comment by fabiangreffrath** [comment]
> Test map: [spawntest.zip](https://github.com/fabiangreffrath/woof/files/12696714/spawntest.zip)

And thank you again!

I just ran this test map, and unfortunately it shows that using the pixel height of the spawn state does not properly work in this case. The sprite height is about three times taller in the awaken state, but the aiming code is never updated to reflect this.

**Comment by ceski-1** [comment]
> Wouldn't this change also make sense in the non-direct aiming case?

`PTR_AimTraverse()` aims at the [center of the thing's height](https://github.com/fabiangreffrath/woof/blob/e1e8e06e96c4ee3920ff69b3b2f12b522dc5a5df/src/p_map.c#L1508). The spawn uses Keen's default `height` (72), so with direct vertical aiming disabled, aiming/firing/crosshair should all be 36 units above the floor. If direct vertical aiming is enabled, the game is now aiming at the center of the initial sprite's (KEENM1) height (26), so aiming/firing/crosshair should all be 13 units above the floor.

Now there's an argument to be made if the "actual height" should account for the sprite's offset, or if it should be updated every time the sprite changes, or if this is a bad idea altogether and only the `height` should be used at all times. There are pros and cons to each approach.

**Comment by ceski-1** [comment]
> I just ran this test map, and unfortunately it shows that using the pixel height of the spawn state does not properly work in this case. The sprite height is about three times taller in the awaken state, but the aiming code is never updated to reflect this.

Right, so as I mentioned above, to solve that mean updating the sprites for each frame change or using the fixed `height` value.

**Comment by fabiangreffrath** [comment]
As outlined on discord, we cannot use the `height` value from `info.c`, because e.g. the "Romero's head on a stick" enemy has a height value of 16, whereas the actual sprite is much taller. So, you would always shoot above it with direct vercial aiming enabled if not pointing at the pool of blood at its bottom.

**Comment by fabiangreffrath** [comment]
> Wouldn't this change also make sense in the non-direct aiming case?

What I meant here is, since the crosshair locking on the target is merely a cosmetic aid, wouldn't it make sense to have it *always* locked at the *visible* center of the sprite (instead of the one set in `info.c`), regardless of direct vertical aiming being enabled or not?

**Comment by MrAlaux** [comment]
> As outlined on discord, we cannot use the `height` value from `info.c`, because e.g. the "Romero's head on a stick" enemy has a height value of 16, whereas the actual sprite is much taller. So, you would always shoot above it with direct vercial aiming enabled if not pointing at the pool of blood at its bottom.

Admittedly, Romero's head being so short has similar consequences in Vanilla: if you fire projectiles at it from far away (enough for vertical autoaim not to take effect), they go through the head without colliding. Ugly, yes, but that's simply how it was (maybe carelessly) designed. Modmakers might do such a thing deliberately.

For what it's worth, I personally vouch for sticking to `height` for Direct Vertical Aiming; `actualheight` still seems useful for 3D Audio. If you wish to stick to `actualheight`, though, maybe it could be made so that `actualheight` is never lesser than `height`?

**Comment by fabiangreffrath** [comment]
We don't have to stick to the `actualheight` concept if it's consensus that it does more harm than good, or does not good enough to justify all the corner cases that it brings.

**Comment by ceski-1** [comment]
Maybe something like this?

**Aiming and Shooting**:
Always use `height`. When using `direct_vertical_aiming`, to prevent issues aiming when there are sprite/hitbox mismatches (Romero's head), increase the vertical autoaim range [here](https://github.com/fabiangreffrath/woof/blob/e1e8e06e96c4ee3920ff69b3b2f12b522dc5a5df/src/p_map.c#L1679) so that it's more forgivable.

**Crosshair and 3D Audio**:
Always aim at the center of sprite (`patch->height`). May have to consider offsets (`topoffset`, maybe `leftoffset`) in case of floating/ceiling/sunken sprites.

**Comment by fabiangreffrath** [comment]
Sounds like a reasonable approach. But, when using actual sprite height for crosshair centering, the crosshair may jump up and down when poiting at enemies during their idle animation - as can be seen e.g. for the two zombiemen at the start of MAP01.

**Comment by ceski-1** [comment]
Some kind of smoothing could help there (easing, lerp, etc.). Hopefully the sound moving around isn't nauseating. A lot to consider with this topic.

**Comment by fabiangreffrath** [comment]
This could be mitigated if we update `actualheight` only when changing sprite, but not when changing frames.

**Comment by fabiangreffrath** [comment]
I think I am somehow stuck here. 🙇

**Comment by fabiangreffrath** [comment]
Superseded by #1213

**Pull request closed without merging**
