### PR TITLE
any resolution (i.e. any multipe of 200p) rendering

### PR DESCRIPTION
**Pull request by fabiangreffrath**
This is a quick prototype of an "any resolution" rendering implementation, whereas "any" actually means "any multiple of 200p" - and even this is currently very restricted to 600p, because that's the easiest case to test.

This is WIP and as much of a quirk as it can get. I'm just posting this here to share the idea.

What doesn't work is the view window rendering, because I didn't focus on fixing this yet. Also, I'm not satisfied with static array sizes anymore and would like to dynamically reallocate anything that's currently `array[MAX_SCREENWIDTH]` etc. Also, I'm sure there is a more sophisticated solution to patch drawing than merely drawing each pixel multiple times in both dimension.

### CODE REVIEW

**Comment by liPillON** [comment]
wow this is a surprise..

are you aware that @MrAlaux has tested this for a while and just [merged](https://github.com/MrAlaux/Nugget-Doom/pull/77) it?

**Comment by rfomin** [comment]
Looks good, but what if we make `hires_mult` `fixed_t` or even `float`? Then we'll really get any resolution.

**Comment by fabiangreffrath** [comment]
> what about the code that @MrAlaux has tested for a while and just [merged](https://github.com/MrAlaux/Nugget-Doom/pull/77)?

I wasn't aware of that, but it looks... familiar. :grin: 

> Looks good, but what if we make `hires_mult` `fixed_t` or even `float`? Then we'll really get any resolution.

Wouldn't we get ugly back-and-forth casting if we used `float`? And using `fixed_t` would turn it even more into a mess..

**Comment by rfomin** [comment]
> > Looks good, but what if we make `hires_mult` `fixed_t` or even `float`? Then we'll really get any resolution.
> 
> Wouldn't we get ugly back-and-forth casting if we used `float`? And using `fixed_t` would turn it even more into a mess..

We can set any `SRCEENWIDTH` `SCREENHEIGHT` and most of the engine will already work. The only problematic parts are rendering patches (v_video.c) and various little things like tiles. I think we can solve this with `fixed_t hires_mult`, with rounding errors, but close enough. Well, I'll have to try it myself.

**Comment by fabiangreffrath** [comment]
Yes, please, feel free to improve on this. I'm not sure how far I'm going to push it myself.

**Comment by rfomin** [comment]
> Yes, please, feel free to improve on this. I'm not sure how far I'm going to push it myself.

I've been really slow lately, maybe this weekend. This PR will already satisfy most people, not much left to fix 👍

**Comment by ceski-1** [comment]
Finally! Now add custom resolutions and multithreading. 😉

<details><summary>This should fix the borders:</summary>

```diff
diff --git a/src/r_draw.c b/src/r_draw.c
index aafe916..59eab83 100644
--- a/src/r_draw.c
+++ b/src/r_draw.c
@@ -899,9 +899,14 @@ static void R_VideoErase(unsigned ofs, int count)
 { 
   if (hires)     // killough 11/98: hires support
     {
-      ofs = ofs * hires_square - (ofs % SCREENWIDTH) * hires_mult;   // recompose offset
-      memcpy(I_VideoBuffer + ofs, background_buffer + ofs, count *= hires_mult);   // LFB copy.
-      ofs += SCREENWIDTH * hires_mult;
+      int i;
+      ofs = ofs * hires_square - (ofs % SCREENWIDTH) * (hires_square - hires_mult);   // recompose offset
+      count *= hires_mult;
+      for (i = 0; i < hires_mult - 1; i++)
+      {
+        memcpy(I_VideoBuffer + ofs, background_buffer + ofs, count);   // LFB copy.
+        ofs += SCREENWIDTH * hires_mult;
+      }
     }
   memcpy(I_VideoBuffer + ofs, background_buffer + ofs, count);   // LFB copy.
 } 
```

</details>

**Comment by fabiangreffrath** [comment]
> Finally! Now add custom resolutions and multithreading. 😉
> 
> This should fix the borders:

Thanks for this. I'm trying to get rid of any `if (hires)` branching, but this helps anyway.

**Comment by MrAlaux** [comment]
I think all of you know that Nugget has higher resolutions already: squares of 2 for months, and multiples of 200p for about a week. Might be a trivial thing to say, but if that's of any help, feel free to check out the code. I'd offer to give directions, but I can only explain so much, given that ceski did most of the work.

@liPillON already mentioned some of it, including the attempt at dynamically-allocated arrays which for some reason destroyed performance, at least in timedemos.

**Comment by fabiangreffrath** [comment]
@MrAlaux Thanks for chiming in! I think I've got pretty far with my naive approach already. My priorities now are getting rid of any `if (hires)` branch where that's possible (and then rename `hires_mult` back to `hires` and interpret it as a multiplicator as in Nugget). In that context, I'd like to find a more sophisticated algorithm for drawing patches, e.g. by drawing entire *columns* multiple times instead of drawing them once but each pixel multiple times.

I am probably only going up to 800p, so the maximum array size is not *that* much of a concern currently, but definitely something to keep in mind.

**Comment by MrAlaux** [comment]
> Also, I'll have to see how you managed to keep blocky spectre drawing intact.

Not sure if _intact_, but here's what I did (sorry that's it's not a diff, I still haven't used those):

https://github.com/MrAlaux/Nugget-Doom/blob/5aee869c86512c9b9a18ce33a827b9f6b57da165/src/r_draw.c#L556-L563

**Comment by fabiangreffrath** [comment]
> Not sure if _intact_, but here's what I did (sorry that it's not a diff, I still haven't used those):

Thanks, I think I'll just take this verbatim.

What do you guys think should the menu entry look like?

* Rendering Resolution: "low", "normal", "high", "very high"
* Rendering Resolution: "200p", "400p", "600p", "800p"
* Rendering Resolution Factor: "1", "2", "3", "4"

Any other suggestions?

**Comment by MrAlaux** [comment]
> What do you guys think should the menu entry look like?

For Nugget, I opted for `Factor (###p)`, i.e. `1X (200p)`, `2X (400p)` and so on. Maybe we could do with just `###p`, but I'm definitely not very fond of using "low", "normal" (this one label is particularly vague IMO) and the like; they're not particularly future-proof either, in case you decide to go higher.

Something else that I did in Nugget and you may want to consider is reporting the current renderer resolution  based on resolution factor, aspect ratio correction and widescreen.
When corrected, 600p actually covers the full height of a 720p display, and also the full width if widescreen is set to 16:9, but an unknowing user could assume that 800p is actually the closest option.

**Comment by liPillON** [comment]
> I am probably only going up to 800p, so the maximum array size is not _that_ much of a concern currently, but definitely something to keep in mind.

I think that reaching 5x (1000p native, 1200p aspect-corrected) would be preferable since that seems to be the ideal target resolution for upscaling and aspect-correcting old 320x200 titles without artifacts (both horizontal and vertical resolution would be multipled using integers, 5x and 6x respectively)

**Comment by rfomin** [comment]
> since this implementation is basically the same as what's in current nugget-master, I'm setting up a quick benchmarking environment to compare both ports
> nothing too rigorous, I'll just run the same AV-MAP20-UVMAX timedemo once

Yes, this is different. This PR sets the native resolution by default, so an exact comparison with Nugget is difficult. A little early for that, but thanks.

**Comment by liPillON** [comment]
yeah I'm aware of the ongoing efforts in that branch
I just wanted to benchmark this PR to use it as a reference, just in case.

FWIW, here's the results

|  |v.res |master |pr1292 |nugget |dsdaSW |dsdaHW |
|--|------|-------|-------|-------|-------|-------|
|2x| 400p |  881.4|  808.6|  831.5|  886.7| 1648.4|
|3x| 600p |       |  484.3|  512.2|  503.2| 1587.3|
|4x| 800p |       |  276.0|  269.8|  286.4| 1446.7|
|5x|1000p |       |  204.0|  218.0|  201.6| 1246.8|

**Comment by fabiangreffrath** [comment]
dead end

**Comment by liPillON** [comment]
I've run the same timedemo against the recently merged #1298.
Here's the updated table:

|  |v.res |master (prev) |pr1292 |master (curr, pr1298)|nugget |dsdaSW |dsdaHW |
|--|------|-------|-------|-------|-------|-------|-------|
|2x| 400p |  881.4|  808.6|  793.8|  831.5|  886.7| 1648.4|
|3x| 600p |       |  484.3|  433.2|  512.2|  503.2| 1587.3|
|4x| 800p |       |  276.0|       |  269.8|  286.4| 1446.7|
|5x|1000p |       |  204.0|       |  218.0|  201.6| 1246.8|



At comparable resolutions (2x, 3x) there's a 5%/10% performance penalty.
It's the same with other timedemo I've quickly tried out.

Nothing to be worried about given the framerates, I would say.

**Comment by rfomin** [comment]
> At comparable resolutions (2x, 3x) there's a 5%/10% performance gap with nugget.

The main difference is the new `V_DrawPatch` function, which is a bit slower than the previous version. We can use the old function for integer multipliers as in PrBoom+/DSDA, although I'm not sure the difference in performance will be noticeable. @MrAlaux maybe there's some kind of secret sauce? 😉

**Comment by MrAlaux** [comment]
> @MrAlaux maybe there's some kind of secret sauce? 😉

I'm just the waiter! Ask the chef: @ceski-1. 😄

**Comment by ceski-1** [comment]
No secret sauce, I'm afraid. My implementation was about as simple and naive as it gets.

**Comment by rfomin** [comment]
Okay, so it's an old optimized `V_DrawPatch`. I'll give it a try.

**Comment by fabiangreffrath** [comment]
My guess is that this extra round of `memcpy()` costs some performance:

https://github.com/fabiangreffrath/woof/blob/834c10510ca193aa9ce684b24eff43d83f729359/src/i_video.c#L449-L457

**Comment by rfomin** [comment]
> My guess is that this extra round of `memcpy()` costs some performance:

I don't think so, it's very fast.

After you changed `V_DrawPatch` in this PR (https://github.com/fabiangreffrath/woof/pull/1292/commits/41538334a0d6e8e15925ef43f92a4054d7d553a3),  the performance also degrades, the old function was really optimized. PrBoom+ still uses it for integer multiples.

**Comment by fabiangreffrath** [comment]
Okay, let's reintroduce the optimized patch drawing for integer multiples.

**Comment by JNechaevsky** [comment]
Have to say, this PR is a pure gold. I briefly tried to adapt it into Inter Doom, which is almost identical to Crispy Doom with few differences in the render, and got it working just in few clicks! This reveals one important thing - clean compatibility with Crispy Doom iself, so if one day we'll decide to have a higher resolutions there, this PR can be used as a sacred text. At least for Doom, because there are still evil things like RAW screens.

**Comment by fabiangreffrath** [comment]
> After you changed `V_DrawPatch` in this PR ([4153833](https://github.com/fabiangreffrath/woof/commit/41538334a0d6e8e15925ef43f92a4054d7d553a3)), the performance also degrades, the old function was really optimized. PrBoom+ still uses it for integer multiples.

Any chance we can get the optimized patch drawing routines back for integer scales?

**Comment by rfomin** [comment]
> Any chance we can get the optimized patch drawing routines back for integer scales?

I've tested it more, and it seems that the current `V_DrawPatch` doesn't differ much from the old one in performance. I have removed the extra copying and now the performance is about the same as the old version.

**Comment by fabiangreffrath** [comment]
> > Any chance we can get the optimized patch drawing routines back for integer scales?
> 
> I've tested it more, and it seems that the current `V_DrawPatch` doesn't differ much from the old one in performance. I have removed the extra copying and now the performance is about the same as the old Woof.

Great, thanks!

**Pull request closed without merging**
