### PR TITLE
add SKILL cheat to show (or change) game skill level

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
But how will the mid-level skill change work? It will not add new monsters.

**Comment by fabiangreffrath** [comment]
No, it will not spawn new monsters. The change will only take effect when changing the level. Though, it should take a certain effect when changing to Nightmare skill or back from that. I will have to add the following calls:

```c
  G_SetFastParms(fastparm || gameskill == sk_nightmare);
  respawnmonsters = gameskill == sk_nightmare || respawnparm;
```

**Comment by rfomin** [comment]
I think we should show a message that the cheat will only work on the next level.

**Comment by fabiangreffrath** [comment]
So probably "Next Level Skill" instead of "New Skill"?

**Comment by rfomin** [comment]
> So probably "Next Level Skill" instead of "New Skill"?

Yes, sounds better.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
