### PR TITLE
fix void function return value

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
This is merely a question of style. Of course, a void function can return the "return value" of another void function. However, I agree it is more clear to not do this.

**Comment by rfomin** [comment]
It was a compiler warning. By the way, there are over 100 MSVC warnings mostly about type conversions. Should we do something about them?

**Comment by fabiangreffrath** [comment]
Are you compiling this as a C++ project? Type conversations are usually a C++ problem.

**Comment by rfomin** [comment]
I tried to force a standard c11, warnings are the same.

**Comment by fabiangreffrath** [comment]
Is it requesting explicit casting of pointers returned by e.g. `malloc()`?

**Comment by rfomin** [comment]
Most of them are [C4244](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-levels-3-and-4-c4244?view=msvc-160). A few examples:
```
C:\develop\woof\Source\p_floor.c(811,33): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data [C:\develop\woof\build\Source\woof.vcxproj]
C:\develop\woof\Source\p_genlin.c(655,25): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data [C:\develop\woof\build\Source\woof.vcxproj]
C:\develop\woof\Source\d_main.c(729,23): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data [C:\develop\woof\build\Source\woof.vcxproj]

```

**Comment by fabiangreffrath** [comment]
The first two are pointer differences stored in int. The second is a string length stored in an int. Should be safe - though strictly wrong. However, I  don't think we are going to introduce ptrdiff_t and size_t types everywhere - or are we?

**Comment by rfomin** [comment]
> ptrdiff_t and size_t types everywhere

No, I don't want this. Personally, I turn off C4244 warning in my local branch, it just feels wrong.

**Comment by fabiangreffrath** [comment]
Or we could just add explicit `(int)` casts to silence the compiler, I guess.

**Comment by rfomin** [comment]
I think MSVC can be too paranoid at times. Let's keep the historical code as it is.

**Comment by fabiangreffrath** [comment]
Alright. Could you unset the warning in the CMake code?

**Pull request merged**
