### PR TITLE
add parallel same-sound limit from DSDA-Doom

### LINKED ISSUE #546: [Feature] Same sound limiter
DSDA-Doom has a feature that could also be useful for this project: Due to an optional limiter of identical sounds, situations where your eardrums are raped by a cacophony of simultaneously played sounds are avoided.

This can happen when waking up many identical enemies at once or in areas with excessive usage of moving pistons with mechanical sounds. I had a level recently that got so loud because of that I had to almost turn volume down to 0. A sound limiter could work wonders here.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #546

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Might have to rearrange the General menu because of this.

**Comment by rfomin** [comment]
Have you tested [dsda_parallellimit.zip](https://github.com/fabiangreffrath/woof/files/9979468/dsda_parallellimit.zip)? Better than before, but still strange.

> Might have to rearrange the General menu because of this.

We can remove the white space between vsync and translucency settings.

**Comment by fabiangreffrath** [comment]
@kraflab I hope you don't mind that I remove the `dsda_` prefix from the function and variable names?

**Comment by fabiangreffrath** [comment]
> Have you tested [dsda_parallellimit.zip](https://github.com/fabiangreffrath/woof/files/9979468/dsda_parallellimit.zip)? Better than before, but still strange.

Hm, what exactly is this?

**Comment by rfomin** [comment]
> Hm, what exactly is this?

Full description: https://www.doomworld.com/forum/topic/118074-dsda-doom-source-port-v0243/?page=37&tab=comments#comment-2451596

**Comment by fabiangreffrath** [comment]
Ah, that's the exact same issue I linked here:
https://github.com/fabiangreffrath/woof/issues/546#issuecomment-1120694835

Couldn't check it, yet, because I am currently, well lets' say, not in a position to compile and run a game with headphones. 😁

**Comment by rfomin** [comment]
Well, it's not perfect, the first button is too quiet. GZDoom and Odamex work well, but they rewrote a lot of code in the sound engine.

**Comment by fabiangreffrath** [comment]
Well, I think to fix this, we would e.g. have to collect all the sounds to be played per tic first, then remove the duplicates and only play the ones with the highest volume. 🤷

**Comment by kraflab** [comment]
> @kraflab I hope you don't mind that I remove the `dsda_` prefix from the function and variable names?

Feel free 😄

**Comment by NightFright2k19** [comment]
Is it OK to leave sound channels at 32 after this or should it be reduced to something lower?

**Comment by fabiangreffrath** [comment]
> Is it OK to leave _snd_channels_ at 32 after this or should it be reduced to something lower?

Of course it is okay however you prefer it. But the few people I asked which settings they prefer all recommended 16 channels as the new default.

**Comment by NightFright2k19** [comment]
I would be OK with it as well. After all, I doubt it comes with any real restrictions that one would notice. Between 8 and 16 seems to be a good range for a port like this.

**Review by rfomin — APPROVED** [review]
Hopefully we will fix it properly someday 😄

**Comment by mikeday0** [comment]
Between this and the clicking crushers, it makes me wonder if it would be better to do all the sound mixing natively.

**Comment by fabiangreffrath** [comment]
> Between this and the clicking crushers, it makes me wonder if it would be better to do all the sound mixing natively.

Hm, could you elaborate?

Has anyone any experience with OpenAL?

**Comment by rfomin** [comment]
> Between this and the clicking crushers, it makes me wonder if it would be better to do all the sound mixing natively.

We can choose another library like OpenAL. Odamex doesn't have these issues with SDL_Mixer, although the DBP25's opening room sounds odd in it.

**Comment by mikeday0** [comment]
> Hm, could you elaborate?
> 

If you have more control over the audio buffer it's much easier to stitch together the end of the previous instance of the looping sound with the start of the next one.

I may have been a little hyperbolic when I made my previous statement. :smile: It appears SDL_mixer does support looping for individual channels. Maybe we just need to fully explore the full capability of the library we're already using.

https://github.com/libsdl-org/SDL_mixer/blob/69f1cb0800aa333464b9fa81203453079f47b917/include/SDL_mixer.h#L1771-L1802

**Comment by fabiangreffrath** [comment]
Indeed. To make one thing clear, I am not going to develop a new *sound engine* in the scope of this project. 

We need full cross platform portability and an easy to use API. Currently, I can only see SDL2_MIXER fulfill this role, but I have to admit I have zero experience with alternatives such as OpenAL.

**Comment by fabiangreffrath** [comment]
Also, SDL2_MIXER allows to to just throw some music track in any digital format before its feet and it will play it.

**Comment by mikeday0** [comment]
I definitely did not mean to imply that SDL_mixer should be thrown out. I was thinking more that we have an internal mixing buffer that we would pass to SDL_mixer to play.

**Comment by rfomin** [comment]
> It appears SDL_mixer does support looping for individual channels. Maybe we just need to fully explore the full capability of the library we're already using.

It seems Odamex is using SDL_mixer looping: https://github.com/odamex/odamex/blob/8845a5108c52d9ae75cae1eb9dea6278f3d39cde/common/p_ceiling.cpp#L120 Maybe we should try it.

**Comment by fabiangreffrath** [comment]
> It seems Odamex is using SDL_mixer looping: https://github.com/odamex/odamex/blob/8845a5108c52d9ae75cae1eb9dea6278f3d39cde/common/p_ceiling.cpp#L120 Maybe we should try it.

Sounds like a promising approach, could be worth looking into.

**Comment by fabiangreffrath** [comment]
Another promising approach from Odamex. Cool! 👍

**Comment by fabiangreffrath** [comment]
> I haven't been able to adapt it to Woof yet.

Could you please post what you've got so far? Maybe as a draft PR?

**Comment by rfomin** [comment]
> > I haven't been able to adapt it to Woof yet.
> 
> Could you please post what you've got so far? Maybe as a draft PR?

I did not do anything - Woof sound system seems to be quite different. You might be able to get through this much faster.

**Comment by fabiangreffrath** [comment]
> I did not do anything - Woof sound system seems to be quite different. You might be able to get through this much faster.

First hurdle might be that we cannot apply `qsort()` on a static `channels[]` array. 🤔

**Comment by rfomin** [comment]
> First hurdle might be that we cannot apply `qsort()` on a static `channels[]` array. 🤔

Hmm, why not, it seems to work - the `static` keyword only refers to the `channels` name, but we send the pointer to the `qsort` function. I was puzzled how to write a comparison function, apparently `priority` is not enough.

**Comment by rfomin** [comment]
> In this specific case here, I am sure we need to at least take channel volume into account as well.

I tried this but got a broken result. Maybe we need `gametic` when the sound was started, not sure. I stopped there.

**Comment by fabiangreffrath** [comment]
Maybe we could use `idnum` which is an ever increasing number.

**Comment by fabiangreffrath** [comment]
Did you consider that in our code, a higher priority numerical value means a lower actual priority?

**Comment by fabiangreffrath** [comment]
Hm, we have the Boom-derived `singularity` comcept in our sound code that I somehow don't want to lose. Not sure how to integrate this into the Odamex code.

**Pull request merged**
