### PR TITLE
Crosshair lock fixes

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Addresses #842

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I don't think it'll be getting much better. The crosshair patch just won't scale properly when reducing the view window. I can only restrict its center coordinate, but under extreme circumstances it will still be possible to draw parts of it on the bezel. 

At least it won't be drawn on the status bar face or weapon sprite anymore when standing above an enemy. 😉

**Comment by kraflab** [comment]
Is it time to disable changing the view window? Are there people that do this?

**Comment by fabiangreffrath** [comment]
> Is it time to disable changing the view window? Are there people that do this?

That would be a rather drastic step. It had been suggested before, but I am reluctant to do it. Sure, we have to maintain some code around the view window stuff. But on the other hand it is so characteristic to Doom, that removing it just feels like heresy. 

Whatever, who is using it? I have no idea. I don't use it myself, that's for sure.

**Comment by rfomin** [comment]
> But on the other hand it is so characteristic to Doom, that removing it just feels like heresy.

I agree, our project should preserve it.

Not sure about crosshair lock, is it supposed to work like that?

woof0002
woof0003

**Comment by fabiangreffrath** [comment]
> Not sure about crosshair lock, is it supposed to work like that?

Wait, but these screenshots were not taken with this PR, right?

**Comment by rfomin** [comment]
> Wait, but these screenshots were not taken with this PR, right?

Just rechecked, yes this PR.

**Comment by rfomin** [comment]
This works for me:
```diff
diff --git a/src/hu_stuff.c b/src/hu_stuff.c
index fa1a0f5..ad2e9d1 100644
--- a/src/hu_stuff.c
+++ b/src/hu_stuff.c
@@ -1088,7 +1088,7 @@ static void HU_UpdateCrosshair(void)

 void HU_UpdateCrosshairLock(int x, int y)
 {
-  crosshair.x = WIDESCREENDELTA + ((viewwindowx + x) >> hires);
+  crosshair.x = ((viewwindowx + x) >> hires) - WIDESCREENDELTA;
   crosshair.y = (viewwindowy + y) >> hires;
 }
```

**Comment by fabiangreffrath** [comment]
Yay, I messed up signs.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
