### PR TITLE
umapinfo: fix parsing of the 'episode' field

### PR DESCRIPTION
**Pull request by rfomin**
The previous code broke on this: `episode = "", "Test", "1"` .

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Will Pr+ require a similar fix as well? I want both ports to be strictly in sync wrt UMAPINFO implementation.

**Comment by rfomin** [comment]
This fix is not that important. Just why use `strtok()` when we have a parser. I plan to make PR for Pr+.

**Comment by fabiangreffrath** [comment]
Great, thank you!

**Comment by rfomin** [comment]
BTW, what about autoload per PWAD for Pr+ ?

**Comment by fabiangreffrath** [comment]
This would be appreciated! :+1:

**Pull request merged**
