### PR TITLE
don't draw HUD on the snapshots

### PR DESCRIPTION
**Pull request by rfomin**
Feature request: [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-1030-sep-23-2022-updated-winmbf/?do=findComment&comment=2548578)

I think that we shouldn't draw STBAR too, but I don't know how to do it better.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I am all for keeping the status bar in snapshots, but I am fine with removing HUD stuff. 👍

**Review by fabiangreffrath — APPROVED** [review]
Looks clean, thanks!

**Comment by rfomin** [comment]
> I am all for keeping the status bar in snapshots

But why? I don't think it's readable. Other ports with snapshots do not draw it.

**Comment by fabiangreffrath** [comment]
> But why? I don't think it's readable. Other ports with snapshots do not draw it.

Well, it's not *clearly* readable, but I think you get at least an *impression* of your health status and active weapon. Also, we would end up with two different snapshot geometries for games saved with the status bar and those with fullscreen HUD.

**Comment by rfomin** [comment]
> Also, we would end up with two different snapshot geometries for games saved with the status bar and those with fullscreen HUD.

Yes, I think we should always save fullscreen HUD snapshots. Not sure how to organize it.

**Comment by fabiangreffrath** [comment]
Or we only save the part of the screen above the status bar (i.e. `SCREENHEIGHT - ST_HEIGHT`), but I am sure this looks crappy for fullscreen savegames.

**Comment by rfomin** [comment]
> I am sure this looks crappy for fullscreen savegames.

Yes, I agree 😉 I guess we need to save one frame with `screenblocks == 11`.

**Comment by fabiangreffrath** [comment]
Let's please merge this first, so we have a clean cut at the point where it will be necessary to convince me. 😉

**Pull request merged**
