### PR TITLE
open/close MIDI device on every song change

### PR DESCRIPTION
**Pull request by rfomin**
This is what SDL_Mixer does and maybe this will reset the device properly. Can fix these issues: [[doomworld]](https://www.doomworld.com/forum/topic/131558-midi-stutter-on-track-start-and-when-looping-on-hardware-module/), [[doomworld]](https://www.doomworld.com/forum/topic/131197-weird-glitch-audio-desyncs-black-screen-instead-of-endoom/)

@ceski-1 What do you think?

### CODE REVIEW

**Comment by rfomin** [comment]
The issue with this approach is slow song change. Test WAD: [MusChange.zip](https://github.com/fabiangreffrath/woof/files/9680643/MusChange.zip)

**Comment by ceski-1** [comment]
There's a bigger issue I'm stuck on right now. Even if I disable every message, the current native MIDI implementation doesn't loop correctly on hardware or software, and it stutters on real hardware. So this has been happening before I started contributing. Adding a small 50-100ms delay after the resets helps the stutter on hardware but it's not the real solution and it doesn't fix the looping. SDL_mixer seems fine (e.g. old Chocolate Doom).

```diff
diff --git a/src/i_winmusic.c b/src/i_winmusic.c
index 55a6a68..af79adf 100644
--- a/src/i_winmusic.c
+++ b/src/i_winmusic.c
@@ -413,7 +413,7 @@ static boolean I_WIN_InitMusic(void)
         return false;
     }
 
-    ResetDevice();
+    //ResetDevice();
 
     hdr->lpData = (LPSTR)buffer.events;
     hdr->dwBytesRecorded = 0;
@@ -454,9 +454,9 @@ static void UpdateVolume()
 
 static void I_WIN_SetMusicVolume(int volume)
 {
-    volume_factor = sqrt((float)volume / 15);
+    //volume_factor = sqrt((float)volume / 15);
 
-    UpdateVolume();
+    //UpdateVolume();
 }
 
 static void I_WIN_StopSong(void *handle)
@@ -472,7 +472,7 @@ static void I_WIN_StopSong(void *handle)
         hPlayerThread = NULL;
     }
 
-    ResetDevice();
+    //ResetDevice();
 
     mmr = midiStreamStop(hMidiStream);
     if (mmr != MMSYSERR_NOERROR)
@@ -502,7 +502,7 @@ static void I_WIN_PlaySong(void *handle, boolean looping)
         MidiError("midiStreamRestart", mmr);
     }
 
-    UpdateVolume();
+    //UpdateVolume();
 }
 
 static void I_WIN_PauseSong(void *handle)
```

**Comment by rfomin** [comment]
> Even if I disable every message, the current native MIDI implementation doesn't loop correctly on hardware or software, and it stutters on real hardware.

PrBoom+ does this: https://github.com/coelckers/prboom-plus/blob/99fd8a8cea5950e51a9a5a46f05ac072d77d6908/prboom2/src/MUSIC/portmidiplayer.c#L595-L605

I didn't notice this problem before. MS GW Wavetable working fine?

**Comment by ceski-1** [comment]
I tried your changes and it still stutters when switching maps (E1M1 -> E2M1) and doesn't loop correctly on real hardware. It seems fine on software, but yes there's a slow music transition for that test wad.

Wow, even Chocolate Doom 3.0.1 doesn't loop correctly (E2M1).

**Comment by ceski-1** [comment]
> I didn't notice this problem before. MS GS Wavetable working fine?

MS GS Wavetable Synth has the same problems with your Woof fork and Chocolate 3.0.1. It also causes the game to pause for moment when the music switches in MusChange.wad, which doesn't happen with Roland SCVA or hardware. I'll look at PrBoom+ next.

**Comment by rfomin** [comment]
> Wow, even Chocolate Doom 3.0.1 doesn't loop correctly (E2M1).

Have you tested GZDoom? How to loop correctly then.

**Comment by ceski-1** [comment]
PrBoom+ (PortMidi) seems to work the best. GZDoom (Zmusic) has problems.

<details><summary>Details</summary>

## Latest snapshot PrBoom+

**Software: MS GS Wavetable Synth**
- E2M1: Loops fine, no stuttering.
- MusChange.wad: No pausing, slightly slow to change songs.

**Software: Roland SCVA**
- E2M1: Loops fine, no stuttering.
- MusChange.wad: No pausing, slightly slow to change songs.

**Hardware: Roland SC-88VL (mus_portmidi_reset_delay = 250)**
- E2M1: Small gap during loop, probably my fault due to `mus_portmidi_reset_delay` altering first delta time. Otherise fine.
- MusChange.wad: no pausing, slightly slow to change songs, occasional chirp sound during song change.


## GZDoom 4.8.2:

**Software: MS GS Wavetable Synth**
- E2M1: Loops fine, stutters when first playing.
- MusChange.wad: Makes the game pause, chirp sound during song change.

**Software: Roland SCVA**
- E2M1: Loops fine, stutters when first playing.
- MusChange.wad: Makes the game pause but only briefly, chirp sound during song change.

**Hardware: Roland SC-88VL**
- E2M1: Loops fine, stutters when first playing.
- MusChange.wad: Makes the game pause but only briefly, chirp sound during song change.
</details>

**Comment by rfomin** [comment]
> I tried your changes and it still stutters when switching maps (E1M1 -> E2M1) and doesn't loop correctly on real hardware. It seems fine on software, but yes there's a slow music transition for that test wad.

I don't have MIDI hardware so there is no way to test this in software (current master seems to be working fine)?

Another difference is that PrBoom+ preserve one last `MIDI_META_END_OF_TRACK` event: https://github.com/coelckers/prboom-plus/blob/99fd8a8cea5950e51a9a5a46f05ac072d77d6908/prboom2/src/MUSIC/midifile.c#L913-L914

**Comment by ceski-1** [comment]
I was looking a [this](https://github.com/coelckers/prboom-plus/blob/99fd8a8cea5950e51a9a5a46f05ac072d77d6908/prboom2/src/MUSIC/midifile.c#L883) yesterday, right above your link. Interesting.

**Comment by rfomin** [comment]
> I was looking at [this](https://github.com/coelckers/prboom-plus/blob/99fd8a8cea5950e51a9a5a46f05ac072d77d6908/prboom2/src/MUSIC/midifile.c#L883) yesterday, right above your link. Interesting.

I do this too in `MIDItoStream()` function: https://github.com/fabiangreffrath/woof/blob/e3dfec919b9b55bffaf37f6fb07ea339ef66a9cd/src/i_winmusic.c#L332

The idea is to convert a multitrack MIDI file to a single track. I do this for compatibility with the `midiStream` API. Not sure why PrBoom+ does this.

**Comment by ceski-1** [comment]
> I don't have MIDI hardware so there is no way to test this in software (current master seems to be working fine)?

I made some comparison videos, listen for the stuttering and wrong looping points:

<details><summary>Details</summary>

DOSBox Staging + Roland SC-88VL (SC-55 Map) + UM-ONE mk2:
https://user-images.githubusercontent.com/56656010/193252245-d339ba9e-3e53-439f-9333-e7d3678a01c8.mp4

Woof + MS GS Wavetable Synth:
https://user-images.githubusercontent.com/56656010/193252810-fb571e53-4f0a-48a5-a2ec-9e9963b1d0c3.mp4

Woof + VirtualMIDISynth:
https://user-images.githubusercontent.com/56656010/193252930-cdf1547b-c891-463b-b0e2-50875df73ee6.mp4

Woof + Roland SCVA + loopMIDI:
https://user-images.githubusercontent.com/56656010/193253014-ea3b2964-1164-4d0b-9262-c52ee0b71362.mp4

Woof + Roland SC-88VL (SC-55 Map) + UM-ONE mk2:
https://user-images.githubusercontent.com/56656010/193253138-3994dd7e-6b5b-43e2-a110-4f450380dc81.mp4

PrBoom-Plus + Roland SCVA + loopMIDI:
https://user-images.githubusercontent.com/56656010/193253532-0f69aae1-85ab-4f42-aefb-5a68a12c323a.mp4

</details>

**Comment by rfomin** [comment]
Wow, thanks for the videos, to be honest the difference is subtle and I probably wouldn't have noticed it myself. So, I'm assuming the problem is resetting the device properly?

**Comment by ceski-1** [comment]
Yeah, I should have captioned the videos, but DOSBox and PrBoom+ sound correct, and the others are off in different ways.

As for what the problem could be, I'm not sure yet. I'm afraid of jumping to conclusions like I did earlier so I'll need to study it some more after I take break.

**Comment by ceski-1** [comment]
Just adding some notes:

> Woof + VirtualMIDISynth: https://user-images.githubusercontent.com/56656010/193252930-cdf1547b-c891-463b-b0e2-50875df73ee6.mp4

The stuttering at the beginning of this video goes away when VirtualMIDISynth's output buffer is set to a low value like 50 ms. At default or higher, the problem gets worse (>=250 ms).

Using MIDI-OX as a router also makes the stuttering go away: Woof -> loopMIDI -> MIDI-OX -> VirtualMIDISyth Device #1 -> VirtualMIDISynth. Some sort of buffering by MIDI-OX?

The synth engine used by VirtualMIDISynth is BASSMIDI. Falcosoft Midi Player also uses BASSMIDI and doesn't stutter. Buffering again?

It's too bad none of these projects are open.

**Comment by rfomin** [comment]
The stuttering happens with ZMusic/SDL_Mixer/i_winmusic.c, all of them using `midiStreamOut` API. Portmidi can use both "immediate" and "streaming" modes, and in the case of streaming, there is some kind of synchronization: https://github.com/PortMidi/portmidi/blob/a498fd19bfe62ba5f7f0c2d3213ea287e0366981/pm_common/portmidi.c#L644-L647

**Comment by ceski-1** [comment]
Okay, I see. PortMidi will use _only_ streaming messages if latency is defined > 0. So that means immediate messages like `midiOutShortMsg()` wouldn't be used. This is the case with PrBoom+ since it uses a latency > 0 (see `DRIVER_LATENCY`).

**Comment by rfomin** [comment]
> So if there are volume, reset, or SysEx messages, they should be inserted into the stream buffer rather than sent directly.

Yes, probably. ZMusic does something like that: https://github.com/ZDoom/ZMusic/blob/47255178329bab4efa4408a4e4d373fb9264e8c5/source/musicformats/music_midi.cpp#L800

**Comment by fabiangreffrath** [comment]
Any news here?

**Comment by rfomin** [comment]
> Any news here?

This PR does not solve a problem, but instead creates another one. I haven't done anything yet.

**Pull request closed without merging**
