### PR TITLE
keep a static copy of src/param.h instead of always regenerating it

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Fixes #722

**Review by rfomin — COMMENTED** [review]
There is also `paramsgen` target: https://github.com/fabiangreffrath/woof/blob/a7f35f0d84ec481748df2de4f7ee0ad71d3a1a3e/man/CMakeLists.txt#L4

**Comment by rfomin** [comment]
I suggest to add `ENABLE_PARAMSGEN` option:
```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index 0f42f3d..047ef54 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -154,10 +154,10 @@ add_executable(woof WIN32 ${WOOF_SOURCES})
 target_woof_settings(woof)
 target_include_directories(woof PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/../")

-# Regenerate the src/params.h header file.
-#if(Python3_EXECUTABLE)
-#    add_dependencies(woof paramsgen)
-#endif()
+option(ENABLE_PARAMSGEN "Regenerate the src/params.h header file" OFF)
+if(ENABLE_PARAMSGEN AND Python3_EXECUTABLE)
+   add_dependencies(woof paramsgen)
+endif()

 if (FluidSynth_FOUND)
     list(APPEND WOOF_LIBRARIES FluidSynth::FluidSynth)
```

**Comment by fabiangreffrath** [comment]
Thanks! Would it make sense to have this option enabled for CI or for release builds?

**Comment by rfomin** [comment]
> Thanks! Would it make sense to have this option enabled for CI or for release builds?

Since we added `params.h` to git, I don't think it matters.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
