### PR TITLE
umapinfo: show CREDIT lump for default Doom 2 ending

### LINKED ISSUE #521: [Bug] UMAPINFO: endgame=true crashes Doom II
Tested with: Latest Github master (Apr 14, 2022)

When using endgame=true in UMAPINFO while playing Doom 2, Woof! crashes to desktop with this message:
`W_GetNumForName: HELP2 not found!`
(HELP2 does not exist in doom2.wad, plutonia.wad or tnt.wad, there is only the HELP lump.)

UMAPINFO code:
```
MAP MAP01
{
	intertext = ""
	interbackdrop = "CREDIT"
	endgame = true
}
```

To reproduce:
- Place attached umapinfo.lmp into autoload\doom2.wad: [umapinfo.txt](https://github.com/fabiangreffrath/woof/files/8513543/umapinfo.txt)
- Launch Doom 2, start a new game
- Reach the end of MAP01
- CREDIT screen will appear first, then when pressing LMB, crash will occur

### PR DESCRIPTION
**Pull request by rfomin**
Fix #521

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Sorry if I missed the most important part of the discussion, but isn't the cast screen the only reasonable "default post-game screen for the current episode" in Doom 2? I mean, because it has never been possible to end Doom 2 in any other way.

**Comment by fabiangreffrath** [comment]
Related discussion:
https://github.com/coelckers/prboom-plus/issues/408

**Comment by rfomin** [comment]
> Sorry if I missed the most important part of the discussion, but isn't the cast screen the only reasonable "default post-game screen for the current episode" in Doom 2? I mean, because it has never been possible to end Doom 2 in any other way.

In Valiant and Ancient Aliens it's a CREDIT lump. Oh well I guess this is discussion for UMAPINFO 2 :smile:

**Comment by fabiangreffrath** [comment]
> In Valiant and Ancient Aliens it's a CREDIT lump. Oh well I guess this is discussion for UMAPINFO 2 😄

Sure, but this is an ending specifically defined for these WADs by means of (U)MAPINFO. And we are talking about the "*default* post-game screen for the current episode" in Doom 2, right? 😉

**Comment by rfomin** [comment]
Doom 2 don't have episodes. In Doom 1 it's CREDIT, in popular PWADs it's CREDIT. Also we have `endcast` field.

**Comment by fabiangreffrath** [comment]
Well, okay. I am fine with it not crashing anymore.

**Pull request merged**
