### PR TITLE
implement per-IWAD savegame directories

### LINKED ISSUE #793: [Feature] Wadname-based savegame dirs
Right now, Woof stores savegames in its root directory. If someone is switching between several addons within a short period of time, it's possible to accidentally overwrite savegames meant for a different PWAD. Therefore, it would be better if there was a way to keep them separate in a more fool-proof way, but also simply in order to maintain some order in the game root directory.

In other ports such as GZDoom, wadname-based savegame directories are created to avoid such situations. It's actually pretty much like the autoload folder works right now, just for savegames.

Suggested realization:
- Introduction of a CVAR to set up directory for savegames (may default to either root dir or e.g. %root%\savegames)
- Port automatically creates subdirs inside of the specified savegame dir with names based on active IWAD/PWAD (e.g. "doom.wad" for Doom 1 or "requiem.wad" for Doom 2 PWAD "Requiem")
- Only savegames from those subdirs are used, depending on which wad is loaded

Things to consider:
- Port needs to recognize if a wad actually contains maps. Savegame dirs should only be created for those, not mere gameplay mods.
- Needs to work with PWADs for Doom 1+2 as well (obviously).

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #793

### CODE REVIEW

**Comment by rfomin** [comment]
How about save directories per PWAD? Per IWAD is not very useful, it's DOOM2.WAD 90% of the time.

**Comment by fabiangreffrath** [comment]
That's complicated. Consider you have a PWAD that replaces MAP02. You start a new game, you are in the IWAD's MAP01 and want to load a game where you are in the PWAD's MAP02. How to tell the right savegame directory?

Same for e.g. Sigil. Consider you have Sigil loaded as Episode 5. You want to load a savegame where you are in Sigil's E5M1 and then another one where you are in Doom.wad's E1M1. 🤷

**Comment by fabiangreffrath** [comment]
Other examples are TNT31fix.wad, or requiem.wad + req21fix.wad.

**Comment by rfomin** [comment]
> Consider you have a PWAD that replaces MAP02. You start a new game, you are in the IWAD's MAP01 and want to load a game where you are in the PWAD's MAP02. How to tell the right savegame directory?

If we have PWAD loaded, the menu will only show saves from the PWAD saves subdirectory. The exception is old saves from previous versions - we will always show them until the user deletes or moves them. Or we can automatically move old saves to subdirectories on the first startup, the PWADs information is in the header.

> Same for e.g. Sigil. Consider you have Sigil loaded as Episode 5. You want to load a savegame where you are in Sigil's E5M1 and then another one where you are in Doom.wad's E1M1.

Only show saves from the Sigil subdirectory. The user will not see saves for IWAD in the menu, perhaps this is counter-intuitive, but we don't have Sigil autoloading like Crispy, so we can assume this is what the user wants.

> Other examples are TNT31fix.wad, or requiem.wad + req21fix.wad.

We can only consider the first PWAD, usually load order matters for this kind of fixes, so the main PWAD should be first. PWADs in the autoload directory should also be ignored.

It got complicated, but I think without the PWADs subdirectories, this feature isn't worth it.

**Comment by fabiangreffrath** [comment]
In all of this, we will have to filter out non-level, e.g. music or sfx, PWADs. We can't explain users why their savegames are all hidden when they just want to try out some new music (or brightmap, or color translation table, or HUD font, or whatever).

**Comment by rfomin** [comment]
> In all of this, we will have to filter out non-level, e.g. music or sfx, PWADs.

Agreed. Usually these kinds of PWAD's are in the autoload directory.

**Comment by fabiangreffrath** [comment]
Usually - but not always. There are still too many assumptions involved here.

What if I want to want to load my E1M7 savegame, but transition to "Tech Gone Bad" instead of the regular E1M8? "Sorry, dude, you loaded a random PWAD that happened to contain a map, now your savegames are gone". 😱

**Comment by rfomin** [comment]
> What if I want to load my E1M7 savegame, but transition to "Tech Gone Bad" instead of the regular E1M8? "Sorry, dude, you loaded a random PWAD that happened to contain a map, now your savegames are gone".

But why would the user load random PWAD? The user must explicitly pass it through the `-file` parameter. I suggest ignoring anything in the autoload folder.

This feature has been around in Doom Retro and DSDA-Doom for a long time, and I've never seen any complaints about it. I think we can make it a bit dumb, usually users don't have very complex setup.

**Comment by fabiangreffrath** [comment]
So, the idea is to put savegames in the subdirectory that is named after the first map-containing PWAD that is explicitly loaded on the command line?

**Comment by rfomin** [comment]
> So, the idea is to put savegames in the subdirectory that is named after the first map-containing PWAD that is explicitly loaded on the command line?

Yes, that's correct.

Not sure what to do with old saves. In DSDA-Doom there is a QOL menu item "organize my save files".

**Comment by fabiangreffrath** [comment]
> Yes, that's correct.

💪 

> Not sure what to do with old saves. In DSDA-Doom there is a QOL menu item "organize my save files".

I like the approach presented here: If there is no savegame in the current slot, try to load from the legacy location. Always store to the new location.

**Comment by rfomin** [comment]
> If there is no savegame in the current slot, try to load from the legacy location. Always store to the new location.

I don't like that sometimes old saves disappear or appear. I think we can try to move them automatically or always show them after new saves.

**Comment by fabiangreffrath** [comment]
> the first map-containing PWAD that is explicitly loaded on the command line

I think this requires some preparation work. We need a way to tag resources as "from IWAD", "from PWAD", "internal", "auto-loaded", "single-file", "contains-maps", etc.

**Comment by rfomin** [comment]
> > the first map-containing PWAD that is explicitly loaded on the command line
> 
> I think this requires some preparation work. We need a way to tag resources as "from IWAD", "from PWAD", "internal", "auto-loaded", "single-file", "contains-maps", etc.

Not sure if this is necessary for this feature. We can check the `wadfiles[1]` (`wadfiles[0]` is always IWAD) from `d_main.c`, if this PWAD contains maps, then use the PWAD subdirectory. Otherwise, use the IWAD subdirectory.

**Comment by fabiangreffrath** [comment]
Okay, we can save the value of `numwadfiles` right before `M_CheckParm ("-file")` is evaluated in `d_main.c`.

**Pull request closed without merging**
