### PR TITLE
automap: flashing key based switch

### PR DESCRIPTION
**Pull request by rfomin**
Fixes this issue: [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-700-sep-27-2021-updated-winmbf/?do=findComment&comment=2397538)
Not sure if this is correct.

### CODE REVIEW

**Comment by rfomin** [comment]
> locked doors would keep on blinking even when they are opened

They don't blink in my testing. Not sure I understand what's going on here.

**Comment by fabiangreffrath** [comment]
I would have expected to add another check for keyed switches instead of removing the closed door check altogether. :wink:

**Comment by rfomin** [comment]
Crispy doesn't have these checks and works fine. I don't know much about automap code, but it seems that these checks are unnecessary?

**Comment by rfomin** [comment]
But how to check for the keyed switch?

**Comment by fabiangreffrath** [comment]
Could you block-comment out the offending lines (instead of removing them) and add a comment why it's done, please?

**Pull request merged**
