### PR TITLE
remove "garbage pixels" fix to avoid crashes on some resolutions

### PR DESCRIPTION
**Pull request by rfomin**
I recorded a demo with an "R_DrawSpriteRange: bad texturecolumn" crash with Pirate Doom II (reported here: [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-1430-mar-15-2024/?do=findComment&comment=2791283)) [dem2.zip](https://github.com/fabiangreffrath/woof/files/15046479/dem2.zip)
How to reproduce - set native resolution to 1366x768, turn off dynamic resolution. Interesting that demo crashes in different places depending on build type (debug ASan, release with debug info).

### CODE REVIEW

**Comment by rfomin** [comment]
Simpler way to reproduce this:
1. Apply this patch
```diff
diff --git a/src/i_video.c b/src/i_video.c
index a412d5c..3713297 100644
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1374,8 +1374,8 @@ static void I_InitVideoParms(void)
         I_Error("Error getting display mode: %s", SDL_GetError());
     }
 
-    native_width = mode.w;
-    native_height = mode.h;
+    native_width = 1366;
+    native_height = 768;
 
     if (use_aspect)
     {
```
2. Get Pirate Doom II [[doomworld]](https://www.doomworld.com/forum/topic/143805-pirate-doom-ii-finished-public-beta-release/)
3. Set native resolution, disable dynamic resolution. Start the game, IDFA, switch to shotgun (not super shotgun), run back and forth - it will crash soon.

I think we should make bugfix release, 1366x768 is still popular resolution.

**Comment by fabiangreffrath** [comment]
This will bring back garbage pixels and then people will continue to complain about these.

How about this approach?

```patch
--- a/src/r_things.c
+++ b/src/r_things.c
@@ -466,8 +466,10 @@ void R_DrawVisSprite(vissprite_t *vis, int x1, int x2)
       texturecolumn = frac>>FRACBITS;
 
 #ifdef RANGECHECK
-      if (texturecolumn < 0 || texturecolumn >= SHORT(patch->width))
-        I_Error ("R_DrawSpriteRange: bad texturecolumn");
+      if (texturecolumn < 0)
+        continue;
+      else if (texturecolumn >= SHORT(patch->width))
+        break;
 #endif
 
       column = (column_t *)((byte *) patch +
```

**Comment by rfomin** [comment]
Is this safe?
```c
if (texturecolumn < 0)
        continue;
```
Eternity's version: https://github.com/team-eternity/eternity/blob/4215270cbfbad1afd01eefa07999df963e97fe28/source/r_things.cpp#L969-L971

> This will bring back garbage pixels and then people will continue to complain about these.

I don't think it's a big deal.

**Comment by fabiangreffrath** [comment]
> Is this safe?

Sure, why not?

**Review by fabiangreffrath — APPROVED** [review]
Thank you!

**Comment by fabiangreffrath** [comment]
> I think we should make bugfix release, 1366x768 is still popular resolution.

Yep, probably on Tuesday.

**Comment by fabiangreffrath** [comment]
> Eternity's version: 

Similar code here:
https://github.com/coelckers/prboom-plus/blob/969515162c5aebea4ad7a125ee178dcad3d576ad/prboom2/src/r_patch.c#L980-L984

**Pull request merged**
