### PR TITLE
fix game speed affect DRS

### LINKED ISSUE #1884: Reducing game speed with capped framerate affects DRS
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/10741219991)._

By capping the framerate and reducing the game speed, one can make the game run at under 35 FPS. The DRS system seems to perceive this as low performance, therefore it reduces the resolution to compensate.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1884

### CODE REVIEW

**Comment by MrAlaux** [comment]
Just tried the [Win-64 artifact](https://github.com/fabiangreffrath/woof/actions/runs/10752241220), and I'm afraid the issue is still there.

**Comment by rfomin** [comment]
> I'm afraid the issue is still there.

Should be fixed in https://github.com/fabiangreffrath/woof/pull/1889/commits/fb563a361b3812ccc01505014d4a5a0c11f99614

**Comment by MrAlaux** [comment]
Tried [this Win-64 artifact](https://github.com/fabiangreffrath/woof/actions/runs/10756528706).

Decreasing the game speed doesn't affect DRS anymore.

On the other hand, increasing the speed (beyond ~400% in my case) does affect it, presumably because the FPS target increases beyond my computer's capabilities. However, this might actually be useful, as I sometimes want to increase the speed to make the game run as fast as possible, but the video settings would bottleneck it; then again, this only takes effect when disabling Vsync and capping the framerate, which are not my usual settings.

Also, I think the button for resetting the game speed doesn't trigger a DRS "refresh"; e.g. by increasing the speed to trigger a resolution decrease, then resetting the speed, the resolution stays in place.

**Comment by rfomin** [comment]
> On the other hand, increasing the speed (beyond ~400% in my case) does affect it, presumably because the FPS target increases beyond my computer's capabilities.

Yes, I think that's an interesting side effect. It can be fixed like this:
```diff
diff --git a/src/i_video.c b/src/i_video.c
index 4e0e4ac6..02104e5a 100644
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1487,7 +1487,9 @@ static void I_ResetTargetRefresh(void)
     }
     else
     {
-        targetrefresh = TICRATE * realtic_clock_rate / 100;
+        targetrefresh = (realtic_clock_rate < 100)
+                            ? (TICRATE * realtic_clock_rate / 100)
+                            : TICRATE;
     }
 
     UpdateLimiter();
```

> Also, I think the button for resetting the game speed doesn't trigger a DRS "refresh"; e.g. by increasing the speed to trigger a resolution decrease, then resetting the speed, the resolution stays in place.

Fixed in https://github.com/fabiangreffrath/woof/pull/1889/commits/c0496dee9f9e5e0147645bd2746515d3b0e22586

**Pull request merged**
