### PR TITLE
add setup icon

### PR DESCRIPTION
**Pull request by rfomin**
I tried to draw the setup icon:

### CODE REVIEW

**Comment by rfomin** [comment]
@fabiangreffrath @JNechaevsky Is this icon is alright?

**Comment by fabiangreffrath** [comment]
Yes, I like it! But I'd prefer if there was a little "gap" between the wheel and the dog, just as the gap between the Doom-styled "D" and the dog in the game executable's icon.

**Comment by rfomin** [comment]
> Yes, I like it! But I'd prefer if there was a little "gap" between the wheel and the dog, just as the gap between the Doom-styled "D" and the dog in the game executable's icon.

I am very bad at this, I have tried but not happy with the results.

**Comment by JNechaevsky** [comment]
Do we have a vector source for the dog icon by the chance? AFAIR it was somewhere, probably in initial issue.
I still not good with vector graphics, but I'll see what I can do according to Fabian's recommendation. 

And wait a sec, setup executable for Woof, which have all setting inside game executable? Or am I getting something wrong?

**Comment by rfomin** [comment]
> Do we have a vector source for the dog icon by the chance?

Yes: [icon.zip](https://github.com/fabiangreffrath/woof/files/8860603/icon.zip)

> And wait a sec, setup executable for Woof, which have all setting inside game executable? Or am I getting something wrong?

This is only for multiplayer, all other settings in the in-game menu.

**Comment by fabiangreffrath** [comment]
> And wait a sec, setup executable for Woof, which have all setting inside game executable? Or am I getting something wrong?

Network setup.

**Comment by JNechaevsky** [comment]
Ah, understood. Maybe it should be not a gear, but network icon? The question is - which exactly. Wifi or LAN probably aren't clear enough, maybe something like globe? Or...?

**Comment by fabiangreffrath** [comment]
A globe would be nice!

**Comment by fabiangreffrath** [comment]
🎶 Woof around the world 🎶

**Comment by fabiangreffrath** [comment]
Beautiful! I'd like to go with this one if @rfomin doesn't object.

**Comment by rfomin** [comment]
Sure I like it, thanks!

**Pull request merged**
