### PR TITLE
disable compatibility menu items according to command line parameters

### PR DESCRIPTION
**Pull request by rfomin**
* Only disable "Improved Hit Detection" if "Emulate INTERCEPTS overflow" enabled

Fix [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-1430-mar-15-2024/?do=findComment&comment=2779896)

### CODE REVIEW

**Comment by rfomin** [comment]
This gets confusing again. Alternatively, we could remove item disabling altogether. Does this really help users? Not sure.

**Comment by fabiangreffrath** [comment]
> This gets confusing again. Alternatively, we could remove item disabling altogether. Does this really help users? Not sure.

I agree that it's getting maximum confusing, but I wouldn't want to drop the concept of disabling menu items altogether. More specifically, I'd like to keep it to show direct reaction to user interaction. For example, dynamic resolution should be grayed out if the user selects a resolution below 600p, and crosshair choices should be disabled if no crosshair is selected. Also, I think all options that are unavailable if strict mode is selected should be grayed out. 

But options that depend on a combination of internal states, the choice of default or current complevel may get dropped. Prominent example is the translucent ghost monster feature, which only makes sense with Vanilla complevels. Non-Vanilla complevels don't even have ghost monsters, so it is perfectly fine to have this feature enabled all the time. 

The case at hand is a bit more complicated, granted. Improved hit detection could get applied to all complevels, whereas intercepts overflow emulation is restricted to Vanilla complevel, but having both enabled at the same time is impossible. I think we should gray out improved hit detection in the menu with the same conditions that are checked in the actual game code. So it's clear to the user that this feature is currently not available.

**Comment by fabiangreffrath** [comment]
Just realized that my last sentence contradicts my first sentence in the second paragraph. 😫

**Comment by rfomin** [comment]
I think it makes sense to remove all compatibility checks from the menus (S_VANILLA, S_BOOM and S_MBF flags). Although this PR works so far, we can keep the checks for a while and remove them later if things get even more complicated.

**Comment by fabiangreffrath** [comment]
> I think it makes sense to remove all compatibility checks from the menus (S_VANILLA, S_BOOM and S_MBF flags). 

That's what I wanted to say. However, we still don't have a way to show mutually exclusive features then.

**Comment by rfomin** [comment]
Is this better? https://github.com/fabiangreffrath/woof/pull/1600/commits/b613bfeb731ac0b8a416e1038821749f27362c83


> > I think it makes sense to remove all compatibility checks from the menus (S_VANILLA, S_BOOM and S_MBF flags).
> 
> That's what I wanted to say. However, we still don't have a way to show mutually exclusive features then.

I'm fine with either approach.

**Comment by fabiangreffrath** [comment]
> Is this better?

It's an improvement. Any chance we can get rid of `complevel_t` and check against `demo_version` again?

**Comment by rfomin** [comment]
> Any chance we can get rid of `complevel_t` and check against `demo_version` again?

Then menu items will be disabled during demo reel playback, which is annoying. I think `complevel_t` makes sense historically, originally complevel is a menu item index in PrBoom+ 😄

**Comment by fabiangreffrath** [comment]
Right, but now we have both the concepts of `demo_version` and `complevel` which basically mean the same.

**Comment by rfomin** [comment]
> Right, but now we have both the concepts of `demo_version` and `complevel` which basically mean the same.

We need two concepts, because `demo_version` changes when the demo is played, and we need an index for the `default_complevel` menu item. Although, we can organize it differently.

By the way, I don't like the magic numbers `109`, `202` etc., I think we should macronize them.

**Comment by fabiangreffrath** [comment]
> We need two concepts, because `demo_version` changes when the demo is played, and we need an index for the `default_complevel` menu item. 

I see, thank you. 

> By the way, I don't like the magic numbers `109`, `202` etc., I think we should macronize them.

Yes, absolutely.

**Comment by rfomin** [comment]
> > By the way, I don't like the magic numbers `109`, `202` etc., I think we should macronize them.
> 
> Yes, absolutely.

Done in https://github.com/fabiangreffrath/woof/pull/1600/commits/16ddfccd6d8b7d312ac2f76fbdbd61e9afc9fd47

**Comment by fabiangreffrath** [comment]
There are other missed occasions in `g_game.c` where `demo_version` is checked.

**Review by fabiangreffrath — APPROVED** [review]
Alright, thanks!

**Pull request merged**
