### PR TITLE
always display level title in automap overlay mode

### PR DESCRIPTION
**Pull request by rfomin**
Feature request: [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-1010-july-18-2022-updated-winmbf/?do=findComment&comment=2528696)

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]

**Review by rfomin — COMMENTED** [review]
@fabiangreffrath What if we remove automap widgets at this point?

**Comment by rfomin** [comment]
> Do we have any idea how many people actually use them?

There were small bugs with a distributed HUD and multi-line messages that no one noticed, but these are also obscure features. 😄

**Comment by fabiangreffrath** [comment]
Do you think you have everything ironed or now?

**Comment by rfomin** [comment]
> Do you think you have everything ironed or now?

Yes, I think so.

**Review by fabiangreffrath — APPROVED** [review]

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
