### PR TITLE
CI: bump to ubuntu-22.04

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Let's see what breaks.

### CODE REVIEW

**Comment by rfomin** [comment]
I suggest to add `--force` to fix this warning:
> Too many #ifdef configurations - cppcheck only checks 12 configurations. Use --force to check all configurations.

Then it seems to work more correctly.
```diff
diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
index f4f7ea7..04a4a70 100644
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -47,7 +47,7 @@ jobs:
       - name: Run cppcheck
         shell: bash
         run: |
-          cppcheck --error-exitcode=1 -q -U_WIN32 -Isrc opl src setup textscreen
+          cppcheck --error-exitcode=1 -q -j4 --force -U_WIN32 -Isrc opl src setup textscreen
 
   win64_msys2:
     runs-on: windows-latest
```

**Comment by fabiangreffrath** [comment]
> I suggest to add `--force` to fix this warning:

Oh, yes, sure. Could you please just add it?

**Comment by rfomin** [comment]
> Oh, yes, sure. Could you please just add it?

OK. The UMAPINFO `scanner` errors are gone, but everything else is still there.

**Comment by fabiangreffrath** [comment]
Thanks! I think I'll have to report this string size alert in `src/m_menu.c` as a bug report to the cppcheck authors.

**Comment by fabiangreffrath** [comment]
`ubuntu-22.04` will become `ubuntu-latest` as of December 1st:
https://github.com/actions/runner-images/issues/6399

After this date, this PR will become obsolete and we can merge #771 to get rid of all new warnings at once.

**Comment by fabiangreffrath** [comment]
> Thanks! I think I'll have to report this string size alert in `src/m_menu.c` as a bug report to the cppcheck authors.

I have just requested access (!) to the cppcheck issue tracker. Let's see where this leads us...

**Comment by rfomin** [comment]
> I have just requested access (!) to the cppcheck issue tracker. Let's see where this leads us...

It seems ubuntu-22.04 has cppcheck-2.7 and there have been two releases since then: https://github.com/danmar/cppcheck/releases

Anyway I think there were no useful warnings from cppcheck ever. Maybe we should remove it?

**Comment by fabiangreffrath** [comment]
> > I have just requested access (!) to the cppcheck issue tracker. Let's see where this leads us...
> 
> It seems ubuntu-22.04 has cppcheck-2.7 and there have been two releases since then: 

Right, but 2.9 in Debian emits the same warnings.

> Anyway I think there were no useful warnings from cppcheck ever. Maybe we should remove it?

It was very helpful in the early days and is mostly meant to catch rough edges. I don't know when it started to go "super smart", but I think the few nit-picks that it unveils are easy enough to fix and improve code quality as a whole. The one odd issue that IMHO makes no sense will be reported upstream and meanwhile there is a trivial fix for it in the corresponding PR.

**Comment by fabiangreffrath** [comment]
Yep, this is indeed a bug in cppchecker that is now fixed:
https://github.com/danmar/cppcheck/pull/4428

**Comment by fabiangreffrath** [comment]
ubuntu-22.04 is now ubuntu-latest

**Pull request closed without merging**
