### PR TITLE
loop MIDI using SDL_Mixer method

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Hm, I don't get it. Hasn't this code been taken from another port where it was known to work? Is this a threading issue again?

**Comment by rfomin** [comment]
> Hm, I don't get it. Hasn't this code been taken from another port where it was known to work? Is this a threading issue again?

Maybe this code is not enabled by default in Odamex (they also have portmidi). There is no problem with the threads, just no MIDI reset when looping. The better solution would be to reset like we do in the Windows module, but I still don't have a macOS VM and MIDI hardware to test.

**Comment by rfomin** [comment]
@fabiangreffrath Is this OK to merge? I think it's good enough to solve the https://github.com/fabiangreffrath/woof/issues/1355
In the future, we will unify this with Windows and the ALSA modules.

**Review by fabiangreffrath — APPROVED** [review]
Well, okay. 😉

**Pull request merged**
