### PR TITLE
stop looping sounds after reaching a timeout

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Seems to work well, but now looping sounds play over the screen melt when the map exits and only stop when the intermission screen starts (even worse in DSDA, btw).

**Comment by fabiangreffrath** [comment]
Possible solution:
```patch
diff --git a/src/d_main.c b/src/d_main.c
index 47b3f4d..9707d2e 100644
--- a/src/d_main.c
+++ b/src/d_main.c
@@ -369,6 +369,7 @@ void D_Display (void)
       done = wipe_ScreenWipe(wipe_Melt,0,0,SCREENWIDTH,SCREENHEIGHT,tics);
       M_Drawer();                   // menu is drawn even on top of wipes
       I_FinishUpdate();             // page flip or blit buffer
+      S_UpdateSounds(NULL);
     }
   while (!done);
 }
diff --git a/src/s_sound.c b/src/s_sound.c
index 26c294a..de6bbe1 100644
--- a/src/s_sound.c
+++ b/src/s_sound.c
@@ -542,6 +542,11 @@ void S_UpdateSounds(const mobj_t *listener)
          continue;
       }
 
+      if (!listener)
+      {
+         S_StopChannel(cnum);
+      }
+
       if(sfx)
       {
          if (c->loop && gametic > c->loop_timeout)

```

**Comment by fabiangreffrath** [comment]
I think I'd rather just reintroduce `S_StopLoopSounds()` for this.

**Review by kraflab — APPROVED** [review]

**Review by rfomin — APPROVED** [review]
The current version of this PR seems to improve clicking in the [DBP25](https://www.doomworld.com/idgames/levels/doom2/Ports/d-f/dbp25_dbd) start room (clicking returns in #830)

**Pull request merged**
