### PR TITLE
Replace `show_endoom` with `exit_sequence`

### PR DESCRIPTION
**Pull request by ceski-1**
Fixes https://github.com/fabiangreffrath/woof/issues/1871

### CODE REVIEW

**Review by rfomin — APPROVED** [review]
Thank you!

**Review by fabiangreffrath — APPROVED** [review]
Cool, thank you! The current default value would correspond to `EXIT_SEQUENCE_PWAD_ENDOOM`, though.

**Comment by ceski-1** [comment]
> Cool, thank you! The current default value would correspond to `EXIT_SEQUENCE_PWAD_ENDOOM`, though.

Before and after this PR, the default is off, but would you like it to be "PWAD ENDOOM" instead? (Play sound, show ENDOOM for PWADs only)

**Comment by fabiangreffrath** [comment]
I somehow had in mind that "PWAD only" was the default. I'm fine with it being "off", though.

**Comment by MrAlaux** [comment]
Given the scope of this new setting, and the fact that it arguably affects something outside of the game (doesn't affect the display immediately), wouldn't it be more appropriate to move it to the _Misc_ tab?

**Comment by ceski-1** [comment]
> Given the scope of this new setting, and the fact that it arguably affects something outside of the game (doesn't affect the display immediately), wouldn't it be appropriate to move it to the _Misc_ tab?

Seems reasonable to me. Maybe at the bottom of "Misc > Miscellaneous"?

(Should we move "Menu Backdrop" to config-only while we're at it?)

**Comment by MrAlaux** [comment]
> Should we move "Menu Backdrop" to config-only while we're at it?

FWIW, in Nugget, I usually leave it on _Dark_ for readability, but I often disable it momentarily to check the effect of some settings -- old and new -- on the screen, world and whatnot.

**Comment by rfomin** [comment]
> Given the scope of this new setting, and the fact that it arguably affects something outside of the game (doesn't affect the display immediately), wouldn't it be appropriate to move it to the _Misc_ tab?

Yes, agreed.

> > Should we move "Menu Backdrop" to config-only while we're at it?
> 
> FWIW, in Nugget, I usually leave it on _Dark_ for readability, but I often disable it momentarily to check the effect of some settings -- old and new -- on the screen, world and whatnot.

We can disable it if the user hover cursor over “Resolution Scale”, “FOV” and some display settings. But it might be too intrusive.

**Comment by fabiangreffrath** [comment]
> Yes, agreed.

Me too.

> We can disable it if the user hover cursor over “Resolution Scale”, “FOV” and some display settings. But it might be too intrusive.

This would be very surprising. I think you can see the impact of your changes even through the shaded background. If you want to focus on details, it's probably not asked too much to close (and reopen) the menu.

**Pull request merged**
