### PR TITLE
Move tranmap.dat to /autoload/cache

### PR DESCRIPTION
**Pull request by ceski-1**
Any opinions on moving this file to keep the game root clean? This is just one idea.

### CODE REVIEW

**Comment by rfomin** [comment]
Maybe we should eliminate the file caching of the tranmap altogether.

I believe it's generally acceptable to save things to the game root. On modern OS applications should save configs to user profiles, but I dislike Doom ports doing this (only GZDoom?)

**Comment by ceski-1** [comment]
I don't mind getting rid of it either. Killough's log has a funny comment that slow computers in '98 would take 10 seconds to generate that file, so it seems like an artifact of the past. I also dislike saving to the user directory even though it's supposedly the correct practice now (for GZDoom, I use `gzdoom_portable.ini` to avoid it).

**Comment by kraflab** [comment]
When I refactored tranmap management in dsda-doom I also considered getting rid of the file caching, but when I checked how much time it saves for instance when running the regression tests where you're launching the program repeatedly, it did add up.

**Comment by fabiangreffrath** [comment]
I am generally all for caching data instead of calculating the same values again and again. That's why I'm so much in favor of precaching sounds (although strictly speaking we are mostly caching the same IWAD sound data during each start, but anyway, same applies to e.g. 
color translation tables).

In the case at hand, I don't think that `tranmsp.dat` litters the game directory more than, say, the config file or screen shots. We would have to measure if it's really faster nowadays to read the table from disk than to recalculate it, but if it doesn't do harm, why remove it?

**Comment by ceski-1** [comment]
Good points, it makes sense to keep it then. Files that sit loose in the root start to quickly add up and clutter things, so that's the motivation, but it's entirely personal preference. I can also rename it to tranmap.lmp and put it in doom-all to suppress the file creation in the root.

As a side note, why not bundle the default one to begin with?

**Comment by rfomin** [comment]
> As a side note, why not bundle the default one to begin with?

It will be regenerated if user changes translucency percentage or there will be custom PLAYPAL from PWAD. Sure, in most cases it's 66% and PLAYPAL from IWAD, but it's just not worth complications.

**Comment by fabiangreffrath** [comment]
> measure if it's really faster nowadays to read the table from disk than to recalculate it

To put some numbers behind this claim, I applied the following patch:
```patch
--- a/src/r_data.c
+++ b/src/r_data.c
@@ -990,6 +990,9 @@ void R_InitTranMap(int progress)
 // Must be called after W_Init.
 //
 
+#include <time.h>
+struct timespec a, b;
+
 void R_InitData(void)
 {
   // [crispy] Moved R_InitFlats() to the top, because it sets firstflat/lastflat
@@ -1000,7 +1003,11 @@ void R_InitData(void)
   R_InitFlatBrightmaps();
   R_InitTextures();
   R_InitSpriteLumps();
+  clock_gettime(CLOCK_MONOTONIC_RAW, &a);
     R_InitTranMap(1);                   // killough 2/21/98, 3/6/98
+  clock_gettime(CLOCK_MONOTONIC_RAW, &b);
+  fprintf(stderr, "%lu\n", (b.tv_sec - a.tv_sec) * 1000000 + (b.tv_nsec - a.tv_nsec) / 1000);
+  exit(0);
   R_InitColormaps();                    // killough 3/20/98
 }
 
```

And then:

```shell
$ for i in 1 2 3 ; do ./build/src/woof > /dev/null ; done
42
51
44

$ for i in 1 2 3 ; do rm ~/.local/share/woof/tranmap.dat ; ./build/src/woof > /dev/null ; done
14972
15071
14855
```

So, yes, even if it only ends up at about 15 ms, reading from disk is still factor 300 times faster than recalculating the table.

**Comment by kraflab** [comment]
dsda-doom structures its tranmap cache like this:
`dsda_doom_data/tranmaps/<hash_of_palette>/tranmap_<alpha>.dat`

With this is remembers the tranmap for different palettes and also doesn't need any of the header data to check if a tranmap has the same context.

**Pull request closed without merging**
