### PR TITLE
update CHANGELOG.md

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by MrAlaux** [comment]
I made a few mostly-unintrusive grammar fixes, I hope you don't mind.

**Comment by rfomin** [comment]
> FWIW, I would personally tweak the wording even further, and I would've done so for previous changelogs too, but I really don't want to be too intrusive.

Please do so, my wording is far from perfect. Any corrections would be appreciated.

**Comment by fabiangreffrath** [comment]
> Please do so, my wording is far from perfect. Any corrections would be appreciated.

Seconded. Every improvement is appreciated, please don't hesitate.

**Comment by ceski-1** [comment]
For future reference, I updated the [Woof MIDI implementation](https://gist.github.com/ceski-1/86b7405a66ff67c42a788000edc3b625) doc. Maybe it can be a wiki page, eventually.

**Comment by fabiangreffrath** [comment]
Yes, please, this information is gold!

**Comment by MrAlaux** [comment]
@ceski-1, what do you think of a064bdbdcb4a413674a4c27032a31049e917f68b?

By the way, what exactly was wrong with UMAPINFO in IWADs? Were UMAPINFO lumps not being loaded from IWADs? I want to write that change correctly.

**Comment by rfomin** [comment]
> By the way, what exactly was wrong with UMAPINFO in IWADs? Were UMAPINFO lumps not being loaded from IWADs?

Before https://github.com/fabiangreffrath/woof/commit/cce6bdec18ab5492e969d986de6baaddfd32450f UMAPINFO simply didn't work in IWADs. [Chex Quest 3: Vanilla Edition](https://www.doomworld.com/forum/topic/143907-rc4-chex-quest-3-vanilla-edition/) is the only IWAD that has UMAPINFO lump (and DBIGFONT).

**Comment by fabiangreffrath** [comment]
Is this still missing the latest commit(s)?

**Comment by rfomin** [comment]
> Is this still missing the latest commit(s)?

I think it's complete now.

**Comment by ceski-1** [comment]
> > Maybe it can be a wiki page, eventually.
> 
> Yes, please! And your excellent gamepad page too, in some form.

MIDI page is up: https://github.com/fabiangreffrath/woof/wiki/MIDI

I'll have to remake the gamepad page since wikis don't allow embedded javascript.

**Comment by fabiangreffrath** [comment]
> MIDI page is up: https://github.com/fabiangreffrath/woof/wiki/MIDI

Thank you!

**Pull request merged**
