### PR TITLE
modify M_BaseName()

### PR DESCRIPTION
**Pull request by rfomin**
Tested it, seems to work.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Thank you, but this would fail for mixed strings which contain both `\\` and `/`. I think we will need two pointers, one calling `strrchr()` for each candidate. If both are `NULL`, return `path` as before, else return the pointer with the higher numerical value plus one.

**Comment by rfomin** [comment]
Maybe just call `NormalizeSlashes()` somewhere?

**Comment by fabiangreffrath** [comment]
We should probably call it on all path strings that we constuct ourselves.

**Comment by rfomin** [comment]
> We should probably call it on all path strings that we constuct ourselves.

Then all path strings must be normalized and in `M_BaseName()` we can check only for `/`?

**Comment by fabiangreffrath** [comment]
Yep. It's a mess! /o\

**Comment by rfomin** [comment]
I still like my first PR :) I agree with your philosophy, but at the same time, I think that the more code we share with Choco, the better.

**Comment by fabiangreffrath** [comment]
You are right. Let's get rid of slash conversion!

**Pull request closed without merging**
