### PR TITLE
bring implementation of -timedemo in line with Chocolate Doom

### PR DESCRIPTION
**Pull request by rfomin**
It doesn't matter of course, I just don't like Boom's implementation.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Is there a difference between -timedemo and -fastdemo now? What is the difference anyway? I am a bit lost here...

**Comment by rfomin** [comment]
> Is there a difference between -timedemo and -fastdemo now? What is the difference anyway? I am a bit lost here...

-fastdemo is much faster since it replaces I_GetTime.
The current implementation works the same as the previous one, with no measurable differences from my testing. Interestingly, -oldsync is faster.

**Comment by fabiangreffrath** [comment]
But -timedemo doesn't wait for the next tic, either, else it would be -playdemo, right?

**Comment by rfomin** [comment]
There is no difference with -nodraw, but with drawing -fastdemo is 5-10 times faster than -timedemo.

**Pull request merged**
