### PR TITLE
use CMake FetchContent for simple dependencies

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Will the sources end up in the release tarballs?

**Comment by rfomin** [comment]
> Will the sources end up in the release tarballs?

I think not, GitHub generates the source archive from the repository. Is there a source package command?

**Comment by fabiangreffrath** [comment]
We need the sources to be conplete and self-contained when we tag a release.

**Comment by rfomin** [comment]
> We need the sources to be conplete and self-contained when we tag a release.

It will be the same as with other dependencies, it's not like we're including SDL sources. Maybe there's something I don't understand?

**Comment by fabiangreffrath** [comment]
SDL and openal-soft are big common projects and we can expect these to be pre-installed on systems on which Woof is built. On the other hand, miniz and spng are tiny pet projects and we cannot expect them to be "just there", so we'll have to carry them with us. For example, there are no Debian packages for miniz, so I won't be able to package up a new release without downloading additional sources. This is what I meant with self-contained.

**Comment by rfomin** [comment]
> For example, there are no Debian packages for miniz, so I won't be able to package up a new release without downloading additional sources.

But CMake downloads them. Is downloading during build time not allowed in Debian?

**Comment by fabiangreffrath** [comment]
No, strictly forbidden.

**Comment by rfomin** [comment]
> No, strictly forbidden.

Okay, what about git submodules then? It will look like this: https://github.com/odamex/odamex/tree/stable/libraries

**Comment by fabiangreffrath** [comment]
Yes, okay, as long as it is easy to update and end up in our released sources.

**Comment by ceski-1** [comment]
It's not too bad, I did it for a contribution to Odamex a couple years ago: https://github.com/odamex/odamex/commit/87713c2b15b8eaf8a03c321ab798c9e925661d79

**Pull request closed without merging**
