### PR TITLE
rearrange includes with include-what-you-use tool

### PR DESCRIPTION
**Pull request by rfomin**
I used this mapping file: [woof.imp.txt](https://github.com/fabiangreffrath/woof/files/9156141/woof.imp.txt)
 Command line:
```
CC="clang" cmake -B build_iwyu -DCMAKE_C_INCLUDE_WHAT_YOU_USE="include-what-you-use;-Xiwyu;--mapping_file=../woof.imp;"
cd build_iwyu
ninja > out
fix_includes.py --reorder < out
```

Still the tool adds includes from "facade" files, I think we need to use pragmas for perfect result. Not sure if it's worth it.

### CODE REVIEW

**Comment by rfomin** [comment]
Still haven't got a good result with this tool. Also the benefits are negligible - our project is only C and relatively small.

**Comment by fabiangreffrath** [comment]
What I liked about this PR, though (and the other IWYU one before), was the admittedly pedantic complete definitions of the structs in header files.

**Comment by rfomin** [comment]
> What I liked about this PR, though (and the other IWYU one before), was the admittedly pedantic complete definitions of the structs in header files.

It seems there is no option to get only structure definitions, only all changes at once.

**Comment by fabiangreffrath** [comment]
Okay.

**Pull request closed without merging**
