### PR TITLE
draw armsbg in ST_refreshBackground

### LINKED ISSUE #539: [bug] ARMS numbers don't display properly
doom00
The ARMS numbers should appear normally like the ammo numbers. I tested Augher Zenith and it showed the numbers properly in PrBoom but not in Woof. Sorry, I don't have PrBoom's screenshot for comparison right now.

There are plenty of wads affected by this bug.

### PR DESCRIPTION
**Pull request by rfomin**
Fixes #539

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Funny, I was *just* about to commit a similar fix:
https://github.com/fabiangreffrath/crispy-doom/commit/443673e3658ea9d12956be5dd04ce97055d54cb7

**Comment by rfomin** [comment]
Wow, I somehow missed that in the Crispy code :smile:  Should we remove the `w_armsbg` widget? It is no longer in use.

**Comment by fabiangreffrath** [comment]
If we don't use it anymore, let's just throw it out.

**Comment by fabiangreffrath** [comment]
And then, we don't even need the entire `st_binicon_t` type anymore! 😮

**Pull request merged**
