### PR TITLE
fixes for -recordfrom command

### PR DESCRIPTION
**Pull request by rfomin**
I also want to add the `-recordfromto` command (from PrBoom+/DSDA-Doom, for demo join). Perhaps we should rename or remove `-recordfrom`.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
`It is the same as "-loadgame <save> -record <demo>"`

Yeah, that's how it works in Crispy since forever.

**Comment by rfomin** [comment]
> `It is the same as "-loadgame <save> -record <demo>"`
> 
> Yeah, that's how it works in Crispy since forever.

Heretic/Hexen has `-recordfrom`, PrBoom+ has both `-recordfrom` and `-recordfromto`, DSDA-Doom removed `-recordfrom`.

On second thought maybe we should have both too 😄

**Comment by fabiangreffrath** [comment]
> On second thought maybe we should have both too 😄

Okay 👍

**Review by fabiangreffrath — APPROVED** [review]

**Comment by kraflab** [comment]
This feature is planned to return to dsda-doom in the future, it was just temporarily removed, fyi

**Pull request merged**
