### PR TITLE
render textscreen content to an upscaled intermediate texture

### LINKED ISSUE #929: show ENDOOM screen / setup window with "nearest" scaling method
Repeatedly requested on Doomworld: To prevent a blurry appearance of the ENDOOM screen (or the setup tool), scale the screen by "nearest" method. Probably depending on font size?

### PR DESCRIPTION
**Pull request by fabiangreffrath**
May this count as a compromise to fix #929 ?

### CODE REVIEW

**Comment by rfomin** [comment]
How about aspect ratio correction?
```diff
diff --git a/textscreen/txt_sdl.c b/textscreen/txt_sdl.c
index 6c47b0f..98de2f6 100644
--- a/textscreen/txt_sdl.c
+++ b/textscreen/txt_sdl.c
@@ -228,6 +228,8 @@ static void ChooseFont(void)
 // Returns 1 if successful, 0 if an error occurred
 //
 
+boolean txt_aspect_ratio = true;
+
 void TXT_PreInit(SDL_Window *preset_window, SDL_Renderer *preset_renderer)
 {
     if (preset_window != NULL)
@@ -244,6 +246,7 @@ void TXT_PreInit(SDL_Window *preset_window, SDL_Renderer *preset_renderer)
 int TXT_Init(void)
 {
     int flags = 0;
+    int actualheight;
 
     if (SDL_Init(SDL_INIT_VIDEO) < 0)
     {
@@ -255,6 +258,11 @@ int TXT_Init(void)
     screen_image_w = TXT_SCREEN_W * font->w;
     screen_image_h = TXT_SCREEN_H * font->h;
 
+    if (txt_aspect_ratio)
+    {
+        screen_image_h = 6 * screen_image_h / 5;
+    }
+
     // If highdpi_font is selected, try to initialize high dpi rendering.
     if (font == &highdpi_font)
     {
@@ -331,8 +339,10 @@ int TXT_Init(void)
                                         TXT_SCREEN_H * font->h,
                                         8, 0, 0, 0, 0);
 
+    actualheight = txt_aspect_ratio ? 6 * screenbuffer->h / 5 : screenbuffer->h;
+
     // Set width and height of the logical viewport for automatic scaling.
-    SDL_RenderSetLogicalSize(renderer, screenbuffer->w, screenbuffer->h);
+    SDL_RenderSetLogicalSize(renderer, screenbuffer->w, actualheight);
 
     SDL_LockSurface(screenbuffer);
     SDL_SetPaletteColors(screenbuffer->format->palette, ega_colors, 0, 16);
@@ -462,7 +472,7 @@ static void GetDestRect(SDL_Rect *rect)
     rect->x = 0;
     rect->y = 0;
     rect->w = screenbuffer->w;
-    rect->h = screenbuffer->h;
+    rect->h = txt_aspect_ratio ? 6 * screenbuffer->h / 5 : screenbuffer->h;
 }
 
 void TXT_UpdateScreenArea(int x, int y, int w, int h)
```

**Comment by rfomin** [comment]
> Will this apply to the setup tool or ENDOOM or both?

In my little patch, this applies to both, although it looks bad in the setup tool.

> Will this consider the aspect ratio correction settings set for the game when applied to the ENDOOM screen?

We can set `txt_aspect_ratio` variable in `TXT_PreInit()`

> This would also have to get applied to the intermediate texture, I assume? Texture height being `txt_aspect_ratio ? 1200 : 1000`?

Probably yes, but I haven't tried it.

**Comment by fabiangreffrath** [comment]
I think we can get even better results with smaller intermediate texture dimensions:

```patch
--- a/textscreen/txt_sdl.c
+++ b/textscreen/txt_sdl.c
@@ -350,7 +350,7 @@ int TXT_Init(void)
     texture_upscaled = SDL_CreateTexture(renderer,
                          SDL_GetWindowPixelFormat(TXT_SDLWindow),
                          SDL_TEXTUREACCESS_TARGET,
-                         1600, 1200);
+                         2*screenbuffer->w, 2*screenbuffer->h);
 
     return 1;
 }
```

**Comment by fabiangreffrath** [comment]
Also, I don't think we need aspect ratio correction for textscreen. The aspect ratio is pretty much given by the font glyphs' dimensions and the 80x35 chars grid, and I think the whole image looks unnaturally stretched if ARC is applied.

**Comment by rfomin** [comment]
> The aspect ratio is pretty much given by the font glyphs' dimensions and the 80x35 chars grid, and I think the whole image looks unnaturally stretched if ARC is applied.

No, it is our text screen unnaturally stretched, try DosBox-staging or ENDOOM screen in GZDoom. I like this better:
```c
4*screenbuffer->w, 4*actualheight);
```
Although I'm fine without aspect ratio correction.

**Comment by rfomin** [comment]
> Upscaling by factor `4` means a 2560x1600 intermediate texture. 😮 For textscreen?

Yes, why not? It's nothing even for an old GPU. I tried the factor `16` with no performance degradation. I think we can consider factor `8`, it looks noticeably better to me.

**Comment by fabiangreffrath** [comment]
It depends on the font. The font glyphs sizes are `4x8`, `8x16` and `16x32` px for the small, normal and large font, respectively. Multiply these values by `80x25` the get window dimensions. We should have the intermediate texture size based on this.

**Comment by liPillON** [comment]
test results for commit [7254d48](https://github.com/fabiangreffrath/woof/pull/944/commits/7254d483bdd7b9c5a40453ec7b5db703333ed382)

- setup: [less distortion, slightly blurrier, still sharper than before](https://user-images.githubusercontent.com/48625273/225924384-384e3e55-e636-4fd3-b775-2daaab708726.png)
- windowed endoom: [basically the same as without any PR applied](https://user-images.githubusercontent.com/48625273/225924386-c3551396-5eb3-4a9a-b8b0-abaf8d3fb353.png)
- fullscreen endoom: [less distortion, slightly blurrier, still sharper than without PR](https://user-images.githubusercontent.com/48625273/225924388-c95506a5-bef1-4544-83d8-50da90376b19.png)

Each image goes like this:
left: without PR
center: with PR v1 (commit e388b11)
right: with PR v2 (commit 7254d48) 

[woof-pr944-tests.zip](https://github.com/fabiangreffrath/woof/files/11002019/woof-pr944-tests.zip)



I'll test V3 (commit [7c68f3e](https://github.com/fabiangreffrath/woof/pull/944/commits/7c68f3e4212ecb97c03bd8a662942b5be313cc03)) later, if there are no other incoming changes.

**Comment by rfomin** [comment]
@liPillON Do you have a 4k monitor? Looks like a `16x32` font.

**Comment by liPillON** [comment]
I'm on a laptop with a 1920x1200 display and an Iris XE gpu.
Windowed screenshots are taken using Windows11's own Snipping Tool.
Fullscreen screenshots are taken using the PrintScreen key and pasting the result into Paint.net

**Comment by liPillON** [comment]
test results for V3 (commit 7c68f3)
I'm comparing it only against V2 (commit 7254d48) which gave the best results yet (imho)

- setup: [basically the same as V2](https://user-images.githubusercontent.com/48625273/225935401-be5f54c3-e8af-440c-9b69-f1ab674215ac.png)
- endoom windowed: [basically the same as V2](https://user-images.githubusercontent.com/48625273/225935398-dcfd36a3-b04a-4188-9a3a-9f01baeddc0e.png)
- endoom fullscreen: [it has regressed back to what's in current master branch](https://user-images.githubusercontent.com/48625273/225935389-e493c2c9-e989-4d8f-b831-fe1b81ea46e1.png)


[woof-pr944-testV3.zip](https://github.com/fabiangreffrath/woof/files/11002448/woof-pr944-testV3.zip)


V2 still looks the winner to me

**Comment by fabiangreffrath** [comment]
Then it's probably factor 2 for the large font and factor 4 for the normal one? (Formerly posted to wrong PR)

**Comment by rfomin** [comment]
> Personally I'm fine with always using 2x without testing which font is being used

I agree, 2x seems to be enough. However, we don't need it for the small font, as if it is ever used, it will be a very old/exotic device. Maybe we should check if hardware acceleration is available?

**Comment by rfomin** [comment]
> Also, do we need some special case for the `highdpi` pseudo font?

To be honest, I'm not a fan of the big font. And SDL2 probably won't work on a very old device anyway. So how about removing the small/big font?

**Comment by fabiangreffrath** [comment]
Yes, we can do that. But the `highdpi` font is actually the normal font with the retina renderer.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
