### PR TITLE
draw crosshair in the menu

### LINKED ISSUE #1475: Show crosshair preview?
Should we draw a crosshair preview? Two ideas:
1. Allow `HU_DrawCrosshair()` to execute if the current menu is the crosshair menu. Some of the crosshair menu item names will have to be shortened so the crosshair can be seen. This won't be useful if the menu backdrop is set to texture.
2. Run a function that draws the current crosshair patch to the right of "Enable Crosshair". So it would be "None", "+", etc. instead of "None", "Cross", etc.

### PR DESCRIPTION
**Pull request by rfomin**
woof0001

Fix #1475

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Thanks for that! The feature is cool, but the position appears a bit random. 🤔

**Comment by rfomin** [comment]
> Thanks for that! The feature is cool, but the position appears a bit random. 🤔

Perhaps we should draw box for like in Eternity:
image

**Comment by ceski-1** [comment]
I like this a lot but maybe we can somehow work on the positioning. Either the center of the screen (requires renaming items so there's space to see it) or shift all of the "Status Bar / HUD" menus slightly to the left to leave more space to the right of "Crosshair".

**Comment by fabiangreffrath** [comment]
> shift all of the "Status Bar / HUD" menus slightly to the left to leave more space to the right of "Crosshair"

I'd prefer this approach.

**Comment by rfomin** [comment]
Still looks awkward:

woof0002

If anyone has better ideas, feel free to commit to this PR.

**Comment by fabiangreffrath** [comment]
How about this?

```patch
--- a/src/m_menu.c
+++ b/src/m_menu.c
@@ -3387,8 +3387,9 @@ static void M_DrawStatusHUD(void)
     patch_t *patch = W_CacheLumpName(crosshair_lumps[hud_crosshair], PU_CACHE);
 
     int x = XH_X + 80 - SHORT(patch->width) / 2;
-    int y = M_Y + 15 - SHORT(patch->height) / 2;
+    int y = M_Y + M_SPC / 2 - SHORT(patch->height) / 2 - 1;
 
+    V_FillRect(x - 4, y - 4, SHORT(patch->width) + 8, SHORT(patch->height) + 8, v_darkest_color);
     V_DrawPatchTranslated(x, y, patch, colrngs[hud_crosshair_color]);
   }
 
```

We could just shade the background a bit darker instead of filling it with solid black.

**Comment by rfomin** [comment]
> `V_FillRect(x - 4, y - 4, SHORT(patch->width) + 8, SHORT(patch->height) + 8, v_darkest_color);`

I don't think a black rectangle looks good on a textured menu backdrop.

**Comment by fabiangreffrath** [comment]
Yes, plain black is a bit harsh. We could use something like `V_ColorizeRect(x, y, w, h, cr)`. 😁

**Comment by rfomin** [comment]
> Yes, plain black is a bit harsh. We could use something like `V_ColorizeRect(x, y, w, h, cr)`. 😁

No rect looks OK to me.

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
