### PR TITLE
restore vanilla "Read This" screens

### LINKED ISSUE #1503: "Read This!" shows Woof Credits and CREDIT lump instead of HELP
As the title says. Was this intentional?

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1503

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Is this Vanilla Doom or Vanilla MBF?

**Comment by rfomin** [comment]
> Is this Vanilla Doom or Vanilla MBF?

It's Vanilla Doom (code taken from Choco/Crispy). I never liked MBF's changes to it. Extended help screens work as before, tested with [sherlock.wad](https://www.doomworld.com/forum/topic/111465-boom-extended-help-screens-an-undocumented-feature/)

**Comment by fabiangreffrath** [comment]
Okay, and port credits only appear during the demo reel?

**Comment by rfomin** [comment]
> Okay, and port credits only appear during the demo reel?

Yes, like with DOOM2.WAD

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
