### PR TITLE
remove unused "ColorXForm" wipe type

### LINKED ISSUE #1547: `wipe_ColorXForm` is broken in some resolutions
_Tested in the [latest master commit](https://github.com/fabiangreffrath/woof/commit/aa10fcc17d47099420e72fcab0004dc397b93178)._

Before anything, I'd like to say that **I consider this to be of very low priority**.

The unused "ColorXForm" wipe seems to have been broken with the recent addition of arbitrary-resolution support, in spite of the changes made to its code.

With 300% resolution at 16:9 widescreen, by the end of the wipe the screen looks like this (it returns to normal afterwards):
imagen

Knowing that it is unused, I believe it could very well just be removed altogether. However, if you insist on keeping it, I believe it should at least be working properly; I've fixed it for Nugget (https://github.com/MrAlaux/Nugget-Doom/commit/433b76e35fe937d3531ec8a30812aa02421e3e7a), so I could make a PR fixing it for Woof.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1547

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Although I agree that the ColorXForm transition is crap, at least as it is currently implemented, wouldn't it be nicer to fix the code and eventually turn it into something useful, than to remove it altogether?

**Comment by rfomin** [comment]
> Although I agree that the ColorXForm transition is crap, at least as it is currently implemented, wouldn't it be nicer to fix the code and eventually turn it into something useful, than to remove it altogether?

I don't like the other kinds of "wipe" I've seen before. So I don't know what to do with this. Alternatively, I suggest restoring the original MBF code and forget about it 😄

**Comment by fabiangreffrath** [comment]
> I don't like the other kinds of "wipe" I've seen before. So I don't know what to do with this. Alternatively, I suggest restoring the original MBF code and forget about it 😄

I like Nugget's "fade" effect, though actual cross-fading would be even cooler. I agree, though, that ColorXForm, or "seizure" as it's called in Nugget, is utter crap. :grin:

**Comment by rfomin** [comment]
> I like Nugget's "fade" effect, though actual cross-fading would be even cooler.

I like only vanilla wipe. Maybe we should experiment with a "high framerate" version.

So what to do with this PR? I don't think the fix of "ColorXForm" is worth it.

**Comment by fabiangreffrath** [comment]
How would you like this?

```patch
diff --git a/src/d_main.c b/src/d_main.c
index 11f6fbe9..ac279e59 100644
--- a/src/d_main.c
+++ b/src/d_main.c
@@ -453,7 +453,7 @@ void D_Display (void)
         }
       while (!tics);
       wipestart = nowtime;
-      done = wipe_ScreenWipe(wipe_Melt, 0, 0, video.unscaledw, SCREENHEIGHT, tics);
+      done = wipe_ScreenWipe(0, 0, 0, video.unscaledw, SCREENHEIGHT, tics);
       M_Drawer();                   // menu is drawn even on top of wipes
       I_FinishUpdate();             // page flip or blit buffer
     }
diff --git a/src/f_wipe.c b/src/f_wipe.c
index 137f8bc6..3c4c5294 100644
--- a/src/f_wipe.c
+++ b/src/f_wipe.c
@@ -23,6 +23,7 @@
 #include "f_wipe.h"
 #include "i_video.h"
 #include "m_random.h"
+#include "v_flextran.h"
 #include "v_video.h"
 #include "z_zone.h"
 
@@ -57,29 +58,40 @@ static void wipe_shittyColMajorXform(byte *array, int width, int height)
   Z_Free(dest);
 }
 
+static int color_tick;
+
 static int wipe_initColorXForm(int width, int height, int ticks)
 {
   V_PutBlock(0, 0, width, height, wipe_scr_start);
+  color_tick = 0;
   return 0;
 }
 
 // killough 3/5/98: reformatted and cleaned up
 static int wipe_doColorXForm(int width, int height, int ticks)
 {
-  boolean unchanged = true;
-  byte *w   = wipe_scr;
-  byte *e   = wipe_scr_end;
-  byte *end = wipe_scr+width*height;
-  for (;w != end; w++, e++)
-    if (*w != *e)
-      {
-        int newval;
-        unchanged = false;
-        *w = *w > *e ?
-          (newval = *w - ticks) < *e ? *e : newval :
-          (newval = *w + ticks) > *e ? *e : newval ;
-      }
-  return unchanged;
+  color_tick = BETWEEN(0, 64, color_tick + 2 * ticks);
+
+  for (int y = 0; y < height; y++)
+  {
+    byte *sta = wipe_scr_start + y * width;
+    byte *end = wipe_scr_end + y * width;
+    byte *dst = wipe_scr + y * video.pitch;
+
+    for (int x = 0; x < width; x++)
+    {
+      unsigned int *fg2rgb = Col2RGB8[color_tick];
+      unsigned int *bg2rgb = Col2RGB8[64 - color_tick];
+      unsigned int fg, bg;
+
+      fg = fg2rgb[end[x]];
+      bg = bg2rgb[sta[x]];
+      fg = (fg + bg) | 0x1f07c1f;
+      dst[x] = RGB32k[0][0][fg & (fg >> 15)];
+    }
+  }
+
+  return (color_tick == 64);
 }
 
 static int wipe_exitColorXForm(int width, int height, int ticks)
```

**Pull request closed without merging**
