### PR TITLE
show time/STS above statusbar

### LINKED ISSUE #308: (Question) Stats above HUD?
I was watching Decino's latest viewer submission WAD playthrough, and I noticed this in the corner;

image

I know that you can get something similar to this in Woof! by pressing the F5 key, but I haven't seen this specific HUD widget. Speaking of which, I can't seem to be able to get the widgets to stay alongside the full status HUD

image

Am I just dumb, or is this a prboom+um only feature? If it is, I suppose you could say this is a suggestion :^)

### PR DESCRIPTION
**Pull request by rfomin**
Fixes #308 
timests

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Hm, I think I favor printing subseconds here.

**Comment by fabiangreffrath** [comment]
> Hm, I think I favor printing subseconds here.

NB this would require a '.' glyph for the tiny font.

**Comment by kraflab** [comment]
> NB this would require a '.' glyph for the tiny font.

Feel free to copy over the font from dsda-doom: I created glyphs not only for the missing period but for all the other missing characters.

**Comment by rfomin** [comment]
> Hm, I think I favor printing subseconds here.

This requires additional updates in uncapped mode. Personally, I'm distracted by subseconds, not sure if it's worth it.

**Comment by fabiangreffrath** [comment]
Ready for merging?

**Pull request merged**
