### PR TITLE
integrate net_gui module from Chocolate Doom

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by rfomin** [comment]
Can we merge this? I want to edit `d_loop.c`, so there might be conflicts.

I think the only non-trivial change here is that I moved `SDL_Init(SDL_INIT_VIDEO)` to `I_InitGraphics()` and `SDL_QuitSubSystem(SDL_INIT_VIDEO); SDL_Quit();` to `I_Quit()`.

**Comment by fabiangreffrath** [comment]
Sure, it's next on the list.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
Wow, exciting! 😁

**Comment by rfomin** [comment]
> Wow, exciting! grin

I still haven't tested this over the internet. Maybe we should try this sometime :smile:

**Pull request merged**
