### PR TITLE
only reset visible parts of visplane rendering arrays

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
Hey @liPillON,

judging from this thread [1] on the DW forums, your system seems to be far less bottle-necked than mine and is probably better suited for some further benchmarking.

Could you please check if this change yields in another performance boost? And if it does, would you mind checking out some other potential changes for me?

1) Increasing the size of `visplane_t.pad` so that `visplane_t.top`  lies on a 4-byte (or 8-byte?) boundary. Could you please check for `pad1[2]` and `pad1[4]`?

```patch
--- a/src/r_defs.h
+++ b/src/r_defs.h
@@ -437,7 +437,7 @@ typedef struct visplane
   int picnum, lightlevel, minx, maxx;
   fixed_t height;
   fixed_t xoffs, yoffs;         // killough 2/28/98: Support scrolling flats
-  unsigned short pad1;          // leave pads for [minx-1]/[maxx+1]
+  unsigned short pad1[2];          // leave pads for [minx-1]/[maxx+1]
   unsigned short top[MAX_SCREENWIDTH];
   unsigned short pad2, pad3;    // killough 2/8/98, 4/25/98
   unsigned short bottom[MAX_SCREENWIDTH];
```

I don't expect too much from this change (if at all), because the struct is not declared as packed and thus the compiler my already arrange it as it sees fit.

2) Increase the value of `MAXVISPLANES` from `128` to, say `1024`. I don't expect anything from this change as well, because this only affects the number of valid visplane hash values. But I have seen this value increased in other ports and thus I am curious.

Thank you!

[1] https://www.doomworld.com/forum/topic/112333-this-is-woof-1120-jun-13-2023/?page=66&tab=comments#comment-2660078

**Comment by fabiangreffrath** [comment]
3) Get rid of 16-bit shift left and right:

```patch
--- a/src/r_plane.c
+++ b/src/r_plane.c
@@ -143,8 +143,8 @@ static void R_MapPlane(int y, int x1, int x2)
     {
       cachedheight[y] = planeheight;
       distance = cacheddistance[y] = FixedMul(planeheight, yslope[y]);
-      ds_xstep = cachedxstep[y] = FixedDiv(FixedMul(viewsin, planeheight), dy);
-      ds_ystep = cachedystep[y] = FixedDiv(FixedMul(viewcos, planeheight), dy);
+      ds_xstep = cachedxstep[y] = (fixed_t)(((int64_t)viewsin * planeheight) / dy);
+      ds_ystep = cachedystep[y] = (fixed_t)(((int64_t)viewcos * planeheight) / dy);
     }
   else
     {
```

**Comment by liPillON** [comment]
Sure no problem, I'm happy to help!

I can't build woof on this pc though, so I'll be able to test only by using the automatic builds. 

I believe you'll have to wait for the first round of results, then push the next batch of changes you'd need to br tested; after that, rinse & repeat.

Is it ok with you?

**Comment by liPillON** [comment]
I'm getting:
- 103 fps max with the latest artifacts from the master branch ([785](https://github.com/fabiangreffrath/woof/actions/runs/5287929619))
- 111 fps max with the current artifacts from this pr ([789](https://github.com/fabiangreffrath/woof/actions/runs/5303424190?pr=1110))

**Comment by fabiangreffrath** [comment]
> I'm getting:
> 
> * [104](https://github.com/fabiangreffrath/woof/assets/48625273/bb51d9b5-5743-4ab1-90c0-7b1ca68f763a) fps max with the latest artifacts from the master branch ([785](https://github.com/fabiangreffrath/woof/actions/runs/5287929619))
> * [111](https://github.com/fabiangreffrath/woof/assets/48625273/fc4e2afa-98e7-4f24-8149-6059cfea065c) fps max with the current artifacts from this pr ([789](https://github.com/fabiangreffrath/woof/actions/runs/5303424190?pr=1110))

Great, thanks! I'll create a PR with the most promising changes next.

**Pull request merged**
