### PR TITLE
free video resources on shut down

### LINKED ISSUE #353: i_video.c: memory leak when quit game
hi,

I see a little bug, not sur if affect Windows...

in function "I_ShutdownGraphics", you dont free SDL resources.

I test that on this function : 

>  if (argbbuffer != NULL)
>    {
>       SDL_FreeSurface(argbbuffer);
>       argbbuffer = NULL;
>    }
>    if (sdlscreen != NULL)
>    {
>       SDL_FreeSurface(sdlscreen);
>       sdlscreen = NULL;
>    }
>    if (texture != NULL)
>    {
>       SDL_DestroyTexture(texture);
> 	  texture = NULL;
>    }
>    if (renderer != NULL)
>    {
>       SDL_DestroyRenderer(renderer);
>       renderer = NULL;
>    }
>    if (screen != NULL)
>    {
> SDL_DestroyWindow(screen);
>       screen = NULL;
>    }

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #353

### CODE REVIEW

**Comment by rfomin** [comment]
Maybe calling SDL_QuitSubSystem is enough (like in Choco/Crispy)? https://wiki.libsdl.org/SDL_QuitSubSystem

**Comment by fabiangreffrath** [comment]
You mean `SDL_QuitSubSystem(SDL_INIT_VIDEO)`?

**Comment by rfomin** [comment]
Yes. I read the SDL_video.c code a bit and it looks like it frees up some resources.

**Comment by fabiangreffrath** [comment]
So, do you mean calling `SDL_QuitSubSystem()` instead of the whole sequence or just to replace `SDL_Quit()`?

**Comment by rfomin** [comment]
In any case, we need to call `SDL_Quit`. To be honest, I don’t know, maybe `SDL_Quit` calls `SDL_QuitSubSystem` too.

**Comment by fabiangreffrath** [comment]
According to this we need to call both `SDL_QuitSubSystem()` and `SDL_Quit()`:

https://wiki.libsdl.org/SDL_QuitSubSystem

**Comment by fabiangreffrath** [comment]
> According to this we need to call both `SDL_QuitSubSystem()` and `SDL_Quit()`:

No, wait, it merely states that it is not enough to call `SDL_QuitSubSystem()` alone.

**Comment by rfomin** [comment]
Not sure and `SDL_Quit.c` doesn't help. I think we should copy Chocolate Doom :smile:

**Comment by fabiangreffrath** [comment]
Current Chocolate Doom has a slightly different shutdown sequence anyway, because it renders ENDOOM in a separate window and does not allow for switching in-game resolutions.

**Comment by fabiangreffrath** [comment]
Hm, how about the renderer pointer that we pass over to `TXT_PreInit()` from the main process? I think we need to set it to `NULL` after destroying it in libtextscreen.

**Comment by BeWorld2018** [comment]
> 

you can put "renderer = NULL"
in https://github.com/fabiangreffrath/woof/blob/master/textscreen/txt_sdl.c#L273
but it's not necessary.. just more beautifull ;-)

**Comment by fabiangreffrath** [comment]
> but it's not necessary.. just more beautifull ;-)

That won't reset it in i_video.c

**Comment by fabiangreffrath** [comment]
I guess I will have to reset both renderer and texture to NULL after calling TXT_Init(), but I'll have to investigate further.

**Comment by BeWorld2018** [comment]
> > but it's not necessary.. just more beautifull ;-)
> 
> That won't reset it in i_video.c

? yes reset it in I_QuitVideo ? i dont undersstand...

**Comment by fabiangreffrath** [comment]
SDL seems to have build-in sanity checking for the destructor functions. For example, the following code exits with success:
```C
#include <SDL.h>

int main (void)
{
	SDL_Renderer *i;

	if(SDL_Init(SDL_INIT_VIDEO) < 0)
		return 1;

	i = NULL;
	SDL_DestroyRenderer(i);

	i = malloc(1<<20);
	memset(i, 0, 1<<20);
	SDL_DestroyRenderer(i);

	memset(i, 0xff, 1<<20);
	SDL_DestroyRenderer(i);

	return 0;
}
```

**Comment by fabiangreffrath** [comment]
Not sure what to do about this one. I won't hurt to merge it, but won't bring much benefit either.

**Comment by rfomin** [comment]
I don't think we need it. Also if we use libtextscreen for the netgame UI we will probably change the shutdown code again.

**Comment by fabiangreffrath** [comment]
> I think we don't need it. Also if we use libtextscreen for the netgame UI we will probably change the shutdown code again.

So, now is the right time to get this sorted out?

**Comment by rfomin** [comment]
> So, now is the right time to get this sorted out?

I guess so.

**Pull request closed without merging**
