### PR TITLE
Add HI_START/HI_END namespace

### PR DESCRIPTION
**Pull request by rfomin**
For load PWADs like Hell Ground https://doomwiki.org/wiki/Hell_Ground

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
What exactly is this supposed to achieve? HI_START marks the beginning of a block of graphic lumps in PNG format, right?

**Comment by rfomin** [comment]
Yes, without it there are a bunch of textures with the same names.

**Comment by fabiangreffrath** [comment]
So, this helps sorting out duplicate textures into a separate name space. Could you please add a more elaborate comment than "e6y"?

**Comment by fabiangreffrath** [comment]
Thank you!

**Pull request merged**
