### PR TITLE
remove download SDL2 libraries for MinGW

### PR DESCRIPTION
**Pull request by rfomin**
I don't mind keeping it.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Wouldn't that kill cross building?

**Comment by rfomin** [comment]
> Wouldn't that kill cross building?

Why? I thought we want to use MinGW libraries when cross-compiling.

**Comment by fabiangreffrath** [comment]
When cross compiling on Linux you build an EXE and have to link it to DLLs. Linux distros ship the capable compiler (mingw = GCC for Windows, but nothing more), but no DLLs for common libraries - you'll have to provide them on your own. MSYS2, in turn, is a mingw distribution for Windows which provides packages for common libraries - and here I prefer to use theirs.

**Comment by rfomin** [comment]
Oh, I thought MSYS2 packages are accessible from Linux. Ok then :smile:

**Pull request closed without merging**
