### PR TITLE
reduce verbosity

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by rfomin** [comment]
@fabiangreffrath Why we print this to `stderr`?
https://github.com/fabiangreffrath/woof/blob/b8b37b78178b359d327dfd98f665c6d6c38ec660/src/p_setup.c#L1645
It doesn't matter in Windows, I'm just curious.

**Comment by fabiangreffrath** [comment]
> @fabiangreffrath Why we print this to `stderr`?

Feel free to change this if you like.

**Comment by rfomin** [comment]
> > @fabiangreffrath Why we print this to `stderr`?
> 
> Feel free to change this if you like.

I like logging, but maybe we don't need that many parameters. I suggest removing time and demo_version for `P_SetupLevel` logging.

**Comment by fabiangreffrath** [comment]
> I like logging, but maybe we don't need that many parameters. I suggest removing time and demo_version for `P_SetupLevel` logging.

Fine with me. I was like "a lot helps a lot" back then. 😉

**Comment by fabiangreffrath** [comment]
Would you like to change that logging line or should I merge this?

**Comment by rfomin** [comment]
Alternatively, we can only log `if (devparm)`.

**Comment by fabiangreffrath** [comment]
Nope, I like a little verbosity. 😉 How about stderr vs. stdout?

**Comment by rfomin** [comment]
> Nope, I like a little verbosity. 😉 How about stderr vs. stdout?

Okay.

**Comment by rfomin** [comment]
@fabiangreffrath Can we merge this? Or should I restore some verbosity?

**Comment by fabiangreffrath** [comment]
> @fabiangreffrath Can we merge this? Or should I restore some verbosity?

No no, it's alright. I just didn't have the time to merge it.

**Pull request merged**
