### PR TITLE
don't parse lumpname as identifier, use indexes instead of pointers

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
This seems to fix parsing of the lump name. However, there was a second issue reported when a brightmap for a texture that was formerly defined in our autoload brghtmps lump was redefined in a PWAD. I have tried but could reproduce it. Do you know what happened there?

Also, while at it, could you remove the redundant `'.'` from the string passed to the `I_Error()` call - or from all the strings passed over to `U_Error()`?

**Comment by fabiangreffrath** [comment]
BTW, how about this? :grin: 

```patch
--- a/src/i_system.c
+++ b/src/i_system.c
@@ -96,7 +96,7 @@ void I_ErrorMsg()
         SDL_ShowSimpleMessageBox(exit_code == 0 ?
                                  SDL_MESSAGEBOX_INFORMATION :
                                  SDL_MESSAGEBOX_ERROR,
-                                 PROJECT_STRING, errmsg, NULL);
+                                 PROJECT_STRING ": Error message (this is not a \"crash\")", errmsg, NULL);
     }
 }
 
```

**Comment by rfomin** [comment]
> I have tried but could reproduce it. Do you know what happened there?

I think there was another error message, that brightmap was not found. So the game didn't load = crash.

**Comment by rfomin** [comment]
> Also, while at it, could you remove the redundant `'.'` from the string passed to the `I_Error()` call - or from all the strings passed over to `U_Error()`?

Sure. I think we should clean up our parser. I will do it during clang re-formatting.

**Comment by rfomin** [comment]
> So, they tried to assign a brightmap that wasn't defined before? How is this an unexpected error?

I don't know, I couldn't replicate the problem either. Not sure what was wrong.

**Comment by fabiangreffrath** [comment]
> This is crap but fixes the crash:

Though, we should probably keep the part that overwrites existing brightmap entries instead of appending new ones with the old names.

**Comment by fabiangreffrath** [comment]
> Also, while at it, could you remove the redundant `'.'` from the string passed to the `I_Error()` call - or from all the strings passed over to `U_Error()`?

How about this?

> Though, we should probably keep the part that overwrites existing brightmap entries instead of appending new ones with the old names.

And this?

**Comment by rfomin** [comment]
> > Though, we should probably keep the part that overwrites existing brightmap entries instead of appending new ones with the old names.
> 
> And this?

We iterate the array from the end, so any newer records will "overwrite" the old ones. We could search and replace, but I think that's an unnecessary complication.

> > Also, while at it, could you remove the redundant `'.'` from the string passed to the `I_Error()` call - or from all the strings passed over to `U_Error()`?
> 
> How about this?

Done in https://github.com/fabiangreffrath/woof/pull/1311/commits/5efb69fa23032593898b8eaa31137c2ebf267853

**Review by fabiangreffrath — APPROVED** [review]
Alright, thank you!

**Pull request merged**
