### PR TITLE
complete crosshair implementation

### LINKED ISSUE #409: [feature request] crosshair
This is another regular feature request. If we don't implement the projected crosshair from Crispy (we won't), this could be a rather straightforward porting over. It's still up for decision which patch to use for the actual rendering or if we should offer a selection of patches at all. In Boom/MBF we have another (smaller) HUD font to choose from. 

This pulls in quite a handful of additional config keys and will require additional care not to trigger INTERCEPT overflow in Vanilla complevel. 

This requires translucent and color translated patch drawing functions as a prerequisite.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #409, fixes #410.

### CODE REVIEW

**Review by rfomin — COMMENTED** [review]
Implementation is good, but CROSS1 looks uneven for some reason:
ch

**Comment by fabiangreffrath** [comment]
May be due to horizontal scaling with "nearest" interpolation. Could you try again with `-1` or `-2` or whatever fits your screen best?

**Comment by rfomin** [comment]
I suggest to use this patch:
ch2
```c
static unsigned char cross1[] = {
  0x09, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00,
  0x32, 0x00, 0x00, 0x00, 0x38, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x00,
  0x3f, 0x00, 0x00, 0x00, 0x4e, 0x00, 0x00, 0x00, 0x4f, 0x00, 0x00, 0x00,
  0x55, 0x00, 0x00, 0x00, 0x5b, 0x00, 0x00, 0x00, 0x04, 0x01, 0x57, 0x57,
  0x57, 0xff, 0x04, 0x01, 0x57, 0x57, 0x57, 0xff, 0x04, 0x01, 0x57, 0x57,
  0x57, 0xff, 0xff, 0x00, 0x03, 0x57, 0x57, 0x57, 0x57, 0x57, 0x06, 0x03,
  0x57, 0x57, 0x57, 0x57, 0x57, 0xff, 0xff, 0x04, 0x01, 0x57, 0x57, 0x57,
  0xff, 0x04, 0x01, 0x57, 0x57, 0x57, 0xff, 0x04, 0x01, 0x57, 0x57, 0x57,
  0xff
};
```

**Comment by rfomin** [comment]
Fixed color:
```c
static unsigned char cross1[] = {
  0x09, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x2c, 0x00, 0x00, 0x00,
  0x32, 0x00, 0x00, 0x00, 0x38, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x00,
  0x3f, 0x00, 0x00, 0x00, 0x4e, 0x00, 0x00, 0x00, 0x4f, 0x00, 0x00, 0x00,
  0x55, 0x00, 0x00, 0x00, 0x5b, 0x00, 0x00, 0x00, 0x04, 0x01, 0xb8, 0xb8,
  0xb8, 0xff, 0x04, 0x01, 0xb8, 0xb8, 0xb8, 0xff, 0x04, 0x01, 0xb8, 0xb8,
  0xb8, 0xff, 0xff, 0x00, 0x03, 0xb8, 0xb8, 0xb8, 0xb8, 0xb8, 0x06, 0x03,
  0xb8, 0xb8, 0xb8, 0xb8, 0xb8, 0xff, 0xff, 0x04, 0x01, 0xb8, 0xb8, 0xb8,
  0xff, 0x04, 0x01, 0xb8, 0xb8, 0xb8, 0xff, 0x04, 0x01, 0xb8, 0xb8, 0xb8,
  0xff
};
```

**Comment by fabiangreffrath** [comment]
Thanks! I'll add this as a fourth "big" option.

**Comment by fabiangreffrath** [comment]
Checked CROSS1 with double scaling (`-2`), looks all fine.

grafik

**Review by rfomin — APPROVED** [review]
I'm guessing it depends on the scaling implementation, maybe it's different between Windows Direct3D and Linux OpenGL.

**Pull request merged**
