### PR TITLE
lightning calculation from PrBoom+

### LINKED ISSUE #1468: Lighting is affected by FOV
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7868482791)._

At least up until the last Woof release -- not to say in vanilla -- wall/sprite lighting was partially determined by the scale of the texture.

I'm not sure if the latest Woof master still does that to calculate lighting, but if it does, you can guess that changing FOV affects the scale and therefore lighting of stuff being drawn. This could very well be something you want to keep, but if the FOV range were broader, it would be a bit questionable to be able to see in dark far places by decreasing FOV, or otherwise having reduced visibility when increasing it.

In any case, [this](https://github.com/MrAlaux/Nugget-Doom/commit/99fc0d4fa65fe846211b9f1d3018d3443e1ca3c3) is the solution I employed in Nugget, where `fovdiff = [current FOV] / [original FOV]`.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1468 

I wonder where the `160` came from?

### CODE REVIEW

**Comment by ceski-1** [comment]
> I wonder where the `160` came from?

The math appears to be a ratio between the original 4:3 projection distance (160) vs. the current projection distance. Can you hold off on merging this until we understand *why* this is the fix? I'd like to work out the math like I did before.

**Comment by rfomin** [comment]
> Can you hold off on merging this until we understand _why_ this is the fix? I'd like to work out the math like I did before.

That would be great!

Eternity solution: https://github.com/team-eternity/eternity/blob/8630fdd23908f535baf4fed8d107753de4924940/source/r_segs.cpp#L244

**Comment by ceski-1** [comment]
Some kind of lighting fix needs to be applied in at least 4 places (there may be more):

https://github.com/fabiangreffrath/woof/blob/37bed431e993b0a1c1d37cc683a8601cc48cdbb7/src/r_segs.c#L160

https://github.com/fabiangreffrath/woof/blob/37bed431e993b0a1c1d37cc683a8601cc48cdbb7/src/r_segs.c#L381

https://github.com/fabiangreffrath/woof/blob/37bed431e993b0a1c1d37cc683a8601cc48cdbb7/src/r_things.c#L667

https://github.com/fabiangreffrath/woof/blob/37bed431e993b0a1c1d37cc683a8601cc48cdbb7/src/r_voxel.c#L727

Here's a test wad for the above 4 examples (masked, standard, sprites, voxels):
[fovlight.zip](https://github.com/fabiangreffrath/woof/files/14272094/fovlight.zip)

The current lighting fix looks one way on walls at FOV 90 and slightly different at any other FOV. I haven't worked out the math yet.

**Comment by rfomin** [comment]
> Some kind of lighting fix needs to be applied in at least 4 places (there may be more):

Yes, I forgot, thank you.

> The current lighting fix looks one way on walls at FOV 90 and slightly different at any other FOV. I haven't worked out the math yet.

The difference is quite subtle, it looks like this fix is good enough.

**Comment by ceski-1** [comment]
> The difference is quite subtle, it looks like this fix is good enough.

I have a solution, I'm just simplifying it at the moment.

**Comment by ceski-1** [comment]
Apply this patch: [fovlight.patch](https://github.com/fabiangreffrath/woof/files/14274771/fovlight.patch)

Without getting into details, we have to do the same inaccurate math as the original game to make things look the same.

**Comment by rfomin** [comment]
> Without getting into details, we have to do the same inaccurate math as the original game to make things look the same.

Looks good, thanks!

**Review by ceski-1 — APPROVED** [review]

**Pull request merged**
