### PR TITLE
Enable Fluidsynth support on Windows

### PR DESCRIPTION
**Pull request by rfomin**
Enable Fluidsynth support if soudfont path is set in config.
Works if user grab fluidsynth release from https://github.com/FluidSynth/fluidsynth/releases
Current MSVC build doesn't work (due to SDL_mixer.dll from libsdl.org).

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Does this mean the port will crash when using this feature due to us shipping an unpatched SDL2_Mixer.dll?

**Comment by rfomin** [comment]
From my testing SDL_mixer from libsdl.org doesn't load fluidsynth-3.dll, so it fallback to native SDL_mixer Windows MIDI (with broken volume).

**Comment by fabiangreffrath** [comment]
Hm, yes. SDL_Mixer decides at build-time which library name to look for opening at run-time. So, if fluidsynth-3.dll wasn't available when libsdl.org created their official builds, it won't ever get loaded at run-time.

**Comment by fabiangreffrath** [comment]
Actually, the upstream SDL2_Mixer.dll that we ship our game with isn't even built with fluidsynth support at all:
```
$ strings ./build/Source/SDL2_mixer.dll | grep -i '\.dll'
libFLAC-8.dll
libmodplug-1.dll
libmpg123-0.dll
libvorbisfile-3.dll
libopusfile-0.dll
SDL2_mixer.dll
KERNEL32.dll
msvcrt.dll
SDL2.dll
WINMM.DLL
```

**Comment by rfomin** [comment]
It works with the current MSYS2 build. Well, I guess this feature is not worth it. We can wait for SDL2_mixer 2.0.5 (a few years :smiley: )

**Comment by fabiangreffrath** [comment]
I guess we will have to, because even if we get SDL2-Mixer to runtime-load fluidsynth.dll it will instantly crash when changing the music tracks because of the infamous free-in-wrong-order bug.

**Comment by rfomin** [comment]
I made a 32-bit dll pack with SDL2_mixer.dll from [migw32 package](https://packages.msys2.org/package/mingw-w64-i686-SDL2_mixer?repo=mingw32) and libfluidsynth from official GitHub release: [fluidsynth-pack.zip](https://github.com/fabiangreffrath/woof/files/7583966/fluidsynth-pack.zip)
Tested it with 32-bit MSVC build, it works.

**Comment by fabiangreffrath** [comment]
How about this one? We could merge it but not advertise it yet, because SDL2_Mixer is not ready yet?

**Comment by rfomin** [comment]
Can we get SDL2_mixer.dll from MinGW somehow? I think we'll have to wait literally years before libsdl.org updates SDL Mixer.

**Comment by fabiangreffrath** [comment]
We'd have to change the CMake magic to try to locate local copies of the libraries first before downloading them from libsdl.org. But my cmake-foo isn't that advanced yet, currently.

**Comment by rfomin** [comment]
I think we can take `FindSDL2.cmake` from PrBoom+ and abandon the idea of downloading packages from libsdl.org. Or I can just post fluidsynth-pack.zip on the DW thread (maybe make a wiki page for it like Crispy).

**Comment by fabiangreffrath** [comment]
While we might want the build script to install MSYS2's SDL2_Mixer library if it is found, we certainly don't want it to do the same for MSYS2's SDL2_Image library, because the latter is still linked with half a dozen unnecessary graphics format libraries - which in turn pull in compressions libraries and much more. Apparently, the patch I submitted to MSYS2 to avoid this does not survive a relibtoolization. 😞

**Comment by rfomin** [comment]
Do we need SDL_image and zlib only for screenshots? How about https://github.com/nothings/stb/blob/master/stb_image.h ? No dependencies, public domain, etc. GZDoom uses it.

**Comment by fabiangreffrath** [comment]
SDL_Image is only used for screenshots currently (and IIRC we dropped the idea of supporting patches in PNG format). ZLib is needed because libpng needs it and for compressed ZDBSP nodes support.

**Comment by fabiangreffrath** [comment]
For zlib there us miniz, AFAIK.

**Comment by rfomin** [comment]
So we need only https://github.com/nothings/stb/blob/master/stb_image_write.h

**Comment by fabiangreffrath** [comment]
Does this include a deflate implementation?

**Comment by rfomin** [comment]
> Does this include a deflate implementation?

Yes, but it can use zlib too.

**Pull request merged**
