### PR TITLE
fix MIDI player timer

### LINKED ISSUE #1655: MIDIs playback slower then they're supposed to
Tested with Commit [8778365](https://github.com/fabiangreffrath/woof/commit/877836530867a100f91834c05c362b48b7dc7c30)

Certain midis are playing back slower than they're normally supposed to. Most notable example is some of the tracks in No Rest for the Living Community Midi Pack like the track for MAP01.

### PR DESCRIPTION
**Pull request by rfomin**
Might fix #1655

### CODE REVIEW

**Comment by rfomin** [comment]
@Terraformer9x Can you please check this PR?

**Comment by fabiangreffrath** [comment]
😌 Thank you!

**Comment by Terraformer9x** [comment]
Ack, the change did fix midis playing slower than they should but now some midis play faster than they're supposed to. Using No Rest for the Living Community Midi Pack again as example, MAP09's music plays back at a way faster tempo.

**Comment by rfomin** [comment]
> Using No Rest for the Living Community Midi Pack again as example, MAP09's music plays back at a way faster tempo.

Right, hopefully it is fixed now.

**Comment by Terraformer9x** [comment]
All midis in the NRftL pack are playing back at their correct speeds now.

**Comment by ceski-1** [comment]
These changes breaks loops unfortunately: [fanfare.zip](https://github.com/fabiangreffrath/woof/files/15070242/fanfare.zip)

**Comment by ceski-1** [comment]
It's Final Fantasy and RPG Maker loops that are broken (please mind your ears): [loop_set.zip](https://github.com/fabiangreffrath/woof/files/15070283/loop_set.zip)

**Comment by rfomin** [comment]
> It's Final Fantasy and RPG Maker loops that are broken (please mind your ears): [loop_set.zip](https://github.com/fabiangreffrath/woof/files/15070283/loop_set.zip)

This seems to be fixed here: https://github.com/fabiangreffrath/woof/pull/1656/commits/35fccb4ee37485447b9a06c81aec5bebb7267b9b

**Comment by rfomin** [comment]
@ceski-1 Should we merge this? There are likely to be conflicts with #1657

**Comment by ceski-1** [comment]
> @ceski-1 Should we merge this? There are likely to be conflicts with #1657

I don't mind if this is merged first. I'll deal with the merging conflicts.

**Pull request merged**
