### PR TITLE
docs update

### PR DESCRIPTION
**Pull request by rfomin**
* convert mbf-bugs.html to Markdown
* remove mbf21.md (it's incomplete)
* replace umapinfo.txt with umapinfo.md

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Is there some more complete mbf21 documentation available anywhere?

**Comment by rfomin** [comment]
> Is there some more complete mbf21 documentation available anywhere?

It has its own repository: https://github.com/kraflab/mbf21

**Comment by fabiangreffrath** [comment]
We could replace mbf21.md with docs/spec.md from this repo?

**Comment by rfomin** [comment]
I don't know, I think it's better organized in that repository.

**Pull request merged**
