### PR TITLE
support up to 8 pages of savegames

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
Without saves in the directory, the game crashes if you press right in an empty list.

**Comment by fabiangreffrath** [comment]
Hm, not for me. Do you have a backtrace?

**Comment by kraflab** [comment]
Does woof store save / load slots in demos the way prboom+ does? Just wondering if this would have any issue there

**Comment by rfomin** [comment]
I fixed crash with this:
```diff
--- a/Source/m_menu.c
+++ b/Source/m_menu.c
@@ -991,6 +991,8 @@ void M_ReadSaveStrings(void)
          }
        }
       // [FG] check return value
+      if (fp)
+      {
       if (!fread(&savegamestrings[i], SAVESTRINGSIZE, 1, fp))
        {
          strcpy(&savegamestrings[i][0],s_EMPTYSTRING);
@@ -998,6 +1000,7 @@ void M_ReadSaveStrings(void)
          continue;
        }
       fclose(fp);
+      }
       LoadMenu[i].status = 1;
     }
 }
```

**Comment by rfomin** [comment]
> Does woof store save / load slots in demos the way prboom+ does? Just wondering if this would have any issue there

No, I don't think so. Need to recheck.

**Comment by fabiangreffrath** [comment]
> I fixed crash with this:

Thanks, but this won't reset the savegamestring to the emptystring. I'll fix it by simply allowing MBF savenames > 8.

**Comment by rfomin** [comment]
Yes, my previous patch was wrong. This fix is working for me:
```diff
--- a/Source/m_menu.c
+++ b/Source/m_menu.c
@@ -978,7 +978,7 @@ void M_ReadSaveStrings(void)
       fp = fopen(name,"rb");
       if (name) (free)(name);

-      if (!fp && !savepage)
+      if (!fp)
        {   // Ty 03/27/98 - externalized:
          name = G_MBFSaveGameName(i);
          fp = fopen(name,"rb");
```

**Comment by rfomin** [comment]
The last commit still crashes for me. I run the game without saves in the directory, press F3 on the title screen, and press right.

**Review by rfomin — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
> Does woof store save / load slots in demos the way prboom+ does? Just wondering if this would have any issue there

I guess we are safe:
https://github.com/fabiangreffrath/woof/blob/dcb80f640b1c56b081f9fb7288adc5168ca25621/Source/g_game.c#L500-L505

**Comment by fabiangreffrath** [comment]
This is the right code snippet to show we are safe. 😉 

https://github.com/fabiangreffrath/woof/blob/dcb80f640b1c56b081f9fb7288adc5168ca25621/Source/g_game.c#L839-L846

**Comment by fabiangreffrath** [comment]
I should probably reset the quicksave slot when the page changes.

**Comment by rfomin** [comment]
I never use Doom's quicksave because it's not quick. Can we remove all dialogs and quicksave slot selection? Basically how it works in Half-Life and all subsequent games.

**Comment by fabiangreffrath** [comment]
> I never use Doom's quicksave because it's not quick. Can we remove all dialogs and quicksave slot selection? Basically how it works in Half-Life and all subsequent games.

Not in the scope of this PR. 😉 I don't remember how Half-Life worked, but I guess you mean that there is a fixed quicksave slot that gets used without asking.

**Comment by rfomin** [comment]
> I guess you mean that there is a fixed quicksave slot that gets used without asking.

Yes exactly.

**Comment by fabiangreffrath** [comment]
Is this quicksave slot still accessible from the regular load/save menus? Ot is it just the last one used for loading/saving?

**Comment by rfomin** [comment]
I think it shouldn't be on the menu. Just a separate `woofquick.dsg` file that is overwritten without question.

**Comment by kraflab** [comment]
Quicksave in dsda-doom works exactly as rfomin described as well.

**Comment by fabiangreffrath** [comment]
Ecxellent!

**Comment by kraflab** [comment]
https://github.com/kraflab/dsda-doom/commit/6f4236141a6eb56ca79bade7c0937daaf232b592 fyi

**Comment by fabiangreffrath** [comment]
> [kraflab/dsda-doom@6f42361](https://github.com/kraflab/dsda-doom/commit/6f4236141a6eb56ca79bade7c0937daaf232b592) fyi

Thanks, but this is a bit too radical for my taste. 😉

**Comment by fabiangreffrath** [comment]
I guess for Woof it'd be sufficient to set `quicksaveslot = 999` and comment out the functions asking for confirmation.

**Comment by rfomin** [comment]
> I guess for Woof it'd be sufficient to set `quicksaveslot = 999` and comment out the functions asking for confirmation.

But then the filename would be `woofsav999.dsg`? It's confusing. Please call it `woofquick` or something like that.

**Pull request merged**
