### PR TITLE
Separate `fake_longtics` and `raw_input`

### PR DESCRIPTION
**Pull request by ceski-1**
Fixes https://github.com/fabiangreffrath/woof/issues/1707

### CODE REVIEW

**Comment by ceski-1** [comment]
This is ready for merging if there are no objections. These settings are now fully independent.

**Review by rfomin — APPROVED** [review]
Looks good.

**Comment by gendlin** [comment]
This appears to have increased input latency compared to a previous version of the code. (testing with shorttics + raw_input + fake_longtics)

**Comment by ceski-1** [comment]
> This appears to have increased input latency compared to a previous version of the code. (testing with shorttics + raw_input + fake_longtics)

Nothing changed with those combination of settings. The only thing this PR does is add support for `fake_longtics` when `raw_input` is `0`.

**Comment by gendlin** [comment]
Yes, it must have been a previous change. I'm testing against the initial check-in of fake_longtics (62ddc5c) and it definitely feels snappier recording a shorttics demo than current master.

**Comment by ceski-1** [comment]
> Yes, it must have been a previous change. I'm testing against the initial check-in of fake_longtics ([62ddc5c](https://github.com/fabiangreffrath/woof/commit/62ddc5c1b84f90db454e69edd385fc790da35846)) and it definitely feels snappier recording a shorttics demo than current master.

If you don't mind checking, see if the issue is present in previous artifacts in the master branch. For example:

https://github.com/fabiangreffrath/woof/actions/runs/9235875272

and

https://github.com/fabiangreffrath/woof/actions/runs/9234324884

could possibly narrow it down.

**Comment by gendlin** [comment]
045b3a2 appears to be the culprit.

**Comment by ceski-1** [comment]
> [045b3a2](https://github.com/fabiangreffrath/woof/commit/045b3a2797a14f3112b93d792a34c2721990dfd8) appears to be the culprit.

Sorry, it's not clear what you compared. Did you try both builds that I linked above?

**Comment by ceski-1** [comment]
So far I can't reproduce this. Both commits seem fine. Looking at the code changes, it's just simple refactoring and nothing that would cause latency issues. I'm not sure what's causing your issue.

**Comment by gendlin** [comment]
Ok interesting. For me it's a pretty stark difference at 300 fps limit on a 155 hz monitor. Also set up to be maximally latency sensitive here with nvidia low latency = on, exclusive fullscreen, widescreen mode. Command line is `doom -iwad doom -complevel vanilla -record 1`

**Comment by ceski-1** [comment]
Please share your woof.cfg and I'll take another look when I'm free again.

**Comment by gendlin** [comment]
Something else that may help to mention is I am using the `SDL_RENDER_DRIVER=direct3d11` environment variable, which reduces latency by 3-4ms on my Win10 system compared to direct3d9. I can still reproduce this issue when using the default driver but it may be less noticeable.

[woof.cfg](https://github.com/fabiangreffrath/woof/files/15458759/woof.zip)

**Comment by gendlin** [comment]
Another odd thing I've noticed: setting `joy_enable=0` also induces the feeling of increased latency, even in builds without 045b3a2. I'm using the mouse, so that seems weird.

Maybe I'm just going insane🙂.

**Comment by ceski-1** [comment]
> I am using the `SDL_RENDER_DRIVER=direct3d11` environment variable

We don't support direct3d11 since we had issues with it during testing. If you want to continue using it, be aware that when you override the default render driver, SDL disables something called "batching" as well. You may have better results trying something like this in a batch file:

```bat
@echo off
set SDL_RENDER_DRIVER=direct3d11
set SDL_HINT_RENDER_BATCHING=1
woof.com -iwad doom -complevel vanilla -record 1
```

Or this:

```bat
@echo off
:: will default to direct3d9
set SDL_HINT_RENDER_BATCHING=0
woof.com -iwad doom -complevel vanilla -record 1
```

I would try one of the above with https://github.com/fabiangreffrath/woof/commit/045b3a2797a14f3112b93d792a34c2721990dfd8 again.

**Comment by fabiangreffrath** [comment]
> Another odd thing I've noticed: setting `joy_enable=0` also induces the feeling of increased latency, 

That's indeed weird. Joystick polling is known to be a performance hog.

**Comment by gendlin** [comment]
> I would try one of the above with [045b3a2](https://github.com/fabiangreffrath/woof/commit/045b3a2797a14f3112b93d792a34c2721990dfd8) again.

The render driver setting doesn't really affect the latency issue, I just thought I'd mention it in case it might help you repro. Turning off render batching in d3d9 mode does reduce perceived latency for me, but d3d11 still feels a little better on my machine (and gets better FPS).

**Comment by ceski-1** [comment]
> > Another odd thing I've noticed: setting `joy_enable=0` also induces the feeling of increased latency,
> 
> That's indeed weird. Joystick polling is known to be a performance hog.

Right, that's odd and makes no sense considering how `joy_enable` and `I_UseController()` are used.

**Pull request merged**
