### PR TITLE
brightmaps implementation from Crispy Doom

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Fixes #404

**Comment by rfomin** [comment]
Can this feature be made compatible with GZDoom? It stores brightmaps in 32-bit monochrome PNG files, for example (FCANA0.png from brightmaps.pk3):
FCANA0

**Comment by fabiangreffrath** [comment]
It can, in theory, yes. But in practice, I wouldn't even know where to start... 😱

**Comment by rfomin** [comment]
> It can, in theory, yes. But in practice, I wouldn't even know where to start... 

We could add PNG support. I don't know how the brightmap works yet, but PNG is useful.

**Comment by NightFright2k19** [comment]
Can the brightmaps be converted to Doom gfx lumps? I could imagine a way how to get brightmaps for both versions (original and fixed) into one wad. All spritefix brightmaps would have to follow a certain renaming scheme Woof needs to recognize, then it might be possible to even have an ingame toggle like "original/fixed/off". However, it's difficult to realize with the 8 char limit you have in wads.

**Comment by fabiangreffrath** [comment]
Do we need separate settings for textures and sprites as in Crispy? I don't remember anymore why I separated these, but actually I only ever enable all or nothing.

**Comment by fabiangreffrath** [comment]
@rfomin Do we still have some place for this in the General menu or should we rather introduce page 3?

**Comment by rfomin** [comment]
> @rfomin Do we still have some place for this in the General menu or should we rather introduce page 3?

We can remove some option (game speed, default skill level, invert mouse...) or it will be another reorganization :smile:

**Comment by fabiangreffrath** [comment]
> Edit: Maybe we should move "default complevel" to "Doom Compatibility"

Yes, okay. And also, could we move the gamma thermo beneath the translucency settings? Somehow I don't like that paragraph starting with a thermo after the gap.

**Comment by fabiangreffrath** [comment]
Apart from this, are we going to go this way until we can show up a 32-bit monochrome PNG implementation as in GZDoom?

**Comment by rfomin** [comment]
> Yes, okay. And also, could we move the gamma thermo beneath the translucency settings? Somehow I don't like that paragraph starting with a thermo after the gap.

Oh sure. I don't have a strong opinion about menu layout.

**Comment by fabiangreffrath** [comment]
> Edit: Maybe we should move "default complevel" to "Doom Compatibility"

Hm. that'd be on top of page 2? Else we would disrupt the complete layout of page 1...

**Comment by fabiangreffrath** [comment]
Yes, okay. Let me just merge this PR and then we can spend some time on menu rearrangement. 😁

**Pull request merged**
