### PR TITLE
unify gamma correction concepts

### LINKED ISSUE #847: unify gamma tables
Currently, we provide two ways to apply gamma correction:

1) Using the original gamma tables, which only lighten up the scene.
2) Using a formula to provide darker gamma levels and intermediate ones for the lighter levels.

As it is now, you can apply gamma using only one of both methods. We keep the first one, because some members of the speed-running cmmunity got so much used to the original values that they depend on them being applied to the scene for pixel-perfect positioning for jumps and glides.

The idea is to keep the original gamma tables (1) for lighting up the scene, calculate 4 intermediate levels from them and use the formula (2) to calculate the darker gamma levels.

Concept patch:

```patch
--- a/src/i_video.c
+++ b/src/i_video.c
@@ -1074,13 +1074,24 @@ static byte gamma2table[18][256];

 static void I_InitGamma2Table(void)
 {
-  int i, j;
+  int i, j, k;

-  for (i = 0; i < 18; ++i)
+  for (i = 0; i < 9; ++i)
     for (j = 0; j < 256; ++j)
     {
       gamma2table[i][j] = (byte)(pow(j / 255.0, 1.0 / gammalevels[i]) * 255.0 + 0.5);
     }
+
+  // [crispy] 5 original gamma levels
+  for (i = 9, k = 0; i < 18 && k < 5; i += 2, k++)
+    memcpy(gamma2table[i], gammatable[k], 256);
+
+  // [crispy] 4 intermediate gamma levels
+  for (i = 10, k = 0; i < 18 && k < 4; i += 2, k++)
+    for (j = 0; j < 256; ++j)
+    {
+      gamma2table[i][j] = (gammatable[k][j] + gammatable[k + 1][j]) / 2;
+    }
 }

 int gamma2;
```

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #847

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Remaining question is how to call gamma levels in the menu now? Formerly, `0` meant "no gamma correction", now that would be `1.0`. Full lighting up was meant to be `4`, now it's `2.0`.

**Comment by fabiangreffrath** [comment]
Should we go from `-4` to `4` in `0.5` steps?

**Comment by rfomin** [comment]
> Should we go from `-4` to `4` in `0.5` steps?

Yes, I agree.

**Comment by fabiangreffrath** [comment]
Well, for nine darker values we need the following assignment?

0,50	"-4,0"
0,55	"-3,6"
0,60	"-3,2"
0,65	"-2,8"
0,70	"-2,4"
0,75	"-2,0"
0,80	"-1,6"
0,85	"-1,2"
0,90	"-0,8"
1,00	"0,0"

**Comment by rfomin** [comment]
> the following assignment

Looks reasonable.

**Comment by fabiangreffrath** [comment]
Final questions: 
"OFF" or "0" or "0.0"?
"1" or "1.0" and the like?

**Comment by rfomin** [comment]
I like:
"0"
"1"

**Review by rfomin — APPROVED** [review]
One nitpick - we need to fix the config help line
https://github.com/fabiangreffrath/woof/blob/65f3da8c841ede85816c8911ccce096b63e344e4/src/m_misc.c#L279

**Comment by fabiangreffrath** [comment]
> One nitpick - we need to fix the config help line

Oh sure, thank you!

**Pull request merged**
