### PR TITLE
missed recoil for MBF21 codepointers

### PR DESCRIPTION
**Pull request by rfomin**
Tested on Vesper mod [[doomworld]](https://www.doomworld.com/forum/topic/123800-v100-vesper-mbf21-showcase-mod/), https://github.com/XaserAcheron/vesper (weapon 1 and 2 have no recoil effect)

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
What if the weapon pointers get bound to, say, slots 3 and 7? Should we make weapon recoil values depend on ammo type instead?

**Comment by rfomin** [comment]
> What if the weapon pointers get bound to, say, slots 3 and 7? Should we make weapon recoil values depend on ammo type instead?

I don't know if it helps. Maybe we should expose `recoil_values[]` array to modders?

**Comment by fabiangreffrath** [comment]
But we don't have that yet and it's not part of any spec.

**Comment by rfomin** [comment]
So far the MBF21 weapon mods are pretty conservative so the current values are ok from my testing. Alternatively, we can disable the recoil feature for all weapon mods for consistency.

**Comment by fabiangreffrath** [comment]
What I mean is: with MBF21 code pointers you could bind a rocket launcher to weapon 1 and it would still get pistol recoil.

**Comment by rfomin** [comment]
> What I mean is: with MBF21 code pointers you could bind a rocket launcher to weapon 1 and it would still get pistol recoil.

Also with the MBF21 code pointers, the rocket launcher can fire like a chain gun, right? 😄 I mean modder can change ammo too.

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
