### PR TITLE
indent MIDI PLAYER menu item only as needed

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
Maybe we should center it? Looks a bit awkward now:
woof0001

**Comment by fabiangreffrath** [comment]
> Maybe we should center it? Looks a bit awkward now: 

Not more than before. 😁 But sure, centering is an option.

**Comment by ceski-1** [comment]
Is this possible without too much work?

linebreak

**Comment by fabiangreffrath** [comment]
Hm, just checked, centering doesn't look any better. :no_good:

**Pull request closed without merging**
