### PR TITLE
fix bunny scroll for 32:9 aspect ratio

### LINKED ISSUE #1782: Upcoming 32:9 support. With 32:9 widescreen assets bunny scroller has a problem.
Hello.

As i have seen today there was a commit to get 32:9 support. Great that this feature is coming!

At the moment i am making some 854pixel wide 32:9 widescreen assets. So far they work with Woof and the latest dev-build.

Only thing that does not work is the bunny scroller with those assets.
The same assets work fine with Crispy DOOM and International DOOM. Those both ports have no problem with the bunny scroller.
As Crispy DOOM is not an unknown port for Fabian, i hope that hint could eventually helpful.

Here is a WAD for testing. It contains the DOOM Ultimate titlepic and the two bunny scroller pictures.

[Bunnytest.zip](https://github.com/user-attachments/files/16178471/Bunnytest.zip)

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1782

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
This is the implementation that @mikeday0 once added to Crispy Doom, right?

**Comment by rfomin** [comment]
> This is the implementation that @mikeday0 once added to Crispy Doom, right?

This is an adaptation of PrBoom+'s: https://github.com/coelckers/prboom-plus/blob/969515162c5aebea4ad7a125ee178dcad3d576ad/prboom2/src/f_finale.c#L666-L680

I don't think that [Bunnytest.zip](https://github.com/user-attachments/files/16178471/Bunnytest.zip) is correct, but it works in PrBoom+/DSDA (and in Crispy).

**Comment by Meerschweinmann** [comment]
> I don't think that [Bunnytest.zip](https://github.com/user-attachments/files/16178471/Bunnytest.zip) is correct,

Hello :)

May i ask how it is done technically correct? I was not sure how to do it and oriented me on Nash Muhandes Widepix. Because it worked in Crispy and Inter, i thought that is the good way.

**Comment by mikeday0** [comment]
> This is the implementation that @mikeday0 once added to Crispy Doom, right?

Not me. :) I think it was @SmileTheory.

**Comment by Meerschweinmann** [comment]
> > May i ask how it is done technically correct?
> 
> I think `PFUB1` and `PFUB2` should have the same width. Take a look at Bethesda's [wide assets](https://bethesda.net/en/game/doom-widescreen-mods). At least your test WAD doesn't work properly in the Eternity Engine.

Thanks for that hint Roman.

Ah, Bethesda has two equal wide pictures which overlap in the middle.
In the end it is full horizontal widescreen Resolution (In Bethesdas case 560, because 21:9) plus 320 pixels as seen with PFUB0 Bethesda has in its WAD. And then cut PFUB1 and PFUB2 out of this picture.


I will change it that way and will have a look at EE too.

**Comment by Meerschweinmann** [comment]
Have changed the PFUB pictures overlapped like they are in the Bethesda widescreen release and they work fine with the new Woof dev-build.
I have tested the new pictures with EE too and they work there too after this change.

Thanks again for this hint @rfomin 

Here is the new 32:9 Bunnytest:

[Bunnytest_V2.zip](https://github.com/user-attachments/files/16196453/Bunnytest_V2.zip)

I have added a WIMAP2, that you can see the 1 pixel shift of the animated parts from the episode 3 intermission.
Or should i open a new issue about this?

**Comment by rfomin** [comment]
> I have added a WIMAP2, that you can see the 1 pixel shift of the animated parts from the episode 3 intermission in 32:9 mode.

Thanks, I will look at it.

**Pull request merged**
