### PR TITLE
add umapdef for SIGIL_v1_21.wad

### LINKED ISSUE #455: SIGIL E5M8 Boss Death flags active
I was recently playing `SIGIL_v1_21.wad` in Woof! 8.1.0 on HNTR, but when I reached the final level, the game unexpectedly cut to the end when I defeated the Spiderdemon boss.  I think it was designed for any source port's non-vanilla (>4) episodes to have boss flags inactive by default for their respective final levels, but I believe those flags have been enabled on accident.  Using `SIGIL_COMPAT_v1_21.wad` does not have this issue as it has specific DEHACKED flags to disable the Spiderdemon's boss death flags on E3M8.

I have not tested this on HMP or UV, where a Cyberdemon will also spawn, to see how it affects the boss flags.

I have observed this bug in multiple source ports, the main ones being Woof!, Crispy Doom, and PrBoom+.  I wasn't sure if it was a shared piece of code between these source ports causing the issue or if they each have unique issues, but I am intending to make unique bug reports for each one.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #455

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Thank you! Is this all that's needed to properly play through Sigil's E5?

**Comment by fabiangreffrath** [comment]
Also, are our autoload directories case-insensitive? They should probably be...

**Comment by rfomin** [comment]
> Is this all that's needed to properly play through Sigil's E5?

I haven't played it properly, but I think so.

> Also, are our autoload directories case-insensitive?

Yes. https://github.com/fabiangreffrath/woof/blob/61927061018d0b6ff57e9a620d1d64490678af47/Source/d_main.c#L1519

**Comment by fabiangreffrath** [comment]
Thank you!

**Pull request merged**
