### PR TITLE
do not redraw view border three times

### PR DESCRIPTION
**Pull request by fabiangreffrath**
We do not have three video buffers anymore.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Just stumbled upon this, everything seems to be working as before.

**Comment by rfomin** [comment]
Why still keep `borderdrawcount = 3;`? Do we even need the `borderdrawcount` variable?

**Comment by fabiangreffrath** [comment]
> Why still keep `borderdrawcount = 3;`? 

No specific reason, this is still a draft. It could be turned into a boolean, sure.

> Do we even need the `borderdrawcount` variable?

It's used another time in the `setsizeneeded` case in line 311.

**Review by rfomin — APPROVED** [review]
LGTM.

**Pull request merged**
