### PR TITLE
add PNG palette translation

### LINKED ISSUE #1864: Converting PNGs to the current palette?
I imagined that PNG support meant that we could load PNGs and they would be automatically converted to Doom graphics with proper colors, but that doesn't seem to be the case. Could such a thing be done? At the very least, it would make the base graphics (dogs, beta BFG projectiles) look correct with all WADs.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1864

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
So, this translates from image palette to PLAYPAL. Do you plan to implement a solution for non-paletted PNG lumps as well?

**Comment by rfomin** [comment]
> Do you plan to implement a solution for non-paletted PNG lumps as well?

I don't know, I think users will get better results if they use external tools for this. We'll see if we get a lot of complaints.

**Review by fabiangreffrath — COMMENTED** [review]
Hu, what went wrong with them?

**Comment by fabiangreffrath** [comment]
> Hu, what went wrong with them?

I mean fix m_butt1, m_butt2, m_vbox.

**Comment by rfomin** [comment]
> > Hu, what went wrong with them?
> 
> I mean fix m_butt1, m_butt2, m_vbox.

The were grayscale somehow.

**Comment by fabiangreffrath** [comment]
> We'll see if we get a lot of complaints.

Well, we can't use our own screenshots as fullscreen patches (e.g. as TITLEPIC or INTERPIC). That's my complaint. 😝

**Comment by MrAlaux** [comment]
I just tested this with a WAD using Wolf3D's palette, and some of the dog sprites have their transparent background replaced with a solid gray color:
imagen

This doesn't happen in plain Doom 2.

**Comment by rfomin** [comment]
> I just tested this with a WAD using Wolf3D's palette, and some of the dog sprites have their transparent background replaced with a solid gray color:

Please try this patch:
```diff
diff --git a/src/v_fmt.c b/src/v_fmt.c
index 7c1aff9e..6290b18d 100644
--- a/src/v_fmt.c
+++ b/src/v_fmt.c
@@ -472,6 +472,7 @@ patch_t *V_CachePatchNum(int lump, pu_tag tag)
     }
     else
     {
+        color_key = translate[color_key];
         patch = V_LinearToTransPatch(image, ihdr.width, ihdr.height, color_key,
                                      tag, &lumpcache[lump]);
     }
```

**Comment by MrAlaux** [comment]
> Please try this patch

It gets rid of the solid-color backgrounds, but also makes some pixels disappear:
imagen

**Comment by rfomin** [comment]
@MrAlaux issues should be fixed here: https://github.com/fabiangreffrath/woof/pull/1867

**Pull request merged**
