### PR TITLE
add a signal handler to exit gracefully on fatal signals

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Another idea would be to do what Pr+ does and go the `I_Error()` exit route. Even in this case `G_CheckDemoStatus()` wouldn't be called a second time, because the first thing this function does is set `demorecording = false`. OTOH I am not sure, how much harm this might cause or how much sense this makes, i.e. to destroy all the SDL objects etc. when there was already a segmentation violation elsewhere.

**Comment by fabiangreffrath** [comment]
> ..., because the first thing this function does is set `demorecording = false`. 

Ah, and right after that it calls `I_Error()` itself. 🤦‍♂️

**Comment by fabiangreffrath** [comment]
I consider adding exit sequence priorization ala DSDA after this.

**Comment by rfomin** [comment]
> I consider adding exit sequence priorization ala DSDA after this.

Is our exit sequence is that complex? I like the idea of getting demos even after crash :+1:

**Comment by fabiangreffrath** [comment]
It's not that complex, but it proceeds on functions calls in the reverse order they were registered. However, we want demos to be stored first, before anything else runs in the sequence that could ruin the process's state even further.

**Comment by fabiangreffrath** [comment]
Also, we might wanto to make sure that the function which calls `SDL_Quit()` get called last in the sequence. (Unfortunately, it is currently the same one that stores demo recordings).

**Pull request merged**
