### PR TITLE
id24: intermission updates

### LINKED ISSUE #2000: Blinking "You are here" sprite missing from Legacy of Rust episode 2 intermission screen.
As the title says. Also the splat sprite seems to be in the wrong spot.

Here it is in Woof:
image

And in Kex:
image

### PR DESCRIPTION
**Pull request by rfomin**
Fix #2000 

id1.wad has been updated with the removal of the "map number" concept.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Yay, now @OpenRift412's version of `id1.wad` works, but mine is broken:

grafik

What. A. Crap.

**Comment by rfomin** [comment]
> Yay, now @OpenRift412's version of `id1.wad` works, but mine is broken:

Steam automatically upgrades everything, so I think we should only support the new version. I asked about it on the forum: [[doomworld]](https://www.doomworld.com/forum/topic/146943-id24-a-new-feature-set-standard/?do=findComment&comment=2842800) For me it's a pleasant surprise that it's fixed.

**Comment by fabiangreffrath** [comment]
I find it frustrating that we have to catch up with our reverse engineering approach even before we released the first version that supports the new specs.

**Comment by fabiangreffrath** [comment]
Alright. I'll calm down and leave this up to you - as I'm doing anyway. 😉

**Pull request merged**
