### PR TITLE
implement DSDHacked support

### PR DESCRIPTION
**Pull request by rfomin**
Spec: https://github.com/kraflab/dsda-doom/blob/master/docs/dsdhacked.md

### CODE REVIEW

**Comment by kraflab** [comment]
Cool 😎

**Comment by fabiangreffrath** [comment]
> Cool 😎

Indeed!

**Comment by rfomin** [comment]
I am thinking of implementing a DECOHack compatible parser using the UMAPINFO scanner. But it looks like @kraflab wants to be compatible with earlier versions of ZDoom.
@fabiangreffrath, @kraflab would you be interested in such a development?

**Comment by kraflab** [comment]
For decohack specifically? Since decohack spits out dehacked already on its own, it feels redundant to me. Also then any updates to decohack would require updates from us in turn. I'm not sure I want to be coupled in that way. I'd be curious what MTrop's opinion is on that if you want to start parsing the "source" directly. In principle I'm not completely against it though.

**Comment by rfomin** [comment]
I think DECOHack could become the DECOLITE standard that was recently discussed at DW. But users are more interested in ZDoom compatibility, so yes, it's probably redundant.

**Comment by kraflab** [comment]
I don't really see a purpose for decolite either right now. If we look at where the real need is - ports that implement mbf21 - we already have dsdhacked support in woof, dsda-doom, and gzdoom. Eternity engine intends to support both of those as well. So adding another standard on top / in parallel feels like unneeded overhead. Of course ketmar wants to see that, but is that really contributing much right now? Not clear to me.

**Comment by kraflab** [comment]
> God help you if you try to implement DECOHack's flavor of DECORATE into your port, which I don't recommend at all, especially when I still have that "0" in front of the version number.

Well there's the answer to that 😄

**Pull request merged**
