### PR TITLE
fix -fastdemo with -skipsec

### LINKED ISSUE #1307: `-fastdemo` doesn't work with `-skipsec`
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7114482145)._

If I play a demo through `-fastdemo`, it works as expected: the demo plays back as fast as possible.
_However,_ if I throw `-skipsec` into the mix, the demo will skip the specified time but then resume at normal speed, as if ignoring `-fastdemo`.

`-timedemo` seems to be unaffected.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1307

### CODE REVIEW

**Comment by MrAlaux** [comment]
This fixes `-skipsec` for me. However, using `-warp` still disables fast playback, but weirdly enough, using both `-warp` and `-skipsec` together doesn't disable it.

**Comment by fabiangreffrath** [comment]
> This fixes `-skipsec` for me. However, using `-warp` still disables fast playback, but weirdly enough, using both `-warp` and `-skipsec` together doesn't disable it.

I think this is also needed:

```patch
--- a/src/p_setup.c
+++ b/src/p_setup.c
@@ -1559,7 +1559,11 @@ void P_SetupLevel(int episode, int map, int playermask, skill_t skill)
   if (playback_warp == map || playback_nextlevel)
   {
     if (!playback_skiptics)
+    {
       G_EnableWarp(false);
+      if (fastdemo)
+        I_SetFastdemoTimer(true);
+    }
 
     playback_warp = -1;
     playback_nextlevel = false;
```

**Comment by MrAlaux** [comment]
> @MrAlaux, did you know that you can enable fastdemo at any time during normal demo playback by pressing the "fast forward" key?

I saw the key binding for it, but I never used it. Regardless, I think this should be fixed anyways.

**Comment by fabiangreffrath** [comment]
@rfomin how do we proceed here?

**Comment by rfomin** [comment]
> I love this guy. We could integrate this code for maps without nodes

This guy is awesome. But do you know any maps like this? For ZDoom?

**Comment by fabiangreffrath** [comment]
Planisf2.wad comes without nodes.

**Comment by rfomin** [comment]
> Planisf2.wad comes without nodes.

I have a version with nodes, interesting. I'm not opposed to the node builder, just want to get some test maps.

**Comment by fabiangreffrath** [comment]
> > Planisf2.wad comes without nodes.
> 
> I have a version with nodes, interesting. I'm not opposed to the node builder, just want to get some test maps.

Unfortunately, it's not as drop-in as the voxel code. It requires changes to some very basic structs used in the renderer.

**Comment by fabiangreffrath** [comment]
This is still pending...

**Comment by rfomin** [comment]
> This is still pending...

Let's postpone this even more 😄 It might not be worth fixing this - skipping a few levels with `nodrawers` and then continuing in fastdemo mode is not very useful. It might be worth refactoring playdemo and related functions. I wanted to revisit this after the menu and DRS changes.

**Comment by fabiangreffrath** [comment]
Oki.

**Pull request closed without merging**
