### PR TITLE
only convert lower case ASCII chars to upper case

### LINKED ISSUE #1627: Yellow keycard is displayed in place of the blue skull key on Boom HUD
Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/8447502663)
The issue was introduced in this commit: https://github.com/fabiangreffrath/woof/commit/b32c4df60f0405184d357e1ec16488664206fa0a
Commenting out the line that specifies the locale fixes the issue:
https://github.com/fabiangreffrath/woof/blob/bb47d3f103b83555cb453f9b0ebd25267bffbf47/src/i_main.c#L55-L57

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Probably fixes #1627

@xemonix0 Could you please test if this fixes the yellow key card / blue skull key issue?

### CODE REVIEW

**Comment by rfomin** [comment]
This doesn't work on Windows. Not sure why.

**Comment by xemonix0** [comment]
Nope. There's a new issue, too:

woof0000

**Comment by rfomin** [comment]
> Even then, I don't think this has anything to do with the blue skull key issue in the first place.

The problem is that keys sprites are treated as font in the HUD code. Windows still supports old 8-bit code pages for backwards compatibility, so I think `toupper` changes the keys codes to big cyrillic letters. Anyway, I do not think we use any other string manipulation functions that are affected by locale.

**Comment by rfomin** [comment]
This is works for me:
```diff
diff --git a/src/hu_lib.c b/src/hu_lib.c
index aa0907e..9ed9ecd 100644
--- a/src/hu_lib.c
+++ b/src/hu_lib.c
@@ -159,12 +159,13 @@ static inline void inc_cur_line (hu_multiline_t *const m)
 
 // [FG] add string to line, increasing its (length and) width
 
-static inline const char hu_toupper (const char c)
+static inline const char hu_toupper (const char ch)
 {
-  if (c < HU_FONTSIZE)
-    return toupper(c);
+  int c = toupper(ch);
+  if (c <= HU_FONTEND)
+    return c;
   else
-    return (c);
+    return ch;
 }
 
 static void add_string_to_line (hu_line_t *const l, const hu_font_t *const f, const char *s)
```

**Comment by xemonix0** [comment]
Works for me as well.

**Comment by fabiangreffrath** [comment]
Dammit, thanks!

Remaining question, why does Windows decide to run free and change how `toupper()` treats is arguments, if I only asked to print time and date in the current locale?

**Comment by rfomin** [comment]
> Remaining question, why does Windows decide to run free and change how `toupper()` treats is arguments, if I only asked to print time and date in the current locale?

Looks like a bug. It seems any `setlocale` call affects `toupper` on my system. I suggest awoid `setlocale` on Windows: https://github.com/fabiangreffrath/woof/pull/1631

**Comment by xemonix0** [comment]
> Remaining question, why does Windows decide to run free and change how `toupper()` treats is arguments, if I only asked to print time and date in the current locale?

I examined the UCRT sources and debugged Woof! a bit to understand the issue. I didn't dig too deep, but here's what I found. In the `_wsetlocale` function of `wsetlocale.cpp`, which is called by `setlocale`, there's this piece of code:
```c
if (wcscmp(_wlocale, __acrt_wide_c_locale_string) != 0)
{
    __acrt_set_locale_changed();
}
```
This results in `__acrt_locale_changed_data` being set to `TRUE` if the locale is being set to something other than "C". Note that this doesn't check the category we are setting. To me this looks like a bug. Let's look at `toupper`:
```c
extern "C" int __cdecl toupper(int const c)
{
    return __acrt_locale_changed()
        ? _toupper_l(c, nullptr)
        : __ascii_toupper(c);
}
```
`__ascii_toupper` is called if the locale has never been set to anything but "C". It performs simple subtraction _only if_ the character is in the range of `'a'` to `'z'`.

`_toupper_l` is called if the locale has been changed (no matter what category it was). My system-wide ANSI codepage is `Windows-1251` (ANSI Cyrillic). I checked the character set, and the first six characters after `0x7f` are: `Ђ Ѓ ‚ ѓ „ …`. `Ѓ` and `ѓ` correspond to the yellow keycard and blue skull key respectively, with the former being the uppercase version of the latter. Debugging Woof! in Visual Studio proved that to be the case. Mystery solved.

`Windows-1252` (ANSI Latin 1) has `€   ‚ ƒ „ …` instead and `Windows-1250` (ANSI Central European) has `€   ‚   „ …`. Neither of those character sets have uppercase variants of any of these characters. That's probably why some couldn't reproduce the issue.

**Comment by rfomin** [comment]
> Mystery solved.

Thank you for your research!

**Comment by fabiangreffrath** [comment]
@ Excellent analysis, thank you very much!

**Comment by fabiangreffrath** [comment]
I have adjusted the `toupper()` implementation in this PR a bit. Now it's reduced to exactly what we need and probably faster than any localized libc implementation.

**Comment by fabiangreffrath** [comment]
Hm, I consider moving the function to `m_misc.c` and use it throughout the code. I'm sure it's more or less the same implementation that any C compiler for DOS had at that time.

**Comment by rfomin** [comment]
> Hm, I consider moving the function to `m_misc.c` and use it throughout the code. I'm sure it's more or less the same implementation that any C compiler for DOS had at that time.

Yes, I like the idea. We also have several uses of the `tolower` function.

We must be careful not to use these `ansii_*` functions with file paths, since we support Unicode. For example, `M_ForceLowercase` from `m_misc.c` is used for file paths.

**Comment by rfomin** [comment]
I've just realised that `M_ForceLowercase` doesn't work properly for non-Latin paths. It seems that we have set the locale to UTF-8.

**Comment by fabiangreffrath** [comment]
> I've just realised that `M_ForceLowercase` doesn't work properly for non-Latin paths. It seems that we have set the locale to UTF-8.

AFAICT we only use it on file names, not path names, and I think we may expect these to be ascii encoded.

**Comment by rfomin** [comment]
> AFAICT we only use it on file names, not path names, and I think we may expect these to be ascii encoded.

Yes, but why can't we add `setlocale(LC_ALL, ".utf8");` ? I suggest to use `ansii_toupper`, `ansii_tolower` for all ingame text and set UTF-8 locale for paths and filenames.

**Comment by fabiangreffrath** [comment]
> Yes, but why can't we add `setlocale(LC_ALL, ".utf8");` ? I suggest to use `ascii_toupper`, `ascii_tolower` for all ingame text and set UTF-8 locale for paths and file names.

We might be ready for this now.

**Review by rfomin — APPROVED** [review]
This version of `M_StringToLower` is still fine for non-Latin filenames on Windows because it's file system is case-insensitive. So for Windows `setlocale(LC_TIME, "");` is sufficient.

**Pull request merged**
