### PR TITLE
review message verbosities

### LINKED ISSUE #1193: properly prioritize console messages
Now that we have proper console logging with different levels of priority/verbosity, I'd like to thoroughly review all messages WRT their priorities. What we currently have:

- `VB_ERROR`: This is when an unexpected situation occurs and there will be consequences that we cannot properly handle or that will affect gameplay in a negative way, e.g. a file cannot be read or written, music won't play.
- `VB_WARNING`: This is when an unexpected situation occurs but we have a workaround for it or are somehow else prepared for it. Most messages that were errors in Vanilla Doom would fall into this category. Examples are lumps in PNG format or INTERCEPTS overflow. In general these information may probably be useful for content creators as well as us developers.
- `VB_INFO`: The usual blubber. Most messages that Vanilla Doom or MBF would print anyway will fall into this category. In general, you don't miss anything really important if you silence these.
- `VB_DEBUG`: Additional blubber that is really only relevant for us developers.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #1193 

@ceski-1 @rfomin I am not sure about the priorities of some of the music (especially MIDI) related error messages and warnings. If you could have a closer look, that'd be appreciated.

### CODE REVIEW

**Comment by ceski-1** [comment]
`midifile.c`
All of the `VB_WARNING` messages lead to the midi parser aborting and no music playing. So maybe `VB_ERROR` is more appropriate.

`midifallback.c`
Looks good, `VB_WARNING` is appropriate. This is useful for wad authors to catch and fix bad midis.

`i_winmusic.c`
WinMM errors are passed through `MidiError()` where they're all categorized as `VB_ERROR`. That seems okay to me. If you really want, maybe lower the messages in `I_WIN_ShutdownMusic()` to `VB_WARNING` and update `MidiError()` to support a `VB_*` parameter. I don't really have a preference.

`i_flmusic.c`
FluidSynth itself can spam the console, especially with bad midis. I believe it has a separate verbosity setting. I don't know if it's possible to filter these messages or get an error code so they can be assigned a `VB_*`.

`i_macmusic.c`
`i_oalmusic.c`
`i_oplmusic.c`
These look fine to me.

**Comment by rfomin** [comment]
I agree with everything Ceski said.

For Fluidsyhth we can disable most of the posts:
```
fluid_set_log_function(FLUID_PANIC, show_dialog, (void*) root_window);
fluid_set_log_function(FLUID_ERR, NULL, NULL);
fluid_set_log_function(FLUID_WARN, NULL, NULL);
fluid_set_log_function(FLUID_DBG, NULL, NULL);
```
from https://www.fluidsynth.org/api/group__logging.html

**Comment by fabiangreffrath** [comment]
Thank you very much for the feedback!

**Comment by fabiangreffrath** [comment]
Another topic that I am unsure about is the `src/net_*` files. That is, I am not sure which messages lead to the connection getting interrupted and which are merely actual warnings/info.

**Comment by fabiangreffrath** [comment]
Thank you! 😽

**Pull request merged**
