### PR TITLE
implement G_GetCurrentComplevelName function

### PR DESCRIPTION
**Pull request by rfomin**
Feature request: [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-1010-july-18-2022-updated-winmbf/?do=findComment&comment=2521559)

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I only tested on Debian so far and here the packaging system overrides all build variables anyway.

**Comment by fabiangreffrath** [comment]
Didn't get any patches (or bug reports) from any other Linux distro yet, we are probably not the most popular source port... yet. 😁

**Comment by rfomin** [comment]
> Didn't get any patches (or bug reports) from any other Linux distro yet, we are probably not the most popular source port... yet. 😁

We seem to have a few hundred users from DW and about 5 speedrunners/coop players 😄

**Comment by fabiangreffrath** [comment]
> We seem to have a few hundred users from DW and about 5 speedrunners/coop players 😄

The 10.1 release has been downloaded 135 times during its first 24 hours.

**Comment by rfomin** [comment]
Don't get me wrong, I didn't mean it's bad, I think it's good for a retro port. Also, these 5 speedrunners are amazing and have recorded some very fun coop demos 😄 I'm planning on adding a join demo command (-recordfromto).

**Comment by fabiangreffrath** [comment]
No, wait, me too. I think that's amazing! I mean the latest Crispy release is approaching 7000 downloads, but that port has a ~10 years history, whereas this project is still very young and shares its users with veterans such as PrBoom+ and The Eternity Engine.

**Pull request merged**
