### PR TITLE
fix par time array overflow for Episode 4

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Alternatively, add the checks from Chocolate Doom.

**Review by rfomin — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
I wonder why it never crashed when we checked support for maps like E9M9 or MAP99.

**Comment by rfomin** [comment]
> I wonder why it never crashed when we checked support for maps like E9M9 or MAP99.

I think this code does not execute if UMAPINFO is used.

**Comment by fabiangreffrath** [comment]
> I think this code does not execute if UMAPINFO is used.

But only if a "next" map is defined, as we have just learned. 🤓 Might still have been the case here, though.

I'd like to add the explicit overflow emulation of Episode 4 into the `cpars[]` array from Chocolate Doom (and also the MAP33 case) if `demo_compatiblity == true`. What do you think?

**Comment by rfomin** [comment]
> I'd like to add the explicit overflow emulation of Episode 4 into the `cpars[]` array from Chocolate Doom (and also the MAP33 case) if `demo_compatiblity == true`. What do you think?

OK, if it's in Chocolate Doom.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
