### PR TITLE
add miniz as a replacement for SDL_Image+libpng+zlib

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — COMMENTED** [review]
I'm not sure if we need this? What if in the future we want to load PNG patches. Also, I prefer to have more DLLs than code :smile:

**Comment by fabiangreffrath** [comment]
> What if in the future we want to load PNG patches. 

🤔 

> Also, I prefer to have more DLLs than code 😄

In general, I agree. But keeping track of SDL libraries from official releases vs. build environment with all hard and optional dependencies turns out to be a burden.

**Comment by rfomin** [comment]
> > What if in the future we want to load PNG patches.
> 
> thinking

I think miniz doesn't have PNG load, only a write function.

**Comment by fabiangreffrath** [comment]
> I think miniz doesn't have PNG load, only a write function.

Sure, that's right. I am pretty sure the mere pixel data can be inflated from the PNG data pretty easily, if you can afford to drop any meta data.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
