### PR TITLE
import R_ClipWallSegment function from PrBoom

### PR DESCRIPTION
**Pull request by rfomin**
This greatly speeds up some places in Sunder.wad map15.  Thanks to @JNechaevsky for the hint.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Wow, this is a rather drastic change, and as you know I am skeptic towards these. How many FPS does this buy us in this specific Sunder map?

**Comment by rfomin** [comment]
I didn't measure FPS, but the difference in some places is ~12000 segs versus ~70 segs. This map was definitely made with PrBoom+ in mind.

**Comment by fabiangreffrath** [comment]
I see. What has become of the flats optimization that @jnechaevsky suggested?

**Comment by rfomin** [comment]
> What has become of the flats optimization that @JNechaevsky suggested?

Do you mean R_DupPlane changes? From my testing, there is no difference in Woof.

**Comment by JNechaevsky** [comment]
@fabiangreffrath, please believe me, I've spent about 1.5 months on Sunder MAP15 while transferring optimizations into RD and literally palped all necessary places for performance checking. This change is really needed, especially for port with Boom/MBF21 modding standards, which many modern slaughter maps are made of nowadays.

If you wish to see a difference by yourself, here are two savegames for latest Sunder wad. I'll explain:

1) [woofsav0.zip](https://github.com/fabiangreffrath/woof/files/7883490/woofsav0.zip) - right after loading fps is mostly low. Very carefully rotate camera left and right, and you will see how fps will grow higher. This is one of most "expensive" scenes which is easy to catch.
2) [woofsav1.zip](https://github.com/fabiangreffrath/woof/files/7883569/woofsav1.zip) - right after loading fps is mostly low. This is because of lots of segs are located in front of player's POV, despite of they are much higher and should be cutted away by tall frontal seg. Mystic, eh?

As about `R_DupPlane`, yes, my bad. I have ported most optimizations into RusHexen (not all of them, polyobjects aren't in love with pseudovertexes), and probably because of some difference in the code, my commit with replacing `memset` made `R_DupPlane` working as it should. I was a worried a bit, that's why I have suggested to check what's going on in Woof, where `memset` approach comes from.

In more short words: current approach in Woof is working fine, no changes needed.

**Comment by fabiangreffrath** [comment]
Thanks for the elaboration! However, I think I remember that the number of rendered visplanes was about halved between the two screenshots that you posted. This would be a very interesting approach.

**Comment by JNechaevsky** [comment]
Yep, and in Woof that number was already halfed - @rfomin temporarily ported visplanes counter from PrBoom+ and confirmed that number is about +-2200 (can't be too precise, numbed heavily depends on camera POV placement), not +-5000. So I believe, `R_DupPlane` in doing it's job just fine already in Woof.

**Comment by fabiangreffrath** [comment]
@rfomin Sorry I am so reluctant to approve this. Sure, I would like to see the optimization in Woof, but this rips out and replaces a central part of the renderer and I get the creeps when looking at the diff. Do you think it could be refactored a bit to become a minimal change or doesn't this make any sense in this case?

**Comment by rfomin** [comment]
I'll give it a try in the coming days, but to be honest, I don't think we should rewrite this function, it's been running in PrBoom for decades and we can just add more bugs.

**Comment by fabiangreffrath** [comment]
Okay, I see. But maybe we can just `#ifdef MBF_STRICT` style comment out the original code, so that it is "still there - just in case".

**Review by fabiangreffrath — APPROVED** [review]

**Comment by kraflab** [comment]
Code gets really frustrating to understand when you add this many conditional defines, especially when you suddenly realize you've been reading code that is actually dead. What about just adding a comment about the change on top of the key function and linking the PR?

**Comment by fabiangreffrath** [comment]
I have a general problem with replacing original code with "better" code. I have gone through this several times during the Crispy development (mostly when porting back code from other ports, e.g. MBF, to the Vanilla code base), and often the "better" code simply covers a few more corner cases but follows the same general logic as the original one. I have adopted the habit to identify the improvements and apply them to the original code instead.

Also, drop-in replacements sometimes introduce subtle bugs in apparently unrelated code, e.g. by changing the type or sign of a variable, and it takes time to find them and even more time to finally fix them.

In the case at hand, sure, the code has been there for literally decades - it's just that it hasn't been in Woof for decades and changing such a central part of the renderer may introduce bugs in other parts of the renderer that we don't yet know of. In this case, I'd like to have the original code as a backup, so switching algorithms for debugging is just one `#define` away.

**Comment by kraflab** [comment]
In exchange for this debug switch that likely will never be used, and could be added ad hoc if and when it is needed, the related code complexity is much higher and the logic is now harder to follow (aka more bug-prone down the line). PRBoom+ has this problem scattered all over the place, random toggles that were left in and never cleaned up. I understand your philosophy about not replacing code, but you _are_ replacing the code here. I'm thinking about potential future contributors to Woof, where this pattern will increase the barrier of entry. Just my opinion. 🦆

**Comment by fabiangreffrath** [comment]
Hm, you are making some good points here. Maybe I should just overcome my fear and dare to jump into the cold water. The negative example of PrBoom+'s code labyrinth really got me. Also, I don't want to increase the entrance burden for future contributions. 

@rfomin Could you please revert to the state of Monday? I'm gonna dare it.

**Comment by fabiangreffrath** [comment]
Thank you!

**Pull request merged**
