### PR TITLE
fix desyncs by SSG-flash correction

### LINKED ISSUE #1669: SSG-flash correction causes desyncs
_Tested in the [latest master artifact (Win-x64)](https://github.com/fabiangreffrath/woof/actions/runs/8868644956)._

Before anything, I'd like to say that this seems to be of very-low priority; I'm not aware of any real cases.

[This](https://github.com/fabiangreffrath/woof/blob/master/src/info.c#L162-L165) is the correction in question.

I could tell right away that it could cause issues, so I put together a little DeHackEd patch that adds a state to the SSG flash animation which fires a rocket, and recorded a demo with it in Chocolate. Both the patch and demo are here: [SSG-Flash_Desync.zip](https://github.com/fabiangreffrath/woof/files/15146010/SSG-Flash_Desync.zip).

Sure enough, the demo desynced in the Woof artifact mentioned above. I checked the DSDA 0.27.5 sources and it doesn't have the correction, and as expected, the demo _does_ sync in it.

Judging by the comment, it would appear that the correction was implemented into either Boom or MBF **_very_** long ago. If that's truly the case, it should probably be complevel-dependent, meaning that neither Woof nor DSDA handle it correctly.

Admittedly, this is something very obscure; assuming that it _is_ a Boom/MBF-specific change, it has been around for over 25 years, and yet I've never heard about it causing desyncs, and judging by the fact that neither Woof nor DSDA handle it as I believe they should, I suspect that it was never reviewed because it never caused any issues.

What do you think? Maybe I missed something.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #1669

### CODE REVIEW

**Comment by MrAlaux** [comment]
With this change, Choco and this build of Woof play back demos from each other properly, but demos recorded in Woof builds from before the change (in place of proper Boom demos) still desync in this build. I'm not familiar with the DEH parsing code, but at first glance, I don't see a complevel check or anything similar that would properly address this.

**Comment by fabiangreffrath** [comment]
> With this change, Choco and this build of Woof play back demos from each other properly, but demos recorded in Woof builds from before the change (in place of proper Boom demos) still desync in this build. I'm not familiar with the DEH parsing code, but at first glance, I don't see a complevel check or anything similar that would properly address this.

Since Woof is currently the only source port in which the `S_DSGUNFLASH1` state lasts 4 tics instead of 5, we must consider all demos which rely on it being 4 tics long as broken, I am afraid. There is no Woof-exclusive complevel. And we even modified pristine MBF code to match PrBoom+'s complevel 11 behavior in the past, look for the `MBF_STRICT` macro.

This code merely checks if it's safe to modify the `S_DSGUNFLASH1` state, or if it has been dehacked to end in an action pointer. I am going to make the recursion check more robust, though.

**Comment by fabiangreffrath** [comment]
I think I'll reverse the logic of this patch:

1. Revert the MBF state duration change and guard it with the `MBF_STRICT` macro.
2. Check if the `S_DSGUNFLASH1` state is safe and lasts 5 tics.
3. Only then reduce it to 4 tics.

**Comment by rfomin** [comment]
> * Revert the MBF state duration change and guard it with the `MBF_STRICT` macro.
> * Check if the `S_DSGUNFLASH1` state is safe and lasts 5 tics.
> * Only then reduce it to 4 tics.

This is the right thing to do in my opinion.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
