### PR TITLE
set widescreen width while maintaining current video height

### PR DESCRIPTION
**Pull request by rfomin**
Might fix https://github.com/fabiangreffrath/woof/issues/1406

### CODE REVIEW

**Comment by ceski-1** [comment]
I can't do a thorough review at the moment, but I made a quick debug build and it no longer crashes on launch.

**Comment by rfomin** [comment]
@MrAlaux Does this PR fix https://github.com/fabiangreffrath/woof/issues/1334#issuecomment-1925272595 for you?

**Comment by ceski-1** [comment]
> @MrAlaux Does this PR fix [#1334 (comment)](https://github.com/fabiangreffrath/woof/issues/1334#issuecomment-1925272595) for you?

I see the HOM issue at 32:9 but not at other aspect ratios.

**Comment by MrAlaux** [comment]
Sorry for the wait, I just got on my computer.

I can confirm ceski's findings -- 32:9 at native resolution has a HOM:
woof0001

16:10 also has a HOM, same resolution setting:
woof0000

**Comment by rfomin** [comment]
@MrAlaux https://github.com/fabiangreffrath/woof/pull/1433/commits/acae4624dc117eb83a6b6caab73c27404856075c fixed HOM for me on all resolutions/aspect ratios (including 640p) except 32:9 on some resolutions (e.g. 600p).

@ceski-1 What is the difference between 32:9 and other aspect ratios? We can remove it, it's a bit extreme anyway.

**Comment by ceski-1** [comment]
> @ceski-1 What is the difference between 32:9 and other aspect ratios? We can remove it, it's a bit extreme anyway.

I don't think it's critical. 32:9 is extremely niche. I also noticed if the FOV slider is increased at 32:9 the sprites disappear near the edges. I think the original fine* tables are showing their limitations at these extreme angles. I'm okay with removing 32:9 for now.

**Comment by rfomin** [comment]
@MrAlaux Could you please check this PR? It works for me, but I might be missing something (the one-pixel HOM column is sometimes hard to see).

**Comment by MrAlaux** [comment]
> @MrAlaux Could you please check this PR? It works for me, but I might be missing something

All aspect ratio and resolution combinations I can use seem to be free of HOMs on my end.

> the one-pixel HOM column is sometimes hard to see

Have you tried using the `HOM` cheat? That's what I've been using.

**Comment by rfomin** [comment]
> All aspect ratio and resolution combinations I can use seem to be free of HOMs on my end.

Thanks!

> Have you tried using the `HOM` cheat? That's what I've been using.

Forgot about it. Checked everything again, seems to work.

**Pull request merged**
