### PR TITLE
Fix stutter in weapon switching animation

### LINKED ISSUE #1081: Yet another stutter in the weapon switching animation
_Tested in the 11.1.4 release._

I must admit, I didn't find this stutter accidentally. I intentionally provoked it myself, because I could already tell that the current approach to prevent stuttering could still fail in some cases.

This is the WAD I made, the new weapon replaces the BFG: [A3X-Railgun.zip](https://github.com/fabiangreffrath/woof/files/11581405/A3X-Railgun.zip)

**Breakdown:**

The deselect animation for the weapon is as follows:

```
    Deselect:
      RLGG D 12 Offset(1,60) A_WeaponSound("RLDOWN")
      RLGG C 12
      RLGG B 11
      RLGG A 1 A_Lower()
      Wait // This loops the A_Lower frame
```

The `RLGG D` frame meets the `state == winfo->downstate` condition, so bobbing is not applied during that frame.
The `RLGG A` frame meets the `psp->state->action == A_Lower` condition, so bobbing is not applied during that frame either.
The two frames in between, however, meet no conditions, so bobbing _is_ applied to them. That's the issue.

I have a potential solution in mind. We could introduce a variable that determines whether a switch is in progress. It'd be set to `true` within the following `if` statement, and set to `false` in a new `else` statement to be added right after it:

https://github.com/fabiangreffrath/woof/blob/6dafe9b7b0e58ecf435d8bd7c239b1022f564a2e/src/p_pspr.c#L473-L479

Of course, we'd disallow any bobbing if the new variable equals true. What I'm not sure of is _where_ we should create that variable in.

What do you think of this approach?

### PR DESCRIPTION
**Pull request by MrAlaux**
Should fix #1081.

Let this serve as a practical explanation of what I have in mind.
From what I've tested with vanilla Doom 2, D4V, Armas29 and A3X-Railgun, it solves the issue.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Thank you for this! I have yet to understand why this approach works, but the former didn't, but it looks reasonable to me. However, I'd prefer if you could define an `enum lor_t` that could take the values `none`, `lowering` and `raising`, and then condense the `lowering` and `raising` variable into a single variable `lowering_or_raising` of type `lor_t`.

**Comment by MrAlaux** [comment]
> I have yet to understand why this approach works, but the former didn't, but it looks reasonable to me.

Here's something I noticed: last three issues I reported regarding weapon stutters occurred during the switching state. When it comes to the attacking state, though, I've encountered no issues. In that case, we determine whether we're attacking or not by checking for `player->attackdown`, whose value is only changed in `A_WeaponReady()`. The approach I'm proposing happens to be very similar to this.

> However, I'd prefer if you could define an `enum lor_t`

Just a suggestion: what about `weapswitch_t` (or something else with the word "switch" in it)?

**Comment by fabiangreffrath** [comment]
Yep, `weapswitch_t` is also fine. 😉

**Comment by MrAlaux** [comment]
I didn't use the exact names you proposed, I consider these more appropriate. Please let me know if you want me to change them.

**Review by fabiangreffrath — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
