### PR TITLE
fix the background update of the credits screen, simplify

### LINKED ISSUE #1858: HOM in credits screen
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/10449481625)._

Steps to reproduce, with a fresh config file:

- Reach the credits screen (only way I know to do so is to let two of Doom 2's demos play)
- Enter any setup menu from the Options menu

From that point on, the background isn't properly cleared until you exit the setup menu.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1858

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Thank you!

Speaking of the credits screen, would you like to take the opportunity and add yourself?

**Comment by rfomin** [comment]
> Speaking of the credits screen, would you like to take the opportunity and add yourself?

I'd like to remove the credits screen 😄 But if others are against removing it, sure, we can add me and Ceski.

**Comment by fabiangreffrath** [comment]
> sure, we can add me and Ceski.

But real names, please. 😉

**Comment by ceski-1** [comment]
> I'd like to remove the credits screen 😄 But if others are against removing it, sure, we can add me and Ceski.

Does the original credits screen not appear in MBF-based ports? If that's the case, it would probably be nice to restore the original id credits screen.

**Comment by rfomin** [comment]
> Does the original credits screen not appear in MBF-based ports? If that's the case, it would probably be nice to restore the original id credits screen.

Eternity has it, but PrBoom+ and others don't. I think the credits screen is awkward, especially now that we have a lot of contributors in Woof and we can't fit everyone into that screen.

**Pull request merged**
