### PR TITLE
switch to libxmp from libmodplug

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
He, where does this change of mind come from?

**Comment by rfomin** [comment]
I canceled the `vcpkg` build as there are a lot of changes. I also want to try a static build so we still have to rebuild everything if you don't mind.

**Comment by fabiangreffrath** [comment]
> It has been added to `vcpkg`. Fluidsynth 2.3.2 has also been added (looping bug fix). Everything is ready for release.

Looking forward to it! 184 commits since the last release, the changelog is going to be a nightmare. 😨 

> I canceled the `vcpkg` build as there are a lot of changes. I also want to try a static build, so we'll have to rebuild everything if you don't mind.

I dont mind! Please do whatever you consider best for the Windows builds.

**Comment by rfomin** [comment]
> 184 commits since the last release, the changelog is going to be a nightmare.

I'll populate it after the static build. I even like it, why is everyone so against changelogs 😆

**Pull request merged**
