### PR TITLE
Keep arrow stable in non-rotate mode

### PR DESCRIPTION
**Pull request by JNechaevsky**
This keeps arrow stable in non-rotate mode with preserving smooth rotation.

Extra suggestion: do not draw little dot in follow mode?

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
> This keeps arrow stable in non-rotate mode with preserving smooth rotation.

Thank you!

> Extra suggestion: do not draw little dot in follow mode?

Sure, I'll add this after merging.

**Comment by JNechaevsky** [comment]
Sigh. Found one more problem across our ports. It happens in re-release of [Planisphere ﻿2](https://www.doomworld.com/forum/topic/61701-planisphere-2/?page=2&tab=comments#comment-1884524) (initial release simply will not load). The more player getting closer to the bottom edge of the map (south) in rotate mode, the more some lines are screwed up ([screenshot](https://user-images.githubusercontent.com/21193394/176837710-8404280d-aa4e-4600-a61a-7e5d939d65c0.png)). Possibly it's an in integer overflow? Interestingly, it does not happen in PrBoom.

**Comment by fabiangreffrath** [comment]
I have seen this before. Could you check if this also happens in Crispy?

**Comment by JNechaevsky** [comment]
Yep, exactlly the same way: [screenshot](https://user-images.githubusercontent.com/21193394/176844344-9217c477-5fe2-46f0-a350-c21eddd6aa74.png).

**Comment by fabiangreffrath** [comment]
Pretty much definitely an integer overflow, though not sure in which function.

**Comment by fabiangreffrath** [comment]
The point is that it would have to draw lines across the "end of the world". If you IDCLIP and just walk straight into this area in the south you'll find yourself back in the north of the map after a few steps.

**Comment by JNechaevsky** [comment]
Nope, no luck for the moment. I even tried to replace every single variable with `int_64` type as well as `INT_MAX` macroses to `LLONG_MAX`, everything still same. Probably it's a not an overflow of the value itself, but it's condition while rotate mode (line clipping?).

However, what makes me really confused is a performance. Here's a scene, where I have about ~45 fps in [Woof!](https://user-images.githubusercontent.com/21193394/176997446-fb60bec6-1117-42b5-ba9e-f892cce74273.png) and ~73 fps in [InterDoom](https://user-images.githubusercontent.com/21193394/176997517-f58700eb-cb22-4fb1-a76a-aed5727df938.png). Note that rendering counters are mostly same except for sprites (but 100 sprites can't be a reason for such fps dropoff?). Here's this place on map: [screenshot](https://user-images.githubusercontent.com/21193394/176997710-07095e1f-5f8f-4f31-8100-f5f487f85f4d.png). AFAIR, all existing optimizations were ported from PrBoom to Woof, but turns out, there is something more? 😮

**Comment by JNechaevsky** [comment]
Figured it out, there is missing optimization written by Andrey Budko: https://github.com/fabiangreffrath/prboom-plus/blob/master/prboom2/src/r_things.c#L80-L97

After applying, fps is about stable 75-76 fps (yay!). I'll try to make an accurate PR, but apply it or not will be at your discretion.

**Comment by fabiangreffrath** [comment]
> Nope, no luck for the moment.

Pr+ has this `FRACTOMAPBITS` concept. Maybe this makes the difference here.

**Comment by rfomin** [comment]
> > Nope, no luck for the moment.
> 
> Pr+ has this `FRACTOMAPBITS` concept. Maybe this makes the difference here.

As far as I understand, the Pr+ version increases the precision. Looks smooth, but they rewrote a lot of code in am_map.c.

**Comment by JNechaevsky** [comment]
> Pr+ has this FRACTOMAPBITS concept. Maybe this makes the difference here.

😍 This is exactly what was needed! Made a brief porting to ID, yes, that works ([screenshot](https://user-images.githubusercontent.com/21193394/177092113-5582ebc0-d519-4dd8-8add-da4fbe377cee.png)). However, some things like grid and iddt triangles requires some additional. extra accurate polishing, otherwise they will have wrong sizes, but it seems to be doable. 

Once I'm done, I'll apply it to ID first so you can see how much code changes it will require, and then we can decide should be applied to Woof and Crispy family or not.

_P.S. ... a-a-a-a-and yes, vacation time! 🤠_

**Comment by fabiangreffrath** [comment]
🥳

**Comment by JNechaevsky** [comment]
Here, still WIP, but I've got it working: https://github.com/JNechaevsky/inter-doom/pull/357
Have to say, not that small changes, but fortunately, visually everything is still same.

**Comment by fabiangreffrath** [comment]
Looks pretty clean and straightforward to me. 👍

**Pull request merged**
