### PR TITLE
make "skull" the back button in mouse mode.

### PR DESCRIPTION
**Pull request by rfomin**
Not that useful, frankly.

https://github.com/fabiangreffrath/woof/assets/5077629/c26a741e-70d6-4db8-87d0-1cad4c704153

### CODE REVIEW

**Comment by ceski-1** [comment]
Yeah, this was just a quick idea I threw out during the big menu PR, but I'm not sure about it. Actually, I wonder now if the skull and reset button should be moved back to the top or if it will clash with the tab names. The reason I suggest this is that it would make HUD changes easier to see when using the "dark" or "off" background options. Also, they tend to blend in with the status bar.

**Comment by fabiangreffrath** [comment]
I like it that the skulls now have an actual use in the menus.

Some PWADs replace the skull with a graphic that resembles a right pointing arrow. We could draw it with `V_DrawPatchFlipped()` in the menus to point out that it leads "back".

**Comment by rfomin** [comment]
> > Some PWADs replace the skull with a graphic that resembles a right pointing arrow. We could draw it with V_DrawPatchFlipped() in the menus to point out that it leads "back".
> 
> Yes, I like the idea.

Unfortunately, the "active" frames in PWADs are not always the same as in vanilla, so it's "highlited" when inactive (BTSX):
 
woof0000

It seems that this PR won't work.

**Comment by ceski-1** [comment]
> How about removing the menu background options and making it dark (but less saturated) by default?

Maybe it's a good time to rearrange the background options to be: 0 = Off, 1 = Dark, 2 = Pattern (or Texture or something similar to that) and make dark the default. The order is a little confusing currently because it starts at 0 = On, I believe.

**Comment by fabiangreffrath** [comment]
> Unfortunately, the "active" frames in PWADs are not always the same as in vanilla, so it's "highlited" when inactive (BTSX):

You can still draw the patch with the `cr_hilight` translation table.

**Comment by rfomin** [comment]
> Maybe it's a good time to rearrange the background options to be: 0 = Off, 1 = Dark, 2 = Pattern (or Texture or something similar to that) and make dark the default. The order is a little confusing currently because it starts at 0 = On, I believe.

Agreed. Maybe we should change the intensity and remove the "animation"?

**Comment by fabiangreffrath** [comment]
> Agreed. Maybe we should change the intensity and remove the "animation"?

But the animation looks great.

**Comment by rfomin** [comment]
> But the animation looks great.

But this is the only animated thing in the menu, everything else is "instant" (which I like).

**Comment by fabiangreffrath** [comment]
It blends with the shaded automap overlay mode.

**Comment by rfomin** [comment]
> You can still draw the patch with the `cr_hilight` translation table.

I tried this in https://github.com/fabiangreffrath/woof/pull/1426/commits/1b41c9f14fa71b62126ce4c91852fd3ac2add284 But now it's different from reset button.

Don't think it's worth it, we still don't have a 'Back' button in the 'Options' menu (only in 'Setup'), so the user can't return to the 'Main' menu using this method.

**Comment by fabiangreffrath** [comment]
Hm'kay. 😞

**Comment by ceski-1** [comment]
> Agreed. Maybe we should change the intensity and remove the "animation"?

I'm late to the discussion but yes, even though the "fading" effect is nice the first few times, I actually prefer instant feedback for both the menu and the automap. Sort of like how I disable animations in an OS.

**Pull request closed without merging**
