### PR TITLE
adapt Eternity Engine's smooth Automap line drawing approach

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — APPROVED** [review]
Looks good!

**Comment by JNechaevsky** [comment]
@fabiangreffrath may I ask for small advice here? True color wants to use `V_GetPaletteIndex` instead of `I_GetPaletteIndex`, this is absolutely clear. But I'm a bit confused with these two lines:
* [This one](https://github.com/fabiangreffrath/woof/blob/master/src/am_map.c#L1299). It should be in `colormaps[...]` array?
* And [this one](https://github.com/fabiangreffrath/woof/blob/master/src/am_map.c#L1291). It have to be `pixel_t`, not just `byte` to hold whole screen buffer data, but after such replacement engine simply crashes by trying to draw line, not sure why. Using `byte` isn't crashing, but using just a blue for all translucency.

**Comment by fabiangreffrath** [comment]
This code isn't truecolor compatible at all. It converts palette colors into a reduced 3x5-bits color space, mixed them is this space and then converts back to the closest palette color.

**Comment by JNechaevsky** [comment]
That's catastrophy... 🙂 I was thinking to experement with blending functions somehow, but probably better to leave them for good, as such drawing will be more expensive. Thank you for explanation!

**Comment by fabiangreffrath** [comment]
Na, it's not a catastrophe. We already have a working implementation. It's a bit slow and naive, but it works. And we can have a better one some day, I already have some ideas for this.

**Pull request merged**
