### PR TITLE
interpolate sfx in a 16-bit int domain

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
Does this eliminate “hiss”? I can send a build to dw user Game, he hears it.

**Comment by fabiangreffrath** [comment]
That's the question I wanted to ask him, as I am unable to hear it myself. I am still in Croatia with access to a Win system not earlier than next Tuesday, so if you could provide a test build that'd be appreciated.

**Comment by rfomin** [comment]
Game thinks the "hissing" is fixed. He is not sure and tests more tomorrow.

**Comment by rfomin** [comment]
I've got update from Game:

> I managed to test it. What I did first was managed to hear the high frequency signal in the public Woof version. Then I started playing the same noisy maps in your new beta and I confirm the high frequency signal doesn't appear anymore. So I think you've fixed it, and did so while preserving the lovely old Woof sound.

**Comment by fabiangreffrath** [comment]
Great! So, we will have to keep this as the default route `if (!use_libsamplerate)` once the Crispy sound system inport PR gets merged.

**Pull request merged**
