### PR TITLE
accept '-' in TK_Identifier

### PR DESCRIPTION
**Pull request by rfomin**
Fix this issue: [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-1200-sep-15-2023/?do=findComment&comment=2737328)

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]

**Comment by rfomin** [comment]
Technically, a lump name can contain any byte, and we should use TK_String here. But our TK_String is always enclosed in quotes, so it is incompatible with MUSINFO. Still, I think a TK_Identifier is reasonable, why would anyone want to name lump like "D_[//[*MUS]" 😄

**Comment by fabiangreffrath** [comment]
Hm, we could check with e.g. `isprint()` or similar.

**Comment by rfomin** [comment]
> Hm, we could check with e.g. `isgraph()` or similar.

Than it will be incompatible with UMAPINFO. From spec: "Values can be strings, enclosed in quotation marks ("), numbers or identifiers. Identifiers are case insensitive names that start with a letter and may only contain letters, numbers or the underscore (_)."

Maybe we should add a string token without quotes.

**Comment by fabiangreffrath** [comment]
> "Identifiers are case insensitive names that start with a letter and may only contain letters, numbers or the underscore (_)."

So, we have just become incompatible by adding the minus as an accepted character? :wink:

> Maybe we should add a string token without quotes.

Fine with me. But also fine as it is now. 🤷

**Comment by rfomin** [comment]
> So, we have just become incompatible by adding the minus as an accepted character?

Yes. Maybe rewriting the MUSINFO parser was a bad idea. Or we need to extend u_scanner a bit.

**Comment by coelckers** [comment]
Just wait until someone produces a UMAPINFO depending on such a quirk. The question is not if it will happen but merely when it will happen. You should make this optional so it can be enabled on a per-lump basis.

**Comment by fabiangreffrath** [comment]
Hm, so we either need a new token category, e.g. `TK_LumpName` which is the like `TK_StringConst` but without the quotes (or like `TK_Identifier` but accepting all chars). Or, we introduce a global variable to switch between "complevels" for the `TK_Identifier` token.

**Comment by fabiangreffrath** [comment]
> "Identifiers are case insensitive names *that start with a letter* and may only contain letters, numbers or the underscore (_)."

This was already broken before by accepting Identifiers that start with an underscore and is now even "brokener" by also accepting minus.

**Pull request merged**
