### PR TITLE
fix garbage lines on some sprites

### LINKED ISSUE #1392: Garbage lines in some non-weapon sprites
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7530482576)._

Similar to #1371, also with Triple resolution. I've only noticed it with this doll decoration from [this WAD](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/sihr2fix):
imagen

In case you're going to test with that sprite from that WAD, then that doll in particular is from Map08 at the coordinates in the screenshot.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1392

This problem is not easy to spot, the fix is the same as for pspr sprites.
Save: [woofsav0.zip](https://github.com/fabiangreffrath/woof/files/13974044/woofsav0.zip) [WAD](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/sihr2fix)

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Indeed, with this fix I get a black line at the bottom of the sprite:

woof0000

[woofsav1.zip](https://github.com/fabiangreffrath/woof/files/13980629/woofsav1.zip)

**Comment by rfomin** [comment]
> Indeed, with this fix I get a black line at the bottom of the sprite:

I don't have that at any resolution:
woof0002

I've had this happen before when I changed it in the wrong place. Are you sure you don't have any remnants of the old changes? Also what is your resolution?

**Comment by fabiangreffrath** [comment]
> Are you sure you don't have any remnants of the old changes? 

Nope, this is the only change:

```sh
$ git diff
diff --git a/src/r_things.c b/src/r_things.c
index c998b20..6a64ff4 100644
--- a/src/r_things.c
+++ b/src/r_things.c
@@ -441,7 +441,7 @@ void R_DrawVisSprite(vissprite_t *vis, int x1, int x2)
       else
         colfunc = R_DrawColumn;         // killough 3/14/98, 4/11/98
 
-  dc_iscale = abs(vis->xiscale);
+  dc_iscale = abs(vis->xiscale) + 1;
   dc_texturemid = vis->texturemid;
   frac = vis->startfrac;
   spryscale = vis->scale;
```

> Also what is your resolution?

```gdb
(gdb) p video
$1 = {
  width = 1278,
  height = 600,
  pitch = 1920,
  unscaledw = 426,
  deltaw = 53,
  xscale = 196608,
  yscale = 196608,
  xstep = 21846,
  ystep = 21846,
  fov = 1267733622
}
```
Interestingly, the line vanishes if I switch off widescreen rendering:

woof0001

```gdb
(gdb) p video
$2 = {
  width = 960,
  height = 600,
  pitch = 1920,
  unscaledw = 320,
  deltaw = 0,
  xscale = 196608,
  yscale = 196608,
  xstep = 21846,
  ystep = 21846,
  fov = 1073741824
}
```

**Comment by fabiangreffrath** [comment]
No wait, still there (look at the doll's shoulders).

woof0000

**Comment by fabiangreffrath** [comment]
This is probably what Killough meant with this comment:

https://github.com/fabiangreffrath/woof/blob/093dad5890d22de880c9da3fbfbd781ec89dc85e/src/r_things.c#L375-L377

**Comment by JNechaevsky** [comment]
If I'm not mistaking, "sparkles" was meant to be a transparent pixels at the junction of two-sided midtextures with floors/ceilings. These ones: 

<details>

image

image

</details>

**Comment by rfomin** [comment]
Interesting that #1400 affect this issue (it seems to be improved). I believe the problem is in `centery`/ `projection` and related calculations. Eternity uses float there: https://github.com/team-eternity/eternity/blob/451a67e29cf32658a5bb9d731eb7e21eb5769ff7/source/r_draw.cpp#L133 (`view.ycenter` is `float`).

**Comment by fabiangreffrath** [comment]
> Interesting that #1400 affect this issue (it seems to be improved). 

Doesn't really change much for me.

**Comment by rfomin** [comment]
> > Interesting that #1400 affect this issue (it seems to be improved).
> 
> Doesn't really change much for me.

Right, for some reason it's harder for me to catch this. For example, your save doesn't show any black lines, only after some turning.

**Comment by rfomin** [comment]
This approach doesn't work. I tested this WAD in Eternity and it too has black lines on this sprite. I think the problem is rare, so we can postpone it.

**Pull request closed without merging**
