### PR TITLE
implement -levelstat

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Wow, that was prompt, thanks!

**Comment by kraflab** [comment]
Keyboard_Doomer ran his script on a ton of stuff and didn't find any desyncs with woof 🙂

**Comment by rfomin** [comment]
Great news! I tested almost 100% of the old dsda archive but was not sure about complevel 11.

**Comment by fabiangreffrath** [comment]
This is indeed great news! Maybe even a bit surprising, though, as I know we are still missing emulation for some obscure overflows - intercepts and donut overrun come to mind, but there are others. However, these seem to be so uncommon that they don't make a difference for the average demo run. Should we add support for them once issues pop up or how do we proceed?

**Comment by rfomin** [comment]
Most of the dsda demos are recorded with PrBoom+ and its overflow emulation is disabled by default if I understand correctly. Or they tested only complevel 9, 11.

**Comment by kraflab** [comment]
Got an update from Keyboard_Doomer:

I skipped these before because of the length but some cl11 d2alls desync in woof
eviternity uv max - desyncs immediately at the start of map31
valiant 4:11:39 demo - desyncs soon after the start of map21
valiant 5:50:57 demo - desyncs immediately at the start of map14

**Comment by fabiangreffrath** [comment]
Hm, text screen timing probably?

**Pull request merged**
