### PR TITLE
different colors for different thing classes on the Automap

### LINKED ISSUE #536: Suggestion: extended automap colours
Playing back demos with iddt on is fun and it would be nice to have an option to differentiate different things like the one in crispy.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #536

### CODE REVIEW

**Comment by rfomin** [comment]
I need this patch to build it on MSVC (not relevant to this PR):
```diff
--- a/Source/m_menu.c
+++ b/Source/m_menu.c
@@ -134,8 +134,8 @@ boolean menuactive;    // The menus are up
 #define SKULLXOFF  -32
 #define LINEHEIGHT  16
 
-static const int M_Y_WARN = 29 + 19 * 8;
-static const int M_Y_PREVNEXT = 29 + 20 * 8;
+#define M_Y_WARN     (29 + 19 * 8)
+#define M_Y_PREVNEXT (29 + 20 * 8)
 
 char savegamestrings[10][SAVESTRINGSIZE];
 
```
Oterwise I've got error C2099: initializer is not a constant

**Review by rfomin — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
What's not constant about these terms?! MSVC... 👎 

Could you fix this for me, please?

**Comment by rfomin** [comment]
> What's not constant about these terms?! MSVC... -1
> 
> Could you fix this for me, please?

Done in master. MS recommends in [MSDN](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/compiler-error-c2099): "To resolve this error, compile the module as a .cpp file or simplify the expression." At this point we could compile on VC6, there is not much difference :smile:

**Comment by fabiangreffrath** [comment]
Hm, did MSVC mistake this as a float expression?

**Comment by rfomin** [comment]
I can't say exactly. Anyway, I think `#define` is more in line with the rest of m_menu.c, or are there plans to refactor the menu system?

**Comment by fabiangreffrath** [comment]
OMG, no. 😱 I just wanted to achieve more consistent look and behavior for the warning and prev/next lines. There is still a lot more to do for a *really* consistent look, though, I admit. Just fixed what I stumbled upon.

The downside with `#defines` is that they are replaced with the entire mathematic expression that they define, whereas a `static const int` is evaluated only once. But I guess modern compilers are smart enough to optimize this out of the way anyway.

**Comment by rfomin** [comment]
We could write `#define M_Y_PREVNEXT 189 // (29 + 20 * 8)`, but I think even in 1993 compilers were smart enough to optimize this :smile:

**Pull request merged**
