### PR TITLE
fit finale text to widescreen instead of inserting line breaks

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
I think this PR doesn't work correctly, test WAD: [finale.zip](https://github.com/fabiangreffrath/woof/files/15243490/finale.zip)

How about this approach:
```diff
diff --git a/src/f_finale.c b/src/f_finale.c
index 9f4cf01..e664391 100644
--- a/src/f_finale.c
+++ b/src/f_finale.c
@@ -52,9 +52,8 @@ int finalecount;
 #define NEWTEXTSPEED 0.01f // new value                         // phares
 #define NEWTEXTWAIT  1000  // new value                         // phares
 
-char*   finaletext;
-char*   finaleflat;
-static char* finaletext_rw = NULL;
+const char *finaletext;
+const char *finaleflat;
 
 void    F_StartCast (void);
 void    F_CastTicker (void);
@@ -218,14 +217,6 @@ void F_StartFinale (void)
 
   finalestage = 0;
   finalecount = 0;
-
-  // [FG] do the "char* vs. const char*" dance
-  if (finaletext_rw)
-  {
-    free(finaletext_rw);
-    finaletext_rw = NULL;
-  }
-  finaletext_rw = M_StringDuplicate(finaletext);
 }
 
 
@@ -353,35 +344,14 @@ void F_Ticker(void)
 // text can be increased, and there's still time to read what's     //   |
 // written.                                                         // phares
 
-// [FG] add line breaks for lines exceeding screenwidth
-static inline boolean F_AddLineBreak (char *c)
-{
-    while (c-- > finaletext_rw)
-    {
-	if (*c == '\n')
-	{
-	    return false;
-	}
-	else
-	if (*c == ' ')
-	{
-	    *c = '\n';
-	    return true;
-	}
-    }
-
-    return false;
-}
-
 void F_TextWrite (void)
 {
   int         w;         // killough 8/9/98: move variables below
   int         count;
-  char*       ch;
+  const char  *ch;
   int         c;
   int         cx;
   int         cy;
-  static int deltaw = -1;
   
   // [FG] if interbackdrop does not specify a valid flat, draw it as a patch instead
   if (gamemapinfo && W_CheckNumForName(finaleflat) != -1 &&
@@ -400,13 +370,8 @@ void F_TextWrite (void)
   // draw some of the text onto the screen
   cx = 10;
   cy = 10;
-  ch = finaletext_rw;
+  ch = finaletext;
 
-  if (deltaw != video.deltaw)
-  {
-    strcpy(finaletext_rw, finaletext);
-    deltaw = video.deltaw;
-  }
       
   count = (int)((finalecount - 10)/Get_TextSpeed());                 // phares
   if (count < 0)
@@ -432,13 +397,9 @@ void F_TextWrite (void)
     }
               
     w = SHORT (hu_font[c]->width);
-    if (cx+w > SCREENWIDTH + deltaw)
+    if (cx + w > video.unscaledw)
     {
-      // [FG] add line breaks for lines exceeding screenwidth
-      if (F_AddLineBreak(ch))
-        continue;
-      else
-      break;
+      continue;
     }
     // [cispy] prevent text from being drawn off-screen vertically
     if (cy + SHORT(hu_font[c]->height) > SCREENHEIGHT)
```

**Comment by fabiangreffrath** [comment]
> I think this PR doesn't work correctly

Well, it wraps text if it doesn't fit and draws it towards the right screen boundary else.

> How about this approach:

Well, if you want to get rid of text wrapping entirely, sure that's the way to go.

> +    if (cx + w > video.unscaledw)

I'm not sure if this is correct, because `V_DrawPatch(x, y, p)` already draws `p` to `x + video.deltaw`.

**Comment by rfomin** [comment]
> > I think this PR doesn't work correctly
> 
> Well, it wraps text if it doesn't fit and draws it towards the right screen boundary else.

I'm talking about this ([finale.zip](https://github.com/fabiangreffrath/woof/files/15243490/finale.zip)) :
woof0001
My patch:
woof0000

> Well, if you want to get rid of text wrapping entirely, sure that's the way to go.

PrBoom+/DSDA-Doom works like this, I think it's simpler and there are no complaints about it.

**Comment by fabiangreffrath** [comment]
> PrBoom+/DSDA-Doom works like this, I think it's simpler and there are no complaints about it.

Alright, thanks. I'm still not sure if `video.unscaledw` is the right horizontal boundary, though.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
