### PR TITLE
always flush whole lines printed to stdout

### LINKED ISSUE #1778: Overlapping music strings in console
_Tested in the [latest master artifact (Win-64)](https://github.com/fabiangreffrath/woof/actions/runs/9802804920)._

See for yourself, third-to-last line:
imagen

As you may gather, I'm using FluidSynth with a specific soundfont that seems to lack some instruments, and the MIDI seems to expect one of them, triggering the warning -- I had to run with `-verbose` for it to show up.

I'd guess that you would need the WAD and soundfont (`GM.sf2`) in question to debug this, but I'm not sure if I should share the latter, and without it, the former may be useless. Let me know what to do.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Hopefully fixes #1778

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
@MrAlaux could you check that please?

**Comment by MrAlaux** [comment]
> @MrAlaux could you check that please?

Just tried [the Win-64 artifact](https://github.com/fabiangreffrath/woof/actions/runs/9913631756), and unfortunately it doesn't help.

**Comment by rfomin** [comment]
It's only visible with -verbose, I don't think it's worth fixing.

**Comment by fabiangreffrath** [comment]
Didn't work.

**Pull request closed without merging**
