### PR TITLE
replace win_fopen.c with wrappers from Chocolate Doom

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
How about having these compatibility wrappers in their own source file, e.g. m_io.c?

**Comment by rfomin** [comment]
> How about having these compatibility wrappers in their own source file, e.g. m_io.c?

But we already have d_io.c :smile: We can move them to d_io.c (maybe rename it to m_io.c)

**Comment by fabiangreffrath** [comment]
That would fit.

**Review by fabiangreffrath — APPROVED** [review]
Looks great!

**Pull request merged**
