### PR TITLE
netgame fixes

### PR DESCRIPTION
**Pull request by rfomin**
* Fix SDL_Net shutdown.

* Remove some demos/netgame warnings from the menu. We disable all relevant options anyway, so there is nothing to warn about.

### CODE REVIEW

**Comment by JNechaevsky** [comment]
Not that I wish to annoy here, but probably [this idea](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/g_game.c#L344-L347) could be useful while taking care about multiplayer or solo-net?

**Comment by rfomin** [comment]
> Not that I wish to annoy here, but probably [this idea](https://github.com/JNechaevsky/international-doom/blob/main/src/doom/g_game.c#L344-L347) could be useful while taking care about multiplayer or solo-net?

Do you stop the game for all players when someone enters the menu? It will be annoying, I like vanilla behavior here.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by JNechaevsky** [comment]
No, of course not, it's a local input handler, not global. At least in vanilla Doom codebase. In Woof this approach doesn't seems to work as it should by placing that condition right after `cmd->consistancy = consistancy[consoleplayer][maketic%BACKUPTICS];`.

If done right, you can see it in action just by running two Woof clients like `-privateserver` and `-autojoin`.

**Comment by rfomin** [comment]
> No, of course not, it's a local input handler, not global.

Then I still like vanilla more, it indicates that the game is not stopped. 😉

**Comment by JNechaevsky** [comment]
No-o, I'm afraid you got it wrong. This will not stop the game itself, it's not a `paused`, it should fix case like this. Moving left-right happening by pressing `A` and `D` respectively. 

https://github.com/fabiangreffrath/woof/assets/21193394/3647c398-0b31-4fe8-92d2-6d700141d850

**Comment by JNechaevsky** [comment]
_Pfff-pfff-pfff!_ 😤 Well then. 🙂

**Pull request merged**
