### PR TITLE
replace SDL_Image with stb_image_write

### PR DESCRIPTION
**Pull request by rfomin**
Also first search for SDL2 libraries and if not found download them from libsdl.org. Works fine with my MSYS2 and MSVC installation.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
This is pretty cool already, thank you! But I think with miniz we can get rid of SDL_Image and zlib at once. It is used by SDL_Image as a fallback implementation if libpng is not available.

**Comment by rfomin** [comment]
Oh, miniz has a PNG writer function, I didn't know that. Alternatively, we can use libpng like Choco/Crispy.

**Comment by fabiangreffrath** [comment]
But with libpng we would still have to carry an external dependency and would not get rid of zlib either.

**Comment by rfomin** [comment]
> But with libpng we would still have to carry an external dependency and would not get rid of zlib either.

Yes but these dependencies are not as cumbersome as SDL_Image. Anyway, I like all variants. I'll try to replace stb_image_write and zlib with miniz.

**Comment by rfomin** [comment]
Doesn't work either.

**Pull request closed without merging**
