### PR TITLE
rename Smooth to Animated Health/Armor Count

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Thanks @mikeday0

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Up for discussion, but maybe not even that controversial.

**Comment by MrAlaux** [comment]
I agree with the description change, but what about the CVAR? They don't match anymore.

I think we can afford to change the CVAR even at the cost of disabling the feature for those with old configs. After all, it's a single cosmetic setting that can easily be toggled from the menu.

**Comment by rfomin** [comment]
I like the name.

> I think we can afford to change the CVAR even at the cost of disabling the feature for those with old configs. After all, it's a single cosmetic setting that can easily be toggled from the menu.

Agreed.

**Comment by MrAlaux** [comment]
> Agreed.

So, `animated_counts`?

**Comment by ceski-1** [comment]
Maybe `hud_animated_counts`?

**Comment by MrAlaux** [comment]
> Maybe `hud_animated_counts`?

Agreed, that's more specific.

**Comment by MrAlaux** [comment]
By the way, the description of the feature in `m_misc.c` (currently `"1 to enable smooth health/armor counts"`) should also be changed accordingly.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
