### PR TITLE
combine XYZ coords into a single widget, add separate FPS widget

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — COMMENTED** [review]
Hmm, player coords didn't show up in overlay mode, also FPS widget looks different:
woof0001
So, the plan is to change all the widgets gradually?

**Comment by fabiangreffrath** [comment]
Yes, I need a clear separation. "To Automap or not to Automap: That is the question!"

Automap has status bar and map title, and I need to end the mixing of widgets in order to get things straight. Automap overlay mode is thus strictly "not Automap" but with the map drawn on top.

The FPS widget is already making vertical place for the top-right widgets in distributed mode. It's a bit ugly, but nothing too critical IMHO.

**Comment by rfomin** [comment]
But what is the goal of these changes? What do you think of 5 hud modes idea from https://github.com/fabiangreffrath/woof/issues/593#issuecomment-1405273179?

**Comment by fabiangreffrath** [comment]
To gradually straighten out the HUD widgets implementation in preparation for the `WOOFHUD` lump support. This is not yet in the clean-up phase! I need to change things one by one. If I try to change all at once, it ends up in the mess that is my current `hu_hud` branch.

Honestly, I don't like the idea of 5 modes. I think we should only support free placement of the widgets on the fullscreen HUD. It's pretty clean where which widget belong in the automap - and overlay mode should be treated as non-automap with an automap on top. 😉 

Even then, nothing is lost. We can still discuss further ideas, but I need to implement these changes first to make my *initial* idea possible at all.

**Comment by rfomin** [comment]
> Honestly, I don't like the idea of 5 modes. I think we should only support free placement of the widgets on the fullscreen HUD.

Okay, I agree with that. But currently the player coords do not work in overlay and "always" mode, do we cut this functionality? (I think we can cut a lot of stuff).

**Comment by fabiangreffrath** [comment]
> Okay, I agree with that. But currently the player coords do not work in overlay and "always" mode, do we cut this functionality? (I think we can cut a lot of stuff).

Nope, that's an oversight. Thanks for finding it!

However, this is all supposed to get fixed once I factor out widget generation (per tic) and widget drawing (per frame). Then things will become *a lot* clearer!

> Edit: Ah, player coords widget work in fullscreen mode. I never use fullscreen mode 😄 So we changed how this widget works.

No, they are also supposed to work with the status bar. I fixed this.

**Comment by rfomin** [comment]
Now it works strange in fullscreen mode with crispy hud:
woof0002

I think we should introduce some sort of state machine (hud modes) or just cut most of the stuff.

**Comment by fabiangreffrath** [comment]
> Now it works strange in fullscreen mode with crispy hud:

See what a mess I am about to clean up? 😁 

> I think we should introduce some sort of state machine (hud modes) or just cut most of the stuff.

Yes, in the end `HU_Drawer()` will be one big `if then else` with the different hud modes and display only the appropriate widgets with their correct coordinates.

**Comment by fabiangreffrath** [comment]
And now that crap already collides with the next step I was going to do, i.e. not show the map title in overlay mode. It's all interconnected with each other in the most chaotic ways...

**Comment by rfomin** [comment]
So should we fix all the inconsistences or just delete `hu_stuff.c` (or at least part of it) and start from scratch?

**Comment by fabiangreffrath** [comment]
> So should we fix all the inconsistences or just delete `hu_stuff.c` (or at least part of it) and start from scratch?

LOL! You are probably right. I just realized I messed up HU_Erase() if I don't set the widget coordinates permanently. 😭

**Comment by ceski-1** [comment]
> i.e. not show the map title in overlay mode

I actually like being able to see the map #/name in overlay mode in Crispy/Prboom+/Woof and don't like that dsda-doom seems to have removed it.

**Comment by fabiangreffrath** [comment]
grafik

**Pull request closed without merging**
