### PR TITLE
remove looping sounds quirk

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — APPROVED** [review]
Tested with DBP25 and others - no clicking.

**Comment by fabiangreffrath** [comment]
🥳

**Comment by fabiangreffrath** [comment]
One little issue remains, though. Since we are not `qsort()`ing our channels anymore, the last channel is not guaranteed to have the lowest priority (highest numerical priority value) of all. I should probably go back to the original WinMBF logic and save the channel with the lowest priority in the loop looking for an empty channel.

**Comment by rfomin** [comment]
> I should probably go back to the original WinMBF logic and save the channel with the lowest priority in the loop looking for an empty channel.

Yes, I have seen this code in the git log. Not sure if this is correct, but I think we should go back to vanilla MBF if possible.

**Comment by fabiangreffrath** [comment]
MBF or WinMBF? They differ in details...

**Comment by fabiangreffrath** [comment]
> MBF or WinMBF? They differ in details...

I guess haleyjd has a point in his changes, so I'll probably use the WinMBF implementation. It's where we came from anyway.

**Comment by mikeday0** [comment]
I experience significant clicking in DBP25 in the latest master (8058a80). Going to try to build an updated version of OpenAL (currently on 1.19.1) to see if that addresses the problem.

**Comment by rfomin** [comment]
I know that OpenAL Soft is the most developed implementation right now. Also OpenAL can use SDL as output, which of course defeats the purpose. 😄

**Comment by fabiangreffrath** [comment]
Indeed, it clicks on Linux, with "OpenAL Soft". 😭

**Comment by mikeday0** [comment]
Upgrading to OpenAL version 1.23.0 fixes the clicking for me.

**Comment by rfomin** [comment]
> Upgrading to OpenAL version 1.23.0 fixes the clicking for me.

Great! Curious what the problem was, on Windows, no matter what I threw into it, I didn't hear a single click.

**Comment by fabiangreffrath** [comment]
Oh, right, debian is still on 1.19.1.

**Comment by fabiangreffrath** [comment]
Just checked, the clicking is present with libopenal-soft 1.19.1, but it's fixed with 1.21.1! :tada:

**Comment by fabiangreffrath** [comment]
Voila:
https://github.com/kcat/openal-soft/blob/9062721fa84322d794e9676974ad1a3e82913b91/ChangeLog#L311

**Pull request merged**
