### PR TITLE
do not trigger silent teleports in the SPECHITS cheat

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — APPROVED** [review]
Looks good.

**Comment by fabiangreffrath** [comment]
This should keep the player alive in Resurge.wad MAP15, right?

**Comment by rfomin** [comment]
> This should keep the player alive in Resurge.wad MAP15, right?

Yes, the player is alive.

**Comment by fabiangreffrath** [comment]
Thank you!

**Pull request merged**
