### PR TITLE
add map announcements

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
Do we need this? The user can simply press TAB to see the title on automap.

**Comment by fabiangreffrath** [comment]
Yes, right. No, nobody needs this! I was just curios how easy it would be to optionally implement this with our selective messaging system. 😁

**Comment by rfomin** [comment]
I suggest waiting for the feature request. Sure, if people like it in DSDA-Doom, we can add it.

**Comment by fabiangreffrath** [comment]
Good idea!

**Pull request closed without merging**
