### PR TITLE
add support for DSDHACKED, more checks and cosmetic changes

### LINKED ISSUE #1263: voxel-capable builds crash when using DSDHACKED
I was toying around with the latest master branch build and loaded SD21 by @MrAlaux just for fun.
Usually I autoload a map I've made to showcase/detect all sprite replacements made by a pwad.
When warping to this map, Woof crashes without any error message.

The last working build is [this](https://github.com/fabiangreffrath/woof/actions/runs/6824488296), right before voxels support was [merged](https://github.com/fabiangreffrath/woof/actions/runs/6833523760) in the master branch.

Admittedly, this could be an issue with my map - though that would not explain why older builds work just fine.
I guess that having all monsters/pickups/decorations visible right from the player1 starting position might have something to do with the crash.

Steps to reproduce:
1. download one of the affected build and unzip it to a folder
2. download [MINIWADM](https://www.doomworld.com/forum/topic/136409/) and extract MINIWAD2.WAD (I use this for testing, but the crash happens with DOOM2.WAD too)
3. download [my "showroom" map](https://github.com/fabiangreffrath/woof/files/13389689/MAP88.zip) 
5. download [SD21](https://www.doomworld.com/forum/topic/133318) Classic variant (I tested also the full-featured one and it crashes too)
6. start a command prompt session from the folder where the woof binaries are
7. launch the game `woof.com -iwad MINIWAD2.WAD -file MAP88.ZIP SD21-Classic.zip -CompLevel 21 -warp 88`

The crash might happen either as soon as the map has been loaded, or after a couple of seconds.
If the warp command line parameter is omitted, the game loads up fine but crashes after using the IDCLEV88 cheat.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1263

### CODE REVIEW

**Comment by liPillON** [comment]
build tested, I can confirm that SD21.zip now loads up fine.

when using voxels (and no other pwads) I noticed [this](https://github.com/fabiangreffrath/woof/assets/48625273/4dc333ac-2e03-4238-8aa4-99b102cebffb) rendering issue 
it happens with both widescreen on and off, always on the left side of the frame
it seems to affect voxels based on how far they are from the player: when I walk closer to them, the problem goes away

**Comment by rfomin** [comment]
> when using voxels (and no other pwads) though I noticed [this](https://github.com/fabiangreffrath/woof/assets/48625273/4dc333ac-2e03-4238-8aa4-99b102cebffb) rendering issue...

Is this a problem with this PR, or has it been like this before? Can you make a save with this issue on screen?

**Comment by rfomin** [comment]
Also, please try turning off the "high" resolution. Looks similar to the previous problem with it.

**Comment by liPillON** [comment]
> Also, please try turning off the "high" resolution. Looks similar to the previous problem with it.

It's still there: [woof0001.png](https://github.com/fabiangreffrath/woof/assets/48625273/252dc54f-6139-4dcc-9038-1d4b292e6949)



> Is this a problem with this PR, or has it been like this before? Can you make a save or demo with this issue on screen?

It's there in the latest master branch build, too. Should we move the discussion from this PR to a new issue?

**Comment by rfomin** [comment]
Okay, I can replicate it. Test wad: [2.zip](https://github.com/fabiangreffrath/woof/files/13399918/2.zip) save: [woofsav0.zip](https://github.com/fabiangreffrath/woof/files/13399921/woofsav0.zip) Looks like another integer overflow problem.

> Should we move the discussion from this PR to a new issue?

Yes, if it's difficult to fix, I'll create a new issue. Thanks for testing!

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
