### PR TITLE
move action pointers into a separate header file

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I don't know, I was somehow annoyed by these redundant `extern` action pointer function declarations in `.c`-files. Maybe motivated by @turol's vendetta against these in Chocolate Doom. 😉

**Comment by fabiangreffrath** [comment]
> LGTM! Although I like the previous policy to keep as much of the old code as possible 😉

Yes, me too, of course. That's why I'm unsure about an unnecessary and strictly cosmetic change like this.

**Comment by rfomin** [comment]
> That's why I'm unsure about an unnecessary and strictly cosmetic change like this.

I think this PR is good even with conservative approach, I have no objections.

**Comment by fabiangreffrath** [comment]
> > That's why I'm unsure about an unnecessary and strictly cosmetic change like this.
> 
> I think this PR is good even with conservative approach, I have no objections.

That's encouraging, thanks!

**Comment by turol** [comment]
The problem with `extern` in .c files is that if the function type is ever changed and the extern declaration is not you will get a problem that is pure hell to debug. With `extern` in headers the compiler will complain about mismatches.

This is especially important for these function pointers since Doom somewhat abuses them already and fixing some issues/warnings will probably require changing them.

So good call.

**Comment by fabiangreffrath** [comment]
Unfortunately, this breaks clang-15 build again. 😭

**Comment by rfomin** [comment]
> Is it warning about bad function pointer arguments?

Yes, fixed here: https://github.com/fabiangreffrath/woof/commit/f9ccf54869aa5bf3feb73438ddf18b2dcf62cf0e

**Comment by fabiangreffrath** [comment]
The warning was like 
```
warning: a function declaration without a prototype is deprecated in all versions of C and is treated as a zero-parameter prototype in C2x, conflicting with a subsequent definition [-Wdeprecated-non-prototype]
```
but it's gone now.

**Pull request merged**
