### PR TITLE
only set quicksaveslot upon successful load/save completion

### LINKED ISSUE #1083: `quickSaveSlot` can remain set to an incompatible savegame slot
_Tested in the 11.1.4 release._

I haven't quite checked the code, I just tested this in-game.

Starting from a new game, with `quickSaveSlot` set to -1, when entering the Save or Load Game menus (be it through the main menu or the dedicated function keys) `quickSaveSlot` remains set to -1. Even when saving or loading a game, the latter whether successful or not, `quickSaveSlot` still remains set to -1.

When pressing the Quick Save or Load keys, though, `quickSaveSlot` is set to -2. Then, when saving or loading a game, the latter whether successful or not, `quickSaveSlot` is set to the selected slot. I find this to be quite a nuisance if I accidentally select an incompatible savegame.

It wasn't immediately clear to me that using End Game resets `quickSaveSlot` to -1, which leads me to believe that many other users wouldn't be aware of that either, leaving them with the sole option of restarting the game altogether if they want to reset `quickSaveSlot`.

I suggest that `quickSaveSlot` is set to the selected slot _only_ if the savegame is actually loaded (i.e. if the "incompatible savegame" warning pops up, the user confirms loading of the save anyways), and in case saving can fail too, if the saving is successful. Going further with this, it could also be made so that `quickSaveSlot` is set to the last loaded (not saved!) game, whether it was a Quick Load or not.

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes #1083

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Could you please double-check @MrAlaux ?

**Comment by MrAlaux** [comment]
Yep, this solves the original issue: `quickSaveSlot` isn't set to unsuccessfully loaded games anymore.

However, merely entering the quick save/load menus still sets `quickSaveSlot` to -2. If I open either of those menus, close it then save/load a game normally, `quickSaveSlot` is set to the saved/loaded game despite not being a quick save/load.

This also doesn't cover my other suggestion (i.e. setting `quickSaveSlot` to the last successfully saved/loaded game whether quick or not), but that's not nearly as important.

All in all, this is definitely an improvement as it is currently.

**Comment by fabiangreffrath** [comment]
I'm not sure if we should change the general behavior begin the quicksave feature. People are very sensitive to changes like this.

**Comment by MrAlaux** [comment]
You're right. Feel free to merge this as is, we can always revisit it later if it's worth changing.

**Pull request merged**
