### PR TITLE
Apply brightmaps to translucent columns

### PR DESCRIPTION
**Pull request by JNechaevsky**
This should make possible to lit up pixels on translucent walls and sprites. Testing map: ~~tl_bmap.zip~~ _updated version in my comment below_ (BFG made translucent and can't be picked up via BEX, so you can take a closed look). Inspired by this [question](https://www.doomworld.com/forum/topic/112333-this-is-woof-1202-dec-13-2023/?do=findComment&comment=2746522) on DW forum. Just one remark:

- Those ... old fashioned style and code itself in R_Draw functions is a nightmare to read. 😑

### CODE REVIEW

**Comment by JNechaevsky** [comment]
Oh my, small update:
- Brightmapping of translated columns now also possible. This is how Plasmagun originally looks, but translated from green-to-red via Dehacked.
PLASA0
- Plasmagun have "Translucent" flag set, but since there is no logics for handling both translated and translucent columns, as well as no `R_DrawTranslatedTLColumn` function, it's sprite is drawn as solid.
- Updated testing map for Plasmagun sprite and non-translucent two-sided wall: [tl_bmap.zip](https://github.com/fabiangreffrath/woof/files/13697596/tl_bmap.zip)

**Review by fabiangreffrath — APPROVED** [review]
Looks good, thank you!

**Comment by JNechaevsky** [comment]
One more thing to discuss, please, before merging. It's about translated+translucent columns. 

I have checked, none of our friendly ports doesn't handle such case, even PrBoom+. DSDA handles it, probably because of Heretic support, where "translated" player (i.e. non first) is having active Shadow Sphere which making them translucent, but better ask @kraflab.

So, implementing such column is possible, an example straight from [Chocolate Heretic](https://github.com/chocolate-doom/chocolate-doom/blob/master/src/heretic/r_draw.c#L195), but the question is - do we need it? In terms of standards: probably we don't. It wasn't there for many years, and the case itself is extremely rare. In technical terms: yes, we can. But again, and expression: _"Just because we can, doesn't mean we should"..._ Until vanilla fuzz is replaced with translucency. 🤔

Aside from this, I have nothing to add, it's all seems to be done. Once we'll merge it, I'll take care about in Crispy Doom. There are no translucent walls, it's a Boom-ism, but we still have a working `MF_TRANSLUCENT` flag. 😉

**Comment by fabiangreffrath** [comment]
Hm, good question. We have colored blood, which is translated but usually not translucent, but I can well imagine people wanting to highlight certain colors in a blood splat sprite. Let's go the full mile, else we'll meet again in some years and wonder why we didn't fix it back then when we were at it anyway. 😉

**Comment by JNechaevsky** [comment]
So be it then ([screenshot](https://github.com/fabiangreffrath/woof/assets/21193394/1f0e4066-7ac4-4ada-9cb6-e733229ef7bf)). Will commit shortly, just need to wrote code in traditional Woof style, which most complicated part for me in this PR.

**Comment by fabiangreffrath** [comment]
> just need to wrote code in traditional Woof style, which most complicated part for me in this PR.

Looks quite right to me already.

**Comment by JNechaevsky** [comment]
I was meaning new `R_DrawTranslatedTLColumn()` function, but it wasn't that scary. Done in https://github.com/fabiangreffrath/woof/pull/1340/commits/c621ba482162c039ecb7d5871b53c6952b903806, Plasmagun now can be translucent + translated + bmapped (note that few red pixels on "translated" word along with red lamp are also lit).

**Comment by JNechaevsky** [comment]
Just before move on, is it okay to merge? You made your confirmation, but few minutes later I have added whole new function. It's a small thing if fact, but for me personally it's not. 🙂

And thank you for invitation, it is a honor! I gladly accept it, though still a bit scared of Woof code - it's something about two or three levels higher of my current abilities.

**Comment by fabiangreffrath** [comment]
> Just before move on, is it okay to merge? You made your confirmation, but few minutes later I have added whole new function. It's a small thing if fact, but for me personally it's not. 🙂

If we want translucent colored blood to be possible, we need this, right?

> And thank you for invitation, it is a honor! I gladly accept it, though still a bit scared of Woof code - it's something about two or three levels higher of my current abilities.

You are welcome! And don't be scared, we leave most of Killough's code untouched anyway. 😉

**Comment by JNechaevsky** [comment]
> If we want translucent colored blood to be possible, we need this, right?

Hmm, definitely need, but it also must be handled [here](https://github.com/fabiangreffrath/woof/blob/master/src/r_things.c#L423) like:
```diff
    // [FG] colored blood and gibs
    if (vis->mobjflags2 & MF2_COLOREDBLOOD)
      {
+++     if (vis->mobjflags & MF_TRANSLUCENT)
+++     {
+++     colfunc = R_DrawTranslatedTLColumn;
+++     }
+++     else
+++     {
        colfunc = R_DrawTranslatedColumn;
+++     }
        dc_translation = (byte *)red2col[vis->color];
      }
```

Because my current code is handling only color-shifted (green-to-something) cases.

**Comment by fabiangreffrath** [comment]
Ah, I see, this is getting complicated...

**Comment by JNechaevsky** [comment]
To make it properly, we have to rearrange flags handling in `R_DrawVisSprite()` a bit, me neither like two hits of `if (vis->mobjflags & MF_TRANSLUCENT)` here and there. Or did we reject transtlcol at all?

**Comment by fabiangreffrath** [comment]
Let's just fix the initial issue for now.

**Comment by fabiangreffrath** [comment]
Thank you!

**Pull request merged**
