### PR TITLE
avoid collisions between very long left/right aligned widgets

### PR DESCRIPTION
**Pull request by fabiangreffrath**
@MrAlaux does this fix the issue you mentioned in #1067 ?

### CODE REVIEW

**Comment by MrAlaux** [comment]
Tested with the [x64 autobuild](https://github.com/fabiangreffrath/woof/actions/runs/5042941797), not everything seems right.

The Chat text (i.e. what you're typing) doesn't affect the widget on the other side of the screen, so it can still overlap with it.

Also, I noticed weird behavior with multi-line messages: if there's at least one "very long" message in the list, widgets aligned top right are drawn on the row below said message, even if the message is actually drawn below the row of the affected widget. See for yourself:
woof0000

**Comment by fabiangreffrath** [comment]
Alright, this isn't going to work. Thanks for testing anyway! Next iteration to follow...

**Comment by fabiangreffrath** [comment]
@MrAlaux the latest commit should also fix the bug with the oddly colored cursor.

**Comment by MrAlaux** [comment]
Alright! That solves the Chat issues. We'd just be missing a fix for very wide widgets:
woof0000

**Comment by fabiangreffrath** [comment]
This is killing me. 😭 

I am considering an `align_topleft_exclusive` mode for the chat and message widgets, which will *always* reserve a whole line for them. This means, though, that a multi-line message widget would push down all widgets on the right by four lines. Probably still better than before, though. 🤔

**Comment by MrAlaux** [comment]
> I am considering an `align_topleft_exclusive` mode for the chat and message widgets, which will _always_ reserve a whole line for them. This means, though, that a multi-line message widget would push down all widgets on the right by four lines. Probably still better than before, though.

I guess that would work, yes, but I hope that by "always reserve a whole line" you mean just when the widget is visible.

**Comment by fabiangreffrath** [comment]
> I guess that would work, yes, but I hope that by "always reserve a whole line" you mean just when the widget is visible.

Yes, of course. 😉 I have just pushed the commit.

**Comment by MrAlaux** [comment]
Looks good to me, I think we can call it a day.

**Comment by fabiangreffrath** [comment]
Thank you!

**Pull request merged**
