### PR TITLE
fix "monsters can see through walls" from ZDoom

### PR DESCRIPTION
**Pull request by rfomin**
Taken from https://www.doomworld.com/forum/topic/48276-is-it-possible-to-heretic-source/

I haven't found a test for it yet.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I don't think we want to touch the actual `P_PathTraverse()` function for this?

**Comment by ceski-1** [comment]
> I haven't found a test for it yet.

E1M3 is mentioned in the thread. A simple test wad should probably be created for this.

**Comment by kitchen-ace** [comment]
The E1M3 case mentioned is a shotgun guy that wakes up immediately at the start of the map with fast LOS on.

**Comment by fabiangreffrath** [comment]
I can't reproduce the E1M3 shotgun guy, but the trooper in E4M5 is quite obvious.

**Comment by kitchen-ace** [comment]
>I can't reproduce the E1M3 shotgun guy

Oops, needs `-skill 4`

**Comment by rfomin** [comment]
> The E1M3 case mentioned is a shotgun guy that wakes up immediately at the start of the map with fast LOS on. (UV only)
> 
> E4M5 also has a trooper that wakes up with fast LOS. (HMP/UV)

Thanks, fixed for me with current PR.

**Comment by fabiangreffrath** [comment]
I don't quite get it. `P_CheckSight_12()` calls its own variant of `P_PathTraverse()` called `P_SightPathTraverse()` and I can at least fix the shotgun guy on E1M3 with this fix:

```patch
--- a/src/p_maputl.c
+++ b/src/p_maputl.c
@@ -1333,12 +1333,27 @@ boolean P_SightPathTraverse(fixed_t x1, fixed_t y1, fixed_t x2, fixed_t y2)
     if (mapx == xt2 && mapy == yt2)
       break;
 
+    // xintercept and yintercept both match
+    if ((xintercept >> FRACBITS) == mapx && (yintercept >> FRACBITS) == mapy)
+    {
+      // The trace is exiting a block through its corner. Not only does the block
+      // being entered need to be checked (which will happen when this loop
+      // continues), but the other two blocks adjacent to the corner also need to
+      // be checked.
+
+      if (!P_SightBlockLinesIterator(mapx + mapxstep, mapy) ||
+          !P_SightBlockLinesIterator(mapx, mapy + mapystep))
+      {
+        return false;
+      }
+    }
+
     if ((yintercept >> FRACBITS) == mapy)
     {
       yintercept += ystep;
       mapx += mapxstep;
     }
-    else if ((xintercept >> FRACBITS) == mapx)
+    if ((xintercept >> FRACBITS) == mapx)
     {
       xintercept += xstep;
       mapy += mapystep;
```

**Comment by rfomin** [comment]
> I don't quite get it. `P_CheckSight_12()` calls its own variant of `P_PathTraverse()` called `P_SightPathTraverse()` and I can at least fix the shotgun guy on E1M3 with this fix:

Yes, this is better. I didn't notice `P_SightPathTraverse`. Interesting that this PR also fixes the bug. Perhaps we need to change both `P_PathTraverse` and `P_SightPathTraverse`?

**Comment by ceski-1** [comment]
> E4M5 also has a trooper that wakes up with fast LOS. (HMP/UV)

I believe this is just an example of blockmap-based LoS in action. It's not an example of the see through walls issue or corner bug, unless I'm mistaken.

**Comment by fabiangreffrath** [comment]
> I believe this is just an example of blockmap-based LoS in action. It's not an example of the see through walls issue or corner bug, unless I'm mistaken.

Yes, that's what I thought. The shotgun guy is literally in the same room as the player.

**Comment by rfomin** [comment]
> > Thanks, fixed for me with current PR.
> 
> E1M3 is not fixed with the latest commit.

Strangely, it works for me, although I've had a crash after rebuild.

I apply Fabian's variant here: https://github.com/fabiangreffrath/woof/pull/1558/commits/8d53a4ec1541671c226d77db475a8c6c7a49d3e1

**Review by fabiangreffrath — APPROVED** [review]
Could you add the original `[RH]` comment?

**Pull request merged**
