### PR TITLE
load sound lumps with libsndfile

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I am loving it! :clown_face: 

[dspistol.zip](https://github.com/fabiangreffrath/woof/files/10382286/dspistol.zip)

**Comment by fabiangreffrath** [comment]
@rfomin will we have to modify vcpkg again for this?

**Comment by rfomin** [comment]
> @rfomin will we have to modify vcpkg again for this?

Yes, and we have some options:
```
libsndfile[external-libs]                 Enable FLAC, Vorbis, and Opus codecs
libsndfile[mpeg]                          Enable MPEG codecs
```
Also it doesn't work for some reason: `C:\develop\woof\src\i_sndfile.c(92): error C2036: 'void *': unknown size`

**Comment by fabiangreffrath** [comment]
Ah, this is because I add a value to a `void` pointer.

**Comment by rfomin** [comment]
This is how it looks:
image
Do we need mp3/mpeg sounds?

> Ah, this is because I add a value to a `void` pointer.

Yep, this is the fix:  `memcpy(ptr, (char *)data->data + data->offset, count);`

**Comment by rfomin** [comment]
I suggest these dependencies:
```diff
diff --git a/vcpkg.json b/vcpkg.json
index a69c86e..ca79059 100644
--- a/vcpkg.json
+++ b/vcpkg.json
@@ -9,6 +9,11 @@
       "features": [ "libmodplug", "opusfile" ]
     },
     "sdl2-net",
+    {
+        "name": "libsndfile",
+        "default-features": false,
+        "features": [ "external-libs" ]
+    },
     "fluidsynth"
   ]
 }
```
I think `mpg123` and `lame` are too much 😄

**Comment by fabiangreffrath** [comment]
> Yep, this is the fix: `memcpy(ptr, (char *)data->data + data->offset, count);`

Sorry, saw your reply just a bit to late. I fixed it differently, please report back if my solution works in vcpkg.

> I think `mpg123` and `lame` are too much 😄

Yes, I fully agree. Cool that they split it up that way!

**Comment by rfomin** [comment]
> I fixed it differently, please report back if my solution works in vcpkg.

Your solution is better, works good.

**Pull request merged**
