### PR TITLE
support dedicated music for Episode 4 of Ultimate Doom

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
Thanks, but how about UMAPINFO music? (SIGIL_v1_21.wad)

**Comment by fabiangreffrath** [comment]
> Thanks, but how about UMAPINFO music? (SIGIL_v1_21.wad)

You mean via IDMUS cheat? UMAPINFO music is treated the same as MUSINFO music, i.e. the music lump names are random and are not necessarily part of the `S_music[]` array. Thus, they aren't accessible from the IDMUS cheat, which calls `S_ChangeMusic(musnum)` with musnum being an index into the `S_music[]` array.

**Review by rfomin — APPROVED** [review]
LGTM but Sigil music from IDMUS episode 5 works in GZDoom so people can check it in Woof 😉

**Comment by rfomin** [comment]
> Sigil works now, as do all the other maps. Could you check again, please?

Yes, it works well. A small inconsistency that I found in both GZDoom and this PR: start level one, IDMUS51, die and restart the level, and the music changes to E1M1. If you are using IDMUS for music other than UMAPINFO, it will not change. The problem is here: https://github.com/fabiangreffrath/woof/blob/c338701fea8a98b628a33fa45552e1990307b8bd/src/s_sound.c#L812
Not sure if this is worth fixing.

**Review by rfomin — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
I think this is because we use `idmusnum` to track the index in the `S_music[]` array of the music selected by the IDMUS cheat and we cannot track the mere music lump number the same way - because MUSINFO/UMAPINFO allow music tracks outside the `S_music[]` array.

**Pull request merged**
