### PR TITLE
add 200 dummy sounds for DEHEXTRA

### PR DESCRIPTION
**Pull request by rfomin**
Fixes this issue: [[doomworld]](https://www.doomworld.com/forum/topic/112333-this-is-woof-600-june-25-2021-updated-winmbf/?do=findComment&comment=2340160)

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Does this work with HacX as IWAD?

**Comment by rfomin** [comment]
I don't know, I will check. But this code is from Eternity/PrBoom+/Doom Retro

**Comment by fabiangreffrath** [comment]
I am asking because of this: https://github.com/coelckers/prboom-plus/commit/752ab855d66032f951a744988a9f98fbc45c5009

**Comment by rfomin** [comment]
But Hacx still doesn't work as IWAD.

**Comment by fabiangreffrath** [comment]
> But Hacx still doesn't work as IWAD,

Yep, I know, but that's a different issue. I once wrote a patch for it:
https://salsa.debian.org/fabian/winmbf/-/blob/master/debian/patches/feature-hacx.patch

**Comment by rfomin** [comment]
I also tested Rekkr as IWAD, it fails in CheckIWAD function. Not sure if all these IWADs should be added. But you right, it's another issue.

**Comment by fabiangreffrath** [comment]
Does Rekkr fail because it has a PWAD header?

**Comment by rfomin** [comment]
> Does Rekkr fail because it has a PWAD header?

Yes, I remove this check and it works:
https://github.com/fabiangreffrath/woof/blob/e51a57ebe5c11bbf69d5cb2f3220d0b72575165f/Source/d_main.c#L744-L745

**Comment by fabiangreffrath** [comment]
> Yes, I remove this check and it works:
> https://github.com/fabiangreffrath/woof/blob/e51a57ebe5c11bbf69d5cb2f3220d0b72575165f/Source/d_main.c#L744-L745

This should probably get turned into a mere warning. If a usual PWAD is used as IWAD, the engine will crash sooner or later anyway.

**Pull request merged**
