### PR TITLE
restore original fix for "garbage lines at the top of weapon sprites"

### PR DESCRIPTION
**Pull request by rfomin**
This reverts commit 6cccb751849b83d0f5e12b9c85f139f085d62db1.

People on DW don't seem to like it (amazing how they notice the tiniest things).

### CODE REVIEW

**Comment by MrAlaux** [comment]
Would it be possible to just apply the fix selectively, only in resolutions where it does matter (probably powers of two)? If reverting this brings back the black outline, I wouldn't be surprised if someone complains about it eventually.

**Comment by fabiangreffrath** [comment]
How about my original fix (from prboom+) which doesn't  *unconditionally* add that ominous `+1`, but only if `pspritescale` and its inverse don't multiply to `FRACUNIT`?

**Comment by rfomin** [comment]
> How about my original fix (from prboom+) which doesn't _unconditionally_ add that ominous `+1`, but only if `pspritescale` and its inverse don't multiply to `FRACUNIT`?

Sure, if the weapon doesn't "wobble".

**Comment by rfomin** [comment]
I tried this and the weapon sprite seem to "wobble" when the player stops. I think this fix is not worth it.

```diff
diff --git a/src/r_main.c b/src/r_main.c
index 4426c8a..b6268cf 100644
--- a/src/r_main.c
+++ b/src/r_main.c
@@ -587,6 +587,11 @@ void R_ExecuteSetViewSize (void)
   // psprite scales
   pspritescale = FixedDiv(viewwidth_nonwide, SCREENWIDTH);       // killough 11/98
   pspriteiscale = FixedDiv(SCREENWIDTH, viewwidth_nonwide);      // killough 11/98
+  // [FG] make sure that the product of the weapon sprite scale factor and its
+  // reciprocal is always at least FRACUNIT to fix garbage lines at the top
+  // of weapon sprites
+  while (FixedMul(pspriteiscale, pspritescale) < FRACUNIT)
+    pspriteiscale++;
 
   skyiscale = FixedDiv(160 << FRACBITS, focallength);
 
```

**Comment by fabiangreffrath** [comment]
With my original fix and some extra debug messages:
```patch
--- a/src/r_main.c
+++ b/src/r_main.c
@@ -587,6 +587,16 @@ void R_ExecuteSetViewSize (void)
   // psprite scales
   pspritescale = FixedDiv(viewwidth_nonwide, SCREENWIDTH);       // killough 11/98
   pspriteiscale = FixedDiv(SCREENWIDTH, viewwidth_nonwide);      // killough 11/98
+  // [FG] make sure that the product of the weapon sprite scale factor
+  //      and its reciprocal is always at least FRACUNIT to
+  //      fix garbage lines at the top of weapon sprites
+  printf("%d ", video.height);
+  while (FixedMul(pspriteiscale, pspritescale) < FRACUNIT)
+  {
+    pspriteiscale++;
+    printf(".");
+  }
+  printf("\n");
 
   skyiscale = FixedDiv(160 << FRACBITS, focallength);
 
```

Original resolutions remain untouched:

```
200 
400 
450 .
500 .
550 .
600 .
650 .
700 .
750 .
800 
850 .
900 .

```

**Comment by rfomin** [comment]
> With my original fix and some extra debug messages:

> weapon sprite seem to "wobble" when the player stops.

Do you notice it? I'm not sure myself.

**Comment by fabiangreffrath** [comment]
Never noticed it myself, but I'm very insensitive to such details.

**Comment by rfomin** [comment]
> Never noticed it myself, but I'm very insensitive to such details.

Turns out I forgot to turn off dynamic resolution. I don't notice it either.

**Review by fabiangreffrath — APPROVED** [review]
Thank you!

**Pull request merged**
