### PR TITLE
allow to set gamedescription (and thus the window title) with DEHACKED

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — APPROVED** [review]
LGTM, thanks. Shouldn't we print banners in the terminal?

**Comment by fabiangreffrath** [comment]
Boom didn't print these banners to the terminal anymore. The engine didn't contain strings like "DOOM 2: Hell on Earth v%i.%i" anymore. They were replaced with the concept of STARTUPx strings in BEX.

**Comment by rfomin** [comment]
> Boom didn't print these banners to the terminal anymore. The engine didn't contain strings like "DOOM 2: Hell on Earth v%i.%i" anymore. They were replaced with the concept of STARTUPx strings in BEX.

Right, but I've never seen PWAD using STARTUPx strings. Anyway, I'm happy with the current terminal output.

**Comment by fabiangreffrath** [comment]
> Right, but I've never seen PWAD using STARTUPx strings. Anyway, I'm happy with the current terminal output.

Me too! I don't think printing an additional banner will make it any better. 

Should I add a comment and elaborate why I cannot use `snprintf()` to fill the version number into the new string?

**Comment by rfomin** [comment]
> Should I add a comment and elaborate why I cannot use `snprintf()` to fill the version number into the new string?

Yes, please. Honestly, I don't understand what's going on here.

**Comment by fabiangreffrath** [comment]
Another remark: if there is more than one such string replacement in the dehacked lump, as in aoddoom2, they will successively override each other. However, the same happens in Chocolate Doom and this is the implementation that we will be compared against.

**Comment by rfomin** [comment]
Thanks for comments.

> However, the same happens in Chocolate Doom and this is the implementation that we will be compared against.

Sure. It probably works the same way as with the original DEHACKED.EXE

There are a lot more PWADs with the `GAMEINFO` (STARTUPTITLE field) these days: https://zdoom.org/wiki/GAMEINFO

**Pull request merged**
