### PR TITLE
allow parsing of cosmetic items in the OPTIONS lump for all complevels

### LINKED ISSUE #839: Suggestion: Support multiple keys in one slot a la Crispy
WAD: Knee-Deep in Knee-Deep in ZDoom
Command-line: `woof -iwad doom2.wad -complevel vanilla -file KDiKDi_A.wad KDiKDi_B.wad`

This wad replaces the skull keys with orange, silver and green key cards and does some offset trickery so that you can display two keys in one slot on the status bar. 

Here's what it looks like on Crispy when you have the yellow key and then pick up the green:
DOOM0001
DOOM0002

Note how the yellow key moves up and to the left, and the green key gets drawn in the lower right. (If you reverse the order of pickup, the green key will initially be drawn in the center of the box and then moved down and to the right.)

Woof does not correctly support this behavior:
woof0007
woof0008

### PR DESCRIPTION
**Pull request by rfomin**
Fix #839

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Thanks for the prompt fix! 👍 

Remember when I suggested a similar concept for handling of "critical" config keys/ menu items in the past? Now we have at least three different concepts of temporarily disabling certain config flags (critical, strict, cosmetic) and at least two different meanings of the term "cosmetic" (menu sections, settable by OPTIONS lump). And while this is all technically correct, we need to be careful not to make things even more complicated.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by rfomin** [comment]
> Now we have at least three different concepts of temporarily disabling certain config flags (critical, strict, cosmetic) and at least two different meanings of the term "cosmetic" (menu sections, settable by OPTIONS lump).

Yes, this system needs refactoring. Although `m_menu.c` and `m_misc.c` are not fun to edit.

**Comment by fabiangreffrath** [comment]
> Yes, this system needs refactoring. Although `m_menu.c` and `m_misc.c` are not fun to edit.

Yes, I know! Maybe an opportunity opens up in the future to clean things up from the ground.

**Comment by rfomin** [comment]
Maybe we should make `S_STRICT`, `S_CRITICAL`, `S_BOOM`, `S_VANILLA` etc. flags and remove most of `DISABLE_ITEM` macros. But I think bugs are almost inevitable, maybe not in this release?

**Comment by fabiangreffrath** [comment]
> Maybe we should make `S_STRICT`, `S_CRITICAL`, `S_BOOM`, `S_VANILLA` etc. flags and remove most of `DISABLE_ITEM` macros. 

Yes.

> But I think bugs are almost inevitable, maybe not in this release?

And yes. 😁

**Pull request merged**
