### PR TITLE
fix level stats widget string overflow

### LINKED ISSUE #1227: Broken level stats widget in grindfest.wad multiplayer demo
The level stats widget disappears at about 2:30 in [gf32tc2218.zip](https://dsdarchive.com/files/demos/grindfest/82830/gf32tc2218.zip) demo. WAD: [grindfest.zip](https://dsdarchive.com/files/wads/doom2/4411/grindfest.zip)
Command line: `woof -file grindfest.zip gf32tc2218.zip -playdemo gf32b2218 -skipsec 2:25`

It works in Woof 11.3.0
image

Woof 12.0.0
image

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1227

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Cool, thanks! But the stats line in the demo would still get truncated.

**Comment by rfomin** [comment]
> Cool, thanks! But the stats line in the demo would still get truncated.

I increased `HU_MAXLINELENGTH` to `160`. There seems to be no side effects.

**Comment by fabiangreffrath** [comment]
Should we shorten the other buffers to their previous length? They seem very unlikely to be in danger of overflows.

**Comment by rfomin** [comment]
> Should we shorten the other buffers to their previous length? They seem very unlikely to be in danger of overflows.

The width of a small font character is 5px, and the maximum screen width in low res is 1152 / 2 = 576, right? So maybe 160 is a bit much.

Anyway, those buffers are small, I'm not sure it's worth resizing.

**Comment by fabiangreffrath** [comment]
Sounds like `120` should suffice.

**Review by fabiangreffrath — APPROVED** [review]
Thanks!

**Comment by fabiangreffrath** [comment]
> Sounds like `120` should suffice.

This was probably a bit short-sighted. The color changing sequences take up two bytes, but don't print a single char. Nevertheless, this was the longest stats line I have ever seen and it just broke the buffer bounds, so I think we are safe with 40 more bytes.

**Pull request merged**
