### PR TITLE
move General menu below Setup menu

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
But that's not all, DSDA-Doom has also removed the classic "Options" menu. You just go directly to "Setup", did you notice that? Again, no one uses the classic "Options" anymore.

But then we should improve the mouse options in "General". Maybe we should use the original graphics for the sliders (no mini thermo).

**Comment by rfomin** [comment]
> I do! I use it to change my view size, volumes and mouse sensitivities. These would have to get stuffed in to the General menu then.

I agree about volume and mouse sensitivity. And I think it would make more sense to have all relevant settings in one place/group. I also suggest using the original graphics for the thermo bars, our mini thermos often look bad due to palette changes.

There are -/+ buttons for view size. I like it, but honestly, it's been irrelevant for years.

**Comment by fabiangreffrath** [comment]
>> I agree about volume and mouse sensitivity. And I think it would make more sense to have all relevant settings in one place/group. 

Right! We already have a "Sound & Music" section -> move volumes there. We already have "Mouse Settings" -> move sensitivities there.

> original graphics for the thermo bars, our mini thermos often look bad due to palette changes.

Fine with me. What was the reason again why we introduced them in the first place?

> There are -/+ buttons for view size. I like it, but honestly, it's been irrelevant for years.

Yes, I agree that keyboard shortcuts might be sufficient. On the other hand, we already have a "Video" and a "Display" menu. I mostly change it, though, to see if it still works after some changes. :grin:

**Comment by rfomin** [comment]
> > original graphics for the thermo bars, our mini thermos often look bad due to palette changes.
> 
> Fine with me. What was the reason again why we introduced them in the first place?

I wanted to cram more stuff on first page. And JNechaevsky kindly agreed to help 😄.

**Comment by fabiangreffrath** [comment]
Could we agree on this as an intermediate step, though?

**Pull request merged**
