### PR TITLE
fix netgame reload

### PR DESCRIPTION
**Pull request by rfomin**
I think this change is needed for #464. Sorry, I don't have much time to test right now.

### CODE REVIEW

**Comment by Ch0wW** [comment]
This PR only fixes vanilla desyncs. This doesn't seem to correct MBF/21 desyncs.

**Comment by JCDorne** [comment]
I just tested this in Single player, here are my results :

Vanilla : Revenant missiles are fixed, demos playback correctly. Even with reload.
Boom : RNG is fixed in the header with reload, but demo using the reload key desync.
Mbf : RNG is fixed in the header with reload, but demo using the reload key desync.
Mbf21 : RNG is fixed in the header with reload, but demo using the reload key desync.

**Comment by fabiangreffrath** [comment]
With "single player" do you mean the `-solo-net` parameter?

**Comment by fabiangreffrath** [comment]
G_BeginRecording() calls G_WriteOptions() which saves the rngseed to the demo file, but we reset rngseed just afterwards.

**Comment by JCDorne** [comment]
> With "single player" do you mean the -solo-net parameter?
No. "single player" means normal gameplay. I didn't tried -solo-net yet.

> G_BeginRecording() calls G_WriteOptions() which saves the rngseed to the demo file, but we reset rngseed just afterwards.
You are right, the first two demos use the same seed. Sorry about that, I was thinking of some coincidences when I tried.

**Comment by fabiangreffrath** [comment]
Guys, does it help it you swap the order of rngseed initialization and demo header writing?
```patch
--- a/Source/g_game.c
+++ b/Source/g_game.c
@@ -683,6 +683,12 @@ static void G_ReloadLevel(void)
     gameepisode = startepisode;
   }
 
+  basetic = gametic;
+  rngseed = time(NULL);
+  M_ClearRandom();
+  AM_clearMarks();
+  totalleveltimes = 0;
+
   if (demorecording)
   {
     ddt_cheating = 0;
@@ -695,12 +701,6 @@ static void G_ReloadLevel(void)
   for (i = 0; i<MAXPLAYERS; i++)
     players[i].playerstate = PST_REBORN;
 
-  basetic = gametic;
-  rngseed = time(NULL);
-  M_ClearRandom();
-  AM_clearMarks();
-  totalleveltimes = 0;
-
   G_DoLoadLevel();
 }
 
```

**Comment by JCDorne** [comment]
@fabiangreffrath If we swap the order of rngseed initialization and demo header writing, results are as follow :

- Single player vanilla/boom/mbf/mbf21 demos are fine.
- The RNG are correct in the header for boom/mbf/mbf21 if you use restart key

However, that's another story in multiplayer :

- Vanilla demos are fine.
- RNG are fine in the header for boom, mbf & mbf21.
- The first demo recorded is fine in boom, mbf & mbf21.
- Demos recorded using the restart key desync in boom, mbf & mbf21.
- When using the restart key in boom, mbf & mbf21 the demo crash with a consistency failure most of the time.

I didn't tried -solo-net yet.

**Comment by fabiangreffrath** [comment]
So, in other words, with my proposed change everything is fine for single-player demo recording?

**Comment by JCDorne** [comment]
For Single player demo recording, everything seems fine, yes.

**Comment by fabiangreffrath** [comment]
Is there a `playeringame[i]` check missing in the loop?

**Comment by fabiangreffrath** [comment]
@JCDorne Could you please check one more change for me?
```patch
--- a/Source/g_game.c
+++ b/Source/g_game.c
@@ -699,6 +699,7 @@ static void G_ReloadLevel(void)
 
   // force players to be initialized upon first level load
   for (i = 0; i<MAXPLAYERS; i++)
+   if (playeringame[i])
     players[i].playerstate = PST_REBORN;
 
   G_DoLoadLevel();
```

**Comment by JCDorne** [comment]
hmm, just checked. That addition change absolutely nothing.
All players respawn anyway if we press the restart key.

**Comment by fabiangreffrath** [comment]
Yes, but it doesn't respawn players 3 and 4 if you are only two players.

**Comment by fabiangreffrath** [comment]
Well, I have to agree this change didn't do anything.

We probably need to check for `(gametic - basetic)` instead of `gametic` in `g_game.c:G_Ticker()`?

**Comment by fabiangreffrath** [comment]
> We probably need to check for `(gametic - basetic)` instead of `gametic` in `g_game.c:G_Ticker()`?

@rfomin Any other ideas?

**Comment by rfomin** [comment]
> > We probably need to check for `(gametic - basetic)` instead of `gametic` in `g_game.c:G_Ticker()`?
> 
> @rfomin Any other ideas?

Not sure about this. I thought I was missing something in `G_ReloadLevel()`, perhaps for a test we can use `G_DeferedInitNew()` with removing `netgame = false` in the that code path.

**Comment by fabiangreffrath** [comment]
> Not sure about this. I thought I was missing something in `G_ReloadLevel()`, perhaps for a test we can use `G_DeferedInitNew()` with removing `netgame = false` in the that code path.

If that's the one thing that prevented us from using this code path in the first place, the sure, why not.

**Comment by fabiangreffrath** [comment]
Superseded by #468

**Pull request closed without merging**
