### PR TITLE
rearrange the menu for Woof 10.6

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
Wow, there are a lot of changes here. What if we just cut out a paragraph from the first page? Or move "Transparency/Percentage Transparency" to "Display Options" and move "Mouse Settings" to the "Key Bindings" menu.

**Comment by rfomin** [comment]
> Then it's probably factor 2 for the large font and factor 4 for the normal one?

Sure, but not in this PR 😉

**Comment by fabiangreffrath** [comment]
Just realized. 🤦 

Would you file another PR with your suggestions wrt menu rearrangement?

**Comment by fabiangreffrath** [comment]
Superseded by #946

**Pull request closed without merging**
