### PR TITLE
initial implementation of macOS native MIDI module

### LINKED ISSUE #1043: no native MIDI on MacOS
Greetings, jumping back and forth between Woof-from-early-2022 and latest version I noticed that SDL is no longer available as a midi_player option (on mac SDL uses the default system soundfont which I've grown quite attached to). Instead my only option is OPL, which I guess I might've installed at some point. Doesn't matter what values I feed the cfg, it'll revert to 0 and use OPL. Whereas in the earlier version I can switch between SDL / OPL.

Probably a mac thing? I'm currently running Ventura 13.3.1. Testing out the 11.0.0 win32 binaries in a VM all the usual suspects are present and function as expected, microsoft gs <--> opl <--> fluidsynth.

### PR DESCRIPTION
**Pull request by rfomin**
Taken from SDL_Mixer.

Fix #1043

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
> OpenAL is deprecated in favor of AVAudioEngine

They must be joking 😆

**Comment by rfomin** [comment]
> > OpenAL is deprecated in favor of AVAudioEngine
> 
> They must be joking 😆

It seems we need to force OpenAL Soft, I just need to figure out how.

**Comment by rfomin** [comment]
It builds, but I still don't have a way to test it properly.

@mikeday0 Could you check it out please?

**Comment by mikeday0** [comment]
Yes, I will give it a try later this evening. Are there any midis in particular I should test?

**Comment by rfomin** [comment]
> Are there any midis in particular I should test?

No, standard IWAD music will suffice. I hope it doesn't crash 😄

**Comment by mikeday0** [comment]
IWAD music appears to play and loop just fine on Monterey 12.6.3!

**Comment by rfomin** [comment]
> IWAD music appears to play and loop just fine on Monterey 12.6.3!

Wow, I didn't expect this to just work, great! Thank you.

It seems that MIDI support on macOS is much more advanced than on Windows.

**Comment by rfomin** [comment]
@mikeday0 Please check any PWAD with multi track MIDI music (e.g. [av.wad](https://www.doomworld.com/idgames/levels/doom2/megawads/av) or [gd.wad](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/gd)). I'm curious if looping will work correctly.

**Comment by mikeday0** [comment]
> @mikeday0 Please check any PWAD with multi track MIDI music (e.g. [av.wad](https://www.doomworld.com/idgames/levels/doom2/megawads/av) or [gd.wad](https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/gd)). I'm curious if looping will work correctly.

Hmm. Looping does seem to be broken with the music in av.wad. It sounds like the individual tracks in the MIDI start to get out of sync with one another as you approach the loop point. Let me see if I can get a recording.

**Comment by rfomin** [comment]
> It sounds like the individual tracks in the MIDI start to get out of sync with one another as you approach the loop point.

Maybe the AU Graph setup is wrong. I will try to copy the Odamex code: https://github.com/odamex/odamex/blob/stable/client/sdl/i_musicsystem_au.cpp

**Comment by mikeday0** [comment]
FWIW, I fixed it with this:

```diff

diff --git a/src/i_macmusic.c b/src/i_macmusic.c
index e2dfe4d..fccdbd3 100644
--- a/src/i_macmusic.c
+++ b/src/i_macmusic.c
@@ -138,6 +138,7 @@ static void I_MAC_ResumeSong(void *handle)
 static void I_MAC_PlaySong(void *handle, boolean looping)
 {
     uint32_t i, ntracks;
+    MusicTimeStamp maxtracklen = 0;
 
     if (song == NULL)
         return;
@@ -154,7 +155,6 @@ static void I_MAC_PlaySong(void *handle, boolean looping)
     {
         MusicTrack track;
         MusicTimeStamp tracklen;
-        MusicTrackLoopInfo info;
         uint32_t tracklenlen = sizeof(tracklen);
 
         MusicSequenceGetIndTrack(song->sequence, i, &track);
@@ -162,7 +162,20 @@ static void I_MAC_PlaySong(void *handle, boolean looping)
         MusicTrackGetProperty(track, kSequenceTrackProperty_TrackLength,
                               &tracklen, &tracklenlen);
 
-        info.loopDuration = tracklen;
+        if (tracklen > maxtracklen)
+        {
+            maxtracklen = tracklen;
+        }
+    }
+
+    for (i = 0; i < ntracks; i++)
+    {
+        MusicTrack track;
+        MusicTrackLoopInfo info;
+
+        MusicSequenceGetIndTrack(song->sequence, i, &track);
+
+        info.loopDuration = maxtracklen;
         info.numberOfLoops = (looping ? 0 : 1);
 
         MusicTrackSetProperty(track, kSequenceTrackProperty_LoopInfo,

```

**Comment by rfomin** [comment]
> I fixed it with this:

Looks reasonable, but I like the Odamex changes and integrated them anyway. I hope it works 😄

**Comment by mikeday0** [comment]
> > I fixed it with this:
> 
> Looks reasonable, but I like the Odamex changes and integrated them anyway. I hope it works smile

Sorry, this appears to have the same issue.

**Comment by rfomin** [comment]
> Sorry, this appears to have the same issue.

It seems we have found a bug in Odamex. SDL_Mixer has a similar `GetSequenceLength()` function, but differs in its approach to looping.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by mikeday0** [comment]
Sorry for the delay - everything looks good on my end with the latest changes. Also, I confirmed that Odamex has the same track sync looping bug.

**Comment by rfomin** [comment]
> Sorry for the delay - everything looks good on my end with the latest changes. Also, I confirmed that Odamex has the same track sync looping bug.

Thanks for testing!

**Pull request merged**
