### PR TITLE
Integration of netcode from Chocolate Doom

### PR DESCRIPTION
**Pull request by rfomin**
This is incomplete, in particular, there is no Boom/MBF options sync. I tested it on the local network, it works. With `complevel vanilla` I have successfully connected to the chocolate doom server/client.

Basically, I delete the original `d_net.c` and `i_net.c` files (containing the old Eternity networking code) and replace them with the Chocolate Doom version.

Also I add libtextscreen, love this library.

What do you think of this approach?

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
"Files changed: 109"

Erm, wait a minute... 😨

**Comment by rfomin** [comment]
> "Files changed: 109"

Most of it is libtextscreen.

**Comment by fabiangreffrath** [comment]
What do we need libtextscreen for? ENDOOM?

**Comment by rfomin** [comment]
libtextscreen is needed for multiplayer setup/luncher tool.

**Comment by rfomin** [comment]
I don't have clang installed, and I don't know how to fix this:
```
/home/travis/build/fabiangreffrath/woof/textscreen/txt_sdl.c:965:38: error: 
      format string is not a string literal [-Werror,-Wformat-nonliteral]
    result = vsnprintf(buf, buf_len, s, args);
```
gcc and msvc build works.

**Comment by fabiangreffrath** [comment]
What if you use `M_vsnprintf()` instead?

**Comment by rfomin** [comment]
Uh, I think I need to install clang to fix these format warnings.

So what do you think? Should I continue with this branch?

**Comment by fabiangreffrath** [comment]
> Uh, I think I need to install clang to fix these format warnings.

Clang is a bitch sometimes. Warnings differ even between versions, so it's sometimes hard to reproduce a warning emitted by one version of Clang with a different version.

> So what do you think? Should I continue with this branch?

Hm, I am not sure. Although the idea is tempting to join Chocolate servers, this commit changes so incredibly much code, sometimes even completely unrelated, that it's frightening me. 😨

**Comment by rfomin** [comment]
> sometimes even completely unrelated

This is due to the integration of `net_gui.c` - I rearrange a few things. The rest of the changes are hopefully related to netcode. So we can do this without libtextscreen and `net_gui.c`?

**Comment by fabiangreffrath** [comment]
Yes, this is probably are better suited first step. However, I am still afraid about e.g. the removal of `singletics` and the rearrangements of initialization calls in `D_DoomMain()` and other movement of more or less unrelated code.

**Comment by rfomin** [comment]
`singletics` is here - all the code in `d_net.c`. The rearrangements in `D_DoomMain ()` are related to timer and `net_gui.c` integration. Ok I suggest one PR is netcode only, another one - libtextsceen and `net_gui.c`.

**Pull request closed without merging**
