### PR TITLE
weapon pickup voxels spinning in place

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by MrAlaux** [comment]
I like it! Perhaps it could use some interpolation?

**Comment by fabiangreffrath** [comment]
Yes, interpolation is still missing.

**Comment by rfomin** [comment]
> Yes, interpolation is still missing.

Like this?
```diff
diff --git a/src/r_voxel.c b/src/r_voxel.c
index 6696fd8..9ffcc9d 100644
--- a/src/r_voxel.c
+++ b/src/r_voxel.c
@@ -554,7 +554,16 @@ boolean VX_ProjectVoxel (mobj_t * thing)
 			break;
 
 		case 3:
-			angle = 4 * leveltime * ANG1;
+			static int oldgametic = -1;
+			static angle_t newangle, oldangle;
+
+			if (oldgametic < gametic)
+			{
+				oldangle = newangle;
+				newangle = 4 * leveltime * ANG1;
+				oldgametic = gametic;
+			}
+			angle = R_InterpolateAngle (oldangle, newangle, fractionaltic);
 			break;
 	}
 
```

**Comment by fabiangreffrath** [comment]
> Like this?

Feel free to directly commit to the branch, please.

**Comment by MrAlaux** [comment]
Excuse me, wouldn't that be missing an `if (uncapped)`? Other code does have that condition.

**Comment by rfomin** [comment]
> Excuse me, wouldn't that be missing an `if (uncapped)`? Other code does have that condition.

Sure, I just wanted to show the approach.

**Pull request merged**
