### PR TITLE
demotest update

### PR DESCRIPTION
**Pull request by rfomin**
* Implement -levelstat support.

* Use external diff tool instead of difflib to ignore whitespace.

* Add Judgment (MBF21) demos.

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
> Use external diff tool instead of difflib to ignore whitespace.

What a shame. 🙄

**Comment by rfomin** [comment]
> > Use external diff tool instead of difflib to ignore whitespace.
> 
> What a shame. 🙄

We should fix the `-levelstat` output, I just give up on PrBoom+ formatting: https://github.com/coelckers/prboom-plus/blob/969515162c5aebea4ad7a125ee178dcad3d576ad/prboom2/src/e6y.c#L1029

**Comment by fabiangreffrath** [comment]
> We should fix the `-levelstat` output, I just give up on PrBoom+ formatting: https://github.com/coelckers/prboom-plus/blob/969515162c5aebea4ad7a125ee178dcad3d576ad/prboom2/src/e6y.c#L1029

OMG, what is this? One printf-monster to contruct the format string and then another one to build the actual string. Phew...

I am still negatively surprised that there is no `diff -w` pendant in Python's difflib, though.

**Comment by fabiangreffrath** [comment]
We could regex all repeated spaces into a single space for both inputs:
https://stackoverflow.com/a/70799971

**Comment by rfomin** [comment]
> We could regex all repeated spaces into a single space for both inputs:
> https://stackoverflow.com/a/70799971

I saw this, but decided to use an external `diff`. It's ubiquitous these days, a Windows user will get it with `git` or almost any development tool.

**Comment by fabiangreffrath** [comment]
Okay, let's go with it.

**Pull request merged**
