### PR TITLE
improve Vanilla automap color preset accuracy

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Review by rfomin — APPROVED** [review]
Thanks!

By the way, what should we do with the "smooth lines" automap feature? It doesn't work well with the ZDoom preset. We can just remove it.

**Comment by fabiangreffrath** [comment]
> By the way, what should we do with the "smooth lines" automap feature? It doesn't work well with the ZDoom preset. We can just remove it.

I think @JNechaevsky had an idea for a workaround. If this doesn't work out, we can remove smooth lines, no problem.

**Comment by fabiangreffrath** [comment]
Btw, I once had the idea to "unstretch" the automap, i.e. to squash it by factor 1.2 vertically so that it would stretch to 1:1 level geometry if rendered with aspect ratio correction. How would you like this idea?

**Comment by JNechaevsky** [comment]
I'm afraid I don't. ☹️ Spent few days and got nothing. But allow me please to explain what exactly is happening, it's not exactly related to ZDoom color scheme, there are two problems with smoothing.

**1.** Fading pixels to dark on bright background. ZDoom color scheme, presumably, is created from traditional Heretic colors. In original Heretic, common walls are fading not "from bright to dark" but in reverse, "from dark to bright". Let's take a closer look:

image

This is not an assumption, let's take a look at the [Chocolate Heretic code](https://github.com/chocolate-doom/chocolate-doom/blob/master/src/heretic/am_map.c#L148). Values `{96, 97, 98, 99, 100, 101, 102, 103}` are representing color indexes, and it's exactly from dark-to-bright in Heretic palette:

image

Our problem is - color gatherer [from COLORMAPS](https://github.com/fabiangreffrath/woof/blob/master/src/am_map.c#L660) is catching colors by from bright-to-dark logics, which is giving bad looking results on bright background, while on dark ones it's always looking fine, just like in Vanilla or Boom scheme.

image

**2.** ZDoom color sceme is supposed to have Raven's diminishing steps. Now, this lines:

image

They are bright and should go by from bright-to-darks, and they are going such way, but what's wrong then? Amount of [color steps](https://github.com/fabiangreffrath/woof/blob/master/src/am_map.c#L664C8-L665C61). If we'll replace it with Raven diminishing:
```
      int shade_index[NUMSHADES] =
      {
          REINDEX(0), REINDEX(1),  REINDEX(2),  REINDEX(3),
          REINDEX(4), REINDEX(5), REINDEX(6), REINDEX(7),
      };
```
Then such lines will look fine.

image

________

Possible workarounds or, honestly, two raw and abstract ideas:

* Have different `shade_index[NUMSHADES]` and `shade_index_inverse[NUMSHADES]`. But when we should use "inversed" then? When map background is _"brighter than..."_?
* Replace antialiased line drawer with different one? @rfomin knows better with which one exactly. 🤭
* ...Worth headache? 🤔

That's pretty much all of it. On top of that, I'm afraid I screwed up Crispy Heretic's common wall colors by replacing tablified approach with [COLORMAP one](https://github.com/fabiangreffrath/crispy-doom/blob/master/src/heretic/am_map.c#L581-L587). Diminishing steps are correct there, so this problem is applied only to normal walls in non-overlay mode. Honestly, I don't want to leave it "as is", but still can't find a way to make COLORMAP gather working in reverse logics.

**Comment by rfomin** [comment]
> Btw, I once had the idea to "unstretch" the automap, i.e. to squash it by factor 1.2 vertically so that it would stretch to 1:1 level geometry if rendered with aspect ratio correction. How would you like this idea?

I like the whole game to use one aspect ratio, but of course this could be an interesting alternative mode. I suggest using `SDL_RenderDrawLine` and drawing the automap lines on the GPU, which would be much faster. Also the automap would always be in native resolution regardless of the rest of the game, although I haven't tested this I'm not sure if it would work.

> Replace antialiased line drawer with different one? @rfomin knows better with which one exactly. 🤭

Eternity seems to have solved these problems: https://github.com/team-eternity/eternity/blob/3f830ac203002730f0997c8d05aad1b99010f551/source/am_map.cpp#L1394C4-L1394C4 There's also some interesting palette functions as well.

**Comment by rfomin** [comment]
> Also the automap would always be in native resolution regardless of the rest of the game, although I haven't tested this I'm not sure if it would work.

This doesn't seem to work since we are using `SDL_RenderSetLogicalSize`. Perhaps this will work in SDL3 or we can rewrite the i_video.c functions using OpenGL like in Rum and Raisin Doom. Then we can blit the 8 bit surface on the GPU, which saves about 1ms per frame.

**Comment by fabiangreffrath** [comment]
> I like the whole game to use one aspect ratio, but of course this could be an interesting alternative mode. 

Me too, and I have always defended this approach. However, some level geometry starts to look more plausible if seen with the same aspect ratio as in the map editor.

> Replace antialiased line drawer with different one? @rfomin knows better with which one exactly. 

Instead of always blending to "dark" using `colormaps[]`, we could use a cascade of `main_tranmap[]` to blend forground and background, similar to the approach used here:

https://github.com/fabiangreffrath/woof/blob/78c1fccebdee1ee8a072d74d062f71bea7fcb04c/src/r_draw.c#L346

**Comment by rfomin** [comment]
> > I like the whole game to use one aspect ratio, but of course this could be an interesting alternative mode.
> 
> Me too, and I have always defended this approach. However, some level geometry starts to look more plausible if seen with the same aspect ratio as in the map editor.

I haven't tried it, but probably stretching twice won't look good, especially at low resolutions. I suggest we postpone this until SDL3, which has more "logical size" stretching options. I think it will be much faster and look better if we draw lines on the GPU.

> Instead of always blending to "dark" using colormaps[], we could use a cascade of main_tranmap[] to blend forground and background

Looks interesting.

**Pull request merged**
