### PR TITLE
use include-what-you-use tool to remove/reorganize superfluous #includes

### PR DESCRIPTION
**Pull request by rfomin**
https://include-what-you-use.org/ tool is not perfect, it doesn't understand windows.h, SDL.h and differences between MinGW/gcc on Linux. I fixed it manually but it can be automated with [pragmas](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md) and [mappings](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md).

Not sure if it's worth it, our project is relatively small so there aren't many benefits.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I am all for clean and slick code! I didn't even know this toll, yet, but it seems that it prefers explicit includes for all symbols in a source file over including headers that include headers that include headers. In out case, though, it appears that this leads to more net includes in the sources files than before. Not sure if this is desirable, but if it's the most consistent state determined by static code analysis, then be it.

Does this tool have a config file and does it probably make sense to save it somwhere in our source tree? Is it possible to integrate this in our CI pipeline, so new contributions are always checked for consistent includes?

**Comment by rfomin** [comment]
> it prefers explicit includes for all symbols in a source file over including headers that include headers that include headers. In out case, though, it appears that this leads to more net includes in the sources files than before. Not sure if this is desirable, but if it's the most consistent state determined by static code analysis, then be it.

It's possible to configure "facade" header, in our case `doomstat.h` `doomdef.h` etc. In current PR I do opposite - I remove all unnecessary includes from "facade" headers.

> Does this tool have a config file and does it probably make sense to save it somwhere in our source tree? Is it possible to integrate this in our CI pipeline, so new contributions are always checked for consistent includes?

As far as I understand, all this is possible, but requires some effort. See [pragmas](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md) and [mappings](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUMappings.md).

**Comment by fabiangreffrath** [comment]
I want to avoind modifying source code for the sole reason to satisfy an external tool, so I'd like to go without "IWYU pragma". But if we can use mappings to teach the tool what we use windows.h and SDL.h for, that sounds useful.

**Comment by rfomin** [comment]
> But if we can use mappings to teach the tool what we use windows.h and SDL.h for, that sounds useful.

It seems that to really automate this, we need to write another script to create such mappings like this: https://github.com/include-what-you-use/include-what-you-use/blob/master/mapgen/iwyu-mapgen-qt.py

There is prebuild mappings for STL, Boost and Qt, but not for WIN API and SDL. I think in our case its easier to remove superfluous includes manually.

**Comment by fabiangreffrath** [comment]
What I like about this PR, though , is the "drive-by fixes", like e.g. the struct declarations in some of the textscreen headers.

**Comment by rfomin** [comment]
Okay, so what to do with `doomdef.h`, `r_main.h` and similar headers? I can write small mappings for them by hand, but we need to decide what to include in them.

And where to include standard C libraries (`stdlib.h`, `stdio.h`, etc.)? I currently include them everywhere.

**Comment by rfomin** [comment]
By the way, the `include-what-you-use` tool should be in all major Linux distributions and even in MSYS2 (I use it with MSYS2).

**Pull request closed without merging**
