### PR TITLE
do not move the menu cursor when moving the mouse

### PR DESCRIPTION
**Pull request by rfomin**
Similiar to GZDoom's "touchscreen-like" mod﻿e [[doomworld]](https://www.doomworld.com/forum/topic/125256-nugget-doom-300-updated-march-17th-24/?do=findComment&comment=2781706)

### CODE REVIEW

**Comment by rfomin** [comment]
Has anyone tried this PR? I'm interested in the feedback. I think it's better than before, but it may look a little weird.

@MrAlaux What do you think?

**Comment by MrAlaux** [comment]
I like it conceptually: the skull and highlight indicate what item would be used by the keyboard and mouse respectively.

I did come across some apparent bugs, though:

**(1)** If I move over an item with the mouse, then move away from it and rest on nothing (no item is highlighted) and click, the last-highlighted item will now have the skull on it -- pressing Enter would use said item -- but it won't be used by the mouse itself.

If you want to try it yourself (requires widescreen):

- Enter the menu
- Navigate to some item, setting the skull on it (e.g. _New Game_)
- Move over some other item with the mouse (remember which one, e.g. _Save Game_)
- Move the mouse sideways until you reach the widescreen region (i.e. outside of the original 4:3 region); menu rects aren't "hit" in that region
- Optionally, move the mouse to the top or bottom of the screen, still staying on the widescreen region and not moving over any menu items
- Click

You should observe the behavior described above this list of steps.

**(2)** If I close the menu while an item is highlighted, then re-open it, the item will remain highlighted even though the mouse cursor isn't displayed.

**Comment by rfomin** [comment]
> I did come across some apparent bugs, though:

Fixed in [13d83c3](https://github.com/fabiangreffrath/woof/pull/1651/commits/13d83c33702b19f700e614ea845ae52025ac8f1e) and [1c85771](https://github.com/fabiangreffrath/woof/pull/1651/commits/1c85771270d6a232f379d0477f28ebbbb7f5fdab). Thanks.

**Comment by rfomin** [comment]
@fabiangreffrath Should we merge this?

**Comment by fabiangreffrath** [comment]
I haven't tested it myself, yet, so I'll rely on your opinion.

**Comment by rfomin** [comment]
> I haven't tested it myself, yet, so I'll rely on your opinion.

Then I'll wait. The menu controls have become more convenient (accidental mouse movements don't affect the keyboard menu controls), but now it doesn't look so obvious.

**Pull request merged**
