### PR TITLE
apply a 5ms fade in/out envelope to each sound

### PR DESCRIPTION
**Pull request by fabiangreffrath**
I hope I got all the byte->short and mono->stereo calculations right. 😁

### CODE REVIEW

**Comment by rfomin** [comment]
Does not help in DBP25 case. How to check: quickly turn around in the starting room of MAP01 or just hold down the key on any thermo bar.
I think we need to add a little fade in/fade out when the volume or sample changes abruptly.

**Comment by ak-988** [comment]
Yep, noticed the same thing in DBP25. That one still happens even with my "broken" Woof version with apparently no interrupting sounds.

**Comment by fabiangreffrath** [comment]
Please try again! I accidently used unsigned calculations.

**Comment by rfomin** [comment]
> Please try again! I accidently used unsigned calculations.

No change for me.

**Comment by ak-988** [comment]
No luck, sadly. I'd say it's about as clicky as before, I tried changing it to 100ms and it still clicked. This discussion was sort of buried in my post, not sure if you saw or if it's anything relevant, from their example video it seems like a very similar problem:

https://github.com/kcat/openal-soft/issues/273

**Comment by ak-988** [comment]
Just googling around I found this discussion about loading sound data a certain way, not sure if it applies here/to SDL:

https://gamedev.stackexchange.com/questions/71571/how-do-i-prevent-clicking-at-the-end-of-each-sound-play-in-openal

A possible SDL issue with resampling chunks of data and losing some of it?:

https://github.com/libsdl-org/SDL/issues/7358

**Comment by rfomin** [comment]
I tried to experiment with [Mix_FadeInChannel](https://wiki.libsdl.org/SDL2_mixer/Mix_FadeInChannel) etc functions:
<details>
  <summary>diff</summary>

```diff
diff --git a/src/i_sound.c b/src/i_sound.c
index 02bb5b5..a6cef06 100644
--- a/src/i_sound.c
+++ b/src/i_sound.c
@@ -92,6 +92,8 @@ channel_info_t channelinfo[MAX_CHANNELS];
 // Pitch to stepping lookup, unused.
 float steptable[256];
 
+#define FADETIME 20
+
 //
 // StopChannel
 //
@@ -100,8 +102,6 @@ float steptable[256];
 //
 static void StopChannel(int channel)
 {
-  int cnum;
-
 #ifdef RANGECHECK
   // haleyjd 02/18/05: bounds checking
   if (channel < 0 || channel >= MAX_CHANNELS)
@@ -110,28 +110,33 @@ static void StopChannel(int channel)
 
   if (channelinfo[channel].data)
   {
-    Mix_HaltChannel(channel);
+    Mix_FadeOutChannel(channel, FADETIME);
+  }
+}
 
-    // [FG] immediately free samples not connected to a sound SFX
-    if (channelinfo[channel].sfx == NULL)
-    {
-      free(channelinfo[channel].data);
-    }
-    channelinfo[channel].data = NULL;
+void SDLCALL I_HaltChannel(int channel)
+{
+  // [FG] immediately free samples not connected to a sound SFX
+  if (channelinfo[channel].sfx == NULL)
+  {
+    free(channelinfo[channel].data);
+  }
+  channelinfo[channel].data = NULL;
 
-    if (channelinfo[channel].sfx)
+  if (channelinfo[channel].sfx)
+  {
+    int cnum;
+
+    // haleyjd 06/03/06: see if we can free the sound
+    for (cnum = 0; cnum < MAX_CHANNELS; cnum++)
     {
-      // haleyjd 06/03/06: see if we can free the sound
-      for (cnum = 0; cnum < MAX_CHANNELS; cnum++)
-      {
-        if (cnum == channel)
-          continue;
+      if (cnum == channel)
+        continue;
 
-        if (channelinfo[cnum].sfx &&
-            channelinfo[cnum].sfx->data == channelinfo[channel].sfx->data)
-        {
-          return; // still being used by some channel
-        }
+      if (channelinfo[cnum].sfx &&
+          channelinfo[cnum].sfx->data == channelinfo[channel].sfx->data)
+      {
+        return; // still being used by some channel
       }
     }
   }
@@ -352,7 +357,7 @@ static boolean CacheSound(sfxinfo_t *sfx, int channel, int pitch)
     sfx->data = cvt.buf;
     sfx->alen = cvt.len_cvt;
 
-    Envelope(sfx);
+    //Envelope(sfx);
   }
 
   // don't need original lump data any more
@@ -538,8 +543,8 @@ int I_StartSound(sfxinfo_t *sound, int vol, int sep, int pitch, boolean loop)
   if (CacheSound(sound, channel, pitch))
   {
     channelinfo[channel].idnum = id++; // give the sound a unique id
-    Mix_PlayChannelTimed(channel, &channelinfo[channel].chunk, loop ? -1 : 0, -1);
     I_UpdateSoundParams(channel, vol, sep);
+    Mix_FadeInChannel(channel, &channelinfo[channel].chunk, loop ? -1 : 0, FADETIME);
   }
   else
     channel = -1;
@@ -723,6 +728,8 @@ void I_InitSound(void)
     // [FG] let SDL_Mixer do the actual sound mixing
     Mix_AllocateChannels(MAX_CHANNELS);
 
+    Mix_ChannelFinished(I_HaltChannel);
+
     I_AtExit(I_ShutdownSound, true);
 
     snd_init = true;
```
</details>

This still does not help in the case of DBP25. I'm assuming the problem is with the DSSTNMOV sound itself (from DBP25.wad).

**Comment by ak-988** [comment]
I deleted the bottom third of DBP25's DSSTNMOV spectrogram (using Izotope RX 10) and it does get rid of the crackling. Deleting the top third did not affect it. It sounds a lot different; I'm not really sure if I've removed a bad low frequency or if cutting the bottom out dropped something down from too high up, if that makes any sense. Times like this I wish I knew what I was doing. I've attached a WAD with the new butchered sound if you're curious.

When I talked to John Novak from DOSBox Staging he mentioned a 20hz high pass filter to fix DC offset problems like popping:

    // Initialise master high-pass filter
    // ----------------------------------
    // The purpose of this filter is two-fold:
    //
    // - Remove any DC offset from the summed master output (any high-pass
    //   filter can achieve this, even a 6dB/oct HPF at 1Hz). Virtually all
    //   synth modules (CMS, OPL, etc.) can introduce DC offset; this
    //   usually isn't a problem on real hardware as most audio interfaces
    //   include a DC-blocking or high-pass filter in the analog output
    //   stages.
    //
    // - Get rid of (or more precisely, attenuate) unnecessary rumble below
    //   20Hz that serves no musical purpose and only eats up headroom.
    //   Issues like this could have gone unnoticed in the 80s/90s due to
    //   much lower quality consumer audio equipment available, plus
    //   most sound cards had weak bass response (on some models the bass
    //   rolloff starts from as high as 100-120Hz), so the presence of
    //   unnecessary ultra low-frequency content never became an issue back
    //   then.
    //
    // Thanks to the float mixbuffer, it is sufficient to peform the
    // high-pass filtering only once at the very end of the processing
    // chain, instead of doing it on every single mixer channel.

But I tried the 20hz Butterworth high pass filter in my Windows equalizer and it didn't do anything.

[crusher.zip](https://github.com/fabiangreffrath/woof/files/10890976/crusher.zip)

**Comment by ak-988** [comment]
"Some games though, beg for an even strong hand, for example: Prehistorik 2. This sucker shovels 17 bytes of initial junk into the Sound Blaster and then plays its heavily DC-offset audio samples.

The large size of its initial transfer evades SB-supression, and the samples whipsaw, which even with the enveloping, still produce an audible pop. The fix for this unruly game is 15ms of envelope duration and a 0% peak, which effectively mutes the garbage at the start. After this, the envelope disappears and the game is free to play its dc-offset samples :-)"

https://github.com/dosbox-staging/dosbox-staging/pull/442

**Comment by rfomin** [comment]
I tested the original DOS MBF (which uses Allegro) with DBP25 in DosBox-staging and it still clicks (menu volume bar).

**Comment by ak-988** [comment]
So far the only effective thing for the volume sliders is breaking sound interruptions. It also "fixes" chaingunners and other fast repeated sounds. Since that makes crushers interrupt themselves and click it's hard to test the spinning around case. I just can't figure out why removing the lowest frequencies from DBP DSSTNMOV makes spinning around OK, and the untouched sound only sounds bad when you spin.

**Comment by fabiangreffrath** [comment]
When you spin stereo panning is applied:
https://github.com/fabiangreffrath/woof/blob/f49693b204030f2a8ee76c5ff4c1721b90a4a03c/src/i_sound.c#L410

So, if the result of this research is that clicking occurs whenever SDL_Mixer touches the sound, e.g. by either stopping it from playing or by recalculating its stereo panning, then we are fighting windmills here.

**Comment by rfomin** [comment]
> So, if the result of this research is that clicking occurs whenever SDL_Mixer touches the sound, e.g. by either stopping it from playing or by recalculating its stereo panning, then we are fighting windmills here.

Yes, that's right. Maybe we can pre-process the sounds to somehow avoid peaks.

**Comment by ak-988** [comment]
https://github.com/libsdl-org/SDL_mixer/issues/106

Is this issue maybe relevant?

**Comment by ak-988** [comment]
I can't think of much else to try, thanks very much for giving it a shot and testing though. 

For what it's worth there's some more good discussion about basic causes of these issues (torridgristle is right I think) and then some recommendation from an OpenAL person:

https://forum.zdoom.org/viewtopic.php?f=3&t=55212

Later on more discussion
https://forum.zdoom.org/viewtopic.php?t=71069  

OpenAL thing
https://mantis.zdoom.org/view.php?id=232

**Comment by rfomin** [comment]
@ak-988 thanks for the feedback and interesting links. I'm not an audio mixing expert, but openal-soft seems to be a lot more sophisticated than SDL_Mixer and it seems reasonable to use it instead of trying to fix clipping myself. I'll try when I have time.

**Comment by mikeday0** [comment]
Has anyone ever experimented with using `Mix_FadeOutChannel()` instead of `Mix_HaltChannel()` to stop sounds?

https://github.com/libsdl-org/SDL_mixer/blob/1a2a58174b47e718b324aa3cd246e916308e9d09/include/SDL3/SDL_mixer.h#L2184-L2208

**Comment by rfomin** [comment]
> Has anyone ever experimented with using `Mix_FadeOutChannel()` instead of `Mix_HaltChannel()` to stop sounds?

I tried it here: https://github.com/fabiangreffrath/woof/pull/925#issuecomment-1454996035 Doesn't work for me.

**Comment by mikeday0** [comment]
> > Has anyone ever experimented with using `Mix_FadeOutChannel()` instead of `Mix_HaltChannel()` to stop sounds?
> 
> I tried it here: [#925 (comment)](https://github.com/fabiangreffrath/woof/pull/925#issuecomment-1454996035) Doesn't work for me.

Understood, sorry that I overlooked that.

To handle the pops during panning changes, you could create a custom panning function that waits for the waveform to be near a zero-crossing before applying the updated panning values. You would register the custom panning function as an effect using `Mix_RegisterEffect()`. Woof would have to keep track of all the panning values for each sound channel.

For pops associated with halting sounds, I feel like `Mix_FadeOutChannel()` should have done the trick.

**Comment by rfomin** [comment]
> To handle the pops during panning changes, you could create a custom panning function that waits for the waveform to be near a zero-crossing before applying the updated panning values. You would register the custom panning function as an effect using `Mix_RegisterEffect()`. Woof would have to keep track of all the panning values for each sound channel.

It may be easier to use openal-soft which solves this problem. It doesn't have a `Mix_SetPanning()` equivalent, but it can be emulated like this:
```c
// create a panning effect by moving the source in an arc around the listener
alSourcef(source, AL_ROLLOFF_FACTOR, 0.0f);
alSourcei(source, AL_SOURCE_RELATIVE, TRUE);
alSource3f(source, AL_POSITION, {pan, 0, -sqrtf(1.0f - pan*pan)});
```
> For pops associated with halting sounds, I feel like `Mix_FadeOutChannel()` should have done the trick.

It still clicks if using menu thermo bar in DBP25.wad

**Comment by mikeday0** [comment]
> It still clicks if using menu thermo bar in DBP25.wad

Yeah, looking at the SDL_Mixer source it seems for fading out it only changes the volume once a slice. So if the requested fadeout time is less than the slice time, it's pretty much the same as calling `Mix_HaltChannel()`, just delayed once slice period.

**Comment by fabiangreffrath** [comment]
> It may be easier to use openal-soft which solves this problem. It doesn't have a `Mix_SetPanning()` equivalent, but it can be emulated like this:

Why do you have to teach an advanced audio engine like openal something as basic as stereo separation? Doesn't it support spatial audio natively and stereo separation is just a result of the relative positioning of sound source and listener?

**Comment by rfomin** [comment]
> Doesn't it support spatial audio natively and stereo separation is just a result of the relative positioning of sound source and listener?

Yes it does. The code snippet is exactly that, it sets the relative position of the sound source and the listener. I shouldn't have used the word "emulate".

**Comment by fabiangreffrath** [comment]
Well have to try something different.

**Pull request closed without merging**
