### PR TITLE
add transparent ghost monsters from Crispy Doom

### LINKED ISSUE #291: (Suggestion) Transparent ghost monsters
I've seen a couple of source ports do this and I think it's not only a neat feature but could serve as a utility for some maps. On -complevel 2, it would be cool if ghost monsters produced by resurrecting crushed corpses could be transparent like fireballs or plasma shots in Boom. It wouldn't break demo compatibility since it is merely a visual effect, and could makes some megawads that utilize it a little more manageable (I'm looking at _you_, Hell Revealed MAP26).

### PR DESCRIPTION
**Pull request by rfomin**
Fixes #291

### CODE REVIEW

**Comment by kraflab** [comment]
A strict mode would be great 🙏 

@srludicolo There are speedrunners who prefer a more conservative / classic feeling port, and woof is probably going to replace crispy for many of those players, since it has added a lot of key features and has support for cl9+.

**Comment by srludicolo** [comment]
Ah, I totally get that. Tbh, I don't think I've touched Crispy for anything besides 90s megawads since I went down the Woof rabbit hole. GZDoom is now a distant memory. Unrelated, but has anyone had the experience of starting with GZDoom, and gradually becoming more conservative with their taste in source ports? I sure have.

**Comment by rfomin** [comment]
I think we should implement `-strict` mode. For that, I want to refactor compatibility options, because it's a mess now. I think after netgame PR merge because it's related to options too.

**Comment by fabiangreffrath** [comment]
> I like this idea too. The option for it in the "Enemies" menu looks very specific - it works only when `comp[comp_vile]` is on. Maybe we make it config only? doom00


I actually like the "Consmetic" subsection in this screenshot. Would you mind actually implementing it - along with the switch for the transparent ghost monsters?

**Comment by kraflab** [comment]
Yes, weapon attack alignment is something blocked by strict mode.
```
dboolean dsda_WeaponAttackAlignment(void) {
  return weapon_attack_alignment && !hexen && !dsda_StrictMode();
}
```

**Pull request merged**
