### PR TITLE
apply scalefactor from command line only once during initialization

### PR DESCRIPTION
**Pull request by fabiangreffrath**
On subsequent calls of I_InitGraphicsMode(), e.g. when changing hires
or widescreen in-game, determine (coarse, integer) scalefactor from
current ratio of window and framebuffer size. Resize window only if
new size is going to be wider than previous size. Force resizing of
window if scalefactor was set on command line.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I'd like to move other parts of the code which are really only relevant for at-start initialization into the `if (firsttime)` block, e.g. the checks for the `grabmouse` and `fullscreen` command line parameters, which should strictly not get reset when the video mode is changed in-game.

Also, I'd like to get rid of the `usehires`, `in_hires` and `in_page_flip` variables, which seem redundant and don't make any sense to me.

**Comment by rfomin** [comment]
If you run Woof the first time without config it didn't resize the window if the user turns on the widescreen mode. I hope this makes sense :smile:

**Comment by fabiangreffrath** [comment]
Hm, but why? If run without config, window size will default to 640x480, so scalefactor will be 1 and `1* v_w > window_width` will be `true` so the window should get resized. Or not?

**Comment by rfomin** [comment]
I've got this:
doom03
Its worked fine with old logic.

**Comment by fabiangreffrath** [comment]
>  Its worked fine with old logic.

Only if you didn't resize the window (i.e. make it more than twisce as large) between first start and switch to widescreen.

**Comment by fabiangreffrath** [comment]
We strictly need to get `scalefactor` out of this equation. It is really only needed to reset the game window to an integer multiple of the framebuffer once at start-up.

**Comment by fabiangreffrath** [comment]
Alright, it works fine now if you keep the window size close to the original dimensions. But if you do what I often like to do, i.e. Win+Left to have the game window cover the entire left half of the screen with the game content centered, and then switch from regular to widescreen, you'll get a giant window covering your entire screen. Not sure how to prevent that, though.

**Comment by fabiangreffrath** [comment]
I could prevent automatic window resizing if the game window's w/h ratio did not match the framebuffer's w/h ratio by a certain margin before.

**Comment by rfomin** [comment]
> But if you do what I often like to do, i.e. Win+Left to have the game window cover the entire left half of the screen with the game content centered, and then switch from regular to widescreen, you'll get a giant window covering your entire screen. Not sure how to prevent that, though.

I don't use Win + Left, this version works well for me.

**Review by rfomin — COMMENTED** [review]
It works fine for me.

> Also, I'd like to get rid of the usehires, in_hires and in_page_flip variables, which seem redundant and don't make any sense to me.

This will not be in this PR?

**Comment by fabiangreffrath** [comment]
> This will not be in this PR?

Nope, that's unrelated and mostly cosmetic.

**Review by rfomin — APPROVED** [review]

**Pull request merged**
