### PR TITLE
stretch short skies

### PR DESCRIPTION
**Pull request by fabiangreffrath**
While at it, remove the "Files Preloaded at Game Startup" section
from the General menu. More menu clean-up will be due with the follow-up
commits, though.

Unfortunately, I couldn't simplify the code path in do_draw_plane() any
further, because there are maps like Ancient Aliens MAP11 which have
a short F_SKY1 texture but tall PL_SKYFLAT textures,
which have to be taken into account.

### CODE REVIEW

**Comment by rfomin** [comment]
For some reason tall sky don't work in Valiant map25 (both Woof and PrBoom+):
doom01
Works in Eternity:
etrn01

**Comment by fabiangreffrath** [comment]
> Works in Eternity:

This is how it looks for me with "stretch short skies" enabled.

**Comment by fabiangreffrath** [comment]
Apparently SKY3 is 128px tall and needs stretching for mouselook.

**Comment by rfomin** [comment]
> > Works in Eternity:
> 
> This is how it looks for me with "stretch short skies" enabled.

Are you sure? I double checked, for me it's always like in first screenshot.

**Comment by fabiangreffrath** [comment]
grafik

**Comment by fabiangreffrath** [comment]
Interestingly, it also works as intended in PrBoom+ for me.

this is my version of Valiant:
```
$ ll ~/Downloads/valiant/valiant.*
-rw-r--r-- 1 fabian fabian    12479 16. Apr 2015  /home/fabian/Downloads/valiant/valiant.txt
-rw-r--r-- 1 fabian fabian 97396545 17. Apr 2015  /home/fabian/Downloads/valiant/valiant.wad
```

**Comment by rfomin** [comment]
Eternity doen't stretch SKY3 somehow, and it's tall:
etrn00
Not sure what's going on here. https://github.com/team-eternity/eternity/blob/79f2cbe2e64383b49c7e0f946777cedd3b320355/source/r_sky.cpp#L164-L167
Anyway, it's a little thing. Other skies are working fine so far.

**Review by rfomin — APPROVED** [review]

**Comment by rfomin** [comment]
My version of Valiant.wad changed on 16 ‎may ‎2015 ‏‎9:42:30

**Comment by fabiangreffrath** [comment]
I re-downloaded and now got the same version as you. Still no tall sky, though (Deutex output):
```
$ grep ^SKY3 -A1 textures/texture1.txt 
SKY3        		1024	128
*	MOON_SKY    	0	0

$ file patches/moon_sky.png 
patches/moon_sky.png: PNG image data, 1024 x 128, 8-bit colormap, non-interlaced
```

**Comment by rfomin** [comment]
I think Eternity show SAWSKY22 lump. (1024x480) I don't know yet how it works.

**Comment by fabiangreffrath** [comment]
Maybe that's the reason:
```
$ grep MAP25 -A7 lumps/emapinfo.lmp
[MAP25]
	levelname = MAP25: The Eagle Has Landed
	creator = skillsaw
	skyname = SAWSKYMN
	music = ADRIAN
	levelpic = CWILV24
	nextlevel = MAP26
	partime = 270
	killfinale = true

$ grep ^SAWSKYMN -A1 textures/texture1.txt 
SAWSKYMN    		1024	240
*	SAWSKYMN    	0	0

$ file patches/sawskymn.png 
patches/sawskymn.png: PNG image data, 1024 x 240, 8-bit colormap, non-interlaced
```

**Comment by fabiangreffrath** [comment]
Is there a command line switch for Eternity to skip `*MAPINFO` lump parsing?

**Comment by rfomin** [comment]
> Is there a command line switch for Eternity to skip `*MAPINFO` lump parsing?

Don't know about the command line switch, but I just removed the EMAPINFO lump and yes, the sky got short.

**Comment by rfomin** [comment]
With this patch and UMAPINFO it works corretly:
```diff
--- a/Source/r_sky.c
+++ b/Source/r_sky.c
@@ -57,6 +57,8 @@ void R_InitSkyMap (void)
   // [FG] stretch short skies
   if (stretchsky && (textureheight[skytexture]>>FRACBITS) < 200)
     skytexturemid = -28*FRACUNIT;
+  else if ((textureheight[skytexture]>>FRACBITS) >= 200)
+    skytexturemid = 200*FRACUNIT;
   else
   skytexturemid = 100*FRACUNIT;
 }
```
UMAPINFO:
```
map MAP25
{
	skytexture = "SAWSKYMN"
}
```

**Comment by fabiangreffrath** [comment]
Thanks for the patch! However, this doc states the following:
```
//        h >  200: Unstretched, but the baseline is shifted down so that the top
//                  of the texture is at the top of the screen when looking fully up.
```

https://github.com/coelckers/prboom-plus/blob/5a5233a729fa65aa2d9e03a1cddffc7e4e0eb66c/prboom2/src/r_sky.c#L88

Please note that it is *not* implemented that way in PrBoom+, because `skytexturemid = 100*FRACUNIT;` a few lines later in the  `!skystretch` case.

**Comment by fabiangreffrath** [comment]
That'd be this line, could you check?
```
  skytexturemid = (200 - skyheight) << FRACBITS;
```

**Comment by rfomin** [comment]
> That'd be this line, could you check?
> 
> ```
>   skytexturemid = (200 - skyheight) << FRACBITS;
> ```

This also works. But Eternity has a different approach: https://github.com/team-eternity/eternity/blob/85d5105207edf856d664932c428099dffb228b69/source/r_sky.cpp#L172-L181

**Comment by fabiangreffrath** [comment]
Thanks! If PrBoom+ doesn't provide a working solution, EE is probably the next best choice to follow. 😉

**Comment by rfomin** [comment]
This rule seems to be taken from ZDoom: https://zdoom.org/wiki/Sky_stretching
But maybe a simple version will suffice.

**Comment by fabiangreffrath** [comment]
We more or less follow that if you consider that `skytexturemid = 200*FRACUNIT` is exactly the same as `skytexturemid = 0` for a texture with height 200px.

**Pull request merged**
