### PR TITLE
clean up I_GetTime() and I_GetFracTime() implementations

### PR DESCRIPTION
**Pull request by fabiangreffrath**
How does this work for you @rfomin ?

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I can currently only test via remote desktop, where everything feels wanky anyway.

**Comment by rfomin** [comment]
Yes, it works well for me.

**Review by rfomin — APPROVED** [review]
LGTM.
So the problem was here `return (int)((Long64) I_GetTime_RealTime() * I_GetTime_Scale >> 24);` ? Interesting.

**Comment by fabiangreffrath** [comment]
Cool, thanks!

**Comment by fabiangreffrath** [comment]
> LGTM. So the problem was here `return (int)((Long64) I_GetTime_RealTime() * I_GetTime_Scale >> 24);` ? Interesting.

Yes, this calculation seems to be incompatible with the pragmatic `clock_rate * TICRATE / 100` approach. It seems that Lee Killough wanted to move the whole calculation into the powers-of-two regime?

**Pull request merged**
