### PR TITLE
disable missed backside emulation by default

### PR DESCRIPTION
**Pull request by fabiangreffrath**
Fixes HOM in sstruggle.wad E1M3.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Downside is that FEZ renders now just like Crispy.

**Review by rfomin — APPROVED** [review]
It seems PrBoom+ don't have this fix but render it's differently (still little glitchy). Interestingly, "missed backside" overflow emulation is disabled by default: https://github.com/coelckers/prboom-plus/blob/3d2445366f7a771d04fcd92e0f6524eadda7a669/prboom2/src/m_misc.c#L1211

**Comment by fabiangreffrath** [comment]
I think we have two different cases here that we shouldn't mix up:

- In FEZ1.wad we have lines without a second sidedef, although they strictly have part of sector 90 behind them.
- In sstruggle.wad E1M3 we have lines with no frontsector which we see only from the back side.

Now we just have to find a logic which pleases both. 😕

**Comment by fabiangreffrath** [comment]
@rfomin I hope you are well again! Do you have any other idea how to render the line in sstruggle.wad E1M3 without overriding its backsector and thus without destroying rendering of the railings in FEZ1.wad?

**Comment by rfomin** [comment]
> I hope you are well again!

Thanks, I'm fine.

> Do you have any other idea how to render the line in sstruggle.wad E1M3 without overriding its backsector and thus without destroying rendering of the railings in FEZ1.wad?

I haven't researched this yet, but PrBoom+ somehow shows this depending on the `-setmem` option and the overflow emulation setting.
`-setmem dosbox`
doom00
default:
doom01
Rendering of FEZ1.WAD also depends on `-setmem` option. I'll try to figure it out this weekend.

**Comment by rfomin** [comment]
> Yes, that's because `setmem` affects the floorheight and ceilingheight values of the fake sector returned by `GetSectorAtNullAddress()`.

I guess we should just turn off "backside overvflow" emulation setting by default to copy PrBoom+'s behavior. It seems to be what users want.

**Comment by fabiangreffrath** [comment]
> I guess we should just turn off "backside overvflow" emulation setting by default to copy PrBoom+'s behavior. It seems to be what users want.

Yes, we should just do that.

**Review by rfomin — APPROVED** [review]
LGTM

**Pull request merged**
