### PR TITLE
allow code to build with -std=gnu23 (which is the new default in gcc-15)

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
> -std=gnu23 (for C23 with GNU extensions).

C23 is only partially implemented in Clang: https://clang.llvm.org/c_status.html#c2x
I think C99 is just fine for us.

**Comment by fabiangreffrath** [comment]
Linux GCC and MSYS2 pass without changes. Good.

**Comment by rfomin** [comment]
> Linux GCC and MSYS2 pass without changes. Good.

Should we set the standard there? https://github.com/fabiangreffrath/woof/blob/3f41e8f14dcda9ac7256c9b99bd62fb3bef8ab3f/CMakeLists.txt#L18
I think otherwise CMake will force C99 anyway.

**Comment by fabiangreffrath** [comment]
Indeed, seems that it overrides the standard at this point. I misread this as an "at least" requirement.

**Comment by fabiangreffrath** [comment]
I'll try this as an experiment.

**Comment by fabiangreffrath** [comment]
> ~Linux GCC and MSYS2 pass without changes. Good.~

Now that's the kind of trouble I was expecting. 😁

**Comment by rfomin** [comment]
> Now, I consider these changes worth keeping. Is there anything we put to risk by including `<stdbool.h>` instead of defining our own `false`/`true`?

It should work, but I prefer to avoid it. It's misleading since we have our own `boolean` type with `int32_t` size.

**Comment by fabiangreffrath** [comment]
> It should work, but I prefer to avoid it. It's misleading since we have our own `boolean` type with `int32_t` size.

Right, we don't let `stdbool.h` define our `boolean` type, just `false` and `true`. We still have `typedef int boolean` a few lines later.

**Comment by rfomin** [comment]
> Right, we don't let `stdbool.h` define our `boolean` type, just `false` and `true`. We still have `typedef int boolean` a few lines later.

So why do we need `stdbool.h`? Because of https://en.cppreference.com/w/c/language/bool_constant?

**Review by rfomin — APPROVED** [review]
LGTM.

**Comment by fabiangreffrath** [comment]
> Because in newer C standards, `true` and `false` are reserved key words. You can check for them being defined, though, and we do so by checking the `__bool_true_false_are_defined` macro. But guess what, this macro is only ever defined if you include `stdbool.h` and this in turn unconditionally defines the key words.

In other words, Schroedinger's cat. You only know if the key words are defined if you make sure they are defined. 😉

**Comment by fabiangreffrath** [comment]
> LGTM.

Thanks!

**Pull request merged**
