### PR TITLE
test cross building in our CI rule

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by kraflab** [comment]
So many PRs coming in Woof! I'm gonna have to step up my game in 2022 🤠

**Comment by fabiangreffrath** [comment]
> So many PRs coming in Woof! I'm gonna have to step up my game in 2022 cowboy_hat_face

**Comment by fabiangreffrath** [comment]
PS: This was meant as an actual invitation to join our effort. Just in case my humor or movie choice appeared questionable. 😉

**Comment by fabiangreffrath** [comment]
It fails in the install rule for cross building. Any idea @rfomin ?

**Comment by rfomin** [comment]
I think we should use GET_RUNTIME_DEPENDENCIES only on MSYS2. I build this on my repository with this change: https://github.com/rfomin/woof/commit/faa1fdee8a5438dc49aab9b95a23dc06fc2f5589

**Comment by rfomin** [comment]
Alternatively, we can use GET_RUNTIME_DEPENDENCIES with [vcpkg](https://github.com/microsoft/vcpkg) for MSVC, but I think the download from libsdl.org is good enough. Should we support downloads from libsdl.org on MSYS2? It is currently working but may conflict with installed libraries. I suggest using downloads for MSVC and cross-compilation only.

**Comment by fabiangreffrath** [comment]
I have to say I like the "if it's not available I'll get it for you" approach. For example, there is an older implementation of MSYS (without the '2') which doesn't provide precompiled library packages but is strictly MSYS and MINGW. Shouldn't we rather track if packages have been downloaded and decide on this choice rather than guessing from the build environment?

**Comment by rfomin** [comment]
> Shouldn't we rather track if packages have been downloaded and decide on this choice rather than guessing from the build environment?

I think you are right, but GET_RUNTIME_DEPENDENCIES makes sense only in MSYS2 environment (and possibly vcpkg).

**Comment by fabiangreffrath** [comment]
Something like this (untested naive patch)?
```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 88fd6c5d..bbca7572 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -56,6 +56,7 @@ check_symbol_exists(strsignal "string.h" HAVE_STRSIGNAL)
 #
 # In some instances, we can do useful things if a library can't be found.
 
+set(SDL_DOWNLOADED FALSE)
 # SDL2.  On Windows, we use the official development library.
 find_package(SDL2 2.0.7)
 if(NOT SDL2_FOUND)
@@ -80,12 +81,12 @@ if(NOT SDL2_FOUND)
         endif()
         set(SDL2_DIR "${CMAKE_CURRENT_BINARY_DIR}/SDL2-2.0.18")
         find_package(SDL2)
+        set(SDL_DOWNLOADED TRUE)
     endif()
 endif()
 
 # SDL2_mixer.  On Windows, we use the official development library.
-find_package(SDL2_mixer 2.0.2)
-if(NOT SDL2_MIXER_FOUND)
+if(SDL_DOWNLOADED)
     if(WIN32)
         message(STATUS "Downloading SDL2_mixer Development Library...")
         if(MSVC)
@@ -106,13 +107,12 @@ if(NOT SDL2_MIXER_FOUND)
                 WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
         endif()
         set(SDL2_MIXER_DIR "${CMAKE_CURRENT_BINARY_DIR}/SDL2_mixer-2.0.4")
-        find_package(SDL2_mixer)
     endif()
 endif()
+find_package(SDL2_mixer 2.0.2)
 
 # SDL2_net.  On Windows, we use the official development library.
-find_package(SDL2_net)
-if(NOT SDL2_NET_FOUND)
+if(SDL_DOWNLOADED)
     if(WIN32)
         message(STATUS "Downloading SDL2_net Development Library...")
         if(MSVC)
@@ -133,9 +133,9 @@ if(NOT SDL2_NET_FOUND)
                 WORKING_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
         endif()
         set(SDL2_NET_DIR "${CMAKE_CURRENT_BINARY_DIR}/SDL2_net-2.0.1")
-        find_package(SDL2_net)
     endif()
 endif()
+find_package(SDL2_net)
 
 # Python 3.
 #
diff --git a/Source/CMakeLists.txt b/Source/CMakeLists.txt
index 42d45ce4..b9de0c05 100644
--- a/Source/CMakeLists.txt
+++ b/Source/CMakeLists.txt
@@ -180,7 +180,7 @@ target_compile_definitions(woof PRIVATE MINIZ_NO_ARCHIVE_APIS)
 
 # Assemble library files.
 set(WOOF_DLLS "")
-if(WIN32 AND NOT MINGW)
+if(SDL_DOWNLOADED)
     # SDL2
     list(APPEND WOOF_DLLS "${SDL2_DLL_DIR}/SDL2.dll")
 
@@ -214,7 +214,7 @@ else()
 endif()
 install(FILES ${WOOF_DLLS} DESTINATION .)
 
-if(MINGW)
+if(NOT SDL_DOWNLOADED)
     find_program(DLLTOOL_EXECUTABLE
         NAMES dlltool dlltool.exe
     )
```

**Comment by rfomin** [comment]
> Something like this (untested naive patch)?

We already have SDL2_DIR* variables for that. I'll try to fix this later today.

**Comment by fabiangreffrath** [comment]
Okay, but the crucial concept is that "if you downloaded one library, you have to download them all" so we don't risk ending up with a mixed bag of native and downloaded libraries.

**Comment by rfomin** [comment]
> so we don't risk ending up with a mixed bag of native and downloaded libraries.

Yes, that's what is happening sometimes in MSYS2. I'm not sure if we can guarantee this without `if(MSYS)` checks.

**Pull request merged**
