### PR TITLE
rearrange the startup messages

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
This already fixes most complaints expressed in #860

**Comment by fabiangreffrath** [comment]
This is e.g. how it looks for HACX:
```
IWAD found: /home/fabian/.local/share/games/doom/hacx.wad
HACX: Twitch n' Kill
                                  Woof 10.5.1
Built on Jan 12 2023
M_LoadDefaults: Load system defaults.
 default file: /home/fabian/.local/share/woof/woof.cfg
V_Init: allocate screens.
W_Init: Init WADfiles.
 adding /home/fabian/.local/share/games/doom/hacx.wad
 adding ./build/src/autoload/hacx.wad/brghtmps.lmp

Loading DEH file (WAD)
Loading DEH file ./build/src/autoload/hacx.wad/bloodcolor.deh
M_Init: Init miscellaneous info.
R_Init: Init DOOM refresh daemon - [ ......................... ]
P_Init: Init Playloop state.
I_Init: Setting up machine state.
I_InitJoystick: Initialize game controller.
I_InitSound: Configured audio device with 44.1 kHz (S16LSB), 2 channels.
Precaching all sound effects...done.
FluidSynth Init: Using '/usr/share/sounds/sf2/default-GM.sf2'.
NET_Init: Init network subsystem.
D_CheckNetGame: Checking network game status.
startskill 3  deathmatch: 0  startmap: 1  startepisode: 1
player 1 of 1 (1 nodes)
S_Init: Setting up sound.
HU_Init: Setting up heads up display.
ST_Init: Init status bar.
S_ChangeMusic: D_HAXTTL (hacx.wad)
```

Ultimately, I'd like it to look more like this (draft!):
```
Woof 10.5.1 (built on Jan 12 2023)

IWAD found: /home/fabian/.local/share/games/doom/hacx.wad
HACX: Twitch n' Kill

M_LoadDefaults: Load system defaults.
 default file: /home/fabian/.local/share/woof/woof.cfg
W_Init: Init WADfiles.
 adding /home/fabian/.local/share/games/doom/hacx.wad
 adding ./build/src/autoload/hacx.wad/brghtmps.lmp
Loading DEH lump from file /home/fabian/.local/share/games/doom/hacx.wad
Loading DEH file ./build/src/autoload/hacx.wad/bloodcolor.deh

R_Init: Init DOOM refresh daemon - [ ......................... ]
I_InitJoystick: Initialize game controller.
I_InitSound: Configured audio device with 44.1 kHz (S16LSB), 2 channels.
  Precaching all sound effects...done.
  FluidSynth Init: Using '/usr/share/sounds/sf2/default-GM.sf2'.
NET_Init: Init network subsystem.
D_CheckNetGame: Checking network game status.

S_ChangeMusic: D_HAXTTL (hacx.wad)
```

**Comment by rfomin** [comment]
> Ultimately, I'd like it to look more like this (draft!):

I like this draft 👍

**Comment by fabiangreffrath** [comment]
I did not remove any messages yet, just rearranged. Like it a lot better already.

**Pull request merged**
