### PR TITLE
OAL: set "linear" resampler for all channel sources

### PR DESCRIPTION
**Pull request by rfomin**
PrBoom+ and Crispy use a linear resampler, so it's more familiar to the Doom community.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Erm, wow, that's quite a lot that's required to change the resampling mode.

**Comment by rfomin** [comment]
> Erm, wow, that's quite a lot that's required to change the resampling mode.

Also it is limited, we can only choose between default, nearest and linear. And by default it is only set in config or env variable. https://github.com/kcat/openal-soft/blob/master/alsoftrc.sample
```
## resampler: (global)
#  Selects the default resampler used when mixing sources. Valid values are:
#  point - nearest sample, no interpolation
#  linear - extrapolates samples using a linear slope between samples
#  cubic - extrapolates samples using a Catmull-Rom spline
#  bsinc12 - extrapolates samples using a band-limited Sinc filter (varying
#            between 12 and 24 points, with anti-aliasing)
#  fast_bsinc12 - same as bsinc12, except without interpolation between down-
#                 sampling scales
#  bsinc24 - extrapolates samples using a band-limited Sinc filter (varying
#            between 24 and 48 points, with anti-aliasing)
#  fast_bsinc24 - same as bsinc24, except without interpolation between down-
#                 sampling scales
resampler = fast_bsinc12
```
Maybe we should just add `alsoft.ini` to our distribution and ask people to change it themselves.

**Comment by fabiangreffrath** [comment]
Either this, or we can set an env variable according to player config before we init openal.

**Comment by rfomin** [comment]
> Either this, or we can set an env variable according to player config before we init openal.

I agree, the env variable is probably better. I close this.

**Pull request closed without merging**
