### PR TITLE
Increase thread priority when window is visible and focused

### PR DESCRIPTION
**Pull request by ceski-1**
Continuation of idea from here but much more conservative: https://github.com/fabiangreffrath/woof/commit/a8b898a8139d28127e3ecc79496f019b865d6d48#commitcomment-138252625

This may reduce context switching (increase performance) on systems running multiple programs at the same time (Discord, web browser, etc.).

References:
- https://learn.microsoft.com/en-us/windows/win32/procthread/scheduling-priorities
- https://github.com/libsdl-org/SDL/blob/df00a7dd4c3deb03839e799187a3c75fc4e8854b/src/thread/pthread/SDL_systhread.c#L189
- https://github.com/libsdl-org/SDL/blob/df00a7dd4c3deb03839e799187a3c75fc4e8854b/src/thread/windows/SDL_systhread.c#L172

### CODE REVIEW

**Comment by rfomin** [comment]
Interesting, I didn't know about "priority classes". Does it help with frame times in your case?

**Comment by ceski-1** [comment]
> Interesting, I didn't know about "priority classes". Does it help with frame times in your case?

For my system, not really. The benefit seems to be mostly about other processes having less opportunity to interrupt Woof so performance should be better in those cases. Maybe it's more apparent on different configurations.

**Review by rfomin — APPROVED** [review]
It doesn't change anything on my laptop, but I have a really old CPU there. Maybe it will be useful these days with "e-cores".

**Comment by ceski-1** [comment]
As a follow-up, this is beneficial for older computers:



Quick reference for the below graphs:

| Frametime (ms) | Framerate (fps) |
|---|---|
| 30 | 33 |
| 25 | 40 |
| 20 | 50 |
| 15 | 67 |
| 10 | 100 |
| 5 | 200 |
| 2 | 500 (test point) |
| 0 | Inf |

Raised priority:


Raised priority with a 480p YouTube video playing in the background:


Normal priority:


Normal priority with a 480p YouTube video playing in the background:

**Pull request merged**
