### PR TITLE
deactivate thermo if input deactivated not in active range

### LINKED ISSUE #1472: Thermos still affected by cursor even after letting go of left-click
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/7896078489)._

Steps to reproduce:

- Go to `Options > General`;
- Left-click on the FOV slider;
- Holding left click, move the cursor up to the Widescreen item;
- Let go of left click;
- Hover over the FOV slider.

You should see the slider moving around even though you're not holding left click anymore.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1472

### CODE REVIEW

**Comment by MrAlaux** [comment]
This doesn't fix the issue for me, I'm afraid.

**Comment by rfomin** [comment]
> You can try it by clicking on the FOV thermo, holding left click and moving onto the Resolution Scale thermo.

Fixed here: https://github.com/fabiangreffrath/woof/pull/1477/commits/02eca6db84e3a4b91a805a6942270723b0e66751

**Comment by MrAlaux** [comment]
> > You can try it by clicking on the FOV thermo, holding left click and moving onto the Resolution Scale thermo.
> 
> Fixed here: [02eca6d](https://github.com/fabiangreffrath/woof/commit/02eca6db84e3a4b91a805a6942270723b0e66751)

Just tried it, and it works.

I did encounter another quirk, however: if I click on a thermo, hold click and go outside of its bounding box onto empty space (i.e. NOT onto another menu item, thermo or otherwise), I can still move the slider around even though the cursor's not on it anymore (once again, you can test it with the FOV slider and the empty space below it). This wasn't the case before, but I think that it's an acceptable quirk.

Ultimately, I'd say this is an improvement.

**Review by MrAlaux — APPROVED** [review]

**Comment by rfomin** [comment]
> I did encounter another quirk, however: if I click on a thermo, hold click and go outside of its bounding box onto empty space (i.e. NOT onto another menu item, thermo or otherwise), I can still move the slider around even though the cursor's not on it anymore (once again, you can test it with the FOV slider and the empty space below it). This wasn't the case before, but I think that it's an acceptable quirk.

It seems to have worked that way before, it was intended. The OS sliders also allow this to some extent. I don't think we should limit movement to just thermo rect.

**Comment by MrAlaux** [comment]
> I don't think we should limit movement to just thermo rect.

Neither do I, I just thought it could be a bit odd for some people.

**Comment by rfomin** [comment]
> I just thought it could be a bit odd for some people.

Try any Windows slider, I think it's natural.

**Comment by MrAlaux** [comment]
> Try any Windows slider, I think it's natural.

Yep, it works on my Win7 volume slider, and now that I think about it, it could be useful in case someone can't move their cursor steadily enough to stay within the slider's bounding box. Still weird in a sense IMO, but probably more user-friendly -- and again, I'm not against it myself anyways.

**Comment by MrAlaux** [comment]
Speaking of redundant checks, I saw this:

https://github.com/fabiangreffrath/woof/blob/65fdb4a896e7d5acb42209b4534e860528c41b95/src/m_menu.c#L5969-L5983

Do we need those two `ItemDisabled()` checks? I'm hardly familiar with the menu code, so I don't really know.

**Comment by rfomin** [comment]
> Do we need those two `ItemDisabled()` checks?

We don't 😄 I plan to continue refactoring the menu, it's still a mess. I think separating "main menu" and "setup" will help.

**Pull request merged**
