### PR TITLE
reformat added source code files

### LINKED ISSUE #1296: reformat added source code files
The following files in the `src/`directory were not part of the original WinMBF sources, are not auto-generated and are not already formatted with clear author intentions. We should reformat them with e.g. `clang-format` and Chocolate Doom's formatting rules at some point:

```
beta.h
cross.h
d_iwad.c
d_iwad.h
d_loop.c
d_loop.h
d_quit.c
d_quit.h
dogs.h
doomkeys.h
dsdhacked.c
dsdhacked.h
font.h
hu_obituary.c
hu_obituary.h
i_3dsound.c
i_endoom.c
i_endoom.h
i_flmusic.c
i_glob.c
i_glob.h
i_input.c
i_input.h
i_macmusic.c
i_mbfsound.c
i_oalmusic.c
i_oalmusic.h
i_oalsound.c
i_oalsound.h
i_oalstream.h
i_oplmusic.c
i_pcsound.c
i_printf.c
i_printf.h
i_sndfile.c
i_sndfile.h
i_timer.c
i_timer.h
i_winmusic.c
i_xmp.c
m_input.c
m_input.h
m_io.c
m_io.h
m_misc2.c
m_misc2.h
m_snapshot.c
m_snapshot.h
manifest.xml
memio.c
memio.h
midifallback.c
midifallback.h
midifile.c
midifile.h
mus2mid.c
mus2mid.h
net_client.c
net_client.h
net_common.c
net_common.h
net_dedicated.c
net_dedicated.h
net_defs.h
net_gui.c
net_gui.h
net_io.c
net_io.h
net_loop.c
net_loop.h
net_packet.c
net_packet.h
net_petname.c
net_petname.h
net_query.c
net_query.h
net_sdl.c
net_sdl.h
net_server.c
net_server.h
net_structrw.c
net_structrw.h
p_action.h
p_extnodes.c
p_extnodes.h
r_bmaps.c
r_bmaps.h
r_swirl.c
r_swirl.h
s_musinfo.c
s_musinfo.h
statdump.c
statdump.h
thermo.h
u_mapinfo.c
u_mapinfo.h
u_scanner.c
u_scanner.h
v_trans.c
v_trans.h
```

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1296

Used `.clang_format` config:
<details>

```
---
AlignAfterOpenBracket: Align
AlignArrayOfStructures: Left
AlignConsecutiveAssignments:
  Enabled: true
  AcrossEmptyLines: true
  AcrossComments: true
  AlignCompound: true
  PadOperators: true
AlignConsecutiveDeclarations:
  Enabled: false
AlignConsecutiveMacros:
  Enabled: true
  AcrossEmptyLines: true
  AcrossComments: true
  AlignCompound: true
  PadOperators: true
AlignConsecutiveShortCaseStatements:
  Enabled: false
AlignEscapedNewlines: Left
AlignOperands: Align
AlignTrailingComments:
  Kind: Always
AllowAllArgumentsOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Never
AllowShortCaseLabelsOnASingleLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: Never
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: false
BinPackArguments: true
BinPackParameters: true
BracedInitializerIndentWidth: 4
BreakArrays: false
BreakBeforeBinaryOperators: NonAssignment
BreakBeforeBraces: Custom
BraceWrapping:
  AfterCaseLabel: true
  AfterControlStatement: Always
  AfterEnum: true
  AfterFunction: true
  AfterStruct: true
  AfterUnion: true
  AfterExternBlock : true
  BeforeElse: true
  BeforeWhile: false
  SplitEmptyFunction: true
  SplitEmptyRecord: true
BreakBeforeTernaryOperators: true
BreakStringLiterals: true
ColumnLimit: 80
IncludeBlocks: Preserve
IndentCaseBlocks: true
IndentCaseLabels: true
IndentPPDirectives: AfterHash
IndentWidth: 4
IndentWrappedFunctionNames: false
InsertBraces: true
InsertNewlineAtEOF: true
InsertTrailingCommas: None
KeepEmptyLinesAtTheStartOfBlocks: true
Language: Cpp
MaxEmptyLinesToKeep: 1
PPIndentWidth: 2
PointerAlignment: Right
ReflowComments: true
RemoveBracesLLVM: false
SeparateDefinitionBlocks: Always
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeParens: ControlStatementsExceptControlMacros
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: false
SpacesBeforeTrailingComments: 2
SpacesInContainerLiterals: false
SpacesInSquareBrackets: false
SpacesInParensOptions:
  InConditionalStatements: false
  InCStyleCasts: false
  InEmptyParentheses: false
  Other: false
TabWidth: 4
UseTab: Never
```
</details>

`clang-format` tool is still far from perfect (I also tried config from the Choco repository).

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
I don't like how it's filling up with spaces up to the '=' char.

**Comment by rfomin** [comment]
> I don't like how it's filling up with spaces up to the '=' char.

That is [AlignConsecutiveAssignments](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#alignconsecutiveassignments) option. We already have it in some places, but I agree that I may have gone too far.

**Comment by fabiangreffrath** [comment]
> `.clang_format`

Please add this file in this PR.

**Comment by fabiangreffrath** [comment]
> SpacesBeforeTrailingComments: 2

I think 1 is enough.

**Comment by rfomin** [comment]
Maybe we don't need to reformat _all_ new files, there are a lot of small changes in this PR that are unnecessary. Also, I think that reformatting files with "lumps" is not interesting.

I suggest this list for reformatting:
```
d_loop.c
d_loop.h
dsdhacked.c
dsdhacked.h
i_sound.c
i_sound.h
s_sound.c
s_sound.h
i_video.c
i_video.h
i_input.c
i_input.h
m_input.c
m_input.h
m_snaphot.c
m_snaphot.h
m_memio.c
m_memio.h
r_swirl.c
r_swirl.h
v_video.c
v_video.h
v_flextran.c
v_flextran.h
u_mapinfo.c
u_mapinfo.h
u_scanner.v
u_scanner.h
```

**Comment by fabiangreffrath** [comment]
> Also, I think that reformatting files with "lumps" is not interesting.

I think even the lump data files should be consistently formatted. But we can do this in a follow up PR, if you don't want to blow up this one.

**Comment by rfomin** [comment]
> I think even the lump data files should be consistently formatted. But we can do this in a follow up PR, if you don't want to blow up this one.

I'm fine with the current PR. I think it's done.

**Review by fabiangreffrath — APPROVED** [review]

**Pull request merged**
