### PR TITLE
Pan/zoom automap faster by holding run button

### PR DESCRIPTION
**Pull request by JNechaevsky**
I'm afraid I need some help here. What I have got at this moment:

* Fast panning working just fine.
* Fast keyboard zoom have notable delay before start zooming. Standard zooming still fine though.
* Fast mouse wheel zoom isn't working at all. Really no idea why, I've left it commented out for now.

This PR was used as reference: https://github.com/fabiangreffrath/crispy-doom/pull/906/commits/e4233bc82e753c7b0d4cadb8dca8878832ee07d3

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
To be honest, I don't know the difference between `M_InputGameActive()` and `M_InputActivated()`, but it may play a role here.

**Comment by JNechaevsky** [comment]
Nope, `M_InputActivated()` isn't working at all. Apparently, delay caused by this condition: https://github.com/fabiangreffrath/woof/blob/master/src/am_map.c#L922

**Comment by JNechaevsky** [comment]
Yeah, as I expected. Now I've got fully working approach without delays, but the question of the ~~day~~ night is: how to do it smarter, to get rid of `M1_ZOOMIN` and `M1_ZOOMOUT`? 🤤 I'm totally confused by reset conditions:
```
        mtof_zoommul = FRACUNIT;
        ftom_zoommul = FRACUNIT;
```

**Comment by fabiangreffrath** [comment]
There is a `static boolean mousewheelzoom` for this purpose in Crispy now.

**Comment by JNechaevsky** [comment]
Though it is not needed in MBF event handling, but fortunately, I was wrong - it should be placed just a little bit different. All done now.

**Comment by rfomin** [comment]
> To be honest, I don't know the difference between `M_InputGameActive()` and `M_InputActivated()`, but it may play a role here.

`M_InputGameActive()` checks the `gamekeydown` array in `g_game.c` if the button is "on hold" . `M_InputActivated()` checks if the button was pressed in this tick.

@JNechaevsky what do you think if we increase speed of fast map panning? It feels slow compared with fast zoom.

**Comment by fabiangreffrath** [comment]
> > To be honest, I don't know the difference between `M_InputGameActive()` and `M_InputActivated()`, but it may play a role here.
> 
> `M_InputGameActive()` checks the `gamekeydown` array in `g_game.c` if the button is "on hold" . `M_InputActivated()` checks if the button was pressed in this tick.

Thank you!

> @JNechaevsky what do you think if we increase speed of fast map panning? It feels slow compared with fast zoom.

Which value do you suggest?

**Comment by rfomin** [comment]
> Which value do you suggest?

I suggest 12:
```diff
--- a/src/am_map.c
+++ b/src/am_map.c
@@ -81,7 +81,7 @@ int map_keyed_door_flash; // keyed doors are flashing
 // moves 140 pixels in 1 second
 #define F_PANINC  4
 // [crispy] pan faster by holding run button
-#define F2_PANINC 8
+#define F2_PANINC 12
 // how much zoom-in per tic
 // goes to 2x in 1 second
 #define M_ZOOMIN        ((int) (1.02*FRACUNIT))
```

**Comment by JNechaevsky** [comment]
Feels perfect, I'm all for it. For my personal taste I'm using even faster speed for normal scrolling ([link](https://github.com/JNechaevsky/inter-doom/blob/master/src/doom/am_map.c#L79-L80)), but here we probably should left normal speed as is.

I have to leave for job and will not have code/git access until evening, so if we okay with `F2_PANINC 12` please change it that way.

There is small problem with player arrow: try to enable rotate mode, zoom in a little bit and move mouse left-right fast - you'll notice that arrow is slightly rotating left-right as well. I remember I was having same issue and mostly remember how to fix it, but let's leave it for another PR.

**Comment by fabiangreffrath** [comment]
> I have to leave for job and will not have code/git access until evening, so if we okay with `F2_PANINC 12` please change it that way.

Done, thanks!

> There is small problem with player arrow: try to enable rotate mode, zoom in a little bit and move mouse left-right fast - you'll notice that arrow is slightly rotating left-right as well. I remember I was having same issue and mostly remember how to fix it, but let's leave it for another PR.

I think this is because of `smoothangle = automaprotate ? plr->mo->angle : viewangle` in `AM_drawPlayers()`, but `mapangle = ANG90 - viewangle` in `AM_Drawer()` for use in `AM_rotatePoint()`.

**Comment by JNechaevsky** [comment]
Thanks @mikeday0 for `mousewheelzoom`!  

> I think this is because of smoothangle = automaprotate ? plr->mo->angle : viewangle in AM_drawPlayers(), but mapangle = ANG90 - viewangle in AM_Drawer() for use in AM_rotatePoint()

Oh yes, must be it.  And should we increase `F2_PANINC` to `12` in Crispy as well?

**Pull request merged**
