### PR TITLE
support miniwadm (miniwad1.wad/miniwad2.wad) project

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
Do we only need it because of the "doom-all" autoload directory? Maybe we should change the logic of "doom-all" instead.

**Comment by fabiangreffrath** [comment]
> Maybe we should change the logic of "doom-all" instead.

Yes sure, what's the idea?

**Comment by rfomin** [comment]
> Yes sure, what's the idea?

It's simple, "doom-all" should only work for known Doom-based IWADs - Doom 1, Doom 2, Plutonia, TNT.

**Comment by fabiangreffrath** [comment]
Another thought, at least fraggle's miniwad.wad contains a FREEDOOM lump, so maybe we don't even need the "miniwad" game variant.

**Comment by MrAlaux** [comment]
> > Do we need an "all" directory as in Nugget Doom?
> 
> Okay. Not sure if there's a demand for it.

If you're going to implement such a directory, think about whether you want to name it "all-all" as in DSDA or "all" as in Nugget.

I asked about DSDA's convention, and someone thinks that it has to do with the directories being named following a `game-iwad` format, e.g. "doom-all", "doom-tnt", "heretic-all". Woof doesn't follow such format, though, so just "all" seems more fitting IMO.

**Comment by liPillON** [comment]
uhm since the scope of this pr is becoming wider.. may I?

You might take this opportunity to add support for the following folders:
"all" 
"doom-all" for all ID iwads
"doom2-all" for doom2/plutonia/tnt
"freedoom-all" for all FD iwads

What do you guys think?

**Comment by rfomin** [comment]
> Another thought, at least fraggle's miniwad.wad contains a FREEDOOM lump, so maybe we don't even need the "miniwad" game variant.

I agree, we don't need a "miniwad" game variant, and maybe not even a `GameVariant_t` concept.

> "all"
> "doom-all" for all ID iwads
> "doom2-all" for doom2/plutonia/tnt
> "freedoom-all" for all FD iwads

Okay, although I'm not sure about "freedoom-all".

**Comment by fabiangreffrath** [comment]
> If you're going to implement such a directory, think about whether you want to name it "all-all" as in DSDA or "all" as in Nugget.

Do you know of any specific use case for the "all" autoload directory? I find it hard to imagine one, to be honest.

**Comment by MrAlaux** [comment]
> Do you know of any specific use case for the "all" autoload directory? I find it hard to imagine one, to be honest.

Well, I personally use it just to load a single HUD-customization lump; perhaps it could also be used for test maps. In short, it's useful for WAD-agnostic content, but I admit that I haven't come across much of that kind of content.

**Pull request closed without merging**
