### PR TITLE
back to Crispy Doom formula for fractionaltic calculation

### PR DESCRIPTION
**Pull request by rfomin**
Is there a way to simplify `I_GetFracScaledTime`?

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
But why? Does it have to do with newsync?

**Comment by rfomin** [comment]
> But why? Does it have to do with newsync?

No, newsync is not related, Crispy's formula is simpler.

**Comment by fabiangreffrath** [comment]
That's right. But if you are concerned about the timing bug that @kraflab uncovered, it could be mitigated by simply fixing the order in which the functions get executed.

**Comment by fabiangreffrath** [comment]
> Is there a way to simplify `I_GetFracScaledTime`?

I think you need to replace `TICRATE` with `(clock_rate * TICRATE / 100)` or similar.

**Comment by rfomin** [comment]
> I think you need to replace `TICRATE` with `(clock_rate * TICRATE / 100)` or similar.

I tried that, didn't work.

This is not necessary but I believe there is a simpler way than calling SDL_GetTicks twice and converting it to tics and then back to ms.

**Comment by fabiangreffrath** [comment]
> I tried that, didn't work.

Hm, but it should. The order of multiplication and division is important, else values may get badly truncated. 

> This is not necessary but I believe there is a simpler way than calling SDL_GetTicks twice and converting it to tics and then back to ms.

Hm, right. I think we need one function that returns `SDL_GetTicks / ticrate` and another one that returns `SDL_GetTicks % ticrate` with `ticrate` being either `TICRATE` or variable ticrate.

**Comment by rfomin** [comment]
> The order of multiplication and division is important, else values may get badly truncated.

It seems that this is the tricky part. Can't get it to work so far.

**Comment by fabiangreffrath** [comment]
`return (I_GetTimeMS() * clock_rate * TICRATE / 100) % 1000 * FRACUNIT / 1000;`
Perhaps?

**Comment by rfomin** [comment]
> `return (I_GetTimeMS() * clock_rate * TICRATE / 100) % 1000 * FRACUNIT / 1000;` Perhaps?

No, it doesn't work. I tested with the `-speed 30` parameter:

https://user-images.githubusercontent.com/5077629/151739114-1e993488-4b2b-4f85-bb2e-c8d43e24cfdf.mp4

**Comment by rfomin** [comment]
Deprecated by #438

**Pull request closed without merging**
