### PR TITLE
remove same input element in menu instead of ignoring

### LINKED ISSUE #1039: [Request] Allow bind keys to be unbound in menus
When a user goes into the key binds options, they see the default key binds. Say a user has key that they do not want bound, instead of having to move that key to another bind or hitting delete and removing all binds, it would be more helpful to be able to hit that bound key - after hitting enter to change the key bind - and it unbinds the key.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1039

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Very nice fix! Can we somehow document this in the "Press key or button" string?

**Comment by rfomin** [comment]
> Can we somehow document this in the "Press key or button" string?

I couldn't come up with a short description.

**Comment by kraflab** [comment]
I don't understand, if I hit the key that is already bound, it removes it? That doesn't seem intuitive at all. In dsda-doom you can just press delete to unbind a specific input.

**Comment by fabiangreffrath** [comment]
> I couldn't come up with a short description.

"Press key or button to bind/unbind this action" or alternatively "set/unset".

**Comment by rfomin** [comment]
>> I couldn't come up with a short description.
>
>"Press key or button to bind/unbind this action" or alternatively "set/unset".

image
Do you like it? Not sure about it.

**Comment by kraflab** [comment]
I'd say it's also unintuitive that the delete key resets everything instead of deleting something, so fixing that would fix another problem :^)

**Comment by rfomin** [comment]
> I'd say it's also unintuitive that the delete key resets everything instead of deleting something, so fixing that would fix another problem :^)

But the delete key also resets everything in DSDA-Doom 😄 This is probably a misunderstanding.

**Comment by kraflab** [comment]
> But the delete key also resets everything in DSDA-Doom 😄 This is probably a misunderstanding.

Ah yes, I misunderstood what you meant. At any rate, this still makes no sense to me. The fact that coming up with any sensible text to display succinctly is proving a challenge is a strong indicator that the behaviour is unexpected.

**Comment by rfomin** [comment]
> At any rate, this still makes no sense to me. The fact that coming up with any sensible text to display succinctly is proving a challenge is a strong indicator that the behaviour is unexpected.

Have you tried building it? It actually feels natural, but it's hard to articulate it properly. I quite like it.

**Comment by fabiangreffrath** [comment]
Whatever, I want this feature.

Real life example: I rarely play with a gamepad, but when I do, I always want to use the same bindings. Now, if I play with keyboard and accidentally mis-bind a key, I have to either (a) bind this accidental key away to some other action or (b) delete all bindings to this action, including mouse and gamepad buttons. Both alternatives are moot and we are strictly missing a way to unbind a specific key/button from an action.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by kraflab** [comment]
I'm not disputing that there is a feature gap, it's the solution I'm not a fan of. But this is probably the easiest solution to this problem to implement. It just has the side effect that some users will go to set something and decide to use the key they want, and then poof it gets unbound for no clear reason.

**Comment by rfomin** [comment]
Just checked other ports/games. Exactly the same approach is implemented in the Eternity Engine menu. GZDoom and Quake have our old behavior.

**Pull request merged**
