### PR TITLE
initial sub menu implementation

### PR DESCRIPTION
**Pull request by rfomin**
Should we make it a part of #1714 ?

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
> Should we make it a part of #1714 ?

I don't think so. We'll have to rearrange the menu page in #1714 anyway and it would be easier if we could do so into the new sub menu infrastructure.

**Comment by fabiangreffrath** [comment]
> I don't think so. We'll have to rearrange the menu page in #1714 anyway and it would be easier if we could do so into the new sub menu infrastructure.

Okay, I just checked this out and I admit that it doesn't make too much sense to merge code for a sub menu without an actual sub menu. So, if you don't mind, maybe you could mangle it into #1714, please?

**Comment by rfomin** [comment]
> Okay, I just checked this out and I admit that it doesn't make too much sense to merge code for a sub menu without an actual sub menu. So, if you don't mind, maybe you could mangle it into #1714, please?

I'm thinking about some details, like whether to draw the old menu in the background and whether the "Back" button is needed. I'll improve this tomorrow.

**Comment by rfomin** [comment]
Deprecated by https://github.com/fabiangreffrath/woof/pull/1895

**Pull request closed without merging**
