### PR TITLE
add darkcolormap to shade the screen during drawing

### LINKED ISSUE #1609: No HOMs with dark overlay
The hall of mirrors effect doesn't work when the dark overlay is active; missing textures render as black.
Screenshot from wow.wad:
darkhom

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1609 

This is unfinished. I think we should duplicate r_draw functions for this, or introduce some other system for changing drawing parameters.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Thanks, but I think you are over-engineering this. If you want to fix #1609 and help spot HOMs, then we could either (1) draw them in a brighter color, or (2) ask users to use the menu without backdrop or (3) use pause instead of the menu to interrupt the game.

**Comment by fabiangreffrath** [comment]
Also, does it hep if we let HOMs blink based on `leveltime` instead of `gametic`?

**Comment by rfomin** [comment]
> If you want to fix #1609 and help spot HOMs, then we could either (1) draw them in a brighter color, or (2) ask users to use the menu without backdrop or (3) use pause instead of the menu to interrupt the game.

It's not about the HOM cheat or the menu background, it's about the automap overlay. There are some PWADs that use HOM as a visual effect, [wow.wad](https://doomwiki.org/wiki/Wow) is one of them.

HOM pixels are not "refreshed" every frame, so if we use the current `V_ShadeScreen` they will go black very quickly.

**Comment by fabiangreffrath** [comment]
Ah, now I see.

But, instead of duplicating drawing functions or introducing more branching into drawing functions I'd recommend to introduce a function pointer for pixel drawing and use this in the drawing functions.

```c
static byte draw_pixel_regular (byte src) {return colormap[brightmap[src]][src];};
static byte draw_pixel_shaded  (byte src) {return darkcolormap[colormap[brightmap[src]][src]];};
static byte (*draw_pixel) (byte src) = draw_pixel_regular;

void R_ShadeScreen(boolean on)
{
    if (on)
    {
        draw_pixel = draw_pixel_shaded;
    }
    else
    {
        draw_pixel = draw_pixel_regular;
    }
}
```

However, this doesn't solve the problem of shading the HUD elements and status bar. Is this really worth the effort?

**Comment by rfomin** [comment]
> However, this doesn't solve the problem of shading the HUD elements and status bar. Is this really worth the effort?

It's not hard to add a "shade" option to a patch drawing, but yeah, I'm not sure it's worth it. 

If we already had a system for drawing parameters, we can add another option to it. Maybe we should have such a system, for example we could remove `brightmaps[]` if the user has disabled it.

**Comment by fabiangreffrath** [comment]
> If we already had a system for drawing parameters, we can add another option to it. Maybe we should have such a system, for example we could remove `brightmaps[]` if the user has disabled it.

If we had such a system, we'd be one step closer to truecolor rendering. 🤔

**Comment by ceski-1** [comment]
Just a note that this method has a nice performance boost over the old one, so it may be worth pursuing for that reason alone. For example, compare the master branch and this one at native resolution with dark overlay automap.

**Comment by fabiangreffrath** [comment]
Obsoleted by https://github.com/fabiangreffrath/woof/commit/e81db0ae778da97052b231093034b2e70fa984e1

**Pull request closed without merging**
