### PR TITLE
set scalefactor = 2 by default

### PR DESCRIPTION
**Pull request by rfomin**
Fixes window size if toggle widescreen mode

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Hm, what if we only call `SDL_SetWindowSize()` a few lines later `if (!fullscreen && firsttime)`.

**Comment by fabiangreffrath** [comment]
PS: And set `firsttime = false` only at the end of the function.

**Comment by rfomin** [comment]
> Hm, what if we only call `SDL_SetWindowSize()` a few lines later `if (!fullscreen && firsttime)`.

Then it won't resize the window if the user toggles widescreen mode, right?

**Comment by rfomin** [comment]
`scalefactor == 2` is clearly not right. Not sure how to fix it.

**Comment by rfomin** [comment]
Ah there was this commit: 040ebdc133c2407865985a6cdcfe0a18d3025a77 What if we got rid of the scale factor completely? And maybe refactoring the `I_InitGraphicsMode` a bit.

**Comment by fabiangreffrath** [comment]
How about this?
```patch
--- a/Source/i_video.c
+++ b/Source/i_video.c
@@ -1310,6 +1310,17 @@ static void I_InitGraphicsMode(void)
          usehires = hires = true;
       else if(M_CheckParm("-nohires"))
          usehires = hires = false; // grrr...
+
+      if(M_CheckParm("-1"))
+         scalefactor = 1;
+      else if(M_CheckParm("-2"))
+         scalefactor = 2;
+      else if(M_CheckParm("-3"))
+         scalefactor = 3;
+      else if(M_CheckParm("-4"))
+         scalefactor = 4;
+      else if(M_CheckParm("-5"))
+         scalefactor = 5;
    }

    // haleyjd 10/09/05: from Chocolate DOOM
@@ -1398,19 +1409,13 @@ static void I_InitGraphicsMode(void)

    SDL_SetWindowMinimumSize(screen, v_w, actualheight);

-   if(M_CheckParm("-1"))
-      scalefactor = 1;
-   else if(M_CheckParm("-2"))
-      scalefactor = 2;
-   else if(M_CheckParm("-3"))
-      scalefactor = 3;
-   else if(M_CheckParm("-4"))
-      scalefactor = 4;
-   else if(M_CheckParm("-5"))
-      scalefactor = 5;
-
    // [FG] window size when returning from fullscreen mode
-   if (scalefactor > 0)
+   if (scalefactor == 0)
+   {
+      scalefactor = MIN(window_width / v_w, window_height / actualheight);
+   }
+
+   if (scalefactor * v_w > window_width)
    {
       window_width = scalefactor * v_w;
       window_height = scalefactor * actualheight;

```

**Comment by fabiangreffrath** [comment]
This should do it. Now it's even uglier.
```patch
--- a/Source/i_video.c
+++ b/Source/i_video.c
@@ -1310,6 +1310,17 @@ static void I_InitGraphicsMode(void)
          usehires = hires = true;
       else if(M_CheckParm("-nohires"))
          usehires = hires = false; // grrr...
+
+      if(M_CheckParm("-1"))
+         scalefactor = 1;
+      else if(M_CheckParm("-2"))
+         scalefactor = 2;
+      else if(M_CheckParm("-3"))
+         scalefactor = 3;
+      else if(M_CheckParm("-4"))
+         scalefactor = 4;
+      else if(M_CheckParm("-5"))
+         scalefactor = 5;
    }

    // haleyjd 10/09/05: from Chocolate DOOM
@@ -1398,19 +1409,18 @@ static void I_InitGraphicsMode(void)

    SDL_SetWindowMinimumSize(screen, v_w, actualheight);

-   if(M_CheckParm("-1"))
-      scalefactor = 1;
-   else if(M_CheckParm("-2"))
-      scalefactor = 2;
-   else if(M_CheckParm("-3"))
-      scalefactor = 3;
-   else if(M_CheckParm("-4"))
-      scalefactor = 4;
-   else if(M_CheckParm("-5"))
-      scalefactor = 5;
-
    // [FG] window size when returning from fullscreen mode
-   if (scalefactor > 0)
+   if (scalefactor == 0)
+   {
+      scalefactor = MIN(window_width / v_w, window_height / actualheight);
+   }
+   else
+   {
+      // [FG] trigger resetting window size below if scalefactor was set on the command line
+      window_width = 0;
+   }
+
+   if (scalefactor * v_w > window_width)
    {
       window_width = scalefactor * v_w;
       window_height = scalefactor * actualheight;
```

**Comment by rfomin** [comment]
Deprecated by #393

**Pull request closed without merging**
