### PR TITLE
skip first and last 16 bytes of Doom SFX lumps

### PR DESCRIPTION
**Pull request by fabiangreffrath**

### CODE REVIEW

**Comment by rfomin** [comment]
As far as I can hear, the click issue is not resolved here. Do you hear it in the video from the Doomworld thread? Maybe this is a resampling issue.

**Comment by fabiangreffrath** [comment]
Honestly, I have no idea what people are talking about when they report clicking sounds. That's why I need a "second opinion". 😉

**Comment by fabiangreffrath** [comment]
Maybe we should hand SFX resampling over to `SDL_ConvertAudio()´. It seems to have some pretty sophisticated algorithms nowadays:
https://github.com/libsdl-org/SDL/blob/ca22b30e46238d870251ff2dbc68744fd111f4f2/src/audio/SDL_audiocvt.c#L1254-L1259

**Comment by rfomin** [comment]
I tested light_test.wad from this issue: https://github.com/fabiangreffrath/crispy-doom/issues/794 in Crispy, PrBoom+ and Woof. There is clicking with vanilla sound in all ports, but it can be minimized with samplerate parameters in Crispy. My hearing is not good, so I can't say with certainty.

**Comment by fabiangreffrath** [comment]
We should wait until someone reports a specific complaint with our implementation and check if this could mitigate it.

**Pull request closed without merging**
