### PR TITLE
rearrange automap menu, consistency changes

### PR DESCRIPTION
**Pull request by rfomin**
doom01
Colors have been moved to the following pages.

The only remaining menu that doesn't match the looks of the others is "Doom Compatibility".

### CODE REVIEW

**Review by fabiangreffrath — APPROVED** [review]
Beautiful!

**Comment by fabiangreffrath** [comment]
Could we achieve that the heading and the first item are on the same line in every menu?

**Comment by rfomin** [comment]
> Could we achieve that the heading and the first item are on the same line in every menu?

Yes, if I understand correctly, we have already achieved this.

**Comment by fabiangreffrath** [comment]
Alright, but I'd like them all to use the same variables (or defines, for that matter) for positioning.

**Comment by rfomin** [comment]
While we're here, can we remove/rearrange the help screen?
doom02

**Comment by fabiangreffrath** [comment]
> While we're here, can we remove/rearrange the help screen? doom02

What do you suggest?

**Comment by rfomin** [comment]
> What do you suggest?

Delete it or remove some elements from it so everything can fit. Make it more like the original help screen:
doom00

**Comment by fabiangreffrath** [comment]
> Delete it or remove some elements from it so everything can fit. Make it more like the original help screen:

Deleting it would be a bit harsh. But reducing it to show less, but more relevant information would be fine.

**Comment by fabiangreffrath** [comment]
How many different values of `KB_X` and `AM_X` and the like do we have? Could we condense them into two distinct values for menus with short and long items, respectively?

**Comment by rfomin** [comment]
> How many different values of `KB_X` and `AM_X` and the like do we have? Could we condense them into two distinct values for menus with short and long items, respectively?

We can set most of them to `X = 250`. Exceptions are "Doom Compatibilty" (`C_X = 284`), "Key Bindings" (`KB_X = 120`) and "Chat Strings" (`CS_X = 20`)

**Comment by fabiangreffrath** [comment]
Ok, let's combine them then.

**Comment by fabiangreffrath** [comment]
> The only remaining menu that doesn't match the looks of the others is "Doom Compatibility".

Do you have any plans to adapt this as well?

**Comment by rfomin** [comment]
> > The only remaining menu that doesn't match the looks of the others is "Doom Compatibility".
> 
> Do you have any plans to adapt this as well?

Not sure what to do with it. It seems 12px spacing is needed for readability. About the content there are several issues:
1. Strange reverse logic - "yes" means "restore the bug".
2. "Default Complevel" should be at the top of this menu.
3. As always I think we should delete at least half of it :smile:

**Comment by fabiangreffrath** [comment]
> 3. As always I think we should delete at least half of it 😄

I agree that for some items it feels wrong to even have a choice about. For example "Zombie players can exit levels". I mean, yes of course?!

**Pull request merged**
