### PR TITLE
enable hires and uncapped by default

### PR DESCRIPTION
**Pull request by rfomin**
I think we need to enable hires and uncapped otherwise Woof will look like Chocolate Doom to a new user. Also should we enable fullscreen mode by default?

Widescreen looks a bit awkward without wide assets. Since we are still distributing beta assets, I think we can add wide assets as well.

### CODE REVIEW

**Comment by NightFright2k19** [comment]
If you need widescreen assets, here is what I have compiled for private usage. These would probably have to go into autoload folders. They are pretty much completely taken from Nash's widescreen project. You might want to check what's inside the wads anyway since maybe there's something you don't want (e.g. Nash didn't provide a widescreen statusbar for Doom, so I included the one from the Unity port)

[widescreen_assets.zip](https://github.com/fabiangreffrath/woof/files/8560149/widescreen_assets.zip)
.

**Comment by rfomin** [comment]
> If you need widescreen assets, here is what I have compiled for private usage. These would probably have to go into autoload folders. They are pretty much completely taken from Nash's widescreen project. You might want to check what's inside the wads anyway since maybe there's something you don't want (e.g. Nash didn't provide a widescreen statusbar for Doom, so I included the one from the Unity port).

There is official wide assets with permission from Bethesda: https://bethesda.net/en/game/doom-widescreen-mods

**Comment by NightFright2k19** [comment]
True, but it doesn't have everything.
What I didn't get from Nash or Unity, I took from the ["Widescreen Appreciation" thread](https://www.doomworld.com/forum/topic/121385-widescreen-assets-pack-and-appreciation-thread/) over at Doomworld. This way, also more "exotic" content like Chex, Freedoom , HacX, Strife or REKKR are covered.

**Comment by rfomin** [comment]
I know about that thread (it's very good), but we can't use resources from it due to license issues.

**Comment by fabiangreffrath** [comment]
> I know about that thread (it's very good), but we can't use resources from it due to license issues.

Right!

We still have `betagrph.wad` in the repo for historic reasons and I consider its ill-/un-licensed content as a bug. Let's please not introduce another one. We simply cannot add some random artwork found in some thread on the net to this port - escpecially if it is based upon original IWAD assets.

I have taken the painful steps to remove or replace any such content that was embedded into `info.c` before. BTW, these were the main reason why Crispy wasn't based on WinMBF in the first place: Back then I had no clue what to do with this stuff, so I decided to base my project on Chocolate Doom instead, which seemed to have higher standards regarding license compliance.

Anyway, if people want widescreen assets, they know where to find them and download them on their own account. They do not have to be part of the port at all.

Random idea: We could paint the pillars to the left and right of the non-widescreen graphics in widescreen mode based on the median color of the left- and right-most graphics column?

**Comment by rfomin** [comment]
> Random idea: We could paint the pillars to the left and right of the non-widescreen graphics in widescreen mode based on the median color of the left- and right-most graphics column?

I prefer the black stripes.  BTW here is the GZDoom license https://github.com/coelckers/gzdoom/blob/master/wadsrc_widepix/static/license.md

**Pull request merged**
