### PR TITLE
remove from P_Move() parts that are incompatible with PrBoom+ complevel 11

### PR DESCRIPTION
**Pull request by rfomin**
This change fixes desync in Evitenity map14 demos and many others.
P_Move() is a quite convoluted function, so I suggest just replace it. This is the last known desync in complevel 11 demos.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Sorry, but this is a bit *too* dirty. We cannot entirely replace 100 lines of original MBF code with a different implementation... in order to achieve MBF compatibility. There'll be a logic bug lingernig in there and I'll help to figure it out, but just throwing out so much original code isn't going to work.

**Comment by fabiangreffrath** [comment]
Actually, the difference between the implementation in MBF and PrBoom+ isn't that vast. There is one block with some different logic in the `friction > ORIGFRICTION` case (MBF calls `P_SetThingPosition()` here which might be the point):

image

And the logic for the return value is a bit different. I tried to clarify it once, but probably messed it up.

**Comment by rfomin** [comment]
> different logic in the `friction > ORIGFRICTION` case (MBF calls `P_SetThingPosition()` here which might be the point)

Yes, it will desync on custom friction maps. I tried to fix this but couldn't. I'll try more later.

**Comment by rfomin** [comment]
I have integrated it into the original code, so we give up on this:
`// killough 12/98: rearrange, fix potential for stickiness on ice`

**Comment by fabiangreffrath** [comment]
What's the difference between this and simply not calling `P_SetThingPosition()`/`P_UnsetThingPosition()`?

**Comment by rfomin** [comment]
The z coordinates also change here. On the Eviternity14 map, the desync was due to this.

**Comment by fabiangreffrath** [comment]
And if you just undo setting the various `z` values?

**Comment by fabiangreffrath** [comment]
This seems to be enough:
```patch
--- a/Source/p_enemy.c
+++ b/Source/p_enemy.c
@@ -344,9 +344,11 @@ static boolean P_Move(mobj_t *actor, boolean dropoff) // killough 9/12/98
     {
       fixed_t x = actor->x;
       fixed_t y = actor->y;
+#if 0
       fixed_t floorz = actor->floorz;
       fixed_t ceilingz = actor->ceilingz;
       fixed_t dropoffz = actor->dropoffz;
+#endif
 
       try_ok = P_TryMove(actor, tryx, tryy, dropoff);
 
@@ -358,9 +360,11 @@ static boolean P_Move(mobj_t *actor, boolean dropoff) // killough 9/12/98
          P_UnsetThingPosition(actor);
          actor->x = x;
          actor->y = y;
+#if 0
          actor->floorz = floorz;
          actor->ceilingz = ceilingz;
          actor->dropoffz = dropoffz;
+#endif
          P_SetThingPosition(actor);
          movefactor *= FRACUNIT / ORIG_FRICTION_FACTOR / 4;
          actor->momx += FixedMul(deltax, movefactor);
```

**Comment by rfomin** [comment]
Sorry, I can't test it right now. I'll try this tomorrow.

чт, 11 мар. 2021 г., 23:36 Fabian Greffrath ***@***.***>:

**Comment by rfomin** [comment]
I tried unsetting the z values and removing the `P_SetThingPosition() / P_UnsetThingPosition()` - complevel 11 works, but complevel 9 broke. Only the current version works fine everywhere.

**Comment by fabiangreffrath** [comment]
Very good! If now you could add a comment and clean up the remaining unnecessary whitespace changes, please.

**Comment by fabiangreffrath** [comment]
Thanks again! So, we are now in a state of 100% Boom 2.02 and MBF demo compatibility?

**Comment by rfomin** [comment]
Yes, but PrBoom+ uses only Boom's version of BLOCKMAP generation for all complevels.

**Comment by fabiangreffrath** [comment]
Ah, okay. And we still have that change to make in `P_FindShortestTextureAround()`. I think I am going to introduce a e.g. `STRICT_MBF` compile time macro instead of a `-strict` command line option. 🤔

**Comment by rfomin** [comment]
> `STRICT_MBF` compile time macro instead of a `-strict` command line option

Agree. Keep all source code for a historic reason, but users are interested in PrBoom+ compatibility I think.

**Comment by fabiangreffrath** [comment]
Yep, I have come to the same conclusion.

**Pull request merged**
