### PR TITLE
add R_DrawSkyColumn without fade effect

### LINKED ISSUE #508: [Bug] I﻿_SignalHandler: Exit on Signal 11 in "Ancient Aliens"
Used Woof! release: Latest Github build from Master branch (Apr 10, 2022)
OS: Win10 Pro x64 21H2
MIDI device: Roland SCVA, loaded with Falcosoft MIDIPlayer v6.1 (x64) and loopMIDI v1.0.16.27
PWAD: Ancient Aliens

Problem description:
In the final chamber before the exit of MAP23 in "Ancient Aliens", I get crashes to desktop with "I_SignalHandler: Exit on Signal 11" (apparently a SIGSEGV error, meaning the program tries to access a memory location not assigned to it) after killing some monsters that keep spawning in this area. 
Regardless how often I try, this keeps happening. At first I thought it depends on killing monsters, but even when doing nothing at all (just evading all shots), the crash will happen after a while.

Reproduction:
- Enter the area in front of player after loading savegame
- After being locked in, either fight enemies or evade them
- Crash will happen after 30s max

Mods in autoload folders:
- doom_all: bloodcolor.deh, perk_sfx.wad (Perk's enhanced sounds)
- doom2.wad: d2spfx20.wad (Sprite fixes)

Savegame and config are attached.

[woofsav0.zip](https://github.com/fabiangreffrath/woof/files/8465154/woofsav0.zip)
[woof_config.zip](https://github.com/fabiangreffrath/woof/files/8465169/woof_config.zip)

### PR DESCRIPTION
**Pull request by rfomin**
Fixes #508 

A simple solution. I didn't figure out how to use `cr_dark` here.

### CODE REVIEW

**Comment by facespkz** [comment]
If we're going to borrow most of the code for `R_DrawSkyTLColumn` anyways, why not add checks for `general_translucency` to `R_DrawSkyColumn` instead?

**Comment by rfomin** [comment]
Initially, `r_draw.c` has a lot of code dublication. But of course you are right, it can be fixed if this approach is chosen.

**Comment by fabiangreffrath** [comment]
Thanks, but sorry, I consider this approach as over-engineered. Let's just create the 64k translucency table without even asking and be done with it.

**Comment by rfomin** [comment]
Deprecated by #511

**Pull request closed without merging**
