### PR TITLE
add fluidsynth menu item, add TimGM6mb.sf2

### PR DESCRIPTION
**Pull request by rfomin**

### CODE REVIEW

**Comment by rfomin** [comment]
Is it possible to include soundfont from GZDoom? TimGM6mb.sf2 sounds very wrong in Ancient Aliens and Going Down (and probably most other PWADs).

**Comment by fabiangreffrath** [comment]
Depends solely on the license (and file size).

**Comment by rfomin** [comment]
> Depends solely on the license (and file size).

The file size is ~2mb. It was taken from here https://www.vogons.org/viewtopic.php?f=9&t=45600 and probably contains Roland samples, not sure.

**Comment by fabiangreffrath** [comment]
No explicit license means "All rights reserved." ☹️

**Comment by rfomin** [comment]
> No explicit license means "All rights reserved." :frowning_face:

Well, TimGM6mb is good enough. I think users can figure out how to change the soundfont.

**Comment by rfomin** [comment]
There is still this issue: https://github.com/libsdl-org/SDL_mixer/issues/284 Maybe we should implement fluidsynth support without SDL_Mixer? Fluidsyth has a built-in midi player, so it's not hard.

**Comment by fabiangreffrath** [comment]
IMHO, the defaults doesn't sound too bad with TimGM6MB. After all, it's just an alternative, an additional bonus.

**Comment by rfomin** [comment]
Deprecated by #403

**Pull request closed without merging**
