### PR TITLE
add weaponinfo checks to weapon centering code

### LINKED ISSUE #1027: Another stutter in the weapon switch animation
_Tested in the [latest master artifact (x64)](https://github.com/fabiangreffrath/woof/actions/runs/4836654377)._

Similar to a [previous issue](https://github.com/fabiangreffrath/woof/issues/893) I reported, this time with [this WAD](https://www.doomworld.com/idgames/combos/armas29): when switching to some weapons (the SSG replacement, for example), the sprite of said weapon is drawn at the fully-raised position, then snaps downwards and resumes the normal raise animation.

I noticed that multiple weapons in the WAD play a sound before beginning to raise. I can't check the DeHackEd right now, but that's definitely done through an action that's not `A_WeaponReady()`, `A_Lower()` or `A_Raise()`. Rather than checking for the latter two functions [here](https://github.com/fabiangreffrath/woof/blob/master/src/p_pspr.c#L1085-L1087) and [here](https://github.com/fabiangreffrath/woof/blob/master/src/p_pspr.c#L1101-L1103), maybe we should check for `A_WeaponReady()` to account for all cases? There might be issues with that approach that I'm too sleepy to figure out right now.

### PR DESCRIPTION
**Pull request by rfomin**
Fix #1027 

This fixes both D4V.wad and armas29.wad for me. Not sure if this is the correct approach.

### CODE REVIEW

**Comment by fabiangreffrath** [comment]
Additional checks for the weapon state seem reasonable to me. 

Yes, code duplication is always a bad thing (as this example shows), let's factor it out into a function.

**Comment by rfomin** [comment]
> Yes, code duplication is always a bad thing (as this example shows), let's factor it out into a function.

Done https://github.com/fabiangreffrath/woof/pull/1028/commits/367f98621c7d85b75e9fc5a606e9b8236fcdd33b

**Comment by fabiangreffrath** [comment]
Another idea: how about we factor out the weapon state and function checks, since they always appear in pairs?

**Comment by rfomin** [comment]
> Another idea: how about we factor out (macroize) the weapon state and function checks, since they always appear in pairs?

But we also have `if (psp->state->action.p2 == (actionf_p2)A_Lower || state == winfo->downstate)` check. I think there will be too many functions then.

**Comment by fabiangreffrath** [comment]
Oh, I meant something like
```c
#define WEAPON_LOW (psp->state->action.p2 == (actionf_p2)A_Lower ||
             state == winfo->downstate)
```

**Comment by rfomin** [comment]
> Oh, I meant something like
> 
> ```c
> #define WEAPON_LOW (psp->state->action.p2 == (actionf_p2)A_Lower ||
>              state == winfo->downstate)
> ```

I think we can add more shortcuts
```c
actionf_p2 action = psp->state->action.p2;
if (action == (action_p2)A_Lower ...)
```
But for me the current code is good enough.

By the way, do you know that macros were considered bad practice? When I was a programmer, we had a direct ban on the use of macros. Things are different these days, but still: https://stackoverflow.com/questions/14041453/why-are-preprocessor-macros-evil-and-what-are-the-alternatives

**Comment by fabiangreffrath** [comment]
It's alright, I don't insist on using macros. I just would have found out easier to read in this specific case.

**Comment by rfomin** [comment]
Okay, so how do we proceed? Should I add `actionf_p2 action = psp->state->action.p2;`? Or add new little functions?

**Comment by fabiangreffrath** [comment]
It's alright as it is.

**Review by fabiangreffrath — APPROVED** [review]

**Comment by fabiangreffrath** [comment]
Still thinking about macroizing the state checks:
```patch
diff --git a/src/p_pspr.c b/src/p_pspr.c
index 16a0560..801321d 100644
--- a/src/p_pspr.c
+++ b/src/p_pspr.c
@@ -1087,22 +1087,23 @@ void P_MovePsprites(player_t *player)
   winfo = &weaponinfo[player->readyweapon];
   state = psp->state - states;
 
+#define LOWERING (psp->state->action.p2 == (actionf_p2)A_Lower || \
+                  state == winfo->downstate)
+#define RAISING  (psp->state->action.p2 == (actionf_p2)A_Raise || \
+                  state == winfo->upstate)
+
   if (psp->state && !cosmetic_bobbing)
   {
     static fixed_t last_sy = WEAPONTOP;
 
     psp->sx2 = FRACUNIT;
 
-    if (!psp->state->misc1 &&
-        psp->state->action.p2 != (actionf_p2)A_Lower &&
-        psp->state->action.p2 != (actionf_p2)A_Raise &&
-        state != winfo->downstate && state != winfo->upstate)
+    if (!psp->state->misc1 && !LOWERING && !RAISING)
     {
       last_sy = psp->sy2;
       psp->sy2 = WEAPONTOP;
     }
-    else if (psp->state->action.p2 == (actionf_p2)A_Lower ||
-             state == winfo->downstate)
+    else if (LOWERING)
     {
       // We want to move smoothly from where we were
       psp->sy2 -= (last_sy - WEAPONTOP);
@@ -1111,10 +1112,7 @@ void P_MovePsprites(player_t *player)
   else if (psp->state && (cosmetic_bobbing == BOBBING_75 || center_weapon || uncapped))
   {
     // [FG] don't center during lowering and raising states
-    if (psp->state->misc1 ||
-        psp->state->action.p2 == (actionf_p2)A_Lower ||
-        psp->state->action.p2 == (actionf_p2)A_Raise ||
-        state == winfo->downstate || state == winfo->upstate)
+    if (psp->state->misc1 || LOWERING || RAISING)
     {
     }
     // [FG] not attacking means idle
@@ -1130,6 +1128,9 @@ void P_MovePsprites(player_t *player)
     }
   }
 
+#undef LOWERING
+#undef RAISING
+
   player->psprites[ps_flash].sx2 = player->psprites[ps_weapon].sx2;
   player->psprites[ps_flash].sy2 = player->psprites[ps_weapon].sy2;
 }
```

**Comment by rfomin** [comment]
> Still thinking about macroizing the state checks

Sure, if you like it. The patch looks good.

**Pull request merged**
